package com.nicetcm.nibsplus.broker.msg.model;

public class TbPhsUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OP.TB_PHS_USER.USER_IDX
     *
     * @mbggenerated Thu Aug 14 16:45:51 KST 2014
     */
    private Long userIdx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OP.TB_PHS_USER.PHONE_NUMBER
     *
     * @mbggenerated Thu Aug 14 16:45:51 KST 2014
     */
    private String phoneNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OP.TB_PHS_USER.USER_NUMBER
     *
     * @mbggenerated Thu Aug 14 16:45:51 KST 2014
     */
    private String userNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OP.TB_PHS_USER.STATUS
     *
     * @mbggenerated Thu Aug 14 16:45:51 KST 2014
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OP.TB_PHS_USER.DEVICE_TOKEN
     *
     * @mbggenerated Thu Aug 14 16:45:51 KST 2014
     */
    private String deviceToken;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OP.TB_PHS_USER.DEVICE_MODEL
     *
     * @mbggenerated Thu Aug 14 16:45:51 KST 2014
     */
    private String deviceModel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OP.TB_PHS_USER.DEVICE_VERSION
     *
     * @mbggenerated Thu Aug 14 16:45:51 KST 2014
     */
    private String deviceVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OP.TB_PHS_USER.APP_VERSION
     *
     * @mbggenerated Thu Aug 14 16:45:51 KST 2014
     */
    private String appVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OP.TB_PHS_USER.CREATE_DATE
     *
     * @mbggenerated Thu Aug 14 16:45:51 KST 2014
     */
    private String createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OP.TB_PHS_USER.CREATE_TIME
     *
     * @mbggenerated Thu Aug 14 16:45:51 KST 2014
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OP.TB_PHS_USER.UPDATE_DATE
     *
     * @mbggenerated Thu Aug 14 16:45:51 KST 2014
     */
    private String updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OP.TB_PHS_USER.UPDATE_TIME
     *
     * @mbggenerated Thu Aug 14 16:45:51 KST 2014
     */
    private String updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OP.TB_PHS_USER.WORKER
     *
     * @mbggenerated Thu Aug 14 16:45:51 KST 2014
     */
    private String worker;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OP.TB_PHS_USER.USER_IDX
     *
     * @return the value of OP.TB_PHS_USER.USER_IDX
     *
     * @mbggenerated Thu Aug 14 16:45:51 KST 2014
     */
    public Long getUserIdx() {
        return userIdx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OP.TB_PHS_USER.USER_IDX
     *
     * @param userIdx the value for OP.TB_PHS_USER.USER_IDX
     *
     * @mbggenerated Thu Aug 14 16:45:51 KST 2014
     */
    public void setUserIdx(Long userIdx) {
        this.userIdx = userIdx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OP.TB_PHS_USER.PHONE_NUMBER
     *
     * @return the value of OP.TB_PHS_USER.PHONE_NUMBER
     *
     * @mbggenerated Thu Aug 14 16:45:51 KST 2014
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OP.TB_PHS_USER.PHONE_NUMBER
     *
     * @param phoneNumber the value for OP.TB_PHS_USER.PHONE_NUMBER
     *
     * @mbggenerated Thu Aug 14 16:45:51 KST 2014
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OP.TB_PHS_USER.USER_NUMBER
     *
     * @return the value of OP.TB_PHS_USER.USER_NUMBER
     *
     * @mbggenerated Thu Aug 14 16:45:51 KST 2014
     */
    public String getUserNumber() {
        return userNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OP.TB_PHS_USER.USER_NUMBER
     *
     * @param userNumber the value for OP.TB_PHS_USER.USER_NUMBER
     *
     * @mbggenerated Thu Aug 14 16:45:51 KST 2014
     */
    public void setUserNumber(String userNumber) {
        this.userNumber = userNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OP.TB_PHS_USER.STATUS
     *
     * @return the value of OP.TB_PHS_USER.STATUS
     *
     * @mbggenerated Thu Aug 14 16:45:51 KST 2014
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OP.TB_PHS_USER.STATUS
     *
     * @param status the value for OP.TB_PHS_USER.STATUS
     *
     * @mbggenerated Thu Aug 14 16:45:51 KST 2014
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OP.TB_PHS_USER.DEVICE_TOKEN
     *
     * @return the value of OP.TB_PHS_USER.DEVICE_TOKEN
     *
     * @mbggenerated Thu Aug 14 16:45:51 KST 2014
     */
    public String getDeviceToken() {
        return deviceToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OP.TB_PHS_USER.DEVICE_TOKEN
     *
     * @param deviceToken the value for OP.TB_PHS_USER.DEVICE_TOKEN
     *
     * @mbggenerated Thu Aug 14 16:45:51 KST 2014
     */
    public void setDeviceToken(String deviceToken) {
        this.deviceToken = deviceToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OP.TB_PHS_USER.DEVICE_MODEL
     *
     * @return the value of OP.TB_PHS_USER.DEVICE_MODEL
     *
     * @mbggenerated Thu Aug 14 16:45:51 KST 2014
     */
    public String getDeviceModel() {
        return deviceModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OP.TB_PHS_USER.DEVICE_MODEL
     *
     * @param deviceModel the value for OP.TB_PHS_USER.DEVICE_MODEL
     *
     * @mbggenerated Thu Aug 14 16:45:51 KST 2014
     */
    public void setDeviceModel(String deviceModel) {
        this.deviceModel = deviceModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OP.TB_PHS_USER.DEVICE_VERSION
     *
     * @return the value of OP.TB_PHS_USER.DEVICE_VERSION
     *
     * @mbggenerated Thu Aug 14 16:45:51 KST 2014
     */
    public String getDeviceVersion() {
        return deviceVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OP.TB_PHS_USER.DEVICE_VERSION
     *
     * @param deviceVersion the value for OP.TB_PHS_USER.DEVICE_VERSION
     *
     * @mbggenerated Thu Aug 14 16:45:51 KST 2014
     */
    public void setDeviceVersion(String deviceVersion) {
        this.deviceVersion = deviceVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OP.TB_PHS_USER.APP_VERSION
     *
     * @return the value of OP.TB_PHS_USER.APP_VERSION
     *
     * @mbggenerated Thu Aug 14 16:45:51 KST 2014
     */
    public String getAppVersion() {
        return appVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OP.TB_PHS_USER.APP_VERSION
     *
     * @param appVersion the value for OP.TB_PHS_USER.APP_VERSION
     *
     * @mbggenerated Thu Aug 14 16:45:51 KST 2014
     */
    public void setAppVersion(String appVersion) {
        this.appVersion = appVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OP.TB_PHS_USER.CREATE_DATE
     *
     * @return the value of OP.TB_PHS_USER.CREATE_DATE
     *
     * @mbggenerated Thu Aug 14 16:45:51 KST 2014
     */
    public String getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OP.TB_PHS_USER.CREATE_DATE
     *
     * @param createDate the value for OP.TB_PHS_USER.CREATE_DATE
     *
     * @mbggenerated Thu Aug 14 16:45:51 KST 2014
     */
    public void setCreateDate(String createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OP.TB_PHS_USER.CREATE_TIME
     *
     * @return the value of OP.TB_PHS_USER.CREATE_TIME
     *
     * @mbggenerated Thu Aug 14 16:45:51 KST 2014
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OP.TB_PHS_USER.CREATE_TIME
     *
     * @param createTime the value for OP.TB_PHS_USER.CREATE_TIME
     *
     * @mbggenerated Thu Aug 14 16:45:51 KST 2014
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OP.TB_PHS_USER.UPDATE_DATE
     *
     * @return the value of OP.TB_PHS_USER.UPDATE_DATE
     *
     * @mbggenerated Thu Aug 14 16:45:51 KST 2014
     */
    public String getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OP.TB_PHS_USER.UPDATE_DATE
     *
     * @param updateDate the value for OP.TB_PHS_USER.UPDATE_DATE
     *
     * @mbggenerated Thu Aug 14 16:45:51 KST 2014
     */
    public void setUpdateDate(String updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OP.TB_PHS_USER.UPDATE_TIME
     *
     * @return the value of OP.TB_PHS_USER.UPDATE_TIME
     *
     * @mbggenerated Thu Aug 14 16:45:51 KST 2014
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OP.TB_PHS_USER.UPDATE_TIME
     *
     * @param updateTime the value for OP.TB_PHS_USER.UPDATE_TIME
     *
     * @mbggenerated Thu Aug 14 16:45:51 KST 2014
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OP.TB_PHS_USER.WORKER
     *
     * @return the value of OP.TB_PHS_USER.WORKER
     *
     * @mbggenerated Thu Aug 14 16:45:51 KST 2014
     */
    public String getWorker() {
        return worker;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OP.TB_PHS_USER.WORKER
     *
     * @param worker the value for OP.TB_PHS_USER.WORKER
     *
     * @mbggenerated Thu Aug 14 16:45:51 KST 2014
     */
    public void setWorker(String worker) {
        this.worker = worker;
    }
}