package com.nicetcm.nibsplus.broker.msg.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TFnBrandSuspenseSpec {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table OP.T_FN_BRAND_SUSPENSE
     *
     * @mbggenerated Tue Jul 22 11:13:55 KST 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table OP.T_FN_BRAND_SUSPENSE
     *
     * @mbggenerated Tue Jul 22 11:13:55 KST 2014
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table OP.T_FN_BRAND_SUSPENSE
     *
     * @mbggenerated Tue Jul 22 11:13:55 KST 2014
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_BRAND_SUSPENSE
     *
     * @mbggenerated Tue Jul 22 11:13:55 KST 2014
     */
    public TFnBrandSuspenseSpec() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_BRAND_SUSPENSE
     *
     * @mbggenerated Tue Jul 22 11:13:55 KST 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_BRAND_SUSPENSE
     *
     * @mbggenerated Tue Jul 22 11:13:55 KST 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_BRAND_SUSPENSE
     *
     * @mbggenerated Tue Jul 22 11:13:55 KST 2014
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_BRAND_SUSPENSE
     *
     * @mbggenerated Tue Jul 22 11:13:55 KST 2014
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_BRAND_SUSPENSE
     *
     * @mbggenerated Tue Jul 22 11:13:55 KST 2014
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_BRAND_SUSPENSE
     *
     * @mbggenerated Tue Jul 22 11:13:55 KST 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_BRAND_SUSPENSE
     *
     * @mbggenerated Tue Jul 22 11:13:55 KST 2014
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_BRAND_SUSPENSE
     *
     * @mbggenerated Tue Jul 22 11:13:55 KST 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_BRAND_SUSPENSE
     *
     * @mbggenerated Tue Jul 22 11:13:55 KST 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_BRAND_SUSPENSE
     *
     * @mbggenerated Tue Jul 22 11:13:55 KST 2014
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table OP.T_FN_BRAND_SUSPENSE
     *
     * @mbggenerated Tue Jul 22 11:13:55 KST 2014
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andStdDateIsNull() {
            addCriterion("STD_DATE is null");
            return (Criteria) this;
        }

        public Criteria andStdDateIsNotNull() {
            addCriterion("STD_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andStdDateEqualTo(String value) {
            addCriterion("STD_DATE =", value, "stdDate");
            return (Criteria) this;
        }

        public Criteria andStdDateNotEqualTo(String value) {
            addCriterion("STD_DATE <>", value, "stdDate");
            return (Criteria) this;
        }

        public Criteria andStdDateGreaterThan(String value) {
            addCriterion("STD_DATE >", value, "stdDate");
            return (Criteria) this;
        }

        public Criteria andStdDateGreaterThanOrEqualTo(String value) {
            addCriterion("STD_DATE >=", value, "stdDate");
            return (Criteria) this;
        }

        public Criteria andStdDateLessThan(String value) {
            addCriterion("STD_DATE <", value, "stdDate");
            return (Criteria) this;
        }

        public Criteria andStdDateLessThanOrEqualTo(String value) {
            addCriterion("STD_DATE <=", value, "stdDate");
            return (Criteria) this;
        }

        public Criteria andStdDateLike(String value) {
            addCriterion("STD_DATE like", value, "stdDate");
            return (Criteria) this;
        }

        public Criteria andStdDateNotLike(String value) {
            addCriterion("STD_DATE not like", value, "stdDate");
            return (Criteria) this;
        }

        public Criteria andStdDateIn(List<String> values) {
            addCriterion("STD_DATE in", values, "stdDate");
            return (Criteria) this;
        }

        public Criteria andStdDateNotIn(List<String> values) {
            addCriterion("STD_DATE not in", values, "stdDate");
            return (Criteria) this;
        }

        public Criteria andStdDateBetween(String value1, String value2) {
            addCriterion("STD_DATE between", value1, value2, "stdDate");
            return (Criteria) this;
        }

        public Criteria andStdDateNotBetween(String value1, String value2) {
            addCriterion("STD_DATE not between", value1, value2, "stdDate");
            return (Criteria) this;
        }

        public Criteria andOrgCdIsNull() {
            addCriterion("ORG_CD is null");
            return (Criteria) this;
        }

        public Criteria andOrgCdIsNotNull() {
            addCriterion("ORG_CD is not null");
            return (Criteria) this;
        }

        public Criteria andOrgCdEqualTo(String value) {
            addCriterion("ORG_CD =", value, "orgCd");
            return (Criteria) this;
        }

        public Criteria andOrgCdNotEqualTo(String value) {
            addCriterion("ORG_CD <>", value, "orgCd");
            return (Criteria) this;
        }

        public Criteria andOrgCdGreaterThan(String value) {
            addCriterion("ORG_CD >", value, "orgCd");
            return (Criteria) this;
        }

        public Criteria andOrgCdGreaterThanOrEqualTo(String value) {
            addCriterion("ORG_CD >=", value, "orgCd");
            return (Criteria) this;
        }

        public Criteria andOrgCdLessThan(String value) {
            addCriterion("ORG_CD <", value, "orgCd");
            return (Criteria) this;
        }

        public Criteria andOrgCdLessThanOrEqualTo(String value) {
            addCriterion("ORG_CD <=", value, "orgCd");
            return (Criteria) this;
        }

        public Criteria andOrgCdLike(String value) {
            addCriterion("ORG_CD like", value, "orgCd");
            return (Criteria) this;
        }

        public Criteria andOrgCdNotLike(String value) {
            addCriterion("ORG_CD not like", value, "orgCd");
            return (Criteria) this;
        }

        public Criteria andOrgCdIn(List<String> values) {
            addCriterion("ORG_CD in", values, "orgCd");
            return (Criteria) this;
        }

        public Criteria andOrgCdNotIn(List<String> values) {
            addCriterion("ORG_CD not in", values, "orgCd");
            return (Criteria) this;
        }

        public Criteria andOrgCdBetween(String value1, String value2) {
            addCriterion("ORG_CD between", value1, value2, "orgCd");
            return (Criteria) this;
        }

        public Criteria andOrgCdNotBetween(String value1, String value2) {
            addCriterion("ORG_CD not between", value1, value2, "orgCd");
            return (Criteria) this;
        }

        public Criteria andReceiptAmtIsNull() {
            addCriterion("RECEIPT_AMT is null");
            return (Criteria) this;
        }

        public Criteria andReceiptAmtIsNotNull() {
            addCriterion("RECEIPT_AMT is not null");
            return (Criteria) this;
        }

        public Criteria andReceiptAmtEqualTo(Long value) {
            addCriterion("RECEIPT_AMT =", value, "receiptAmt");
            return (Criteria) this;
        }

        public Criteria andReceiptAmtNotEqualTo(Long value) {
            addCriterion("RECEIPT_AMT <>", value, "receiptAmt");
            return (Criteria) this;
        }

        public Criteria andReceiptAmtGreaterThan(Long value) {
            addCriterion("RECEIPT_AMT >", value, "receiptAmt");
            return (Criteria) this;
        }

        public Criteria andReceiptAmtGreaterThanOrEqualTo(Long value) {
            addCriterion("RECEIPT_AMT >=", value, "receiptAmt");
            return (Criteria) this;
        }

        public Criteria andReceiptAmtLessThan(Long value) {
            addCriterion("RECEIPT_AMT <", value, "receiptAmt");
            return (Criteria) this;
        }

        public Criteria andReceiptAmtLessThanOrEqualTo(Long value) {
            addCriterion("RECEIPT_AMT <=", value, "receiptAmt");
            return (Criteria) this;
        }

        public Criteria andReceiptAmtIn(List<Long> values) {
            addCriterion("RECEIPT_AMT in", values, "receiptAmt");
            return (Criteria) this;
        }

        public Criteria andReceiptAmtNotIn(List<Long> values) {
            addCriterion("RECEIPT_AMT not in", values, "receiptAmt");
            return (Criteria) this;
        }

        public Criteria andReceiptAmtBetween(Long value1, Long value2) {
            addCriterion("RECEIPT_AMT between", value1, value2, "receiptAmt");
            return (Criteria) this;
        }

        public Criteria andReceiptAmtNotBetween(Long value1, Long value2) {
            addCriterion("RECEIPT_AMT not between", value1, value2, "receiptAmt");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNull() {
            addCriterion("UPDATE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNotNull() {
            addCriterion("UPDATE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateEqualTo(Date value) {
            addCriterion("UPDATE_DATE =", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotEqualTo(Date value) {
            addCriterion("UPDATE_DATE <>", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThan(Date value) {
            addCriterion("UPDATE_DATE >", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDATE_DATE >=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThan(Date value) {
            addCriterion("UPDATE_DATE <", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThanOrEqualTo(Date value) {
            addCriterion("UPDATE_DATE <=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIn(List<Date> values) {
            addCriterion("UPDATE_DATE in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotIn(List<Date> values) {
            addCriterion("UPDATE_DATE not in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateBetween(Date value1, Date value2) {
            addCriterion("UPDATE_DATE between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotBetween(Date value1, Date value2) {
            addCriterion("UPDATE_DATE not between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateUidIsNull() {
            addCriterion("UPDATE_UID is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUidIsNotNull() {
            addCriterion("UPDATE_UID is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUidEqualTo(String value) {
            addCriterion("UPDATE_UID =", value, "updateUid");
            return (Criteria) this;
        }

        public Criteria andUpdateUidNotEqualTo(String value) {
            addCriterion("UPDATE_UID <>", value, "updateUid");
            return (Criteria) this;
        }

        public Criteria andUpdateUidGreaterThan(String value) {
            addCriterion("UPDATE_UID >", value, "updateUid");
            return (Criteria) this;
        }

        public Criteria andUpdateUidGreaterThanOrEqualTo(String value) {
            addCriterion("UPDATE_UID >=", value, "updateUid");
            return (Criteria) this;
        }

        public Criteria andUpdateUidLessThan(String value) {
            addCriterion("UPDATE_UID <", value, "updateUid");
            return (Criteria) this;
        }

        public Criteria andUpdateUidLessThanOrEqualTo(String value) {
            addCriterion("UPDATE_UID <=", value, "updateUid");
            return (Criteria) this;
        }

        public Criteria andUpdateUidLike(String value) {
            addCriterion("UPDATE_UID like", value, "updateUid");
            return (Criteria) this;
        }

        public Criteria andUpdateUidNotLike(String value) {
            addCriterion("UPDATE_UID not like", value, "updateUid");
            return (Criteria) this;
        }

        public Criteria andUpdateUidIn(List<String> values) {
            addCriterion("UPDATE_UID in", values, "updateUid");
            return (Criteria) this;
        }

        public Criteria andUpdateUidNotIn(List<String> values) {
            addCriterion("UPDATE_UID not in", values, "updateUid");
            return (Criteria) this;
        }

        public Criteria andUpdateUidBetween(String value1, String value2) {
            addCriterion("UPDATE_UID between", value1, value2, "updateUid");
            return (Criteria) this;
        }

        public Criteria andUpdateUidNotBetween(String value1, String value2) {
            addCriterion("UPDATE_UID not between", value1, value2, "updateUid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table OP.T_FN_BRAND_SUSPENSE
     *
     * @mbggenerated do_not_delete_during_merge Tue Jul 22 11:13:55 KST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table OP.T_FN_BRAND_SUSPENSE
     *
     * @mbggenerated Tue Jul 22 11:13:55 KST 2014
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}