package com.nicetcm.nibsplus.broker.msg.mapper;

import com.nicetcm.nibsplus.broker.msg.model.TCtOrgSiteChange;
import com.nicetcm.nibsplus.broker.msg.model.TCtOrgSiteChangeKey;
import com.nicetcm.nibsplus.broker.msg.model.TCtOrgSiteChangeSpec;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface TCtOrgSiteChangeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_CT_ORG_SITE_CHANGE
     *
     * @mbggenerated Wed Aug 06 09:08:57 KST 2014
     */
    @SelectProvider(type=TCtOrgSiteChangeSqlProvider.class, method="countBySpec")
    int countBySpec(TCtOrgSiteChangeSpec spec);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_CT_ORG_SITE_CHANGE
     *
     * @mbggenerated Wed Aug 06 09:08:57 KST 2014
     */
    @DeleteProvider(type=TCtOrgSiteChangeSqlProvider.class, method="deleteBySpec")
    int deleteBySpec(TCtOrgSiteChangeSpec spec);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_CT_ORG_SITE_CHANGE
     *
     * @mbggenerated Wed Aug 06 09:08:57 KST 2014
     */
    @Delete({
        "delete from OP.T_CT_ORG_SITE_CHANGE",
        "where ORG_CD = #{orgCd,jdbcType=VARCHAR}",
          "and BRANCH_CD = #{branchCd,jdbcType=VARCHAR}",
          "and ORG_SITE_CD = #{orgSiteCd,jdbcType=VARCHAR}",
          "and CHANGE_DATE = #{changeDate,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(TCtOrgSiteChangeKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_CT_ORG_SITE_CHANGE
     *
     * @mbggenerated Wed Aug 06 09:08:57 KST 2014
     */
    @Insert({
        "insert into OP.T_CT_ORG_SITE_CHANGE (ORG_CD, BRANCH_CD, ",
        "ORG_SITE_CD, CHANGE_DATE, ",
        "OPER_DATE, NEW_ORG_SITE_CD, ",
        "NEW_ORG_SITE_NM, NEW_OPER_TYPE, ",
        "NEW_OPER_TIME, NEW_SET_ADDR, ",
        "NEW_SERVICE_CD, ORG_MEMO, ",
        "CONFIRM_YN, UPDATE_DATE)",
        "values (#{orgCd,jdbcType=VARCHAR}, #{branchCd,jdbcType=VARCHAR}, ",
        "#{orgSiteCd,jdbcType=VARCHAR}, #{changeDate,jdbcType=VARCHAR}, ",
        "#{operDate,jdbcType=VARCHAR}, #{newOrgSiteCd,jdbcType=VARCHAR}, ",
        "#{newOrgSiteNm,jdbcType=VARCHAR}, #{newOperType,jdbcType=VARCHAR}, ",
        "#{newOperTime,jdbcType=VARCHAR}, #{newSetAddr,jdbcType=VARCHAR}, ",
        "#{newServiceCd,jdbcType=VARCHAR}, #{orgMemo,jdbcType=VARCHAR}, ",
        "#{confirmYn,jdbcType=VARCHAR}, #{updateDate,jdbcType=TIMESTAMP})"
    })
    int insert(TCtOrgSiteChange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_CT_ORG_SITE_CHANGE
     *
     * @mbggenerated Wed Aug 06 09:08:57 KST 2014
     */
    @InsertProvider(type=TCtOrgSiteChangeSqlProvider.class, method="insertSelective")
    int insertSelective(TCtOrgSiteChange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_CT_ORG_SITE_CHANGE
     *
     * @mbggenerated Wed Aug 06 09:08:57 KST 2014
     */
    @SelectProvider(type=TCtOrgSiteChangeSqlProvider.class, method="selectBySpec")
    @Results({
        @Result(column="ORG_CD", property="orgCd", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="BRANCH_CD", property="branchCd", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="ORG_SITE_CD", property="orgSiteCd", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="CHANGE_DATE", property="changeDate", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="OPER_DATE", property="operDate", jdbcType=JdbcType.VARCHAR),
        @Result(column="NEW_ORG_SITE_CD", property="newOrgSiteCd", jdbcType=JdbcType.VARCHAR),
        @Result(column="NEW_ORG_SITE_NM", property="newOrgSiteNm", jdbcType=JdbcType.VARCHAR),
        @Result(column="NEW_OPER_TYPE", property="newOperType", jdbcType=JdbcType.VARCHAR),
        @Result(column="NEW_OPER_TIME", property="newOperTime", jdbcType=JdbcType.VARCHAR),
        @Result(column="NEW_SET_ADDR", property="newSetAddr", jdbcType=JdbcType.VARCHAR),
        @Result(column="NEW_SERVICE_CD", property="newServiceCd", jdbcType=JdbcType.VARCHAR),
        @Result(column="ORG_MEMO", property="orgMemo", jdbcType=JdbcType.VARCHAR),
        @Result(column="CONFIRM_YN", property="confirmYn", jdbcType=JdbcType.VARCHAR),
        @Result(column="UPDATE_DATE", property="updateDate", jdbcType=JdbcType.TIMESTAMP)
    })
    List<TCtOrgSiteChange> selectBySpec(TCtOrgSiteChangeSpec spec);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_CT_ORG_SITE_CHANGE
     *
     * @mbggenerated Wed Aug 06 09:08:57 KST 2014
     */
    @Select({
        "select",
        "ORG_CD, BRANCH_CD, ORG_SITE_CD, CHANGE_DATE, OPER_DATE, NEW_ORG_SITE_CD, NEW_ORG_SITE_NM, ",
        "NEW_OPER_TYPE, NEW_OPER_TIME, NEW_SET_ADDR, NEW_SERVICE_CD, ORG_MEMO, CONFIRM_YN, ",
        "UPDATE_DATE",
        "from OP.T_CT_ORG_SITE_CHANGE",
        "where ORG_CD = #{orgCd,jdbcType=VARCHAR}",
          "and BRANCH_CD = #{branchCd,jdbcType=VARCHAR}",
          "and ORG_SITE_CD = #{orgSiteCd,jdbcType=VARCHAR}",
          "and CHANGE_DATE = #{changeDate,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="ORG_CD", property="orgCd", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="BRANCH_CD", property="branchCd", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="ORG_SITE_CD", property="orgSiteCd", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="CHANGE_DATE", property="changeDate", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="OPER_DATE", property="operDate", jdbcType=JdbcType.VARCHAR),
        @Result(column="NEW_ORG_SITE_CD", property="newOrgSiteCd", jdbcType=JdbcType.VARCHAR),
        @Result(column="NEW_ORG_SITE_NM", property="newOrgSiteNm", jdbcType=JdbcType.VARCHAR),
        @Result(column="NEW_OPER_TYPE", property="newOperType", jdbcType=JdbcType.VARCHAR),
        @Result(column="NEW_OPER_TIME", property="newOperTime", jdbcType=JdbcType.VARCHAR),
        @Result(column="NEW_SET_ADDR", property="newSetAddr", jdbcType=JdbcType.VARCHAR),
        @Result(column="NEW_SERVICE_CD", property="newServiceCd", jdbcType=JdbcType.VARCHAR),
        @Result(column="ORG_MEMO", property="orgMemo", jdbcType=JdbcType.VARCHAR),
        @Result(column="CONFIRM_YN", property="confirmYn", jdbcType=JdbcType.VARCHAR),
        @Result(column="UPDATE_DATE", property="updateDate", jdbcType=JdbcType.TIMESTAMP)
    })
    TCtOrgSiteChange selectByPrimaryKey(TCtOrgSiteChangeKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_CT_ORG_SITE_CHANGE
     *
     * @mbggenerated Wed Aug 06 09:08:57 KST 2014
     */
    @UpdateProvider(type=TCtOrgSiteChangeSqlProvider.class, method="updateBySpecSelective")
    int updateBySpecSelective(@Param("record") TCtOrgSiteChange record, @Param("spec") TCtOrgSiteChangeSpec spec);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_CT_ORG_SITE_CHANGE
     *
     * @mbggenerated Wed Aug 06 09:08:57 KST 2014
     */
    @UpdateProvider(type=TCtOrgSiteChangeSqlProvider.class, method="updateBySpec")
    int updateBySpec(@Param("record") TCtOrgSiteChange record, @Param("spec") TCtOrgSiteChangeSpec spec);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_CT_ORG_SITE_CHANGE
     *
     * @mbggenerated Wed Aug 06 09:08:57 KST 2014
     */
    @UpdateProvider(type=TCtOrgSiteChangeSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(TCtOrgSiteChange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_CT_ORG_SITE_CHANGE
     *
     * @mbggenerated Wed Aug 06 09:08:57 KST 2014
     */
    @Update({
        "update OP.T_CT_ORG_SITE_CHANGE",
        "set OPER_DATE = #{operDate,jdbcType=VARCHAR},",
          "NEW_ORG_SITE_CD = #{newOrgSiteCd,jdbcType=VARCHAR},",
          "NEW_ORG_SITE_NM = #{newOrgSiteNm,jdbcType=VARCHAR},",
          "NEW_OPER_TYPE = #{newOperType,jdbcType=VARCHAR},",
          "NEW_OPER_TIME = #{newOperTime,jdbcType=VARCHAR},",
          "NEW_SET_ADDR = #{newSetAddr,jdbcType=VARCHAR},",
          "NEW_SERVICE_CD = #{newServiceCd,jdbcType=VARCHAR},",
          "ORG_MEMO = #{orgMemo,jdbcType=VARCHAR},",
          "CONFIRM_YN = #{confirmYn,jdbcType=VARCHAR},",
          "UPDATE_DATE = #{updateDate,jdbcType=TIMESTAMP}",
        "where ORG_CD = #{orgCd,jdbcType=VARCHAR}",
          "and BRANCH_CD = #{branchCd,jdbcType=VARCHAR}",
          "and ORG_SITE_CD = #{orgSiteCd,jdbcType=VARCHAR}",
          "and CHANGE_DATE = #{changeDate,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(TCtOrgSiteChange record);
}