package com.nicetcm.nibsplus.broker.msg.mapper;

import com.nicetcm.nibsplus.broker.msg.model.TbPhsPushMessages;
import com.nicetcm.nibsplus.broker.msg.model.TbPhsPushMessagesSpec;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface TbPhsPushMessagesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.TB_PHS_PUSH_MESSAGES
     *
     * @mbggenerated Thu Aug 14 16:45:51 KST 2014
     */
    @SelectProvider(type=TbPhsPushMessagesSqlProvider.class, method="countBySpec")
    int countBySpec(TbPhsPushMessagesSpec spec);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.TB_PHS_PUSH_MESSAGES
     *
     * @mbggenerated Thu Aug 14 16:45:51 KST 2014
     */
    @DeleteProvider(type=TbPhsPushMessagesSqlProvider.class, method="deleteBySpec")
    int deleteBySpec(TbPhsPushMessagesSpec spec);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.TB_PHS_PUSH_MESSAGES
     *
     * @mbggenerated Thu Aug 14 16:45:51 KST 2014
     */
    @Delete({
        "delete from OP.TB_PHS_PUSH_MESSAGES",
        "where PUSH_IDX = #{pushIdx,jdbcType=DECIMAL}"
    })
    int deleteByPrimaryKey(Long pushIdx);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.TB_PHS_PUSH_MESSAGES
     *
     * @mbggenerated Thu Aug 14 16:45:51 KST 2014
     */
    @Insert({
        "insert into OP.TB_PHS_PUSH_MESSAGES (PUSH_IDX, USER_IDX, ",
        "MESSAGE, READ, STATUS, ",
        "DELIVERY_DATE, DELIVERY_TIME, ",
        "CREATE_DATE, CREATE_TIME, ",
        "WORKER, SENDER, ",
        "INSERT_GUBUN, ETC_GUBUN1, ",
        "ETC_GUBUN2, ETC_GUBUN3)",
        "values (#{pushIdx,jdbcType=DECIMAL}, #{userIdx,jdbcType=DECIMAL}, ",
        "#{message,jdbcType=VARCHAR}, #{read,jdbcType=VARCHAR}, #{status,jdbcType=VARCHAR}, ",
        "#{deliveryDate,jdbcType=VARCHAR}, #{deliveryTime,jdbcType=VARCHAR}, ",
        "#{createDate,jdbcType=VARCHAR}, #{createTime,jdbcType=VARCHAR}, ",
        "#{worker,jdbcType=VARCHAR}, #{sender,jdbcType=VARCHAR}, ",
        "#{insertGubun,jdbcType=VARCHAR}, #{etcGubun1,jdbcType=VARCHAR}, ",
        "#{etcGubun2,jdbcType=VARCHAR}, #{etcGubun3,jdbcType=VARCHAR})"
    })
    int insert(TbPhsPushMessages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.TB_PHS_PUSH_MESSAGES
     *
     * @mbggenerated Thu Aug 14 16:45:51 KST 2014
     */
    @InsertProvider(type=TbPhsPushMessagesSqlProvider.class, method="insertSelective")
    int insertSelective(TbPhsPushMessages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.TB_PHS_PUSH_MESSAGES
     *
     * @mbggenerated Thu Aug 14 16:45:51 KST 2014
     */
    @SelectProvider(type=TbPhsPushMessagesSqlProvider.class, method="selectBySpec")
    @Results({
        @Result(column="PUSH_IDX", property="pushIdx", jdbcType=JdbcType.DECIMAL, id=true),
        @Result(column="USER_IDX", property="userIdx", jdbcType=JdbcType.DECIMAL),
        @Result(column="MESSAGE", property="message", jdbcType=JdbcType.VARCHAR),
        @Result(column="READ", property="read", jdbcType=JdbcType.VARCHAR),
        @Result(column="STATUS", property="status", jdbcType=JdbcType.VARCHAR),
        @Result(column="DELIVERY_DATE", property="deliveryDate", jdbcType=JdbcType.VARCHAR),
        @Result(column="DELIVERY_TIME", property="deliveryTime", jdbcType=JdbcType.VARCHAR),
        @Result(column="CREATE_DATE", property="createDate", jdbcType=JdbcType.VARCHAR),
        @Result(column="CREATE_TIME", property="createTime", jdbcType=JdbcType.VARCHAR),
        @Result(column="WORKER", property="worker", jdbcType=JdbcType.VARCHAR),
        @Result(column="SENDER", property="sender", jdbcType=JdbcType.VARCHAR),
        @Result(column="INSERT_GUBUN", property="insertGubun", jdbcType=JdbcType.VARCHAR),
        @Result(column="ETC_GUBUN1", property="etcGubun1", jdbcType=JdbcType.VARCHAR),
        @Result(column="ETC_GUBUN2", property="etcGubun2", jdbcType=JdbcType.VARCHAR),
        @Result(column="ETC_GUBUN3", property="etcGubun3", jdbcType=JdbcType.VARCHAR)
    })
    List<TbPhsPushMessages> selectBySpec(TbPhsPushMessagesSpec spec);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.TB_PHS_PUSH_MESSAGES
     *
     * @mbggenerated Thu Aug 14 16:45:51 KST 2014
     */
    @Select({
        "select",
        "PUSH_IDX, USER_IDX, MESSAGE, READ, STATUS, DELIVERY_DATE, DELIVERY_TIME, CREATE_DATE, ",
        "CREATE_TIME, WORKER, SENDER, INSERT_GUBUN, ETC_GUBUN1, ETC_GUBUN2, ETC_GUBUN3",
        "from OP.TB_PHS_PUSH_MESSAGES",
        "where PUSH_IDX = #{pushIdx,jdbcType=DECIMAL}"
    })
    @Results({
        @Result(column="PUSH_IDX", property="pushIdx", jdbcType=JdbcType.DECIMAL, id=true),
        @Result(column="USER_IDX", property="userIdx", jdbcType=JdbcType.DECIMAL),
        @Result(column="MESSAGE", property="message", jdbcType=JdbcType.VARCHAR),
        @Result(column="READ", property="read", jdbcType=JdbcType.VARCHAR),
        @Result(column="STATUS", property="status", jdbcType=JdbcType.VARCHAR),
        @Result(column="DELIVERY_DATE", property="deliveryDate", jdbcType=JdbcType.VARCHAR),
        @Result(column="DELIVERY_TIME", property="deliveryTime", jdbcType=JdbcType.VARCHAR),
        @Result(column="CREATE_DATE", property="createDate", jdbcType=JdbcType.VARCHAR),
        @Result(column="CREATE_TIME", property="createTime", jdbcType=JdbcType.VARCHAR),
        @Result(column="WORKER", property="worker", jdbcType=JdbcType.VARCHAR),
        @Result(column="SENDER", property="sender", jdbcType=JdbcType.VARCHAR),
        @Result(column="INSERT_GUBUN", property="insertGubun", jdbcType=JdbcType.VARCHAR),
        @Result(column="ETC_GUBUN1", property="etcGubun1", jdbcType=JdbcType.VARCHAR),
        @Result(column="ETC_GUBUN2", property="etcGubun2", jdbcType=JdbcType.VARCHAR),
        @Result(column="ETC_GUBUN3", property="etcGubun3", jdbcType=JdbcType.VARCHAR)
    })
    TbPhsPushMessages selectByPrimaryKey(Long pushIdx);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.TB_PHS_PUSH_MESSAGES
     *
     * @mbggenerated Thu Aug 14 16:45:51 KST 2014
     */
    @UpdateProvider(type=TbPhsPushMessagesSqlProvider.class, method="updateBySpecSelective")
    int updateBySpecSelective(@Param("record") TbPhsPushMessages record, @Param("spec") TbPhsPushMessagesSpec spec);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.TB_PHS_PUSH_MESSAGES
     *
     * @mbggenerated Thu Aug 14 16:45:51 KST 2014
     */
    @UpdateProvider(type=TbPhsPushMessagesSqlProvider.class, method="updateBySpec")
    int updateBySpec(@Param("record") TbPhsPushMessages record, @Param("spec") TbPhsPushMessagesSpec spec);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.TB_PHS_PUSH_MESSAGES
     *
     * @mbggenerated Thu Aug 14 16:45:51 KST 2014
     */
    @UpdateProvider(type=TbPhsPushMessagesSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(TbPhsPushMessages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.TB_PHS_PUSH_MESSAGES
     *
     * @mbggenerated Thu Aug 14 16:45:51 KST 2014
     */
    @Update({
        "update OP.TB_PHS_PUSH_MESSAGES",
        "set USER_IDX = #{userIdx,jdbcType=DECIMAL},",
          "MESSAGE = #{message,jdbcType=VARCHAR},",
          "READ = #{read,jdbcType=VARCHAR},",
          "STATUS = #{status,jdbcType=VARCHAR},",
          "DELIVERY_DATE = #{deliveryDate,jdbcType=VARCHAR},",
          "DELIVERY_TIME = #{deliveryTime,jdbcType=VARCHAR},",
          "CREATE_DATE = #{createDate,jdbcType=VARCHAR},",
          "CREATE_TIME = #{createTime,jdbcType=VARCHAR},",
          "WORKER = #{worker,jdbcType=VARCHAR},",
          "SENDER = #{sender,jdbcType=VARCHAR},",
          "INSERT_GUBUN = #{insertGubun,jdbcType=VARCHAR},",
          "ETC_GUBUN1 = #{etcGubun1,jdbcType=VARCHAR},",
          "ETC_GUBUN2 = #{etcGubun2,jdbcType=VARCHAR},",
          "ETC_GUBUN3 = #{etcGubun3,jdbcType=VARCHAR}",
        "where PUSH_IDX = #{pushIdx,jdbcType=DECIMAL}"
    })
    int updateByPrimaryKey(TbPhsPushMessages record);
}