package com.nicetcm.nibsplus.broker.msg.mapper;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.DELETE_FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.ORDER_BY;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT_DISTINCT;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import com.nicetcm.nibsplus.broker.msg.model.TCmSiteState;
import com.nicetcm.nibsplus.broker.msg.model.TCmSiteStateSpec.Criteria;
import com.nicetcm.nibsplus.broker.msg.model.TCmSiteStateSpec.Criterion;
import com.nicetcm.nibsplus.broker.msg.model.TCmSiteStateSpec;
import java.util.List;
import java.util.Map;

public class TCmSiteStateSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_CM_SITE_STATE
     *
     * @mbggenerated Wed Aug 06 09:58:31 KST 2014
     */
    public String countBySpec(TCmSiteStateSpec spec) {
        BEGIN();
        SELECT("count(*)");
        FROM("OP.T_CM_SITE_STATE");
        applyWhere(spec, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_CM_SITE_STATE
     *
     * @mbggenerated Wed Aug 06 09:58:31 KST 2014
     */
    public String deleteBySpec(TCmSiteStateSpec spec) {
        BEGIN();
        DELETE_FROM("OP.T_CM_SITE_STATE");
        applyWhere(spec, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_CM_SITE_STATE
     *
     * @mbggenerated Wed Aug 06 09:58:31 KST 2014
     */
    public String insertSelective(TCmSiteState record) {
        BEGIN();
        INSERT_INTO("OP.T_CM_SITE_STATE");

        if (record.getOrgCd() != null) {
            VALUES("ORG_CD", "#{orgCd,jdbcType=VARCHAR}");
        }

        if (record.getBranchCd() != null) {
            VALUES("BRANCH_CD", "#{branchCd,jdbcType=VARCHAR}");
        }

        if (record.getSiteCd() != null) {
            VALUES("SITE_CD", "#{siteCd,jdbcType=VARCHAR}");
        }

        if (record.getMacNo() != null) {
            VALUES("MAC_NO", "#{macNo,jdbcType=VARCHAR}");
        }

        if (record.getSiteNm() != null) {
            VALUES("SITE_NM", "#{siteNm,jdbcType=VARCHAR}");
        }

        if (record.getSetDetail() != null) {
            VALUES("SET_DETAIL", "#{setDetail,jdbcType=VARCHAR}");
        }

        if (record.getSetType() != null) {
            VALUES("SET_TYPE", "#{setType,jdbcType=VARCHAR}");
        }

        if (record.getMacType() != null) {
            VALUES("MAC_TYPE", "#{macType,jdbcType=VARCHAR}");
        }

        if (record.getBoothType() != null) {
            VALUES("BOOTH_TYPE", "#{boothType,jdbcType=VARCHAR}");
        }

        if (record.getMonthFee() != null) {
            VALUES("MONTH_FEE", "#{monthFee,jdbcType=VARCHAR}");
        }

        if (record.getStateCd() != null) {
            VALUES("STATE_CD", "#{stateCd,jdbcType=VARCHAR}");
        }

        if (record.getWorkDate() != null) {
            VALUES("WORK_DATE", "#{workDate,jdbcType=VARCHAR}");
        }

        if (record.getWorkTimeFr() != null) {
            VALUES("WORK_TIME_FR", "#{workTimeFr,jdbcType=VARCHAR}");
        }

        if (record.getWorkTimeTo() != null) {
            VALUES("WORK_TIME_TO", "#{workTimeTo,jdbcType=VARCHAR}");
        }

        if (record.getWorkMemo() != null) {
            VALUES("WORK_MEMO", "#{workMemo,jdbcType=VARCHAR}");
        }

        if (record.getSiteGb() != null) {
            VALUES("SITE_GB", "#{siteGb,jdbcType=VARCHAR}");
        }

        if (record.getSiteClss() != null) {
            VALUES("SITE_CLSS", "#{siteClss,jdbcType=VARCHAR}");
        }

        if (record.getMngBranchCd() != null) {
            VALUES("MNG_BRANCH_CD", "#{mngBranchCd,jdbcType=VARCHAR}");
        }

        if (record.getRentFee() != null) {
            VALUES("RENT_FEE", "#{rentFee,jdbcType=VARCHAR}");
        }

        if (record.getPubTelNo() != null) {
            VALUES("PUB_TEL_NO", "#{pubTelNo,jdbcType=VARCHAR}");
        }

        if (record.getOrgSendYn() != null) {
            VALUES("ORG_SEND_YN", "#{orgSendYn,jdbcType=VARCHAR}");
        }

        if (record.getUpdateDate() != null) {
            VALUES("UPDATE_DATE", "#{updateDate,jdbcType=TIMESTAMP}");
        }

        if (record.getUpdateUid() != null) {
            VALUES("UPDATE_UID", "#{updateUid,jdbcType=VARCHAR}");
        }

        if (record.getEnvBranchCd() != null) {
            VALUES("ENV_BRANCH_CD", "#{envBranchCd,jdbcType=VARCHAR}");
        }

        if (record.getBankbookYn() != null) {
            VALUES("BANKBOOK_YN", "#{bankbookYn,jdbcType=VARCHAR}");
        }

        if (record.getBrandOrgCd() != null) {
            VALUES("BRAND_ORG_CD", "#{brandOrgCd,jdbcType=VARCHAR}");
        }

        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_CM_SITE_STATE
     *
     * @mbggenerated Wed Aug 06 09:58:31 KST 2014
     */
    public String selectBySpec(TCmSiteStateSpec spec) {
        BEGIN();
        if (spec != null && spec.isDistinct()) {
            SELECT_DISTINCT("ORG_CD");
        } else {
            SELECT("ORG_CD");
        }
        SELECT("BRANCH_CD");
        SELECT("SITE_CD");
        SELECT("MAC_NO");
        SELECT("SITE_NM");
        SELECT("SET_DETAIL");
        SELECT("SET_TYPE");
        SELECT("MAC_TYPE");
        SELECT("BOOTH_TYPE");
        SELECT("MONTH_FEE");
        SELECT("STATE_CD");
        SELECT("WORK_DATE");
        SELECT("WORK_TIME_FR");
        SELECT("WORK_TIME_TO");
        SELECT("WORK_MEMO");
        SELECT("SITE_GB");
        SELECT("SITE_CLSS");
        SELECT("MNG_BRANCH_CD");
        SELECT("RENT_FEE");
        SELECT("PUB_TEL_NO");
        SELECT("ORG_SEND_YN");
        SELECT("UPDATE_DATE");
        SELECT("UPDATE_UID");
        SELECT("ENV_BRANCH_CD");
        SELECT("BANKBOOK_YN");
        SELECT("BRAND_ORG_CD");
        FROM("OP.T_CM_SITE_STATE");
        applyWhere(spec, false);

        if (spec != null && spec.getOrderByClause() != null) {
            ORDER_BY(spec.getOrderByClause());
        }

        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_CM_SITE_STATE
     *
     * @mbggenerated Wed Aug 06 09:58:31 KST 2014
     */
    public String updateBySpecSelective(Map<String, Object> parameter) {
        TCmSiteState record = (TCmSiteState) parameter.get("record");
        TCmSiteStateSpec spec = (TCmSiteStateSpec) parameter.get("spec");

        BEGIN();
        UPDATE("OP.T_CM_SITE_STATE");

        if (record.getOrgCd() != null) {
            SET("ORG_CD = #{record.orgCd,jdbcType=VARCHAR}");
        }

        if (record.getBranchCd() != null) {
            SET("BRANCH_CD = #{record.branchCd,jdbcType=VARCHAR}");
        }

        if (record.getSiteCd() != null) {
            SET("SITE_CD = #{record.siteCd,jdbcType=VARCHAR}");
        }

        if (record.getMacNo() != null) {
            SET("MAC_NO = #{record.macNo,jdbcType=VARCHAR}");
        }

        if (record.getSiteNm() != null) {
            SET("SITE_NM = #{record.siteNm,jdbcType=VARCHAR}");
        }

        if (record.getSetDetail() != null) {
            SET("SET_DETAIL = #{record.setDetail,jdbcType=VARCHAR}");
        }

        if (record.getSetType() != null) {
            SET("SET_TYPE = #{record.setType,jdbcType=VARCHAR}");
        }

        if (record.getMacType() != null) {
            SET("MAC_TYPE = #{record.macType,jdbcType=VARCHAR}");
        }

        if (record.getBoothType() != null) {
            SET("BOOTH_TYPE = #{record.boothType,jdbcType=VARCHAR}");
        }

        if (record.getMonthFee() != null) {
            SET("MONTH_FEE = #{record.monthFee,jdbcType=VARCHAR}");
        }

        if (record.getStateCd() != null) {
            SET("STATE_CD = #{record.stateCd,jdbcType=VARCHAR}");
        }

        if (record.getWorkDate() != null) {
            SET("WORK_DATE = #{record.workDate,jdbcType=VARCHAR}");
        }

        if (record.getWorkTimeFr() != null) {
            SET("WORK_TIME_FR = #{record.workTimeFr,jdbcType=VARCHAR}");
        }

        if (record.getWorkTimeTo() != null) {
            SET("WORK_TIME_TO = #{record.workTimeTo,jdbcType=VARCHAR}");
        }

        if (record.getWorkMemo() != null) {
            SET("WORK_MEMO = #{record.workMemo,jdbcType=VARCHAR}");
        }

        if (record.getSiteGb() != null) {
            SET("SITE_GB = #{record.siteGb,jdbcType=VARCHAR}");
        }

        if (record.getSiteClss() != null) {
            SET("SITE_CLSS = #{record.siteClss,jdbcType=VARCHAR}");
        }

        if (record.getMngBranchCd() != null) {
            SET("MNG_BRANCH_CD = #{record.mngBranchCd,jdbcType=VARCHAR}");
        }

        if (record.getRentFee() != null) {
            SET("RENT_FEE = #{record.rentFee,jdbcType=VARCHAR}");
        }

        if (record.getPubTelNo() != null) {
            SET("PUB_TEL_NO = #{record.pubTelNo,jdbcType=VARCHAR}");
        }

        if (record.getOrgSendYn() != null) {
            SET("ORG_SEND_YN = #{record.orgSendYn,jdbcType=VARCHAR}");
        }

        if (record.getUpdateDate() != null) {
            SET("UPDATE_DATE = #{record.updateDate,jdbcType=TIMESTAMP}");
        }

        if (record.getUpdateUid() != null) {
            SET("UPDATE_UID = #{record.updateUid,jdbcType=VARCHAR}");
        }

        if (record.getEnvBranchCd() != null) {
            SET("ENV_BRANCH_CD = #{record.envBranchCd,jdbcType=VARCHAR}");
        }

        if (record.getBankbookYn() != null) {
            SET("BANKBOOK_YN = #{record.bankbookYn,jdbcType=VARCHAR}");
        }

        if (record.getBrandOrgCd() != null) {
            SET("BRAND_ORG_CD = #{record.brandOrgCd,jdbcType=VARCHAR}");
        }

        applyWhere(spec, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_CM_SITE_STATE
     *
     * @mbggenerated Wed Aug 06 09:58:31 KST 2014
     */
    public String updateBySpec(Map<String, Object> parameter) {
        BEGIN();
        UPDATE("OP.T_CM_SITE_STATE");

        SET("ORG_CD = #{record.orgCd,jdbcType=VARCHAR}");
        SET("BRANCH_CD = #{record.branchCd,jdbcType=VARCHAR}");
        SET("SITE_CD = #{record.siteCd,jdbcType=VARCHAR}");
        SET("MAC_NO = #{record.macNo,jdbcType=VARCHAR}");
        SET("SITE_NM = #{record.siteNm,jdbcType=VARCHAR}");
        SET("SET_DETAIL = #{record.setDetail,jdbcType=VARCHAR}");
        SET("SET_TYPE = #{record.setType,jdbcType=VARCHAR}");
        SET("MAC_TYPE = #{record.macType,jdbcType=VARCHAR}");
        SET("BOOTH_TYPE = #{record.boothType,jdbcType=VARCHAR}");
        SET("MONTH_FEE = #{record.monthFee,jdbcType=VARCHAR}");
        SET("STATE_CD = #{record.stateCd,jdbcType=VARCHAR}");
        SET("WORK_DATE = #{record.workDate,jdbcType=VARCHAR}");
        SET("WORK_TIME_FR = #{record.workTimeFr,jdbcType=VARCHAR}");
        SET("WORK_TIME_TO = #{record.workTimeTo,jdbcType=VARCHAR}");
        SET("WORK_MEMO = #{record.workMemo,jdbcType=VARCHAR}");
        SET("SITE_GB = #{record.siteGb,jdbcType=VARCHAR}");
        SET("SITE_CLSS = #{record.siteClss,jdbcType=VARCHAR}");
        SET("MNG_BRANCH_CD = #{record.mngBranchCd,jdbcType=VARCHAR}");
        SET("RENT_FEE = #{record.rentFee,jdbcType=VARCHAR}");
        SET("PUB_TEL_NO = #{record.pubTelNo,jdbcType=VARCHAR}");
        SET("ORG_SEND_YN = #{record.orgSendYn,jdbcType=VARCHAR}");
        SET("UPDATE_DATE = #{record.updateDate,jdbcType=TIMESTAMP}");
        SET("UPDATE_UID = #{record.updateUid,jdbcType=VARCHAR}");
        SET("ENV_BRANCH_CD = #{record.envBranchCd,jdbcType=VARCHAR}");
        SET("BANKBOOK_YN = #{record.bankbookYn,jdbcType=VARCHAR}");
        SET("BRAND_ORG_CD = #{record.brandOrgCd,jdbcType=VARCHAR}");

        TCmSiteStateSpec spec = (TCmSiteStateSpec) parameter.get("spec");
        applyWhere(spec, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_CM_SITE_STATE
     *
     * @mbggenerated Wed Aug 06 09:58:31 KST 2014
     */
    public String updateByPrimaryKeySelective(TCmSiteState record) {
        BEGIN();
        UPDATE("OP.T_CM_SITE_STATE");

        if (record.getSiteNm() != null) {
            SET("SITE_NM = #{siteNm,jdbcType=VARCHAR}");
        }

        if (record.getSetDetail() != null) {
            SET("SET_DETAIL = #{setDetail,jdbcType=VARCHAR}");
        }

        if (record.getSetType() != null) {
            SET("SET_TYPE = #{setType,jdbcType=VARCHAR}");
        }

        if (record.getMacType() != null) {
            SET("MAC_TYPE = #{macType,jdbcType=VARCHAR}");
        }

        if (record.getBoothType() != null) {
            SET("BOOTH_TYPE = #{boothType,jdbcType=VARCHAR}");
        }

        if (record.getMonthFee() != null) {
            SET("MONTH_FEE = #{monthFee,jdbcType=VARCHAR}");
        }

        if (record.getStateCd() != null) {
            SET("STATE_CD = #{stateCd,jdbcType=VARCHAR}");
        }

        if (record.getWorkDate() != null) {
            SET("WORK_DATE = #{workDate,jdbcType=VARCHAR}");
        }

        if (record.getWorkTimeFr() != null) {
            SET("WORK_TIME_FR = #{workTimeFr,jdbcType=VARCHAR}");
        }

        if (record.getWorkTimeTo() != null) {
            SET("WORK_TIME_TO = #{workTimeTo,jdbcType=VARCHAR}");
        }

        if (record.getWorkMemo() != null) {
            SET("WORK_MEMO = #{workMemo,jdbcType=VARCHAR}");
        }

        if (record.getSiteGb() != null) {
            SET("SITE_GB = #{siteGb,jdbcType=VARCHAR}");
        }

        if (record.getSiteClss() != null) {
            SET("SITE_CLSS = #{siteClss,jdbcType=VARCHAR}");
        }

        if (record.getMngBranchCd() != null) {
            SET("MNG_BRANCH_CD = #{mngBranchCd,jdbcType=VARCHAR}");
        }

        if (record.getRentFee() != null) {
            SET("RENT_FEE = #{rentFee,jdbcType=VARCHAR}");
        }

        if (record.getPubTelNo() != null) {
            SET("PUB_TEL_NO = #{pubTelNo,jdbcType=VARCHAR}");
        }

        if (record.getOrgSendYn() != null) {
            SET("ORG_SEND_YN = #{orgSendYn,jdbcType=VARCHAR}");
        }

        if (record.getUpdateDate() != null) {
            SET("UPDATE_DATE = #{updateDate,jdbcType=TIMESTAMP}");
        }

        if (record.getUpdateUid() != null) {
            SET("UPDATE_UID = #{updateUid,jdbcType=VARCHAR}");
        }

        if (record.getEnvBranchCd() != null) {
            SET("ENV_BRANCH_CD = #{envBranchCd,jdbcType=VARCHAR}");
        }

        if (record.getBankbookYn() != null) {
            SET("BANKBOOK_YN = #{bankbookYn,jdbcType=VARCHAR}");
        }

        if (record.getBrandOrgCd() != null) {
            SET("BRAND_ORG_CD = #{brandOrgCd,jdbcType=VARCHAR}");
        }

        WHERE("ORG_CD = #{orgCd,jdbcType=VARCHAR}");
        WHERE("BRANCH_CD = #{branchCd,jdbcType=VARCHAR}");
        WHERE("SITE_CD = #{siteCd,jdbcType=VARCHAR}");
        WHERE("MAC_NO = #{macNo,jdbcType=VARCHAR}");

        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_CM_SITE_STATE
     *
     * @mbggenerated Wed Aug 06 09:58:31 KST 2014
     */
    protected void applyWhere(TCmSiteStateSpec spec, boolean includeSpecPhrase) {
        if (spec == null) {
            return;
        }

        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeSpecPhrase) {
            parmPhrase1 = "%s #{spec.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{spec.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{spec.oredCriteria[%d].allCriteria[%d].value} and #{spec.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{spec.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{spec.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{spec.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{spec.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }

        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = spec.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }

                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }

                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }

        if (sb.length() > 0) {
            WHERE(sb.toString());
        }
    }
}