package com.nicetcm.nibsplus.broker.msg.mapper;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.DELETE_FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.ORDER_BY;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT_DISTINCT;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import com.nicetcm.nibsplus.broker.msg.model.TCmSetSiteInfo;
import com.nicetcm.nibsplus.broker.msg.model.TCmSetSiteInfoSpec.Criteria;
import com.nicetcm.nibsplus.broker.msg.model.TCmSetSiteInfoSpec.Criterion;
import com.nicetcm.nibsplus.broker.msg.model.TCmSetSiteInfoSpec;
import java.util.List;
import java.util.Map;

public class TCmSetSiteInfoSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_CM_SET_SITE_INFO
     *
     * @mbggenerated Thu Aug 07 09:04:14 KST 2014
     */
    public String countBySpec(TCmSetSiteInfoSpec spec) {
        BEGIN();
        SELECT("count(*)");
        FROM("OP.T_CM_SET_SITE_INFO");
        applyWhere(spec, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_CM_SET_SITE_INFO
     *
     * @mbggenerated Thu Aug 07 09:04:14 KST 2014
     */
    public String deleteBySpec(TCmSetSiteInfoSpec spec) {
        BEGIN();
        DELETE_FROM("OP.T_CM_SET_SITE_INFO");
        applyWhere(spec, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_CM_SET_SITE_INFO
     *
     * @mbggenerated Thu Aug 07 09:04:14 KST 2014
     */
    public String insertSelective(TCmSetSiteInfo record) {
        BEGIN();
        INSERT_INTO("OP.T_CM_SET_SITE_INFO");

        if (record.getOrgCd() != null) {
            VALUES("ORG_CD", "#{orgCd,jdbcType=VARCHAR}");
        }

        if (record.getWorkSeq() != null) {
            VALUES("WORK_SEQ", "#{workSeq,jdbcType=VARCHAR}");
        }

        if (record.getWorkClass() != null) {
            VALUES("WORK_CLASS", "#{workClass,jdbcType=VARCHAR}");
        }

        if (record.getChangeNo() != null) {
            VALUES("CHANGE_NO", "#{changeNo,jdbcType=DECIMAL}");
        }

        if (record.getOrgBranchCd() != null) {
            VALUES("ORG_BRANCH_CD", "#{orgBranchCd,jdbcType=VARCHAR}");
        }

        if (record.getOrgBranchNm() != null) {
            VALUES("ORG_BRANCH_NM", "#{orgBranchNm,jdbcType=VARCHAR}");
        }

        if (record.getOrgSiteCd() != null) {
            VALUES("ORG_SITE_CD", "#{orgSiteCd,jdbcType=VARCHAR}");
        }

        if (record.getOrgSiteNm() != null) {
            VALUES("ORG_SITE_NM", "#{orgSiteNm,jdbcType=VARCHAR}");
        }

        if (record.getPlaceType() != null) {
            VALUES("PLACE_TYPE", "#{placeType,jdbcType=VARCHAR}");
        }

        if (record.getJpType() != null) {
            VALUES("JP_TYPE", "#{jpType,jdbcType=VARCHAR}");
        }

        if (record.getSpecialType() != null) {
            VALUES("SPECIAL_TYPE", "#{specialType,jdbcType=VARCHAR}");
        }

        if (record.getOperTimeType() != null) {
            VALUES("OPER_TIME_TYPE", "#{operTimeType,jdbcType=VARCHAR}");
        }

        if (record.getOperStartTime() != null) {
            VALUES("OPER_START_TIME", "#{operStartTime,jdbcType=VARCHAR}");
        }

        if (record.getOperEndTime() != null) {
            VALUES("OPER_END_TIME", "#{operEndTime,jdbcType=VARCHAR}");
        }

        if (record.getOperDay() != null) {
            VALUES("OPER_DAY", "#{operDay,jdbcType=VARCHAR}");
        }

        if (record.getOperCheckYn() != null) {
            VALUES("OPER_CHECK_YN", "#{operCheckYn,jdbcType=VARCHAR}");
        }

        if (record.getServiceFee() != null) {
            VALUES("SERVICE_FEE", "#{serviceFee,jdbcType=VARCHAR}");
        }

        if (record.getGuardCd() != null) {
            VALUES("GUARD_CD", "#{guardCd,jdbcType=VARCHAR}");
        }

        if (record.getGuardNm() != null) {
            VALUES("GUARD_NM", "#{guardNm,jdbcType=VARCHAR}");
        }

        if (record.getFacilRentYn() != null) {
            VALUES("FACIL_RENT_YN", "#{facilRentYn,jdbcType=VARCHAR}");
        }

        if (record.getSetAddr() != null) {
            VALUES("SET_ADDR", "#{setAddr,jdbcType=VARCHAR}");
        }

        if (record.getSetPlace() != null) {
            VALUES("SET_PLACE", "#{setPlace,jdbcType=VARCHAR}");
        }

        if (record.getMsg() != null) {
            VALUES("MSG", "#{msg,jdbcType=VARCHAR}");
        }

        if (record.getWorkResult() != null) {
            VALUES("WORK_RESULT", "#{workResult,jdbcType=VARCHAR}");
        }

        if (record.getUpdateDate() != null) {
            VALUES("UPDATE_DATE", "#{updateDate,jdbcType=TIMESTAMP}");
        }

        if (record.getUpdateUid() != null) {
            VALUES("UPDATE_UID", "#{updateUid,jdbcType=VARCHAR}");
        }

        if (record.getDataType() != null) {
            VALUES("DATA_TYPE", "#{dataType,jdbcType=VARCHAR}");
        }

        if (record.getOperStartTimeH() != null) {
            VALUES("OPER_START_TIME_H", "#{operStartTimeH,jdbcType=VARCHAR}");
        }

        if (record.getOperEndTimeH() != null) {
            VALUES("OPER_END_TIME_H", "#{operEndTimeH,jdbcType=VARCHAR}");
        }

        if (record.getOutStartTime() != null) {
            VALUES("OUT_START_TIME", "#{outStartTime,jdbcType=VARCHAR}");
        }

        if (record.getOutEndTime() != null) {
            VALUES("OUT_END_TIME", "#{outEndTime,jdbcType=VARCHAR}");
        }

        if (record.getOutStartTimeH() != null) {
            VALUES("OUT_START_TIME_H", "#{outStartTimeH,jdbcType=VARCHAR}");
        }

        if (record.getOutEndTimeH() != null) {
            VALUES("OUT_END_TIME_H", "#{outEndTimeH,jdbcType=VARCHAR}");
        }

        if (record.getOutComCd() != null) {
            VALUES("OUT_COM_CD", "#{outComCd,jdbcType=VARCHAR}");
        }

        if (record.getCleanComCd() != null) {
            VALUES("CLEAN_COM_CD", "#{cleanComCd,jdbcType=VARCHAR}");
        }

        if (record.getSetDate() != null) {
            VALUES("SET_DATE", "#{setDate,jdbcType=VARCHAR}");
        }

        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_CM_SET_SITE_INFO
     *
     * @mbggenerated Thu Aug 07 09:04:14 KST 2014
     */
    public String selectBySpec(TCmSetSiteInfoSpec spec) {
        BEGIN();
        if (spec != null && spec.isDistinct()) {
            SELECT_DISTINCT("ORG_CD");
        } else {
            SELECT("ORG_CD");
        }
        SELECT("WORK_SEQ");
        SELECT("WORK_CLASS");
        SELECT("CHANGE_NO");
        SELECT("ORG_BRANCH_CD");
        SELECT("ORG_BRANCH_NM");
        SELECT("ORG_SITE_CD");
        SELECT("ORG_SITE_NM");
        SELECT("PLACE_TYPE");
        SELECT("JP_TYPE");
        SELECT("SPECIAL_TYPE");
        SELECT("OPER_TIME_TYPE");
        SELECT("OPER_START_TIME");
        SELECT("OPER_END_TIME");
        SELECT("OPER_DAY");
        SELECT("OPER_CHECK_YN");
        SELECT("SERVICE_FEE");
        SELECT("GUARD_CD");
        SELECT("GUARD_NM");
        SELECT("FACIL_RENT_YN");
        SELECT("SET_ADDR");
        SELECT("SET_PLACE");
        SELECT("MSG");
        SELECT("WORK_RESULT");
        SELECT("UPDATE_DATE");
        SELECT("UPDATE_UID");
        SELECT("DATA_TYPE");
        SELECT("OPER_START_TIME_H");
        SELECT("OPER_END_TIME_H");
        SELECT("OUT_START_TIME");
        SELECT("OUT_END_TIME");
        SELECT("OUT_START_TIME_H");
        SELECT("OUT_END_TIME_H");
        SELECT("OUT_COM_CD");
        SELECT("CLEAN_COM_CD");
        SELECT("SET_DATE");
        FROM("OP.T_CM_SET_SITE_INFO");
        applyWhere(spec, false);

        if (spec != null && spec.getOrderByClause() != null) {
            ORDER_BY(spec.getOrderByClause());
        }

        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_CM_SET_SITE_INFO
     *
     * @mbggenerated Thu Aug 07 09:04:14 KST 2014
     */
    public String updateBySpecSelective(Map<String, Object> parameter) {
        TCmSetSiteInfo record = (TCmSetSiteInfo) parameter.get("record");
        TCmSetSiteInfoSpec spec = (TCmSetSiteInfoSpec) parameter.get("spec");

        BEGIN();
        UPDATE("OP.T_CM_SET_SITE_INFO");

        if (record.getOrgCd() != null) {
            SET("ORG_CD = #{record.orgCd,jdbcType=VARCHAR}");
        }

        if (record.getWorkSeq() != null) {
            SET("WORK_SEQ = #{record.workSeq,jdbcType=VARCHAR}");
        }

        if (record.getWorkClass() != null) {
            SET("WORK_CLASS = #{record.workClass,jdbcType=VARCHAR}");
        }

        if (record.getChangeNo() != null) {
            SET("CHANGE_NO = #{record.changeNo,jdbcType=DECIMAL}");
        }

        if (record.getOrgBranchCd() != null) {
            SET("ORG_BRANCH_CD = #{record.orgBranchCd,jdbcType=VARCHAR}");
        }

        if (record.getOrgBranchNm() != null) {
            SET("ORG_BRANCH_NM = #{record.orgBranchNm,jdbcType=VARCHAR}");
        }

        if (record.getOrgSiteCd() != null) {
            SET("ORG_SITE_CD = #{record.orgSiteCd,jdbcType=VARCHAR}");
        }

        if (record.getOrgSiteNm() != null) {
            SET("ORG_SITE_NM = #{record.orgSiteNm,jdbcType=VARCHAR}");
        }

        if (record.getPlaceType() != null) {
            SET("PLACE_TYPE = #{record.placeType,jdbcType=VARCHAR}");
        }

        if (record.getJpType() != null) {
            SET("JP_TYPE = #{record.jpType,jdbcType=VARCHAR}");
        }

        if (record.getSpecialType() != null) {
            SET("SPECIAL_TYPE = #{record.specialType,jdbcType=VARCHAR}");
        }

        if (record.getOperTimeType() != null) {
            SET("OPER_TIME_TYPE = #{record.operTimeType,jdbcType=VARCHAR}");
        }

        if (record.getOperStartTime() != null) {
            SET("OPER_START_TIME = #{record.operStartTime,jdbcType=VARCHAR}");
        }

        if (record.getOperEndTime() != null) {
            SET("OPER_END_TIME = #{record.operEndTime,jdbcType=VARCHAR}");
        }

        if (record.getOperDay() != null) {
            SET("OPER_DAY = #{record.operDay,jdbcType=VARCHAR}");
        }

        if (record.getOperCheckYn() != null) {
            SET("OPER_CHECK_YN = #{record.operCheckYn,jdbcType=VARCHAR}");
        }

        if (record.getServiceFee() != null) {
            SET("SERVICE_FEE = #{record.serviceFee,jdbcType=VARCHAR}");
        }

        if (record.getGuardCd() != null) {
            SET("GUARD_CD = #{record.guardCd,jdbcType=VARCHAR}");
        }

        if (record.getGuardNm() != null) {
            SET("GUARD_NM = #{record.guardNm,jdbcType=VARCHAR}");
        }

        if (record.getFacilRentYn() != null) {
            SET("FACIL_RENT_YN = #{record.facilRentYn,jdbcType=VARCHAR}");
        }

        if (record.getSetAddr() != null) {
            SET("SET_ADDR = #{record.setAddr,jdbcType=VARCHAR}");
        }

        if (record.getSetPlace() != null) {
            SET("SET_PLACE = #{record.setPlace,jdbcType=VARCHAR}");
        }

        if (record.getMsg() != null) {
            SET("MSG = #{record.msg,jdbcType=VARCHAR}");
        }

        if (record.getWorkResult() != null) {
            SET("WORK_RESULT = #{record.workResult,jdbcType=VARCHAR}");
        }

        if (record.getUpdateDate() != null) {
            SET("UPDATE_DATE = #{record.updateDate,jdbcType=TIMESTAMP}");
        }

        if (record.getUpdateUid() != null) {
            SET("UPDATE_UID = #{record.updateUid,jdbcType=VARCHAR}");
        }

        if (record.getDataType() != null) {
            SET("DATA_TYPE = #{record.dataType,jdbcType=VARCHAR}");
        }

        if (record.getOperStartTimeH() != null) {
            SET("OPER_START_TIME_H = #{record.operStartTimeH,jdbcType=VARCHAR}");
        }

        if (record.getOperEndTimeH() != null) {
            SET("OPER_END_TIME_H = #{record.operEndTimeH,jdbcType=VARCHAR}");
        }

        if (record.getOutStartTime() != null) {
            SET("OUT_START_TIME = #{record.outStartTime,jdbcType=VARCHAR}");
        }

        if (record.getOutEndTime() != null) {
            SET("OUT_END_TIME = #{record.outEndTime,jdbcType=VARCHAR}");
        }

        if (record.getOutStartTimeH() != null) {
            SET("OUT_START_TIME_H = #{record.outStartTimeH,jdbcType=VARCHAR}");
        }

        if (record.getOutEndTimeH() != null) {
            SET("OUT_END_TIME_H = #{record.outEndTimeH,jdbcType=VARCHAR}");
        }

        if (record.getOutComCd() != null) {
            SET("OUT_COM_CD = #{record.outComCd,jdbcType=VARCHAR}");
        }

        if (record.getCleanComCd() != null) {
            SET("CLEAN_COM_CD = #{record.cleanComCd,jdbcType=VARCHAR}");
        }

        if (record.getSetDate() != null) {
            SET("SET_DATE = #{record.setDate,jdbcType=VARCHAR}");
        }

        applyWhere(spec, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_CM_SET_SITE_INFO
     *
     * @mbggenerated Thu Aug 07 09:04:14 KST 2014
     */
    public String updateBySpec(Map<String, Object> parameter) {
        BEGIN();
        UPDATE("OP.T_CM_SET_SITE_INFO");

        SET("ORG_CD = #{record.orgCd,jdbcType=VARCHAR}");
        SET("WORK_SEQ = #{record.workSeq,jdbcType=VARCHAR}");
        SET("WORK_CLASS = #{record.workClass,jdbcType=VARCHAR}");
        SET("CHANGE_NO = #{record.changeNo,jdbcType=DECIMAL}");
        SET("ORG_BRANCH_CD = #{record.orgBranchCd,jdbcType=VARCHAR}");
        SET("ORG_BRANCH_NM = #{record.orgBranchNm,jdbcType=VARCHAR}");
        SET("ORG_SITE_CD = #{record.orgSiteCd,jdbcType=VARCHAR}");
        SET("ORG_SITE_NM = #{record.orgSiteNm,jdbcType=VARCHAR}");
        SET("PLACE_TYPE = #{record.placeType,jdbcType=VARCHAR}");
        SET("JP_TYPE = #{record.jpType,jdbcType=VARCHAR}");
        SET("SPECIAL_TYPE = #{record.specialType,jdbcType=VARCHAR}");
        SET("OPER_TIME_TYPE = #{record.operTimeType,jdbcType=VARCHAR}");
        SET("OPER_START_TIME = #{record.operStartTime,jdbcType=VARCHAR}");
        SET("OPER_END_TIME = #{record.operEndTime,jdbcType=VARCHAR}");
        SET("OPER_DAY = #{record.operDay,jdbcType=VARCHAR}");
        SET("OPER_CHECK_YN = #{record.operCheckYn,jdbcType=VARCHAR}");
        SET("SERVICE_FEE = #{record.serviceFee,jdbcType=VARCHAR}");
        SET("GUARD_CD = #{record.guardCd,jdbcType=VARCHAR}");
        SET("GUARD_NM = #{record.guardNm,jdbcType=VARCHAR}");
        SET("FACIL_RENT_YN = #{record.facilRentYn,jdbcType=VARCHAR}");
        SET("SET_ADDR = #{record.setAddr,jdbcType=VARCHAR}");
        SET("SET_PLACE = #{record.setPlace,jdbcType=VARCHAR}");
        SET("MSG = #{record.msg,jdbcType=VARCHAR}");
        SET("WORK_RESULT = #{record.workResult,jdbcType=VARCHAR}");
        SET("UPDATE_DATE = #{record.updateDate,jdbcType=TIMESTAMP}");
        SET("UPDATE_UID = #{record.updateUid,jdbcType=VARCHAR}");
        SET("DATA_TYPE = #{record.dataType,jdbcType=VARCHAR}");
        SET("OPER_START_TIME_H = #{record.operStartTimeH,jdbcType=VARCHAR}");
        SET("OPER_END_TIME_H = #{record.operEndTimeH,jdbcType=VARCHAR}");
        SET("OUT_START_TIME = #{record.outStartTime,jdbcType=VARCHAR}");
        SET("OUT_END_TIME = #{record.outEndTime,jdbcType=VARCHAR}");
        SET("OUT_START_TIME_H = #{record.outStartTimeH,jdbcType=VARCHAR}");
        SET("OUT_END_TIME_H = #{record.outEndTimeH,jdbcType=VARCHAR}");
        SET("OUT_COM_CD = #{record.outComCd,jdbcType=VARCHAR}");
        SET("CLEAN_COM_CD = #{record.cleanComCd,jdbcType=VARCHAR}");
        SET("SET_DATE = #{record.setDate,jdbcType=VARCHAR}");

        TCmSetSiteInfoSpec spec = (TCmSetSiteInfoSpec) parameter.get("spec");
        applyWhere(spec, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_CM_SET_SITE_INFO
     *
     * @mbggenerated Thu Aug 07 09:04:14 KST 2014
     */
    public String updateByPrimaryKeySelective(TCmSetSiteInfo record) {
        BEGIN();
        UPDATE("OP.T_CM_SET_SITE_INFO");

        if (record.getChangeNo() != null) {
            SET("CHANGE_NO = #{changeNo,jdbcType=DECIMAL}");
        }

        if (record.getOrgBranchCd() != null) {
            SET("ORG_BRANCH_CD = #{orgBranchCd,jdbcType=VARCHAR}");
        }

        if (record.getOrgBranchNm() != null) {
            SET("ORG_BRANCH_NM = #{orgBranchNm,jdbcType=VARCHAR}");
        }

        if (record.getOrgSiteCd() != null) {
            SET("ORG_SITE_CD = #{orgSiteCd,jdbcType=VARCHAR}");
        }

        if (record.getOrgSiteNm() != null) {
            SET("ORG_SITE_NM = #{orgSiteNm,jdbcType=VARCHAR}");
        }

        if (record.getPlaceType() != null) {
            SET("PLACE_TYPE = #{placeType,jdbcType=VARCHAR}");
        }

        if (record.getJpType() != null) {
            SET("JP_TYPE = #{jpType,jdbcType=VARCHAR}");
        }

        if (record.getSpecialType() != null) {
            SET("SPECIAL_TYPE = #{specialType,jdbcType=VARCHAR}");
        }

        if (record.getOperTimeType() != null) {
            SET("OPER_TIME_TYPE = #{operTimeType,jdbcType=VARCHAR}");
        }

        if (record.getOperStartTime() != null) {
            SET("OPER_START_TIME = #{operStartTime,jdbcType=VARCHAR}");
        }

        if (record.getOperEndTime() != null) {
            SET("OPER_END_TIME = #{operEndTime,jdbcType=VARCHAR}");
        }

        if (record.getOperDay() != null) {
            SET("OPER_DAY = #{operDay,jdbcType=VARCHAR}");
        }

        if (record.getOperCheckYn() != null) {
            SET("OPER_CHECK_YN = #{operCheckYn,jdbcType=VARCHAR}");
        }

        if (record.getServiceFee() != null) {
            SET("SERVICE_FEE = #{serviceFee,jdbcType=VARCHAR}");
        }

        if (record.getGuardCd() != null) {
            SET("GUARD_CD = #{guardCd,jdbcType=VARCHAR}");
        }

        if (record.getGuardNm() != null) {
            SET("GUARD_NM = #{guardNm,jdbcType=VARCHAR}");
        }

        if (record.getFacilRentYn() != null) {
            SET("FACIL_RENT_YN = #{facilRentYn,jdbcType=VARCHAR}");
        }

        if (record.getSetAddr() != null) {
            SET("SET_ADDR = #{setAddr,jdbcType=VARCHAR}");
        }

        if (record.getSetPlace() != null) {
            SET("SET_PLACE = #{setPlace,jdbcType=VARCHAR}");
        }

        if (record.getMsg() != null) {
            SET("MSG = #{msg,jdbcType=VARCHAR}");
        }

        if (record.getWorkResult() != null) {
            SET("WORK_RESULT = #{workResult,jdbcType=VARCHAR}");
        }

        if (record.getUpdateDate() != null) {
            SET("UPDATE_DATE = #{updateDate,jdbcType=TIMESTAMP}");
        }

        if (record.getUpdateUid() != null) {
            SET("UPDATE_UID = #{updateUid,jdbcType=VARCHAR}");
        }

        if (record.getDataType() != null) {
            SET("DATA_TYPE = #{dataType,jdbcType=VARCHAR}");
        }

        if (record.getOperStartTimeH() != null) {
            SET("OPER_START_TIME_H = #{operStartTimeH,jdbcType=VARCHAR}");
        }

        if (record.getOperEndTimeH() != null) {
            SET("OPER_END_TIME_H = #{operEndTimeH,jdbcType=VARCHAR}");
        }

        if (record.getOutStartTime() != null) {
            SET("OUT_START_TIME = #{outStartTime,jdbcType=VARCHAR}");
        }

        if (record.getOutEndTime() != null) {
            SET("OUT_END_TIME = #{outEndTime,jdbcType=VARCHAR}");
        }

        if (record.getOutStartTimeH() != null) {
            SET("OUT_START_TIME_H = #{outStartTimeH,jdbcType=VARCHAR}");
        }

        if (record.getOutEndTimeH() != null) {
            SET("OUT_END_TIME_H = #{outEndTimeH,jdbcType=VARCHAR}");
        }

        if (record.getOutComCd() != null) {
            SET("OUT_COM_CD = #{outComCd,jdbcType=VARCHAR}");
        }

        if (record.getCleanComCd() != null) {
            SET("CLEAN_COM_CD = #{cleanComCd,jdbcType=VARCHAR}");
        }

        if (record.getSetDate() != null) {
            SET("SET_DATE = #{setDate,jdbcType=VARCHAR}");
        }

        WHERE("ORG_CD = #{orgCd,jdbcType=VARCHAR}");
        WHERE("WORK_SEQ = #{workSeq,jdbcType=VARCHAR}");
        WHERE("WORK_CLASS = #{workClass,jdbcType=VARCHAR}");

        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_CM_SET_SITE_INFO
     *
     * @mbggenerated Thu Aug 07 09:04:14 KST 2014
     */
    protected void applyWhere(TCmSetSiteInfoSpec spec, boolean includeSpecPhrase) {
        if (spec == null) {
            return;
        }

        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeSpecPhrase) {
            parmPhrase1 = "%s #{spec.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{spec.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{spec.oredCriteria[%d].allCriteria[%d].value} and #{spec.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{spec.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{spec.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{spec.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{spec.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }

        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = spec.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }

                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }

                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }

        if (sb.length() > 0) {
            WHERE(sb.toString());
        }
    }
}