package com.nicetcm.nibsplus.broker.msg.mapper;

import com.nicetcm.nibsplus.broker.msg.model.TCmSite01;
import com.nicetcm.nibsplus.broker.msg.model.TCmSite01Key;
import com.nicetcm.nibsplus.broker.msg.model.TCmSite01Spec;
import com.nicetcm.nibsplus.broker.msg.model.TCmSite01Cond;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface TCmSite01Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_CM_SITE_01
     *
     * @mbggenerated Tue Jul 01 15:57:31 KST 2014
     */
    @SelectProvider(type=TCmSite01SqlProvider.class, method="countBySpec")
    int countBySpec(TCmSite01Spec spec);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_CM_SITE_01
     *
     * @mbggenerated Tue Jul 01 15:57:31 KST 2014
     */
    @DeleteProvider(type=TCmSite01SqlProvider.class, method="deleteBySpec")
    int deleteBySpec(TCmSite01Spec spec);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_CM_SITE_01
     *
     * @mbggenerated Tue Jul 01 15:57:31 KST 2014
     */
    @Delete({
        "delete from OP.T_CM_SITE_01",
        "where ORG_CD = #{orgCd,jdbcType=VARCHAR}",
          "and BRANCH_CD = #{branchCd,jdbcType=VARCHAR}",
          "and SITE_CD = #{siteCd,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(TCmSite01Key key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_CM_SITE_01
     *
     * @mbggenerated Tue Jul 01 15:57:31 KST 2014
     */
    @Insert({
        "insert into OP.T_CM_SITE_01 (ORG_CD, BRANCH_CD, ",
        "SITE_CD, XPOS, YPOS, ",
        "ZIPCODE, SIDO, GUGUN, ",
        "DONG, START_BUNJI, ",
        "END_BUNJI, DETAIL_ADDR, ",
        "H_NICE_START_TIME, H_NICE_END_TIME, ",
        "H_OPER_START_TIME, H_OPER_END_TIME, ",
        "ALARM, AIRFRESHENER, ",
        "NICEEYE, FINGERLOCK, ",
        "SAFE_TYPE, IN_PLACE_YN, ",
        "BOOTH_SET_YN, BOOTH_FIX_YN, ",
        "POS_ALARM_YN, FRONT_BRANCH_YN, ",
        "FRONT_BRANCH_TYPE, FRONT_BRANCH_MNG_TYPE, ",
        "STORE_TYPE, STORE_DETAIL_TYPE, ",
        "OPER_DETAIL_CD, BOOTH_MADE_CD, ",
        "BOOTH_MADE_TYPE, BOOTH_MADE_YEAR, ",
        "NOTICE_HOLDER_CNT, NEW_ADDR, ",
        "SET_BUILDING, OUT_SIGN_TYPE, ",
        "FIRST_MANAGE_DATE, SET_FLOOR, ",
        "SEND_PERIOD, SET_AGENT_YN, ",
        "COOL_HEAT_TYPE, WASTE_BASKET_TYPE, ",
        "POST_HOLDER_CNT, FIRE_EX_CNT, ",
        "SPEC_CRUSH_CNT, BANKBOOK_DEVICE_CNT, ",
        "BILL_MANAGE_CNT, CCTV_TYPE, ",
        "WIRELESS_MODEM_YN, MODEM_RELAY_YN, ",
        "IC_MODULE_YN, SPECS_YN, ",
        "SHOCK_PACK_YN, SIGN_YN, ",
        "TOPER_YN, REG_ID, ",
        "REG_DT, EDIT_ID, ",
        "EDIT_DT)",
        "values (#{orgCd,jdbcType=VARCHAR}, #{branchCd,jdbcType=VARCHAR}, ",
        "#{siteCd,jdbcType=VARCHAR}, #{xpos,jdbcType=DECIMAL}, #{ypos,jdbcType=DECIMAL}, ",
        "#{zipcode,jdbcType=VARCHAR}, #{sido,jdbcType=VARCHAR}, #{gugun,jdbcType=VARCHAR}, ",
        "#{dong,jdbcType=VARCHAR}, #{startBunji,jdbcType=VARCHAR}, ",
        "#{endBunji,jdbcType=VARCHAR}, #{detailAddr,jdbcType=VARCHAR}, ",
        "#{hNiceStartTime,jdbcType=VARCHAR}, #{hNiceEndTime,jdbcType=VARCHAR}, ",
        "#{hOperStartTime,jdbcType=VARCHAR}, #{hOperEndTime,jdbcType=VARCHAR}, ",
        "#{alarm,jdbcType=VARCHAR}, #{airfreshener,jdbcType=VARCHAR}, ",
        "#{niceeye,jdbcType=VARCHAR}, #{fingerlock,jdbcType=VARCHAR}, ",
        "#{safeType,jdbcType=VARCHAR}, #{inPlaceYn,jdbcType=VARCHAR}, ",
        "#{boothSetYn,jdbcType=VARCHAR}, #{boothFixYn,jdbcType=VARCHAR}, ",
        "#{posAlarmYn,jdbcType=VARCHAR}, #{frontBranchYn,jdbcType=VARCHAR}, ",
        "#{frontBranchType,jdbcType=VARCHAR}, #{frontBranchMngType,jdbcType=VARCHAR}, ",
        "#{storeType,jdbcType=VARCHAR}, #{storeDetailType,jdbcType=VARCHAR}, ",
        "#{operDetailCd,jdbcType=VARCHAR}, #{boothMadeCd,jdbcType=VARCHAR}, ",
        "#{boothMadeType,jdbcType=VARCHAR}, #{boothMadeYear,jdbcType=VARCHAR}, ",
        "#{noticeHolderCnt,jdbcType=OTHER}, #{newAddr,jdbcType=VARCHAR}, ",
        "#{setBuilding,jdbcType=VARCHAR}, #{outSignType,jdbcType=VARCHAR}, ",
        "#{firstManageDate,jdbcType=VARCHAR}, #{setFloor,jdbcType=VARCHAR}, ",
        "#{sendPeriod,jdbcType=VARCHAR}, #{setAgentYn,jdbcType=VARCHAR}, ",
        "#{coolHeatType,jdbcType=VARCHAR}, #{wasteBasketType,jdbcType=VARCHAR}, ",
        "#{postHolderCnt,jdbcType=OTHER}, #{fireExCnt,jdbcType=OTHER}, ",
        "#{specCrushCnt,jdbcType=OTHER}, #{bankbookDeviceCnt,jdbcType=OTHER}, ",
        "#{billManageCnt,jdbcType=OTHER}, #{cctvType,jdbcType=VARCHAR}, ",
        "#{wirelessModemYn,jdbcType=VARCHAR}, #{modemRelayYn,jdbcType=VARCHAR}, ",
        "#{icModuleYn,jdbcType=VARCHAR}, #{specsYn,jdbcType=VARCHAR}, ",
        "#{shockPackYn,jdbcType=VARCHAR}, #{signYn,jdbcType=VARCHAR}, ",
        "#{toperYn,jdbcType=VARCHAR}, #{regId,jdbcType=VARCHAR}, ",
        "#{regDt,jdbcType=TIMESTAMP}, #{editId,jdbcType=VARCHAR}, ",
        "#{editDt,jdbcType=TIMESTAMP})"
    })
    int insert(TCmSite01 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_CM_SITE_01
     *
     * @mbggenerated Tue Jul 01 15:57:31 KST 2014
     */
    @InsertProvider(type=TCmSite01SqlProvider.class, method="insertSelective")
    int insertSelective(TCmSite01 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_CM_SITE_01
     *
     * @mbggenerated Tue Jul 01 15:57:31 KST 2014
     */
    @SelectProvider(type=TCmSite01SqlProvider.class, method="selectBySpec")
    @Results({
        @Result(column="ORG_CD", property="orgCd", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="BRANCH_CD", property="branchCd", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="SITE_CD", property="siteCd", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="XPOS", property="xpos", jdbcType=JdbcType.DECIMAL),
        @Result(column="YPOS", property="ypos", jdbcType=JdbcType.DECIMAL),
        @Result(column="ZIPCODE", property="zipcode", jdbcType=JdbcType.VARCHAR),
        @Result(column="SIDO", property="sido", jdbcType=JdbcType.VARCHAR),
        @Result(column="GUGUN", property="gugun", jdbcType=JdbcType.VARCHAR),
        @Result(column="DONG", property="dong", jdbcType=JdbcType.VARCHAR),
        @Result(column="START_BUNJI", property="startBunji", jdbcType=JdbcType.VARCHAR),
        @Result(column="END_BUNJI", property="endBunji", jdbcType=JdbcType.VARCHAR),
        @Result(column="DETAIL_ADDR", property="detailAddr", jdbcType=JdbcType.VARCHAR),
        @Result(column="H_NICE_START_TIME", property="hNiceStartTime", jdbcType=JdbcType.VARCHAR),
        @Result(column="H_NICE_END_TIME", property="hNiceEndTime", jdbcType=JdbcType.VARCHAR),
        @Result(column="H_OPER_START_TIME", property="hOperStartTime", jdbcType=JdbcType.VARCHAR),
        @Result(column="H_OPER_END_TIME", property="hOperEndTime", jdbcType=JdbcType.VARCHAR),
        @Result(column="ALARM", property="alarm", jdbcType=JdbcType.VARCHAR),
        @Result(column="AIRFRESHENER", property="airfreshener", jdbcType=JdbcType.VARCHAR),
        @Result(column="NICEEYE", property="niceeye", jdbcType=JdbcType.VARCHAR),
        @Result(column="FINGERLOCK", property="fingerlock", jdbcType=JdbcType.VARCHAR),
        @Result(column="SAFE_TYPE", property="safeType", jdbcType=JdbcType.VARCHAR),
        @Result(column="IN_PLACE_YN", property="inPlaceYn", jdbcType=JdbcType.VARCHAR),
        @Result(column="BOOTH_SET_YN", property="boothSetYn", jdbcType=JdbcType.VARCHAR),
        @Result(column="BOOTH_FIX_YN", property="boothFixYn", jdbcType=JdbcType.VARCHAR),
        @Result(column="POS_ALARM_YN", property="posAlarmYn", jdbcType=JdbcType.VARCHAR),
        @Result(column="FRONT_BRANCH_YN", property="frontBranchYn", jdbcType=JdbcType.VARCHAR),
        @Result(column="FRONT_BRANCH_TYPE", property="frontBranchType", jdbcType=JdbcType.VARCHAR),
        @Result(column="FRONT_BRANCH_MNG_TYPE", property="frontBranchMngType", jdbcType=JdbcType.VARCHAR),
        @Result(column="STORE_TYPE", property="storeType", jdbcType=JdbcType.VARCHAR),
        @Result(column="STORE_DETAIL_TYPE", property="storeDetailType", jdbcType=JdbcType.VARCHAR),
        @Result(column="OPER_DETAIL_CD", property="operDetailCd", jdbcType=JdbcType.VARCHAR),
        @Result(column="BOOTH_MADE_CD", property="boothMadeCd", jdbcType=JdbcType.VARCHAR),
        @Result(column="BOOTH_MADE_TYPE", property="boothMadeType", jdbcType=JdbcType.VARCHAR),
        @Result(column="BOOTH_MADE_YEAR", property="boothMadeYear", jdbcType=JdbcType.VARCHAR),
        @Result(column="NOTICE_HOLDER_CNT", property="noticeHolderCnt", jdbcType=JdbcType.OTHER),
        @Result(column="NEW_ADDR", property="newAddr", jdbcType=JdbcType.VARCHAR),
        @Result(column="SET_BUILDING", property="setBuilding", jdbcType=JdbcType.VARCHAR),
        @Result(column="OUT_SIGN_TYPE", property="outSignType", jdbcType=JdbcType.VARCHAR),
        @Result(column="FIRST_MANAGE_DATE", property="firstManageDate", jdbcType=JdbcType.VARCHAR),
        @Result(column="SET_FLOOR", property="setFloor", jdbcType=JdbcType.VARCHAR),
        @Result(column="SEND_PERIOD", property="sendPeriod", jdbcType=JdbcType.VARCHAR),
        @Result(column="SET_AGENT_YN", property="setAgentYn", jdbcType=JdbcType.VARCHAR),
        @Result(column="COOL_HEAT_TYPE", property="coolHeatType", jdbcType=JdbcType.VARCHAR),
        @Result(column="WASTE_BASKET_TYPE", property="wasteBasketType", jdbcType=JdbcType.VARCHAR),
        @Result(column="POST_HOLDER_CNT", property="postHolderCnt", jdbcType=JdbcType.OTHER),
        @Result(column="FIRE_EX_CNT", property="fireExCnt", jdbcType=JdbcType.OTHER),
        @Result(column="SPEC_CRUSH_CNT", property="specCrushCnt", jdbcType=JdbcType.OTHER),
        @Result(column="BANKBOOK_DEVICE_CNT", property="bankbookDeviceCnt", jdbcType=JdbcType.OTHER),
        @Result(column="BILL_MANAGE_CNT", property="billManageCnt", jdbcType=JdbcType.OTHER),
        @Result(column="CCTV_TYPE", property="cctvType", jdbcType=JdbcType.VARCHAR),
        @Result(column="WIRELESS_MODEM_YN", property="wirelessModemYn", jdbcType=JdbcType.VARCHAR),
        @Result(column="MODEM_RELAY_YN", property="modemRelayYn", jdbcType=JdbcType.VARCHAR),
        @Result(column="IC_MODULE_YN", property="icModuleYn", jdbcType=JdbcType.VARCHAR),
        @Result(column="SPECS_YN", property="specsYn", jdbcType=JdbcType.VARCHAR),
        @Result(column="SHOCK_PACK_YN", property="shockPackYn", jdbcType=JdbcType.VARCHAR),
        @Result(column="SIGN_YN", property="signYn", jdbcType=JdbcType.VARCHAR),
        @Result(column="TOPER_YN", property="toperYn", jdbcType=JdbcType.VARCHAR),
        @Result(column="REG_ID", property="regId", jdbcType=JdbcType.VARCHAR),
        @Result(column="REG_DT", property="regDt", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="EDIT_ID", property="editId", jdbcType=JdbcType.VARCHAR),
        @Result(column="EDIT_DT", property="editDt", jdbcType=JdbcType.TIMESTAMP)
    })
    List<TCmSite01> selectBySpec(TCmSite01Spec spec);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_CM_SITE_01
     *
     * @mbggenerated Tue Jul 01 15:57:31 KST 2014
     */
    @Select({
        "select",
        "ORG_CD, BRANCH_CD, SITE_CD, XPOS, YPOS, ZIPCODE, SIDO, GUGUN, DONG, START_BUNJI, ",
        "END_BUNJI, DETAIL_ADDR, H_NICE_START_TIME, H_NICE_END_TIME, H_OPER_START_TIME, ",
        "H_OPER_END_TIME, ALARM, AIRFRESHENER, NICEEYE, FINGERLOCK, SAFE_TYPE, IN_PLACE_YN, ",
        "BOOTH_SET_YN, BOOTH_FIX_YN, POS_ALARM_YN, FRONT_BRANCH_YN, FRONT_BRANCH_TYPE, ",
        "FRONT_BRANCH_MNG_TYPE, STORE_TYPE, STORE_DETAIL_TYPE, OPER_DETAIL_CD, BOOTH_MADE_CD, ",
        "BOOTH_MADE_TYPE, BOOTH_MADE_YEAR, NOTICE_HOLDER_CNT, NEW_ADDR, SET_BUILDING, ",
        "OUT_SIGN_TYPE, FIRST_MANAGE_DATE, SET_FLOOR, SEND_PERIOD, SET_AGENT_YN, COOL_HEAT_TYPE, ",
        "WASTE_BASKET_TYPE, POST_HOLDER_CNT, FIRE_EX_CNT, SPEC_CRUSH_CNT, BANKBOOK_DEVICE_CNT, ",
        "BILL_MANAGE_CNT, CCTV_TYPE, WIRELESS_MODEM_YN, MODEM_RELAY_YN, IC_MODULE_YN, ",
        "SPECS_YN, SHOCK_PACK_YN, SIGN_YN, TOPER_YN, REG_ID, REG_DT, EDIT_ID, EDIT_DT",
        "from OP.T_CM_SITE_01",
        "where ORG_CD = #{orgCd,jdbcType=VARCHAR}",
          "and BRANCH_CD = #{branchCd,jdbcType=VARCHAR}",
          "and SITE_CD = #{siteCd,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="ORG_CD", property="orgCd", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="BRANCH_CD", property="branchCd", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="SITE_CD", property="siteCd", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="XPOS", property="xpos", jdbcType=JdbcType.DECIMAL),
        @Result(column="YPOS", property="ypos", jdbcType=JdbcType.DECIMAL),
        @Result(column="ZIPCODE", property="zipcode", jdbcType=JdbcType.VARCHAR),
        @Result(column="SIDO", property="sido", jdbcType=JdbcType.VARCHAR),
        @Result(column="GUGUN", property="gugun", jdbcType=JdbcType.VARCHAR),
        @Result(column="DONG", property="dong", jdbcType=JdbcType.VARCHAR),
        @Result(column="START_BUNJI", property="startBunji", jdbcType=JdbcType.VARCHAR),
        @Result(column="END_BUNJI", property="endBunji", jdbcType=JdbcType.VARCHAR),
        @Result(column="DETAIL_ADDR", property="detailAddr", jdbcType=JdbcType.VARCHAR),
        @Result(column="H_NICE_START_TIME", property="hNiceStartTime", jdbcType=JdbcType.VARCHAR),
        @Result(column="H_NICE_END_TIME", property="hNiceEndTime", jdbcType=JdbcType.VARCHAR),
        @Result(column="H_OPER_START_TIME", property="hOperStartTime", jdbcType=JdbcType.VARCHAR),
        @Result(column="H_OPER_END_TIME", property="hOperEndTime", jdbcType=JdbcType.VARCHAR),
        @Result(column="ALARM", property="alarm", jdbcType=JdbcType.VARCHAR),
        @Result(column="AIRFRESHENER", property="airfreshener", jdbcType=JdbcType.VARCHAR),
        @Result(column="NICEEYE", property="niceeye", jdbcType=JdbcType.VARCHAR),
        @Result(column="FINGERLOCK", property="fingerlock", jdbcType=JdbcType.VARCHAR),
        @Result(column="SAFE_TYPE", property="safeType", jdbcType=JdbcType.VARCHAR),
        @Result(column="IN_PLACE_YN", property="inPlaceYn", jdbcType=JdbcType.VARCHAR),
        @Result(column="BOOTH_SET_YN", property="boothSetYn", jdbcType=JdbcType.VARCHAR),
        @Result(column="BOOTH_FIX_YN", property="boothFixYn", jdbcType=JdbcType.VARCHAR),
        @Result(column="POS_ALARM_YN", property="posAlarmYn", jdbcType=JdbcType.VARCHAR),
        @Result(column="FRONT_BRANCH_YN", property="frontBranchYn", jdbcType=JdbcType.VARCHAR),
        @Result(column="FRONT_BRANCH_TYPE", property="frontBranchType", jdbcType=JdbcType.VARCHAR),
        @Result(column="FRONT_BRANCH_MNG_TYPE", property="frontBranchMngType", jdbcType=JdbcType.VARCHAR),
        @Result(column="STORE_TYPE", property="storeType", jdbcType=JdbcType.VARCHAR),
        @Result(column="STORE_DETAIL_TYPE", property="storeDetailType", jdbcType=JdbcType.VARCHAR),
        @Result(column="OPER_DETAIL_CD", property="operDetailCd", jdbcType=JdbcType.VARCHAR),
        @Result(column="BOOTH_MADE_CD", property="boothMadeCd", jdbcType=JdbcType.VARCHAR),
        @Result(column="BOOTH_MADE_TYPE", property="boothMadeType", jdbcType=JdbcType.VARCHAR),
        @Result(column="BOOTH_MADE_YEAR", property="boothMadeYear", jdbcType=JdbcType.VARCHAR),
        @Result(column="NOTICE_HOLDER_CNT", property="noticeHolderCnt", jdbcType=JdbcType.OTHER),
        @Result(column="NEW_ADDR", property="newAddr", jdbcType=JdbcType.VARCHAR),
        @Result(column="SET_BUILDING", property="setBuilding", jdbcType=JdbcType.VARCHAR),
        @Result(column="OUT_SIGN_TYPE", property="outSignType", jdbcType=JdbcType.VARCHAR),
        @Result(column="FIRST_MANAGE_DATE", property="firstManageDate", jdbcType=JdbcType.VARCHAR),
        @Result(column="SET_FLOOR", property="setFloor", jdbcType=JdbcType.VARCHAR),
        @Result(column="SEND_PERIOD", property="sendPeriod", jdbcType=JdbcType.VARCHAR),
        @Result(column="SET_AGENT_YN", property="setAgentYn", jdbcType=JdbcType.VARCHAR),
        @Result(column="COOL_HEAT_TYPE", property="coolHeatType", jdbcType=JdbcType.VARCHAR),
        @Result(column="WASTE_BASKET_TYPE", property="wasteBasketType", jdbcType=JdbcType.VARCHAR),
        @Result(column="POST_HOLDER_CNT", property="postHolderCnt", jdbcType=JdbcType.OTHER),
        @Result(column="FIRE_EX_CNT", property="fireExCnt", jdbcType=JdbcType.OTHER),
        @Result(column="SPEC_CRUSH_CNT", property="specCrushCnt", jdbcType=JdbcType.OTHER),
        @Result(column="BANKBOOK_DEVICE_CNT", property="bankbookDeviceCnt", jdbcType=JdbcType.OTHER),
        @Result(column="BILL_MANAGE_CNT", property="billManageCnt", jdbcType=JdbcType.OTHER),
        @Result(column="CCTV_TYPE", property="cctvType", jdbcType=JdbcType.VARCHAR),
        @Result(column="WIRELESS_MODEM_YN", property="wirelessModemYn", jdbcType=JdbcType.VARCHAR),
        @Result(column="MODEM_RELAY_YN", property="modemRelayYn", jdbcType=JdbcType.VARCHAR),
        @Result(column="IC_MODULE_YN", property="icModuleYn", jdbcType=JdbcType.VARCHAR),
        @Result(column="SPECS_YN", property="specsYn", jdbcType=JdbcType.VARCHAR),
        @Result(column="SHOCK_PACK_YN", property="shockPackYn", jdbcType=JdbcType.VARCHAR),
        @Result(column="SIGN_YN", property="signYn", jdbcType=JdbcType.VARCHAR),
        @Result(column="TOPER_YN", property="toperYn", jdbcType=JdbcType.VARCHAR),
        @Result(column="REG_ID", property="regId", jdbcType=JdbcType.VARCHAR),
        @Result(column="REG_DT", property="regDt", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="EDIT_ID", property="editId", jdbcType=JdbcType.VARCHAR),
        @Result(column="EDIT_DT", property="editDt", jdbcType=JdbcType.TIMESTAMP)
    })
    TCmSite01 selectByPrimaryKey(TCmSite01Key key);

    /**
     * CommonPackImpl.getAutoSendInfo 에서 호출
     *
     * @author KDJ, on Tue Jul 02 11:18:00 KST 2014
     */
    @Select({
        "SELECT ORG_CD",
        "FROM",
        "(",
        "    SELECT ORG_CD,JIJUM_CD,SITE_CD,H_NICE_START_TIME,H_NICE_END_TIME,",
        "           DECODE(#{sendTypeDetail, jdbcType=VARCHAR}, 2, TO_DATE(TO_CHAR(SYSDATE+1,'YYYYMMDD')||H_NICE_START_TIME, 'YYYYMMDDHH24MISS'), TO_DATE(TO_CHAR(SYSDATE,'YYYYMMDD')||H_NICE_START_TIME,'YYYYMMDDHH24MISS')) AS STTM,",
        "           CASE WHEN H_NICE_START_TIME < H_NICE_END_TIME THEN",
        "                DECODE(#{sendTypeDetail, jdbcType=VARCHAR}, 2, TO_DATE(TO_CHAR(SYSDATE+1,'YYYYMMDD')||H_NICE_END_TIME, 'YYYYMMDDHH24MISS'), TO_DATE(TO_CHAR(SYSDATE,'YYYYMMDD')||H_NICE_END_TIME,'YYYYMMDDHH24MISS'))",
        "           ELSE",
        "                TO_DATE(TO_CHAR(SYSDATE+1,'YYYYMMDD')||H_NICE_END_TIME,'YYYYMMDDHH24MISS')",
        "           END AS EDTM",
        "    FROM   OP.T_CM_SITE_01",
        "    WHERE  ORG_CD = #{orgCd, jdbcType=VARCHAR}",
        "    AND    BRANCH_CD = OP.F_GET_NICE_BRANCH_CD(#{orgCd, jdbcType=VARCHAR}, #{branchCd, jdbcType=VARCHAR}, '', #{macNo, jdbcType=VARCHAR})",
        "    AND    SITE_CD = #{siteCd, jdbcType=VARCHAR}",
        "    AND    LENGTH(H_NICE_START_TIME) = 4",
        "    AND    LENGTH(H_NICE_END_TIME) = 4",
        "    AND    ROWNUM = 1",
        ") SUB",
        "WHERE  DECODE(:HSENDTYPEDETAIL, 2, TO_DATE(TO_CHAR(SYSDATE + 1,'YYYYMMDD')||'080000', 'YYYY-MM-DD HH24:MI:SS'), 3, TO_DATE(TO_CHAR(SYSDATE,'YYYYMMDD')||'080000', 'YYYY-MM-DD HH24:MI:SS'), DECODE(:HWAITTIME, 0, SYSDATE, SYSDATE + (1 / (24*60)) * :HWAITTIME )) BETWEEN STTM AND EDTM"
    })
    @Results({
        @Result(column="ORG_CD", property="orgCd", jdbcType=JdbcType.VARCHAR)
    })
    TCmSite01 selectByCond1( TCmSite01Cond cond );
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_CM_SITE_01
     *
     * @mbggenerated Tue Jul 01 15:57:31 KST 2014
     */
    @UpdateProvider(type=TCmSite01SqlProvider.class, method="updateBySpecSelective")
    int updateBySpecSelective(@Param("record") TCmSite01 record, @Param("spec") TCmSite01Spec spec);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_CM_SITE_01
     *
     * @mbggenerated Tue Jul 01 15:57:31 KST 2014
     */
    @UpdateProvider(type=TCmSite01SqlProvider.class, method="updateBySpec")
    int updateBySpec(@Param("record") TCmSite01 record, @Param("spec") TCmSite01Spec spec);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_CM_SITE_01
     *
     * @mbggenerated Tue Jul 01 15:57:31 KST 2014
     */
    @UpdateProvider(type=TCmSite01SqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(TCmSite01 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_CM_SITE_01
     *
     * @mbggenerated Tue Jul 01 15:57:31 KST 2014
     */
    @Update({
        "update OP.T_CM_SITE_01",
        "set XPOS = #{xpos,jdbcType=DECIMAL},",
          "YPOS = #{ypos,jdbcType=DECIMAL},",
          "ZIPCODE = #{zipcode,jdbcType=VARCHAR},",
          "SIDO = #{sido,jdbcType=VARCHAR},",
          "GUGUN = #{gugun,jdbcType=VARCHAR},",
          "DONG = #{dong,jdbcType=VARCHAR},",
          "START_BUNJI = #{startBunji,jdbcType=VARCHAR},",
          "END_BUNJI = #{endBunji,jdbcType=VARCHAR},",
          "DETAIL_ADDR = #{detailAddr,jdbcType=VARCHAR},",
          "H_NICE_START_TIME = #{hNiceStartTime,jdbcType=VARCHAR},",
          "H_NICE_END_TIME = #{hNiceEndTime,jdbcType=VARCHAR},",
          "H_OPER_START_TIME = #{hOperStartTime,jdbcType=VARCHAR},",
          "H_OPER_END_TIME = #{hOperEndTime,jdbcType=VARCHAR},",
          "ALARM = #{alarm,jdbcType=VARCHAR},",
          "AIRFRESHENER = #{airfreshener,jdbcType=VARCHAR},",
          "NICEEYE = #{niceeye,jdbcType=VARCHAR},",
          "FINGERLOCK = #{fingerlock,jdbcType=VARCHAR},",
          "SAFE_TYPE = #{safeType,jdbcType=VARCHAR},",
          "IN_PLACE_YN = #{inPlaceYn,jdbcType=VARCHAR},",
          "BOOTH_SET_YN = #{boothSetYn,jdbcType=VARCHAR},",
          "BOOTH_FIX_YN = #{boothFixYn,jdbcType=VARCHAR},",
          "POS_ALARM_YN = #{posAlarmYn,jdbcType=VARCHAR},",
          "FRONT_BRANCH_YN = #{frontBranchYn,jdbcType=VARCHAR},",
          "FRONT_BRANCH_TYPE = #{frontBranchType,jdbcType=VARCHAR},",
          "FRONT_BRANCH_MNG_TYPE = #{frontBranchMngType,jdbcType=VARCHAR},",
          "STORE_TYPE = #{storeType,jdbcType=VARCHAR},",
          "STORE_DETAIL_TYPE = #{storeDetailType,jdbcType=VARCHAR},",
          "OPER_DETAIL_CD = #{operDetailCd,jdbcType=VARCHAR},",
          "BOOTH_MADE_CD = #{boothMadeCd,jdbcType=VARCHAR},",
          "BOOTH_MADE_TYPE = #{boothMadeType,jdbcType=VARCHAR},",
          "BOOTH_MADE_YEAR = #{boothMadeYear,jdbcType=VARCHAR},",
          "NOTICE_HOLDER_CNT = #{noticeHolderCnt,jdbcType=OTHER},",
          "NEW_ADDR = #{newAddr,jdbcType=VARCHAR},",
          "SET_BUILDING = #{setBuilding,jdbcType=VARCHAR},",
          "OUT_SIGN_TYPE = #{outSignType,jdbcType=VARCHAR},",
          "FIRST_MANAGE_DATE = #{firstManageDate,jdbcType=VARCHAR},",
          "SET_FLOOR = #{setFloor,jdbcType=VARCHAR},",
          "SEND_PERIOD = #{sendPeriod,jdbcType=VARCHAR},",
          "SET_AGENT_YN = #{setAgentYn,jdbcType=VARCHAR},",
          "COOL_HEAT_TYPE = #{coolHeatType,jdbcType=VARCHAR},",
          "WASTE_BASKET_TYPE = #{wasteBasketType,jdbcType=VARCHAR},",
          "POST_HOLDER_CNT = #{postHolderCnt,jdbcType=OTHER},",
          "FIRE_EX_CNT = #{fireExCnt,jdbcType=OTHER},",
          "SPEC_CRUSH_CNT = #{specCrushCnt,jdbcType=OTHER},",
          "BANKBOOK_DEVICE_CNT = #{bankbookDeviceCnt,jdbcType=OTHER},",
          "BILL_MANAGE_CNT = #{billManageCnt,jdbcType=OTHER},",
          "CCTV_TYPE = #{cctvType,jdbcType=VARCHAR},",
          "WIRELESS_MODEM_YN = #{wirelessModemYn,jdbcType=VARCHAR},",
          "MODEM_RELAY_YN = #{modemRelayYn,jdbcType=VARCHAR},",
          "IC_MODULE_YN = #{icModuleYn,jdbcType=VARCHAR},",
          "SPECS_YN = #{specsYn,jdbcType=VARCHAR},",
          "SHOCK_PACK_YN = #{shockPackYn,jdbcType=VARCHAR},",
          "SIGN_YN = #{signYn,jdbcType=VARCHAR},",
          "TOPER_YN = #{toperYn,jdbcType=VARCHAR},",
          "REG_ID = #{regId,jdbcType=VARCHAR},",
          "REG_DT = #{regDt,jdbcType=TIMESTAMP},",
          "EDIT_ID = #{editId,jdbcType=VARCHAR},",
          "EDIT_DT = #{editDt,jdbcType=TIMESTAMP}",
        "where ORG_CD = #{orgCd,jdbcType=VARCHAR}",
          "and BRANCH_CD = #{branchCd,jdbcType=VARCHAR}",
          "and SITE_CD = #{siteCd,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(TCmSite01 record);
}