package com.nicetcm.nibsplus.broker.msg.mapper;

import com.nicetcm.nibsplus.broker.msg.model.TCtMacInfoMod;
import com.nicetcm.nibsplus.broker.msg.model.TCtMacInfoModSpec;
import java.util.List;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface TCtMacInfoModMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_CT_MAC_INFO_MOD
     *
     * @mbggenerated Wed Aug 06 09:32:43 KST 2014
     */
    @SelectProvider(type=TCtMacInfoModSqlProvider.class, method="countBySpec")
    int countBySpec(TCtMacInfoModSpec spec);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_CT_MAC_INFO_MOD
     *
     * @mbggenerated Wed Aug 06 09:32:43 KST 2014
     */
    @DeleteProvider(type=TCtMacInfoModSqlProvider.class, method="deleteBySpec")
    int deleteBySpec(TCtMacInfoModSpec spec);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_CT_MAC_INFO_MOD
     *
     * @mbggenerated Wed Aug 06 09:32:43 KST 2014
     */
    @Insert({
        "insert into OP.T_CT_MAC_INFO_MOD (REQ_DATE, ORG_CD, ",
        "BRANCH_CD, SITE_CD, ",
        "PLACE_TYPE, BRANCH_ADMIN_NM, ",
        "BRANCH_TEL_NO, WORK_DATE, ",
        "SITE_NM, SET_ADDR, ",
        "BOOTH_TYPE, MNG_COM_CD, ",
        "MOD_NM, MOD_ADDR, ",
        "SUBMIT_CD, DETAIL, ",
        "MEMO, UPDATE_DATE, ",
        "UPDATE_UID, NEXT_BRANCH_CD, ",
        "MAC_NO)",
        "values (#{reqDate,jdbcType=VARCHAR}, #{orgCd,jdbcType=VARCHAR}, ",
        "#{branchCd,jdbcType=VARCHAR}, #{siteCd,jdbcType=VARCHAR}, ",
        "#{placeType,jdbcType=VARCHAR}, #{branchAdminNm,jdbcType=VARCHAR}, ",
        "#{branchTelNo,jdbcType=VARCHAR}, #{workDate,jdbcType=VARCHAR}, ",
        "#{siteNm,jdbcType=VARCHAR}, #{setAddr,jdbcType=VARCHAR}, ",
        "#{boothType,jdbcType=VARCHAR}, #{mngComCd,jdbcType=VARCHAR}, ",
        "#{modNm,jdbcType=VARCHAR}, #{modAddr,jdbcType=VARCHAR}, ",
        "#{submitCd,jdbcType=VARCHAR}, #{detail,jdbcType=VARCHAR}, ",
        "#{memo,jdbcType=VARCHAR}, #{updateDate,jdbcType=TIMESTAMP}, ",
        "#{updateUid,jdbcType=VARCHAR}, #{nextBranchCd,jdbcType=VARCHAR}, ",
        "#{macNo,jdbcType=VARCHAR})"
    })
    int insert(TCtMacInfoMod record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_CT_MAC_INFO_MOD
     *
     * @mbggenerated Wed Aug 06 09:32:43 KST 2014
     */
    @InsertProvider(type=TCtMacInfoModSqlProvider.class, method="insertSelective")
    int insertSelective(TCtMacInfoMod record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_CT_MAC_INFO_MOD
     *
     * @mbggenerated Wed Aug 06 09:32:43 KST 2014
     */
    @SelectProvider(type=TCtMacInfoModSqlProvider.class, method="selectBySpec")
    @Results({
        @Result(column="REQ_DATE", property="reqDate", jdbcType=JdbcType.VARCHAR),
        @Result(column="ORG_CD", property="orgCd", jdbcType=JdbcType.VARCHAR),
        @Result(column="BRANCH_CD", property="branchCd", jdbcType=JdbcType.VARCHAR),
        @Result(column="SITE_CD", property="siteCd", jdbcType=JdbcType.VARCHAR),
        @Result(column="PLACE_TYPE", property="placeType", jdbcType=JdbcType.VARCHAR),
        @Result(column="BRANCH_ADMIN_NM", property="branchAdminNm", jdbcType=JdbcType.VARCHAR),
        @Result(column="BRANCH_TEL_NO", property="branchTelNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="WORK_DATE", property="workDate", jdbcType=JdbcType.VARCHAR),
        @Result(column="SITE_NM", property="siteNm", jdbcType=JdbcType.VARCHAR),
        @Result(column="SET_ADDR", property="setAddr", jdbcType=JdbcType.VARCHAR),
        @Result(column="BOOTH_TYPE", property="boothType", jdbcType=JdbcType.VARCHAR),
        @Result(column="MNG_COM_CD", property="mngComCd", jdbcType=JdbcType.VARCHAR),
        @Result(column="MOD_NM", property="modNm", jdbcType=JdbcType.VARCHAR),
        @Result(column="MOD_ADDR", property="modAddr", jdbcType=JdbcType.VARCHAR),
        @Result(column="SUBMIT_CD", property="submitCd", jdbcType=JdbcType.VARCHAR),
        @Result(column="DETAIL", property="detail", jdbcType=JdbcType.VARCHAR),
        @Result(column="MEMO", property="memo", jdbcType=JdbcType.VARCHAR),
        @Result(column="UPDATE_DATE", property="updateDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="UPDATE_UID", property="updateUid", jdbcType=JdbcType.VARCHAR),
        @Result(column="NEXT_BRANCH_CD", property="nextBranchCd", jdbcType=JdbcType.VARCHAR),
        @Result(column="MAC_NO", property="macNo", jdbcType=JdbcType.VARCHAR)
    })
    List<TCtMacInfoMod> selectBySpec(TCtMacInfoModSpec spec);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_CT_MAC_INFO_MOD
     *
     * @mbggenerated Wed Aug 06 09:32:43 KST 2014
     */
    @UpdateProvider(type=TCtMacInfoModSqlProvider.class, method="updateBySpecSelective")
    int updateBySpecSelective(@Param("record") TCtMacInfoMod record, @Param("spec") TCtMacInfoModSpec spec);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_CT_MAC_INFO_MOD
     *
     * @mbggenerated Wed Aug 06 09:32:43 KST 2014
     */
    @UpdateProvider(type=TCtMacInfoModSqlProvider.class, method="updateBySpec")
    int updateBySpec(@Param("record") TCtMacInfoMod record, @Param("spec") TCtMacInfoModSpec spec);
}