package com.nicetcm.nibsplus.broker.msg.mapper;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.DELETE_FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.ORDER_BY;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT_DISTINCT;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import com.nicetcm.nibsplus.broker.msg.model.TFnAtmsCashPlan;
import com.nicetcm.nibsplus.broker.msg.model.TFnAtmsCashPlanSpec.Criteria;
import com.nicetcm.nibsplus.broker.msg.model.TFnAtmsCashPlanSpec.Criterion;
import com.nicetcm.nibsplus.broker.msg.model.TFnAtmsCashPlanSpec;
import java.util.List;
import java.util.Map;

public class TFnAtmsCashPlanSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_ATMS_CASH_PLAN
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    public String countBySpec(TFnAtmsCashPlanSpec spec) {
        BEGIN();
        SELECT("count(*)");
        FROM("OP.T_FN_ATMS_CASH_PLAN");
        applyWhere(spec, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_ATMS_CASH_PLAN
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    public String deleteBySpec(TFnAtmsCashPlanSpec spec) {
        BEGIN();
        DELETE_FROM("OP.T_FN_ATMS_CASH_PLAN");
        applyWhere(spec, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_ATMS_CASH_PLAN
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    public String insertSelective(TFnAtmsCashPlan record) {
        BEGIN();
        INSERT_INTO("OP.T_FN_ATMS_CASH_PLAN");
        
        if (record.getOrgCd() != null) {
            VALUES("ORG_CD", "#{orgCd,jdbcType=VARCHAR}");
        }
        
        if (record.getBranchCd() != null) {
            VALUES("BRANCH_CD", "#{branchCd,jdbcType=VARCHAR}");
        }
        
        if (record.getSiteCd() != null) {
            VALUES("SITE_CD", "#{siteCd,jdbcType=VARCHAR}");
        }
        
        if (record.getMacNo() != null) {
            VALUES("MAC_NO", "#{macNo,jdbcType=VARCHAR}");
        }
        
        if (record.getCashDate() != null) {
            VALUES("CASH_DATE", "#{cashDate,jdbcType=VARCHAR}");
        }
        
        if (record.getCashAmt() != null) {
            VALUES("CASH_AMT", "#{cashAmt,jdbcType=DECIMAL}");
        }
        
        if (record.getConfirmCashAmt() != null) {
            VALUES("CONFIRM_CASH_AMT", "#{confirmCashAmt,jdbcType=DECIMAL}");
        }
        
        if (record.getOfficeNm() != null) {
            VALUES("OFFICE_NM", "#{officeNm,jdbcType=VARCHAR}");
        }
        
        if (record.getOrgSendConfirmYn() != null) {
            VALUES("ORG_SEND_CONFIRM_YN", "#{orgSendConfirmYn,jdbcType=VARCHAR}");
        }
        
        if (record.getUpdateDate() != null) {
            VALUES("UPDATE_DATE", "#{updateDate,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdateUid() != null) {
            VALUES("UPDATE_UID", "#{updateUid,jdbcType=VARCHAR}");
        }
        
        if (record.getCashTime() != null) {
            VALUES("CASH_TIME", "#{cashTime,jdbcType=VARCHAR}");
        }
        
        if (record.getCheckAmt() != null) {
            VALUES("CHECK_AMT", "#{checkAmt,jdbcType=DECIMAL}");
        }
        
        if (record.getHw15Cnt() != null) {
            VALUES("HW15_CNT", "#{hw15Cnt,jdbcType=DECIMAL}");
        }
        
        if (record.getHw35Cnt() != null) {
            VALUES("HW35_CNT", "#{hw35Cnt,jdbcType=DECIMAL}");
        }
        
        if (record.getHw55Cnt() != null) {
            VALUES("HW55_CNT", "#{hw55Cnt,jdbcType=DECIMAL}");
        }
        
        if (record.getHw16Cnt() != null) {
            VALUES("HW16_CNT", "#{hw16Cnt,jdbcType=DECIMAL}");
        }
        
        if (record.getOrgCashAmt() != null) {
            VALUES("ORG_CASH_AMT", "#{orgCashAmt,jdbcType=DECIMAL}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_ATMS_CASH_PLAN
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    public String selectBySpec(TFnAtmsCashPlanSpec spec) {
        BEGIN();
        if (spec != null && spec.isDistinct()) {
            SELECT_DISTINCT("ORG_CD");
        } else {
            SELECT("ORG_CD");
        }
        SELECT("BRANCH_CD");
        SELECT("SITE_CD");
        SELECT("MAC_NO");
        SELECT("CASH_DATE");
        SELECT("CASH_AMT");
        SELECT("CONFIRM_CASH_AMT");
        SELECT("OFFICE_NM");
        SELECT("ORG_SEND_CONFIRM_YN");
        SELECT("UPDATE_DATE");
        SELECT("UPDATE_UID");
        SELECT("CASH_TIME");
        SELECT("CHECK_AMT");
        SELECT("HW15_CNT");
        SELECT("HW35_CNT");
        SELECT("HW55_CNT");
        SELECT("HW16_CNT");
        SELECT("ORG_CASH_AMT");
        FROM("OP.T_FN_ATMS_CASH_PLAN");
        applyWhere(spec, false);
        
        if (spec != null && spec.getOrderByClause() != null) {
            ORDER_BY(spec.getOrderByClause());
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_ATMS_CASH_PLAN
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    public String updateBySpecSelective(Map<String, Object> parameter) {
        TFnAtmsCashPlan record = (TFnAtmsCashPlan) parameter.get("record");
        TFnAtmsCashPlanSpec spec = (TFnAtmsCashPlanSpec) parameter.get("spec");
        
        BEGIN();
        UPDATE("OP.T_FN_ATMS_CASH_PLAN");
        
        if (record.getOrgCd() != null) {
            SET("ORG_CD = #{record.orgCd,jdbcType=VARCHAR}");
        }
        
        if (record.getBranchCd() != null) {
            SET("BRANCH_CD = #{record.branchCd,jdbcType=VARCHAR}");
        }
        
        if (record.getSiteCd() != null) {
            SET("SITE_CD = #{record.siteCd,jdbcType=VARCHAR}");
        }
        
        if (record.getMacNo() != null) {
            SET("MAC_NO = #{record.macNo,jdbcType=VARCHAR}");
        }
        
        if (record.getCashDate() != null) {
            SET("CASH_DATE = #{record.cashDate,jdbcType=VARCHAR}");
        }
        
        if (record.getCashAmt() != null) {
            SET("CASH_AMT = #{record.cashAmt,jdbcType=DECIMAL}");
        }
        
        if (record.getConfirmCashAmt() != null) {
            SET("CONFIRM_CASH_AMT = #{record.confirmCashAmt,jdbcType=DECIMAL}");
        }
        
        if (record.getOfficeNm() != null) {
            SET("OFFICE_NM = #{record.officeNm,jdbcType=VARCHAR}");
        }
        
        if (record.getOrgSendConfirmYn() != null) {
            SET("ORG_SEND_CONFIRM_YN = #{record.orgSendConfirmYn,jdbcType=VARCHAR}");
        }
        
        if (record.getUpdateDate() != null) {
            SET("UPDATE_DATE = #{record.updateDate,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdateUid() != null) {
            SET("UPDATE_UID = #{record.updateUid,jdbcType=VARCHAR}");
        }
        
        if (record.getCashTime() != null) {
            SET("CASH_TIME = #{record.cashTime,jdbcType=VARCHAR}");
        }
        
        if (record.getCheckAmt() != null) {
            SET("CHECK_AMT = #{record.checkAmt,jdbcType=DECIMAL}");
        }
        
        if (record.getHw15Cnt() != null) {
            SET("HW15_CNT = #{record.hw15Cnt,jdbcType=DECIMAL}");
        }
        
        if (record.getHw35Cnt() != null) {
            SET("HW35_CNT = #{record.hw35Cnt,jdbcType=DECIMAL}");
        }
        
        if (record.getHw55Cnt() != null) {
            SET("HW55_CNT = #{record.hw55Cnt,jdbcType=DECIMAL}");
        }
        
        if (record.getHw16Cnt() != null) {
            SET("HW16_CNT = #{record.hw16Cnt,jdbcType=DECIMAL}");
        }
        
        if (record.getOrgCashAmt() != null) {
            SET("ORG_CASH_AMT = #{record.orgCashAmt,jdbcType=DECIMAL}");
        }
        
        applyWhere(spec, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_ATMS_CASH_PLAN
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    public String updateBySpec(Map<String, Object> parameter) {
        BEGIN();
        UPDATE("OP.T_FN_ATMS_CASH_PLAN");
        
        SET("ORG_CD = #{record.orgCd,jdbcType=VARCHAR}");
        SET("BRANCH_CD = #{record.branchCd,jdbcType=VARCHAR}");
        SET("SITE_CD = #{record.siteCd,jdbcType=VARCHAR}");
        SET("MAC_NO = #{record.macNo,jdbcType=VARCHAR}");
        SET("CASH_DATE = #{record.cashDate,jdbcType=VARCHAR}");
        SET("CASH_AMT = #{record.cashAmt,jdbcType=DECIMAL}");
        SET("CONFIRM_CASH_AMT = #{record.confirmCashAmt,jdbcType=DECIMAL}");
        SET("OFFICE_NM = #{record.officeNm,jdbcType=VARCHAR}");
        SET("ORG_SEND_CONFIRM_YN = #{record.orgSendConfirmYn,jdbcType=VARCHAR}");
        SET("UPDATE_DATE = #{record.updateDate,jdbcType=TIMESTAMP}");
        SET("UPDATE_UID = #{record.updateUid,jdbcType=VARCHAR}");
        SET("CASH_TIME = #{record.cashTime,jdbcType=VARCHAR}");
        SET("CHECK_AMT = #{record.checkAmt,jdbcType=DECIMAL}");
        SET("HW15_CNT = #{record.hw15Cnt,jdbcType=DECIMAL}");
        SET("HW35_CNT = #{record.hw35Cnt,jdbcType=DECIMAL}");
        SET("HW55_CNT = #{record.hw55Cnt,jdbcType=DECIMAL}");
        SET("HW16_CNT = #{record.hw16Cnt,jdbcType=DECIMAL}");
        SET("ORG_CASH_AMT = #{record.orgCashAmt,jdbcType=DECIMAL}");
        
        TFnAtmsCashPlanSpec spec = (TFnAtmsCashPlanSpec) parameter.get("spec");
        applyWhere(spec, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_ATMS_CASH_PLAN
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    public String updateByPrimaryKeySelective(TFnAtmsCashPlan record) {
        BEGIN();
        UPDATE("OP.T_FN_ATMS_CASH_PLAN");
        
        if (record.getCashAmt() != null) {
            SET("CASH_AMT = #{cashAmt,jdbcType=DECIMAL}");
        }
        
        if (record.getConfirmCashAmt() != null) {
            SET("CONFIRM_CASH_AMT = #{confirmCashAmt,jdbcType=DECIMAL}");
        }
        
        if (record.getOfficeNm() != null) {
            SET("OFFICE_NM = #{officeNm,jdbcType=VARCHAR}");
        }
        
        if (record.getOrgSendConfirmYn() != null) {
            SET("ORG_SEND_CONFIRM_YN = #{orgSendConfirmYn,jdbcType=VARCHAR}");
        }
        
        if (record.getUpdateDate() != null) {
            SET("UPDATE_DATE = #{updateDate,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdateUid() != null) {
            SET("UPDATE_UID = #{updateUid,jdbcType=VARCHAR}");
        }
        
        if (record.getCashTime() != null) {
            SET("CASH_TIME = #{cashTime,jdbcType=VARCHAR}");
        }
        
        if (record.getCheckAmt() != null) {
            SET("CHECK_AMT = #{checkAmt,jdbcType=DECIMAL}");
        }
        
        if (record.getHw15Cnt() != null) {
            SET("HW15_CNT = #{hw15Cnt,jdbcType=DECIMAL}");
        }
        
        if (record.getHw35Cnt() != null) {
            SET("HW35_CNT = #{hw35Cnt,jdbcType=DECIMAL}");
        }
        
        if (record.getHw55Cnt() != null) {
            SET("HW55_CNT = #{hw55Cnt,jdbcType=DECIMAL}");
        }
        
        if (record.getHw16Cnt() != null) {
            SET("HW16_CNT = #{hw16Cnt,jdbcType=DECIMAL}");
        }
        
        if (record.getOrgCashAmt() != null) {
            SET("ORG_CASH_AMT = #{orgCashAmt,jdbcType=DECIMAL}");
        }
        
        WHERE("ORG_CD = #{orgCd,jdbcType=VARCHAR}");
        WHERE("BRANCH_CD = #{branchCd,jdbcType=VARCHAR}");
        WHERE("SITE_CD = #{siteCd,jdbcType=VARCHAR}");
        WHERE("MAC_NO = #{macNo,jdbcType=VARCHAR}");
        WHERE("CASH_DATE = #{cashDate,jdbcType=VARCHAR}");
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_ATMS_CASH_PLAN
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    protected void applyWhere(TFnAtmsCashPlanSpec spec, boolean includeSpecPhrase) {
        if (spec == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeSpecPhrase) {
            parmPhrase1 = "%s #{spec.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{spec.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{spec.oredCriteria[%d].allCriteria[%d].value} and #{spec.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{spec.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{spec.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{spec.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{spec.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = spec.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            WHERE(sb.toString());
        }
    }
}