package com.nicetcm.nibsplus.broker.msg.mapper;

import com.nicetcm.nibsplus.broker.msg.model.TFnAtmsCashPlan;
import com.nicetcm.nibsplus.broker.msg.model.TFnAtmsCashPlanKey;
import com.nicetcm.nibsplus.broker.msg.model.TFnAtmsCashPlanSpec;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface TFnAtmsCashPlanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_ATMS_CASH_PLAN
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    @SelectProvider(type=TFnAtmsCashPlanSqlProvider.class, method="countBySpec")
    int countBySpec(TFnAtmsCashPlanSpec spec);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_ATMS_CASH_PLAN
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    @DeleteProvider(type=TFnAtmsCashPlanSqlProvider.class, method="deleteBySpec")
    int deleteBySpec(TFnAtmsCashPlanSpec spec);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_ATMS_CASH_PLAN
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    @Delete({
        "delete from OP.T_FN_ATMS_CASH_PLAN",
        "where ORG_CD = #{orgCd,jdbcType=VARCHAR}",
          "and BRANCH_CD = #{branchCd,jdbcType=VARCHAR}",
          "and SITE_CD = #{siteCd,jdbcType=VARCHAR}",
          "and MAC_NO = #{macNo,jdbcType=VARCHAR}",
          "and CASH_DATE = #{cashDate,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(TFnAtmsCashPlanKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_ATMS_CASH_PLAN
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    @Insert({
        "insert into OP.T_FN_ATMS_CASH_PLAN (ORG_CD, BRANCH_CD, ",
        "SITE_CD, MAC_NO, CASH_DATE, ",
        "CASH_AMT, CONFIRM_CASH_AMT, ",
        "OFFICE_NM, ORG_SEND_CONFIRM_YN, ",
        "UPDATE_DATE, UPDATE_UID, ",
        "CASH_TIME, CHECK_AMT, ",
        "HW15_CNT, HW35_CNT, ",
        "HW55_CNT, HW16_CNT, ",
        "ORG_CASH_AMT)",
        "values (#{orgCd,jdbcType=VARCHAR}, #{branchCd,jdbcType=VARCHAR}, ",
        "#{siteCd,jdbcType=VARCHAR}, #{macNo,jdbcType=VARCHAR}, #{cashDate,jdbcType=VARCHAR}, ",
        "#{cashAmt,jdbcType=DECIMAL}, #{confirmCashAmt,jdbcType=DECIMAL}, ",
        "#{officeNm,jdbcType=VARCHAR}, #{orgSendConfirmYn,jdbcType=VARCHAR}, ",
        "#{updateDate,jdbcType=TIMESTAMP}, #{updateUid,jdbcType=VARCHAR}, ",
        "#{cashTime,jdbcType=VARCHAR}, #{checkAmt,jdbcType=DECIMAL}, ",
        "#{hw15Cnt,jdbcType=DECIMAL}, #{hw35Cnt,jdbcType=DECIMAL}, ",
        "#{hw55Cnt,jdbcType=DECIMAL}, #{hw16Cnt,jdbcType=DECIMAL}, ",
        "#{orgCashAmt,jdbcType=DECIMAL})"
    })
    int insert(TFnAtmsCashPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_ATMS_CASH_PLAN
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    @InsertProvider(type=TFnAtmsCashPlanSqlProvider.class, method="insertSelective")
    int insertSelective(TFnAtmsCashPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_ATMS_CASH_PLAN
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    @SelectProvider(type=TFnAtmsCashPlanSqlProvider.class, method="selectBySpec")
    @Results({
        @Result(column="ORG_CD", property="orgCd", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="BRANCH_CD", property="branchCd", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="SITE_CD", property="siteCd", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="MAC_NO", property="macNo", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="CASH_DATE", property="cashDate", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="CASH_AMT", property="cashAmt", jdbcType=JdbcType.DECIMAL),
        @Result(column="CONFIRM_CASH_AMT", property="confirmCashAmt", jdbcType=JdbcType.DECIMAL),
        @Result(column="OFFICE_NM", property="officeNm", jdbcType=JdbcType.VARCHAR),
        @Result(column="ORG_SEND_CONFIRM_YN", property="orgSendConfirmYn", jdbcType=JdbcType.VARCHAR),
        @Result(column="UPDATE_DATE", property="updateDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="UPDATE_UID", property="updateUid", jdbcType=JdbcType.VARCHAR),
        @Result(column="CASH_TIME", property="cashTime", jdbcType=JdbcType.VARCHAR),
        @Result(column="CHECK_AMT", property="checkAmt", jdbcType=JdbcType.DECIMAL),
        @Result(column="HW15_CNT", property="hw15Cnt", jdbcType=JdbcType.DECIMAL),
        @Result(column="HW35_CNT", property="hw35Cnt", jdbcType=JdbcType.DECIMAL),
        @Result(column="HW55_CNT", property="hw55Cnt", jdbcType=JdbcType.DECIMAL),
        @Result(column="HW16_CNT", property="hw16Cnt", jdbcType=JdbcType.DECIMAL),
        @Result(column="ORG_CASH_AMT", property="orgCashAmt", jdbcType=JdbcType.DECIMAL)
    })
    List<TFnAtmsCashPlan> selectBySpec(TFnAtmsCashPlanSpec spec);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_ATMS_CASH_PLAN
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    @Select({
        "select",
        "ORG_CD, BRANCH_CD, SITE_CD, MAC_NO, CASH_DATE, CASH_AMT, CONFIRM_CASH_AMT, OFFICE_NM, ",
        "ORG_SEND_CONFIRM_YN, UPDATE_DATE, UPDATE_UID, CASH_TIME, CHECK_AMT, HW15_CNT, ",
        "HW35_CNT, HW55_CNT, HW16_CNT, ORG_CASH_AMT",
        "from OP.T_FN_ATMS_CASH_PLAN",
        "where ORG_CD = #{orgCd,jdbcType=VARCHAR}",
          "and BRANCH_CD = #{branchCd,jdbcType=VARCHAR}",
          "and SITE_CD = #{siteCd,jdbcType=VARCHAR}",
          "and MAC_NO = #{macNo,jdbcType=VARCHAR}",
          "and CASH_DATE = #{cashDate,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="ORG_CD", property="orgCd", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="BRANCH_CD", property="branchCd", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="SITE_CD", property="siteCd", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="MAC_NO", property="macNo", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="CASH_DATE", property="cashDate", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="CASH_AMT", property="cashAmt", jdbcType=JdbcType.DECIMAL),
        @Result(column="CONFIRM_CASH_AMT", property="confirmCashAmt", jdbcType=JdbcType.DECIMAL),
        @Result(column="OFFICE_NM", property="officeNm", jdbcType=JdbcType.VARCHAR),
        @Result(column="ORG_SEND_CONFIRM_YN", property="orgSendConfirmYn", jdbcType=JdbcType.VARCHAR),
        @Result(column="UPDATE_DATE", property="updateDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="UPDATE_UID", property="updateUid", jdbcType=JdbcType.VARCHAR),
        @Result(column="CASH_TIME", property="cashTime", jdbcType=JdbcType.VARCHAR),
        @Result(column="CHECK_AMT", property="checkAmt", jdbcType=JdbcType.DECIMAL),
        @Result(column="HW15_CNT", property="hw15Cnt", jdbcType=JdbcType.DECIMAL),
        @Result(column="HW35_CNT", property="hw35Cnt", jdbcType=JdbcType.DECIMAL),
        @Result(column="HW55_CNT", property="hw55Cnt", jdbcType=JdbcType.DECIMAL),
        @Result(column="HW16_CNT", property="hw16Cnt", jdbcType=JdbcType.DECIMAL),
        @Result(column="ORG_CASH_AMT", property="orgCashAmt", jdbcType=JdbcType.DECIMAL)
    })
    TFnAtmsCashPlan selectByPrimaryKey(TFnAtmsCashPlanKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_ATMS_CASH_PLAN
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    @UpdateProvider(type=TFnAtmsCashPlanSqlProvider.class, method="updateBySpecSelective")
    int updateBySpecSelective(@Param("record") TFnAtmsCashPlan record, @Param("spec") TFnAtmsCashPlanSpec spec);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_ATMS_CASH_PLAN
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    @UpdateProvider(type=TFnAtmsCashPlanSqlProvider.class, method="updateBySpec")
    int updateBySpec(@Param("record") TFnAtmsCashPlan record, @Param("spec") TFnAtmsCashPlanSpec spec);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_ATMS_CASH_PLAN
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    @UpdateProvider(type=TFnAtmsCashPlanSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(TFnAtmsCashPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_ATMS_CASH_PLAN
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    @Update({
        "update OP.T_FN_ATMS_CASH_PLAN",
        "set CASH_AMT = #{cashAmt,jdbcType=DECIMAL},",
          "CONFIRM_CASH_AMT = #{confirmCashAmt,jdbcType=DECIMAL},",
          "OFFICE_NM = #{officeNm,jdbcType=VARCHAR},",
          "ORG_SEND_CONFIRM_YN = #{orgSendConfirmYn,jdbcType=VARCHAR},",
          "UPDATE_DATE = #{updateDate,jdbcType=TIMESTAMP},",
          "UPDATE_UID = #{updateUid,jdbcType=VARCHAR},",
          "CASH_TIME = #{cashTime,jdbcType=VARCHAR},",
          "CHECK_AMT = #{checkAmt,jdbcType=DECIMAL},",
          "HW15_CNT = #{hw15Cnt,jdbcType=DECIMAL},",
          "HW35_CNT = #{hw35Cnt,jdbcType=DECIMAL},",
          "HW55_CNT = #{hw55Cnt,jdbcType=DECIMAL},",
          "HW16_CNT = #{hw16Cnt,jdbcType=DECIMAL},",
          "ORG_CASH_AMT = #{orgCashAmt,jdbcType=DECIMAL}",
        "where ORG_CD = #{orgCd,jdbcType=VARCHAR}",
          "and BRANCH_CD = #{branchCd,jdbcType=VARCHAR}",
          "and SITE_CD = #{siteCd,jdbcType=VARCHAR}",
          "and MAC_NO = #{macNo,jdbcType=VARCHAR}",
          "and CASH_DATE = #{cashDate,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(TFnAtmsCashPlan record);
}