package com.nicetcm.nibsplus.broker.msg.mapper;

import com.nicetcm.nibsplus.broker.msg.model.TFnBrandSetState;
import com.nicetcm.nibsplus.broker.msg.model.TFnBrandSetStateSpec;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface TFnBrandSetStateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_BRAND_SET_STATE
     *
     * @mbggenerated Fri Jul 25 16:10:44 KST 2014
     */
    @SelectProvider(type=TFnBrandSetStateSqlProvider.class, method="countBySpec")
    int countBySpec(TFnBrandSetStateSpec spec);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_BRAND_SET_STATE
     *
     * @mbggenerated Fri Jul 25 16:10:44 KST 2014
     */
    @DeleteProvider(type=TFnBrandSetStateSqlProvider.class, method="deleteBySpec")
    int deleteBySpec(TFnBrandSetStateSpec spec);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_BRAND_SET_STATE
     *
     * @mbggenerated Fri Jul 25 16:10:44 KST 2014
     */
    @Delete({
        "delete from OP.T_FN_BRAND_SET_STATE",
        "where MAC_NO = #{macNo,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String macNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_BRAND_SET_STATE
     *
     * @mbggenerated Fri Jul 25 16:10:44 KST 2014
     */
    @Insert({
        "insert into OP.T_FN_BRAND_SET_STATE (MAC_NO, BRAND_ORG_CD, ",
        "UPDATE_DATE)",
        "values (#{macNo,jdbcType=VARCHAR}, #{brandOrgCd,jdbcType=VARCHAR}, ",
        "#{updateDate,jdbcType=TIMESTAMP})"
    })
    int insert(TFnBrandSetState record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_BRAND_SET_STATE
     *
     * @mbggenerated Fri Jul 25 16:10:44 KST 2014
     */
    @InsertProvider(type=TFnBrandSetStateSqlProvider.class, method="insertSelective")
    int insertSelective(TFnBrandSetState record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_BRAND_SET_STATE
     *
     * @mbggenerated Fri Jul 25 16:10:44 KST 2014
     */
    @SelectProvider(type=TFnBrandSetStateSqlProvider.class, method="selectBySpec")
    @Results({
        @Result(column="MAC_NO", property="macNo", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="BRAND_ORG_CD", property="brandOrgCd", jdbcType=JdbcType.VARCHAR),
        @Result(column="UPDATE_DATE", property="updateDate", jdbcType=JdbcType.TIMESTAMP)
    })
    List<TFnBrandSetState> selectBySpec(TFnBrandSetStateSpec spec);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_BRAND_SET_STATE
     *
     * @mbggenerated Fri Jul 25 16:10:44 KST 2014
     */
    @Select({
        "select",
        "MAC_NO, BRAND_ORG_CD, UPDATE_DATE",
        "from OP.T_FN_BRAND_SET_STATE",
        "where MAC_NO = #{macNo,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="MAC_NO", property="macNo", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="BRAND_ORG_CD", property="brandOrgCd", jdbcType=JdbcType.VARCHAR),
        @Result(column="UPDATE_DATE", property="updateDate", jdbcType=JdbcType.TIMESTAMP)
    })
    TFnBrandSetState selectByPrimaryKey(String macNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_BRAND_SET_STATE
     *
     * @mbggenerated Fri Jul 25 16:10:44 KST 2014
     */
    @UpdateProvider(type=TFnBrandSetStateSqlProvider.class, method="updateBySpecSelective")
    int updateBySpecSelective(@Param("record") TFnBrandSetState record, @Param("spec") TFnBrandSetStateSpec spec);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_BRAND_SET_STATE
     *
     * @mbggenerated Fri Jul 25 16:10:44 KST 2014
     */
    @UpdateProvider(type=TFnBrandSetStateSqlProvider.class, method="updateBySpec")
    int updateBySpec(@Param("record") TFnBrandSetState record, @Param("spec") TFnBrandSetStateSpec spec);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_BRAND_SET_STATE
     *
     * @mbggenerated Fri Jul 25 16:10:44 KST 2014
     */
    @UpdateProvider(type=TFnBrandSetStateSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(TFnBrandSetState record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_BRAND_SET_STATE
     *
     * @mbggenerated Fri Jul 25 16:10:44 KST 2014
     */
    @Update({
        "update OP.T_FN_BRAND_SET_STATE",
        "set BRAND_ORG_CD = #{brandOrgCd,jdbcType=VARCHAR},",
          "UPDATE_DATE = #{updateDate,jdbcType=TIMESTAMP}",
        "where MAC_NO = #{macNo,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(TFnBrandSetState record);
}