package com.nicetcm.nibsplus.broker.msg.mapper;

import com.nicetcm.nibsplus.broker.msg.model.TFnBrandSuspense;
import com.nicetcm.nibsplus.broker.msg.model.TFnBrandSuspenseKey;
import com.nicetcm.nibsplus.broker.msg.model.TFnBrandSuspenseSpec;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface TFnBrandSuspenseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_BRAND_SUSPENSE
     *
     * @mbggenerated Tue Jul 22 11:13:55 KST 2014
     */
    @SelectProvider(type=TFnBrandSuspenseSqlProvider.class, method="countBySpec")
    int countBySpec(TFnBrandSuspenseSpec spec);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_BRAND_SUSPENSE
     *
     * @mbggenerated Tue Jul 22 11:13:55 KST 2014
     */
    @DeleteProvider(type=TFnBrandSuspenseSqlProvider.class, method="deleteBySpec")
    int deleteBySpec(TFnBrandSuspenseSpec spec);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_BRAND_SUSPENSE
     *
     * @mbggenerated Tue Jul 22 11:13:55 KST 2014
     */
    @Delete({
        "delete from OP.T_FN_BRAND_SUSPENSE",
        "where STD_DATE = #{stdDate,jdbcType=VARCHAR}",
          "and ORG_CD = #{orgCd,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(TFnBrandSuspenseKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_BRAND_SUSPENSE
     *
     * @mbggenerated Tue Jul 22 11:13:55 KST 2014
     */
    @Insert({
        "insert into OP.T_FN_BRAND_SUSPENSE (STD_DATE, ORG_CD, ",
        "RECEIPT_AMT, UPDATE_DATE, ",
        "UPDATE_UID)",
        "values (#{stdDate,jdbcType=VARCHAR}, #{orgCd,jdbcType=VARCHAR}, ",
        "#{receiptAmt,jdbcType=DECIMAL}, #{updateDate,jdbcType=TIMESTAMP}, ",
        "#{updateUid,jdbcType=VARCHAR})"
    })
    int insert(TFnBrandSuspense record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_BRAND_SUSPENSE
     *
     * @mbggenerated Tue Jul 22 11:13:55 KST 2014
     */
    @InsertProvider(type=TFnBrandSuspenseSqlProvider.class, method="insertSelective")
    int insertSelective(TFnBrandSuspense record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_BRAND_SUSPENSE
     *
     * @mbggenerated Tue Jul 22 11:13:55 KST 2014
     */
    @SelectProvider(type=TFnBrandSuspenseSqlProvider.class, method="selectBySpec")
    @Results({
        @Result(column="STD_DATE", property="stdDate", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="ORG_CD", property="orgCd", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="RECEIPT_AMT", property="receiptAmt", jdbcType=JdbcType.DECIMAL),
        @Result(column="UPDATE_DATE", property="updateDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="UPDATE_UID", property="updateUid", jdbcType=JdbcType.VARCHAR)
    })
    List<TFnBrandSuspense> selectBySpec(TFnBrandSuspenseSpec spec);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_BRAND_SUSPENSE
     *
     * @mbggenerated Tue Jul 22 11:13:55 KST 2014
     */
    @Select({
        "select",
        "STD_DATE, ORG_CD, RECEIPT_AMT, UPDATE_DATE, UPDATE_UID",
        "from OP.T_FN_BRAND_SUSPENSE",
        "where STD_DATE = #{stdDate,jdbcType=VARCHAR}",
          "and ORG_CD = #{orgCd,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="STD_DATE", property="stdDate", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="ORG_CD", property="orgCd", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="RECEIPT_AMT", property="receiptAmt", jdbcType=JdbcType.DECIMAL),
        @Result(column="UPDATE_DATE", property="updateDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="UPDATE_UID", property="updateUid", jdbcType=JdbcType.VARCHAR)
    })
    TFnBrandSuspense selectByPrimaryKey(TFnBrandSuspenseKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_BRAND_SUSPENSE
     *
     * @mbggenerated Tue Jul 22 11:13:55 KST 2014
     */
    @UpdateProvider(type=TFnBrandSuspenseSqlProvider.class, method="updateBySpecSelective")
    int updateBySpecSelective(@Param("record") TFnBrandSuspense record, @Param("spec") TFnBrandSuspenseSpec spec);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_BRAND_SUSPENSE
     *
     * @mbggenerated Tue Jul 22 11:13:55 KST 2014
     */
    @UpdateProvider(type=TFnBrandSuspenseSqlProvider.class, method="updateBySpec")
    int updateBySpec(@Param("record") TFnBrandSuspense record, @Param("spec") TFnBrandSuspenseSpec spec);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_BRAND_SUSPENSE
     *
     * @mbggenerated Tue Jul 22 11:13:55 KST 2014
     */
    @UpdateProvider(type=TFnBrandSuspenseSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(TFnBrandSuspense record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_BRAND_SUSPENSE
     *
     * @mbggenerated Tue Jul 22 11:13:55 KST 2014
     */
    @Update({
        "update OP.T_FN_BRAND_SUSPENSE",
        "set RECEIPT_AMT = #{receiptAmt,jdbcType=DECIMAL},",
          "UPDATE_DATE = #{updateDate,jdbcType=TIMESTAMP},",
          "UPDATE_UID = #{updateUid,jdbcType=VARCHAR}",
        "where STD_DATE = #{stdDate,jdbcType=VARCHAR}",
          "and ORG_CD = #{orgCd,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(TFnBrandSuspense record);
}