package com.nicetcm.nibsplus.broker.msg.mapper;

import com.nicetcm.nibsplus.broker.msg.model.TFnCarry;
import com.nicetcm.nibsplus.broker.msg.model.TFnCarryKey;
import com.nicetcm.nibsplus.broker.msg.model.TFnCarrySpec;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface TFnCarryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_CARRY
     *
     * @mbggenerated Tue Jul 22 11:13:55 KST 2014
     */
    @SelectProvider(type=TFnCarrySqlProvider.class, method="countBySpec")
    int countBySpec(TFnCarrySpec spec);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_CARRY
     *
     * @mbggenerated Tue Jul 22 11:13:55 KST 2014
     */
    @DeleteProvider(type=TFnCarrySqlProvider.class, method="deleteBySpec")
    int deleteBySpec(TFnCarrySpec spec);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_CARRY
     *
     * @mbggenerated Tue Jul 22 11:13:55 KST 2014
     */
    @Delete({
        "delete from OP.T_FN_CARRY",
        "where CARRY_DATE = #{carryDate,jdbcType=VARCHAR}",
          "and CARRY_GROUP_CD = #{carryGroupCd,jdbcType=VARCHAR}",
          "and CARRY_ORG_CD = #{carryOrgCd,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(TFnCarryKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_CARRY
     *
     * @mbggenerated Tue Jul 22 11:13:55 KST 2014
     */
    @Insert({
        "insert into OP.T_FN_CARRY (CARRY_DATE, CARRY_GROUP_CD, ",
        "CARRY_ORG_CD, CASH_AMT, ",
        "CHECK_AMT, INSERT_UID, ",
        "INSERT_DATE, UPDATE_UID, ",
        "UPDATE_DATE, INS_AMT, ",
        "OUTS_AMT, CASH_13_AMT, ",
        "CHECK_13_AMT, CASH1_AMT, ",
        "CHECK1_AMT, CASH2_AMT, ",
        "CHECK2_AMT, CASH3_AMT, ",
        "CHECK3_AMT, CASH4_AMT, ",
        "CHECK4_AMT, CASH5_AMT, ",
        "CHECK5_AMT, CASH_50000_AMT, ",
        "CASH_10000_AMT, CASH_5000_AMT, ",
        "CASH_1000_AMT, OPER_CONFIRM)",
        "values (#{carryDate,jdbcType=VARCHAR}, #{carryGroupCd,jdbcType=VARCHAR}, ",
        "#{carryOrgCd,jdbcType=VARCHAR}, #{cashAmt,jdbcType=DECIMAL}, ",
        "#{checkAmt,jdbcType=DECIMAL}, #{insertUid,jdbcType=VARCHAR}, ",
        "#{insertDate,jdbcType=TIMESTAMP}, #{updateUid,jdbcType=VARCHAR}, ",
        "#{updateDate,jdbcType=TIMESTAMP}, #{insAmt,jdbcType=DECIMAL}, ",
        "#{outsAmt,jdbcType=DECIMAL}, #{cash13Amt,jdbcType=DECIMAL}, ",
        "#{check13Amt,jdbcType=DECIMAL}, #{cash1Amt,jdbcType=DECIMAL}, ",
        "#{check1Amt,jdbcType=DECIMAL}, #{cash2Amt,jdbcType=DECIMAL}, ",
        "#{check2Amt,jdbcType=DECIMAL}, #{cash3Amt,jdbcType=DECIMAL}, ",
        "#{check3Amt,jdbcType=DECIMAL}, #{cash4Amt,jdbcType=DECIMAL}, ",
        "#{check4Amt,jdbcType=DECIMAL}, #{cash5Amt,jdbcType=DECIMAL}, ",
        "#{check5Amt,jdbcType=DECIMAL}, #{cash50000Amt,jdbcType=DECIMAL}, ",
        "#{cash10000Amt,jdbcType=DECIMAL}, #{cash5000Amt,jdbcType=DECIMAL}, ",
        "#{cash1000Amt,jdbcType=DECIMAL}, #{operConfirm,jdbcType=VARCHAR})"
    })
    int insert(TFnCarry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_CARRY
     *
     * @mbggenerated Tue Jul 22 11:13:55 KST 2014
     */
    @InsertProvider(type=TFnCarrySqlProvider.class, method="insertSelective")
    int insertSelective(TFnCarry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_CARRY
     *
     * @mbggenerated Tue Jul 22 11:13:55 KST 2014
     */
    @SelectProvider(type=TFnCarrySqlProvider.class, method="selectBySpec")
    @Results({
        @Result(column="CARRY_DATE", property="carryDate", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="CARRY_GROUP_CD", property="carryGroupCd", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="CARRY_ORG_CD", property="carryOrgCd", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="CASH_AMT", property="cashAmt", jdbcType=JdbcType.DECIMAL),
        @Result(column="CHECK_AMT", property="checkAmt", jdbcType=JdbcType.DECIMAL),
        @Result(column="INSERT_UID", property="insertUid", jdbcType=JdbcType.VARCHAR),
        @Result(column="INSERT_DATE", property="insertDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="UPDATE_UID", property="updateUid", jdbcType=JdbcType.VARCHAR),
        @Result(column="UPDATE_DATE", property="updateDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="INS_AMT", property="insAmt", jdbcType=JdbcType.DECIMAL),
        @Result(column="OUTS_AMT", property="outsAmt", jdbcType=JdbcType.DECIMAL),
        @Result(column="CASH_13_AMT", property="cash13Amt", jdbcType=JdbcType.DECIMAL),
        @Result(column="CHECK_13_AMT", property="check13Amt", jdbcType=JdbcType.DECIMAL),
        @Result(column="CASH1_AMT", property="cash1Amt", jdbcType=JdbcType.DECIMAL),
        @Result(column="CHECK1_AMT", property="check1Amt", jdbcType=JdbcType.DECIMAL),
        @Result(column="CASH2_AMT", property="cash2Amt", jdbcType=JdbcType.DECIMAL),
        @Result(column="CHECK2_AMT", property="check2Amt", jdbcType=JdbcType.DECIMAL),
        @Result(column="CASH3_AMT", property="cash3Amt", jdbcType=JdbcType.DECIMAL),
        @Result(column="CHECK3_AMT", property="check3Amt", jdbcType=JdbcType.DECIMAL),
        @Result(column="CASH4_AMT", property="cash4Amt", jdbcType=JdbcType.DECIMAL),
        @Result(column="CHECK4_AMT", property="check4Amt", jdbcType=JdbcType.DECIMAL),
        @Result(column="CASH5_AMT", property="cash5Amt", jdbcType=JdbcType.DECIMAL),
        @Result(column="CHECK5_AMT", property="check5Amt", jdbcType=JdbcType.DECIMAL),
        @Result(column="CASH_50000_AMT", property="cash50000Amt", jdbcType=JdbcType.DECIMAL),
        @Result(column="CASH_10000_AMT", property="cash10000Amt", jdbcType=JdbcType.DECIMAL),
        @Result(column="CASH_5000_AMT", property="cash5000Amt", jdbcType=JdbcType.DECIMAL),
        @Result(column="CASH_1000_AMT", property="cash1000Amt", jdbcType=JdbcType.DECIMAL),
        @Result(column="OPER_CONFIRM", property="operConfirm", jdbcType=JdbcType.VARCHAR)
    })
    List<TFnCarry> selectBySpec(TFnCarrySpec spec);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_CARRY
     *
     * @mbggenerated Tue Jul 22 11:13:55 KST 2014
     */
    @Select({
        "select",
        "CARRY_DATE, CARRY_GROUP_CD, CARRY_ORG_CD, CASH_AMT, CHECK_AMT, INSERT_UID, INSERT_DATE, ",
        "UPDATE_UID, UPDATE_DATE, INS_AMT, OUTS_AMT, CASH_13_AMT, CHECK_13_AMT, CASH1_AMT, ",
        "CHECK1_AMT, CASH2_AMT, CHECK2_AMT, CASH3_AMT, CHECK3_AMT, CASH4_AMT, CHECK4_AMT, ",
        "CASH5_AMT, CHECK5_AMT, CASH_50000_AMT, CASH_10000_AMT, CASH_5000_AMT, CASH_1000_AMT, ",
        "OPER_CONFIRM",
        "from OP.T_FN_CARRY",
        "where CARRY_DATE = #{carryDate,jdbcType=VARCHAR}",
          "and CARRY_GROUP_CD = #{carryGroupCd,jdbcType=VARCHAR}",
          "and CARRY_ORG_CD = #{carryOrgCd,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="CARRY_DATE", property="carryDate", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="CARRY_GROUP_CD", property="carryGroupCd", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="CARRY_ORG_CD", property="carryOrgCd", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="CASH_AMT", property="cashAmt", jdbcType=JdbcType.DECIMAL),
        @Result(column="CHECK_AMT", property="checkAmt", jdbcType=JdbcType.DECIMAL),
        @Result(column="INSERT_UID", property="insertUid", jdbcType=JdbcType.VARCHAR),
        @Result(column="INSERT_DATE", property="insertDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="UPDATE_UID", property="updateUid", jdbcType=JdbcType.VARCHAR),
        @Result(column="UPDATE_DATE", property="updateDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="INS_AMT", property="insAmt", jdbcType=JdbcType.DECIMAL),
        @Result(column="OUTS_AMT", property="outsAmt", jdbcType=JdbcType.DECIMAL),
        @Result(column="CASH_13_AMT", property="cash13Amt", jdbcType=JdbcType.DECIMAL),
        @Result(column="CHECK_13_AMT", property="check13Amt", jdbcType=JdbcType.DECIMAL),
        @Result(column="CASH1_AMT", property="cash1Amt", jdbcType=JdbcType.DECIMAL),
        @Result(column="CHECK1_AMT", property="check1Amt", jdbcType=JdbcType.DECIMAL),
        @Result(column="CASH2_AMT", property="cash2Amt", jdbcType=JdbcType.DECIMAL),
        @Result(column="CHECK2_AMT", property="check2Amt", jdbcType=JdbcType.DECIMAL),
        @Result(column="CASH3_AMT", property="cash3Amt", jdbcType=JdbcType.DECIMAL),
        @Result(column="CHECK3_AMT", property="check3Amt", jdbcType=JdbcType.DECIMAL),
        @Result(column="CASH4_AMT", property="cash4Amt", jdbcType=JdbcType.DECIMAL),
        @Result(column="CHECK4_AMT", property="check4Amt", jdbcType=JdbcType.DECIMAL),
        @Result(column="CASH5_AMT", property="cash5Amt", jdbcType=JdbcType.DECIMAL),
        @Result(column="CHECK5_AMT", property="check5Amt", jdbcType=JdbcType.DECIMAL),
        @Result(column="CASH_50000_AMT", property="cash50000Amt", jdbcType=JdbcType.DECIMAL),
        @Result(column="CASH_10000_AMT", property="cash10000Amt", jdbcType=JdbcType.DECIMAL),
        @Result(column="CASH_5000_AMT", property="cash5000Amt", jdbcType=JdbcType.DECIMAL),
        @Result(column="CASH_1000_AMT", property="cash1000Amt", jdbcType=JdbcType.DECIMAL),
        @Result(column="OPER_CONFIRM", property="operConfirm", jdbcType=JdbcType.VARCHAR)
    })
    TFnCarry selectByPrimaryKey(TFnCarryKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_CARRY
     *
     * @mbggenerated Tue Jul 22 11:13:55 KST 2014
     */
    @UpdateProvider(type=TFnCarrySqlProvider.class, method="updateBySpecSelective")
    int updateBySpecSelective(@Param("record") TFnCarry record, @Param("spec") TFnCarrySpec spec);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_CARRY
     *
     * @mbggenerated Tue Jul 22 11:13:55 KST 2014
     */
    @UpdateProvider(type=TFnCarrySqlProvider.class, method="updateBySpec")
    int updateBySpec(@Param("record") TFnCarry record, @Param("spec") TFnCarrySpec spec);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_CARRY
     *
     * @mbggenerated Tue Jul 22 11:13:55 KST 2014
     */
    @UpdateProvider(type=TFnCarrySqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(TFnCarry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_CARRY
     *
     * @mbggenerated Tue Jul 22 11:13:55 KST 2014
     */
    @Update({
        "update OP.T_FN_CARRY",
        "set CASH_AMT = #{cashAmt,jdbcType=DECIMAL},",
          "CHECK_AMT = #{checkAmt,jdbcType=DECIMAL},",
          "INSERT_UID = #{insertUid,jdbcType=VARCHAR},",
          "INSERT_DATE = #{insertDate,jdbcType=TIMESTAMP},",
          "UPDATE_UID = #{updateUid,jdbcType=VARCHAR},",
          "UPDATE_DATE = #{updateDate,jdbcType=TIMESTAMP},",
          "INS_AMT = #{insAmt,jdbcType=DECIMAL},",
          "OUTS_AMT = #{outsAmt,jdbcType=DECIMAL},",
          "CASH_13_AMT = #{cash13Amt,jdbcType=DECIMAL},",
          "CHECK_13_AMT = #{check13Amt,jdbcType=DECIMAL},",
          "CASH1_AMT = #{cash1Amt,jdbcType=DECIMAL},",
          "CHECK1_AMT = #{check1Amt,jdbcType=DECIMAL},",
          "CASH2_AMT = #{cash2Amt,jdbcType=DECIMAL},",
          "CHECK2_AMT = #{check2Amt,jdbcType=DECIMAL},",
          "CASH3_AMT = #{cash3Amt,jdbcType=DECIMAL},",
          "CHECK3_AMT = #{check3Amt,jdbcType=DECIMAL},",
          "CASH4_AMT = #{cash4Amt,jdbcType=DECIMAL},",
          "CHECK4_AMT = #{check4Amt,jdbcType=DECIMAL},",
          "CASH5_AMT = #{cash5Amt,jdbcType=DECIMAL},",
          "CHECK5_AMT = #{check5Amt,jdbcType=DECIMAL},",
          "CASH_50000_AMT = #{cash50000Amt,jdbcType=DECIMAL},",
          "CASH_10000_AMT = #{cash10000Amt,jdbcType=DECIMAL},",
          "CASH_5000_AMT = #{cash5000Amt,jdbcType=DECIMAL},",
          "CASH_1000_AMT = #{cash1000Amt,jdbcType=DECIMAL},",
          "OPER_CONFIRM = #{operConfirm,jdbcType=VARCHAR}",
        "where CARRY_DATE = #{carryDate,jdbcType=VARCHAR}",
          "and CARRY_GROUP_CD = #{carryGroupCd,jdbcType=VARCHAR}",
          "and CARRY_ORG_CD = #{carryOrgCd,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(TFnCarry record);
}