package com.nicetcm.nibsplus.broker.msg.mapper;

import com.nicetcm.nibsplus.broker.msg.model.TFnInoutOrg;
import com.nicetcm.nibsplus.broker.msg.model.TFnInoutOrgKey;
import com.nicetcm.nibsplus.broker.msg.model.TFnInoutOrgSpec;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface TFnInoutOrgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_INOUT_ORG
     *
     * @mbggenerated Mon Jul 28 16:08:07 KST 2014
     */
    @SelectProvider(type=TFnInoutOrgSqlProvider.class, method="countBySpec")
    int countBySpec(TFnInoutOrgSpec spec);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_INOUT_ORG
     *
     * @mbggenerated Mon Jul 28 16:08:07 KST 2014
     */
    @DeleteProvider(type=TFnInoutOrgSqlProvider.class, method="deleteBySpec")
    int deleteBySpec(TFnInoutOrgSpec spec);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_INOUT_ORG
     *
     * @mbggenerated Mon Jul 28 16:08:07 KST 2014
     */
    @Delete({
        "delete from OP.T_FN_INOUT_ORG",
        "where ORG_CD = #{orgCd,jdbcType=VARCHAR}",
          "and BRANCH_CD = #{branchCd,jdbcType=VARCHAR}",
          "and MAC_NO = #{macNo,jdbcType=VARCHAR}",
          "and DEAL_DATE = #{dealDate,jdbcType=VARCHAR}",
          "and SEQ = #{seq,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(TFnInoutOrgKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_INOUT_ORG
     *
     * @mbggenerated Mon Jul 28 16:08:07 KST 2014
     */
    @Insert({
        "insert into OP.T_FN_INOUT_ORG (ORG_CD, BRANCH_CD, ",
        "MAC_NO, DEAL_DATE, ",
        "SEQ, MEMBER_ID, DEAL_TIME, ",
        "INOUT_GB, DETAIL_GB, ",
        "IN_KJ_GB, CW15_CNT, ",
        "CW54_CNT, CW14_CNT, ",
        "CW53_CNT, CW13_CNT, ",
        "CW52_CNT, CW12_CNT, ",
        "CW51_CNT, CW11_CNT, ",
        "BOX_CASH_AMT, COIN_AMT, ",
        "CHECK_AMT, SELF_TICKET_AMT, ",
        "ETC_TICKET_AMT, CUPON_AMT, ",
        "ETC_IN_AMT, BOX_AMT, ",
        "UPDATE_DATE, UPDATE_UID, ",
        "CLOSE_YN, HW16_CNT, ",
        "HW55_CNT, HW35_CNT, ",
        "HW15_CNT, CHECK_NONFIXED_CNT, ",
        "CHECK_NONFIXED_AMT, CASH_CUPON_AMT, ",
        "BASE_OUT_TYPE, OWN_TRADE_DATE, ",
        "OWN_TRADE_SEQ, OWN_TRADE_MAC_NO, ",
        "GOOD_TELE_NO, RATE_CUPON_CNT, ",
        "TICKET_AMT, DOLLAR_AMT, ",
        "EURO_AMT, YEN_AMT, ",
        "YUAN_AMT)",
        "values (#{orgCd,jdbcType=VARCHAR}, #{branchCd,jdbcType=VARCHAR}, ",
        "#{macNo,jdbcType=VARCHAR}, #{dealDate,jdbcType=VARCHAR}, ",
        "#{seq,jdbcType=VARCHAR}, #{memberId,jdbcType=VARCHAR}, #{dealTime,jdbcType=VARCHAR}, ",
        "#{inoutGb,jdbcType=VARCHAR}, #{detailGb,jdbcType=VARCHAR}, ",
        "#{inKjGb,jdbcType=VARCHAR}, #{cw15Cnt,jdbcType=DECIMAL}, ",
        "#{cw54Cnt,jdbcType=DECIMAL}, #{cw14Cnt,jdbcType=DECIMAL}, ",
        "#{cw53Cnt,jdbcType=DECIMAL}, #{cw13Cnt,jdbcType=DECIMAL}, ",
        "#{cw52Cnt,jdbcType=DECIMAL}, #{cw12Cnt,jdbcType=DECIMAL}, ",
        "#{cw51Cnt,jdbcType=DECIMAL}, #{cw11Cnt,jdbcType=DECIMAL}, ",
        "#{boxCashAmt,jdbcType=DECIMAL}, #{coinAmt,jdbcType=DECIMAL}, ",
        "#{checkAmt,jdbcType=DECIMAL}, #{selfTicketAmt,jdbcType=DECIMAL}, ",
        "#{etcTicketAmt,jdbcType=DECIMAL}, #{cuponAmt,jdbcType=DECIMAL}, ",
        "#{etcInAmt,jdbcType=DECIMAL}, #{boxAmt,jdbcType=DECIMAL}, ",
        "#{updateDate,jdbcType=TIMESTAMP}, #{updateUid,jdbcType=VARCHAR}, ",
        "#{closeYn,jdbcType=VARCHAR}, #{hw16Cnt,jdbcType=DECIMAL}, ",
        "#{hw55Cnt,jdbcType=DECIMAL}, #{hw35Cnt,jdbcType=DECIMAL}, ",
        "#{hw15Cnt,jdbcType=DECIMAL}, #{checkNonfixedCnt,jdbcType=DECIMAL}, ",
        "#{checkNonfixedAmt,jdbcType=DECIMAL}, #{cashCuponAmt,jdbcType=DECIMAL}, ",
        "#{baseOutType,jdbcType=VARCHAR}, #{ownTradeDate,jdbcType=VARCHAR}, ",
        "#{ownTradeSeq,jdbcType=VARCHAR}, #{ownTradeMacNo,jdbcType=VARCHAR}, ",
        "#{goodTeleNo,jdbcType=VARCHAR}, #{rateCuponCnt,jdbcType=DECIMAL}, ",
        "#{ticketAmt,jdbcType=DECIMAL}, #{dollarAmt,jdbcType=DECIMAL}, ",
        "#{euroAmt,jdbcType=DECIMAL}, #{yenAmt,jdbcType=DECIMAL}, ",
        "#{yuanAmt,jdbcType=DECIMAL})"
    })
    int insert(TFnInoutOrg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_INOUT_ORG
     *
     * @mbggenerated Mon Jul 28 16:08:07 KST 2014
     */
    @InsertProvider(type=TFnInoutOrgSqlProvider.class, method="insertSelective")
    int insertSelective(TFnInoutOrg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_INOUT_ORG
     *
     * @mbggenerated Mon Jul 28 16:08:07 KST 2014
     */
    @SelectProvider(type=TFnInoutOrgSqlProvider.class, method="selectBySpec")
    @Results({
        @Result(column="ORG_CD", property="orgCd", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="BRANCH_CD", property="branchCd", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="MAC_NO", property="macNo", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="DEAL_DATE", property="dealDate", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="SEQ", property="seq", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="MEMBER_ID", property="memberId", jdbcType=JdbcType.VARCHAR),
        @Result(column="DEAL_TIME", property="dealTime", jdbcType=JdbcType.VARCHAR),
        @Result(column="INOUT_GB", property="inoutGb", jdbcType=JdbcType.VARCHAR),
        @Result(column="DETAIL_GB", property="detailGb", jdbcType=JdbcType.VARCHAR),
        @Result(column="IN_KJ_GB", property="inKjGb", jdbcType=JdbcType.VARCHAR),
        @Result(column="CW15_CNT", property="cw15Cnt", jdbcType=JdbcType.DECIMAL),
        @Result(column="CW54_CNT", property="cw54Cnt", jdbcType=JdbcType.DECIMAL),
        @Result(column="CW14_CNT", property="cw14Cnt", jdbcType=JdbcType.DECIMAL),
        @Result(column="CW53_CNT", property="cw53Cnt", jdbcType=JdbcType.DECIMAL),
        @Result(column="CW13_CNT", property="cw13Cnt", jdbcType=JdbcType.DECIMAL),
        @Result(column="CW52_CNT", property="cw52Cnt", jdbcType=JdbcType.DECIMAL),
        @Result(column="CW12_CNT", property="cw12Cnt", jdbcType=JdbcType.DECIMAL),
        @Result(column="CW51_CNT", property="cw51Cnt", jdbcType=JdbcType.DECIMAL),
        @Result(column="CW11_CNT", property="cw11Cnt", jdbcType=JdbcType.DECIMAL),
        @Result(column="BOX_CASH_AMT", property="boxCashAmt", jdbcType=JdbcType.DECIMAL),
        @Result(column="COIN_AMT", property="coinAmt", jdbcType=JdbcType.DECIMAL),
        @Result(column="CHECK_AMT", property="checkAmt", jdbcType=JdbcType.DECIMAL),
        @Result(column="SELF_TICKET_AMT", property="selfTicketAmt", jdbcType=JdbcType.DECIMAL),
        @Result(column="ETC_TICKET_AMT", property="etcTicketAmt", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUPON_AMT", property="cuponAmt", jdbcType=JdbcType.DECIMAL),
        @Result(column="ETC_IN_AMT", property="etcInAmt", jdbcType=JdbcType.DECIMAL),
        @Result(column="BOX_AMT", property="boxAmt", jdbcType=JdbcType.DECIMAL),
        @Result(column="UPDATE_DATE", property="updateDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="UPDATE_UID", property="updateUid", jdbcType=JdbcType.VARCHAR),
        @Result(column="CLOSE_YN", property="closeYn", jdbcType=JdbcType.VARCHAR),
        @Result(column="HW16_CNT", property="hw16Cnt", jdbcType=JdbcType.DECIMAL),
        @Result(column="HW55_CNT", property="hw55Cnt", jdbcType=JdbcType.DECIMAL),
        @Result(column="HW35_CNT", property="hw35Cnt", jdbcType=JdbcType.DECIMAL),
        @Result(column="HW15_CNT", property="hw15Cnt", jdbcType=JdbcType.DECIMAL),
        @Result(column="CHECK_NONFIXED_CNT", property="checkNonfixedCnt", jdbcType=JdbcType.DECIMAL),
        @Result(column="CHECK_NONFIXED_AMT", property="checkNonfixedAmt", jdbcType=JdbcType.DECIMAL),
        @Result(column="CASH_CUPON_AMT", property="cashCuponAmt", jdbcType=JdbcType.DECIMAL),
        @Result(column="BASE_OUT_TYPE", property="baseOutType", jdbcType=JdbcType.VARCHAR),
        @Result(column="OWN_TRADE_DATE", property="ownTradeDate", jdbcType=JdbcType.VARCHAR),
        @Result(column="OWN_TRADE_SEQ", property="ownTradeSeq", jdbcType=JdbcType.VARCHAR),
        @Result(column="OWN_TRADE_MAC_NO", property="ownTradeMacNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="GOOD_TELE_NO", property="goodTeleNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="RATE_CUPON_CNT", property="rateCuponCnt", jdbcType=JdbcType.DECIMAL),
        @Result(column="TICKET_AMT", property="ticketAmt", jdbcType=JdbcType.DECIMAL),
        @Result(column="DOLLAR_AMT", property="dollarAmt", jdbcType=JdbcType.DECIMAL),
        @Result(column="EURO_AMT", property="euroAmt", jdbcType=JdbcType.DECIMAL),
        @Result(column="YEN_AMT", property="yenAmt", jdbcType=JdbcType.DECIMAL),
        @Result(column="YUAN_AMT", property="yuanAmt", jdbcType=JdbcType.DECIMAL)
    })
    List<TFnInoutOrg> selectBySpec(TFnInoutOrgSpec spec);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_INOUT_ORG
     *
     * @mbggenerated Mon Jul 28 16:08:07 KST 2014
     */
    @Select({
        "select",
        "ORG_CD, BRANCH_CD, MAC_NO, DEAL_DATE, SEQ, MEMBER_ID, DEAL_TIME, INOUT_GB, DETAIL_GB, ",
        "IN_KJ_GB, CW15_CNT, CW54_CNT, CW14_CNT, CW53_CNT, CW13_CNT, CW52_CNT, CW12_CNT, ",
        "CW51_CNT, CW11_CNT, BOX_CASH_AMT, COIN_AMT, CHECK_AMT, SELF_TICKET_AMT, ETC_TICKET_AMT, ",
        "CUPON_AMT, ETC_IN_AMT, BOX_AMT, UPDATE_DATE, UPDATE_UID, CLOSE_YN, HW16_CNT, ",
        "HW55_CNT, HW35_CNT, HW15_CNT, CHECK_NONFIXED_CNT, CHECK_NONFIXED_AMT, CASH_CUPON_AMT, ",
        "BASE_OUT_TYPE, OWN_TRADE_DATE, OWN_TRADE_SEQ, OWN_TRADE_MAC_NO, GOOD_TELE_NO, ",
        "RATE_CUPON_CNT, TICKET_AMT, DOLLAR_AMT, EURO_AMT, YEN_AMT, YUAN_AMT",
        "from OP.T_FN_INOUT_ORG",
        "where ORG_CD = #{orgCd,jdbcType=VARCHAR}",
          "and BRANCH_CD = #{branchCd,jdbcType=VARCHAR}",
          "and MAC_NO = #{macNo,jdbcType=VARCHAR}",
          "and DEAL_DATE = #{dealDate,jdbcType=VARCHAR}",
          "and SEQ = #{seq,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="ORG_CD", property="orgCd", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="BRANCH_CD", property="branchCd", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="MAC_NO", property="macNo", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="DEAL_DATE", property="dealDate", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="SEQ", property="seq", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="MEMBER_ID", property="memberId", jdbcType=JdbcType.VARCHAR),
        @Result(column="DEAL_TIME", property="dealTime", jdbcType=JdbcType.VARCHAR),
        @Result(column="INOUT_GB", property="inoutGb", jdbcType=JdbcType.VARCHAR),
        @Result(column="DETAIL_GB", property="detailGb", jdbcType=JdbcType.VARCHAR),
        @Result(column="IN_KJ_GB", property="inKjGb", jdbcType=JdbcType.VARCHAR),
        @Result(column="CW15_CNT", property="cw15Cnt", jdbcType=JdbcType.DECIMAL),
        @Result(column="CW54_CNT", property="cw54Cnt", jdbcType=JdbcType.DECIMAL),
        @Result(column="CW14_CNT", property="cw14Cnt", jdbcType=JdbcType.DECIMAL),
        @Result(column="CW53_CNT", property="cw53Cnt", jdbcType=JdbcType.DECIMAL),
        @Result(column="CW13_CNT", property="cw13Cnt", jdbcType=JdbcType.DECIMAL),
        @Result(column="CW52_CNT", property="cw52Cnt", jdbcType=JdbcType.DECIMAL),
        @Result(column="CW12_CNT", property="cw12Cnt", jdbcType=JdbcType.DECIMAL),
        @Result(column="CW51_CNT", property="cw51Cnt", jdbcType=JdbcType.DECIMAL),
        @Result(column="CW11_CNT", property="cw11Cnt", jdbcType=JdbcType.DECIMAL),
        @Result(column="BOX_CASH_AMT", property="boxCashAmt", jdbcType=JdbcType.DECIMAL),
        @Result(column="COIN_AMT", property="coinAmt", jdbcType=JdbcType.DECIMAL),
        @Result(column="CHECK_AMT", property="checkAmt", jdbcType=JdbcType.DECIMAL),
        @Result(column="SELF_TICKET_AMT", property="selfTicketAmt", jdbcType=JdbcType.DECIMAL),
        @Result(column="ETC_TICKET_AMT", property="etcTicketAmt", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUPON_AMT", property="cuponAmt", jdbcType=JdbcType.DECIMAL),
        @Result(column="ETC_IN_AMT", property="etcInAmt", jdbcType=JdbcType.DECIMAL),
        @Result(column="BOX_AMT", property="boxAmt", jdbcType=JdbcType.DECIMAL),
        @Result(column="UPDATE_DATE", property="updateDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="UPDATE_UID", property="updateUid", jdbcType=JdbcType.VARCHAR),
        @Result(column="CLOSE_YN", property="closeYn", jdbcType=JdbcType.VARCHAR),
        @Result(column="HW16_CNT", property="hw16Cnt", jdbcType=JdbcType.DECIMAL),
        @Result(column="HW55_CNT", property="hw55Cnt", jdbcType=JdbcType.DECIMAL),
        @Result(column="HW35_CNT", property="hw35Cnt", jdbcType=JdbcType.DECIMAL),
        @Result(column="HW15_CNT", property="hw15Cnt", jdbcType=JdbcType.DECIMAL),
        @Result(column="CHECK_NONFIXED_CNT", property="checkNonfixedCnt", jdbcType=JdbcType.DECIMAL),
        @Result(column="CHECK_NONFIXED_AMT", property="checkNonfixedAmt", jdbcType=JdbcType.DECIMAL),
        @Result(column="CASH_CUPON_AMT", property="cashCuponAmt", jdbcType=JdbcType.DECIMAL),
        @Result(column="BASE_OUT_TYPE", property="baseOutType", jdbcType=JdbcType.VARCHAR),
        @Result(column="OWN_TRADE_DATE", property="ownTradeDate", jdbcType=JdbcType.VARCHAR),
        @Result(column="OWN_TRADE_SEQ", property="ownTradeSeq", jdbcType=JdbcType.VARCHAR),
        @Result(column="OWN_TRADE_MAC_NO", property="ownTradeMacNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="GOOD_TELE_NO", property="goodTeleNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="RATE_CUPON_CNT", property="rateCuponCnt", jdbcType=JdbcType.DECIMAL),
        @Result(column="TICKET_AMT", property="ticketAmt", jdbcType=JdbcType.DECIMAL),
        @Result(column="DOLLAR_AMT", property="dollarAmt", jdbcType=JdbcType.DECIMAL),
        @Result(column="EURO_AMT", property="euroAmt", jdbcType=JdbcType.DECIMAL),
        @Result(column="YEN_AMT", property="yenAmt", jdbcType=JdbcType.DECIMAL),
        @Result(column="YUAN_AMT", property="yuanAmt", jdbcType=JdbcType.DECIMAL)
    })
    TFnInoutOrg selectByPrimaryKey(TFnInoutOrgKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_INOUT_ORG
     *
     * @mbggenerated Mon Jul 28 16:08:07 KST 2014
     */
    @UpdateProvider(type=TFnInoutOrgSqlProvider.class, method="updateBySpecSelective")
    int updateBySpecSelective(@Param("record") TFnInoutOrg record, @Param("spec") TFnInoutOrgSpec spec);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_INOUT_ORG
     *
     * @mbggenerated Mon Jul 28 16:08:07 KST 2014
     */
    @UpdateProvider(type=TFnInoutOrgSqlProvider.class, method="updateBySpec")
    int updateBySpec(@Param("record") TFnInoutOrg record, @Param("spec") TFnInoutOrgSpec spec);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_INOUT_ORG
     *
     * @mbggenerated Mon Jul 28 16:08:07 KST 2014
     */
    @UpdateProvider(type=TFnInoutOrgSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(TFnInoutOrg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_INOUT_ORG
     *
     * @mbggenerated Mon Jul 28 16:08:07 KST 2014
     */
    @Update({
        "update OP.T_FN_INOUT_ORG",
        "set MEMBER_ID = #{memberId,jdbcType=VARCHAR},",
          "DEAL_TIME = #{dealTime,jdbcType=VARCHAR},",
          "INOUT_GB = #{inoutGb,jdbcType=VARCHAR},",
          "DETAIL_GB = #{detailGb,jdbcType=VARCHAR},",
          "IN_KJ_GB = #{inKjGb,jdbcType=VARCHAR},",
          "CW15_CNT = #{cw15Cnt,jdbcType=DECIMAL},",
          "CW54_CNT = #{cw54Cnt,jdbcType=DECIMAL},",
          "CW14_CNT = #{cw14Cnt,jdbcType=DECIMAL},",
          "CW53_CNT = #{cw53Cnt,jdbcType=DECIMAL},",
          "CW13_CNT = #{cw13Cnt,jdbcType=DECIMAL},",
          "CW52_CNT = #{cw52Cnt,jdbcType=DECIMAL},",
          "CW12_CNT = #{cw12Cnt,jdbcType=DECIMAL},",
          "CW51_CNT = #{cw51Cnt,jdbcType=DECIMAL},",
          "CW11_CNT = #{cw11Cnt,jdbcType=DECIMAL},",
          "BOX_CASH_AMT = #{boxCashAmt,jdbcType=DECIMAL},",
          "COIN_AMT = #{coinAmt,jdbcType=DECIMAL},",
          "CHECK_AMT = #{checkAmt,jdbcType=DECIMAL},",
          "SELF_TICKET_AMT = #{selfTicketAmt,jdbcType=DECIMAL},",
          "ETC_TICKET_AMT = #{etcTicketAmt,jdbcType=DECIMAL},",
          "CUPON_AMT = #{cuponAmt,jdbcType=DECIMAL},",
          "ETC_IN_AMT = #{etcInAmt,jdbcType=DECIMAL},",
          "BOX_AMT = #{boxAmt,jdbcType=DECIMAL},",
          "UPDATE_DATE = #{updateDate,jdbcType=TIMESTAMP},",
          "UPDATE_UID = #{updateUid,jdbcType=VARCHAR},",
          "CLOSE_YN = #{closeYn,jdbcType=VARCHAR},",
          "HW16_CNT = #{hw16Cnt,jdbcType=DECIMAL},",
          "HW55_CNT = #{hw55Cnt,jdbcType=DECIMAL},",
          "HW35_CNT = #{hw35Cnt,jdbcType=DECIMAL},",
          "HW15_CNT = #{hw15Cnt,jdbcType=DECIMAL},",
          "CHECK_NONFIXED_CNT = #{checkNonfixedCnt,jdbcType=DECIMAL},",
          "CHECK_NONFIXED_AMT = #{checkNonfixedAmt,jdbcType=DECIMAL},",
          "CASH_CUPON_AMT = #{cashCuponAmt,jdbcType=DECIMAL},",
          "BASE_OUT_TYPE = #{baseOutType,jdbcType=VARCHAR},",
          "OWN_TRADE_DATE = #{ownTradeDate,jdbcType=VARCHAR},",
          "OWN_TRADE_SEQ = #{ownTradeSeq,jdbcType=VARCHAR},",
          "OWN_TRADE_MAC_NO = #{ownTradeMacNo,jdbcType=VARCHAR},",
          "GOOD_TELE_NO = #{goodTeleNo,jdbcType=VARCHAR},",
          "RATE_CUPON_CNT = #{rateCuponCnt,jdbcType=DECIMAL},",
          "TICKET_AMT = #{ticketAmt,jdbcType=DECIMAL},",
          "DOLLAR_AMT = #{dollarAmt,jdbcType=DECIMAL},",
          "EURO_AMT = #{euroAmt,jdbcType=DECIMAL},",
          "YEN_AMT = #{yenAmt,jdbcType=DECIMAL},",
          "YUAN_AMT = #{yuanAmt,jdbcType=DECIMAL}",
        "where ORG_CD = #{orgCd,jdbcType=VARCHAR}",
          "and BRANCH_CD = #{branchCd,jdbcType=VARCHAR}",
          "and MAC_NO = #{macNo,jdbcType=VARCHAR}",
          "and DEAL_DATE = #{dealDate,jdbcType=VARCHAR}",
          "and SEQ = #{seq,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(TFnInoutOrg record);
}