package com.nicetcm.nibsplus.broker.msg.mapper;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.DELETE_FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.ORDER_BY;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT_DISTINCT;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import com.nicetcm.nibsplus.broker.msg.model.TFnNotendEmartFrgn;
import com.nicetcm.nibsplus.broker.msg.model.TFnNotendEmartFrgnSpec.Criteria;
import com.nicetcm.nibsplus.broker.msg.model.TFnNotendEmartFrgnSpec.Criterion;
import com.nicetcm.nibsplus.broker.msg.model.TFnNotendEmartFrgnSpec;
import java.util.List;
import java.util.Map;

public class TFnNotendEmartFrgnSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_NOTEND_EMART_FRGN
     *
     * @mbggenerated Tue Jul 22 11:13:55 KST 2014
     */
    public String countBySpec(TFnNotendEmartFrgnSpec spec) {
        BEGIN();
        SELECT("count(*)");
        FROM("OP.T_FN_NOTEND_EMART_FRGN");
        applyWhere(spec, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_NOTEND_EMART_FRGN
     *
     * @mbggenerated Tue Jul 22 11:13:55 KST 2014
     */
    public String deleteBySpec(TFnNotendEmartFrgnSpec spec) {
        BEGIN();
        DELETE_FROM("OP.T_FN_NOTEND_EMART_FRGN");
        applyWhere(spec, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_NOTEND_EMART_FRGN
     *
     * @mbggenerated Tue Jul 22 11:13:55 KST 2014
     */
    public String insertSelective(TFnNotendEmartFrgn record) {
        BEGIN();
        INSERT_INTO("OP.T_FN_NOTEND_EMART_FRGN");
        
        if (record.getDealDate() != null) {
            VALUES("DEAL_DATE", "#{dealDate,jdbcType=VARCHAR}");
        }
        
        if (record.getOrgCd() != null) {
            VALUES("ORG_CD", "#{orgCd,jdbcType=VARCHAR}");
        }
        
        if (record.getBranchCd() != null) {
            VALUES("BRANCH_CD", "#{branchCd,jdbcType=VARCHAR}");
        }
        
        if (record.getMacNo() != null) {
            VALUES("MAC_NO", "#{macNo,jdbcType=VARCHAR}");
        }
        
        if (record.getDealTime() != null) {
            VALUES("DEAL_TIME", "#{dealTime,jdbcType=VARCHAR}");
        }
        
        if (record.getMemberId() != null) {
            VALUES("MEMBER_ID", "#{memberId,jdbcType=VARCHAR}");
        }
        
        if (record.getCloseDate() != null) {
            VALUES("CLOSE_DATE", "#{closeDate,jdbcType=VARCHAR}");
        }
        
        if (record.getDollarAmt() != null) {
            VALUES("DOLLAR_AMT", "#{dollarAmt,jdbcType=DECIMAL}");
        }
        
        if (record.getDollarRemark() != null) {
            VALUES("DOLLAR_REMARK", "#{dollarRemark,jdbcType=VARCHAR}");
        }
        
        if (record.getEuroAmt() != null) {
            VALUES("EURO_AMT", "#{euroAmt,jdbcType=DECIMAL}");
        }
        
        if (record.getEuroRemark() != null) {
            VALUES("EURO_REMARK", "#{euroRemark,jdbcType=VARCHAR}");
        }
        
        if (record.getYenAmt() != null) {
            VALUES("YEN_AMT", "#{yenAmt,jdbcType=DECIMAL}");
        }
        
        if (record.getYenRemark() != null) {
            VALUES("YEN_REMARK", "#{yenRemark,jdbcType=VARCHAR}");
        }
        
        if (record.getYuanAmt() != null) {
            VALUES("YUAN_AMT", "#{yuanAmt,jdbcType=DECIMAL}");
        }
        
        if (record.getYuanRemark() != null) {
            VALUES("YUAN_REMARK", "#{yuanRemark,jdbcType=VARCHAR}");
        }
        
        if (record.getUpdateDate() != null) {
            VALUES("UPDATE_DATE", "#{updateDate,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdateUid() != null) {
            VALUES("UPDATE_UID", "#{updateUid,jdbcType=VARCHAR}");
        }
        
        if (record.getOrgSendYn() != null) {
            VALUES("ORG_SEND_YN", "#{orgSendYn,jdbcType=VARCHAR}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_NOTEND_EMART_FRGN
     *
     * @mbggenerated Tue Jul 22 11:13:55 KST 2014
     */
    public String selectBySpec(TFnNotendEmartFrgnSpec spec) {
        BEGIN();
        if (spec != null && spec.isDistinct()) {
            SELECT_DISTINCT("DEAL_DATE");
        } else {
            SELECT("DEAL_DATE");
        }
        SELECT("ORG_CD");
        SELECT("BRANCH_CD");
        SELECT("MAC_NO");
        SELECT("DEAL_TIME");
        SELECT("MEMBER_ID");
        SELECT("CLOSE_DATE");
        SELECT("DOLLAR_AMT");
        SELECT("DOLLAR_REMARK");
        SELECT("EURO_AMT");
        SELECT("EURO_REMARK");
        SELECT("YEN_AMT");
        SELECT("YEN_REMARK");
        SELECT("YUAN_AMT");
        SELECT("YUAN_REMARK");
        SELECT("UPDATE_DATE");
        SELECT("UPDATE_UID");
        SELECT("ORG_SEND_YN");
        FROM("OP.T_FN_NOTEND_EMART_FRGN");
        applyWhere(spec, false);
        
        if (spec != null && spec.getOrderByClause() != null) {
            ORDER_BY(spec.getOrderByClause());
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_NOTEND_EMART_FRGN
     *
     * @mbggenerated Tue Jul 22 11:13:55 KST 2014
     */
    public String updateBySpecSelective(Map<String, Object> parameter) {
        TFnNotendEmartFrgn record = (TFnNotendEmartFrgn) parameter.get("record");
        TFnNotendEmartFrgnSpec spec = (TFnNotendEmartFrgnSpec) parameter.get("spec");
        
        BEGIN();
        UPDATE("OP.T_FN_NOTEND_EMART_FRGN");
        
        if (record.getDealDate() != null) {
            SET("DEAL_DATE = #{record.dealDate,jdbcType=VARCHAR}");
        }
        
        if (record.getOrgCd() != null) {
            SET("ORG_CD = #{record.orgCd,jdbcType=VARCHAR}");
        }
        
        if (record.getBranchCd() != null) {
            SET("BRANCH_CD = #{record.branchCd,jdbcType=VARCHAR}");
        }
        
        if (record.getMacNo() != null) {
            SET("MAC_NO = #{record.macNo,jdbcType=VARCHAR}");
        }
        
        if (record.getDealTime() != null) {
            SET("DEAL_TIME = #{record.dealTime,jdbcType=VARCHAR}");
        }
        
        if (record.getMemberId() != null) {
            SET("MEMBER_ID = #{record.memberId,jdbcType=VARCHAR}");
        }
        
        if (record.getCloseDate() != null) {
            SET("CLOSE_DATE = #{record.closeDate,jdbcType=VARCHAR}");
        }
        
        if (record.getDollarAmt() != null) {
            SET("DOLLAR_AMT = #{record.dollarAmt,jdbcType=DECIMAL}");
        }
        
        if (record.getDollarRemark() != null) {
            SET("DOLLAR_REMARK = #{record.dollarRemark,jdbcType=VARCHAR}");
        }
        
        if (record.getEuroAmt() != null) {
            SET("EURO_AMT = #{record.euroAmt,jdbcType=DECIMAL}");
        }
        
        if (record.getEuroRemark() != null) {
            SET("EURO_REMARK = #{record.euroRemark,jdbcType=VARCHAR}");
        }
        
        if (record.getYenAmt() != null) {
            SET("YEN_AMT = #{record.yenAmt,jdbcType=DECIMAL}");
        }
        
        if (record.getYenRemark() != null) {
            SET("YEN_REMARK = #{record.yenRemark,jdbcType=VARCHAR}");
        }
        
        if (record.getYuanAmt() != null) {
            SET("YUAN_AMT = #{record.yuanAmt,jdbcType=DECIMAL}");
        }
        
        if (record.getYuanRemark() != null) {
            SET("YUAN_REMARK = #{record.yuanRemark,jdbcType=VARCHAR}");
        }
        
        if (record.getUpdateDate() != null) {
            SET("UPDATE_DATE = #{record.updateDate,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdateUid() != null) {
            SET("UPDATE_UID = #{record.updateUid,jdbcType=VARCHAR}");
        }
        
        if (record.getOrgSendYn() != null) {
            SET("ORG_SEND_YN = #{record.orgSendYn,jdbcType=VARCHAR}");
        }
        
        applyWhere(spec, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_NOTEND_EMART_FRGN
     *
     * @mbggenerated Tue Jul 22 11:13:55 KST 2014
     */
    public String updateBySpec(Map<String, Object> parameter) {
        BEGIN();
        UPDATE("OP.T_FN_NOTEND_EMART_FRGN");
        
        SET("DEAL_DATE = #{record.dealDate,jdbcType=VARCHAR}");
        SET("ORG_CD = #{record.orgCd,jdbcType=VARCHAR}");
        SET("BRANCH_CD = #{record.branchCd,jdbcType=VARCHAR}");
        SET("MAC_NO = #{record.macNo,jdbcType=VARCHAR}");
        SET("DEAL_TIME = #{record.dealTime,jdbcType=VARCHAR}");
        SET("MEMBER_ID = #{record.memberId,jdbcType=VARCHAR}");
        SET("CLOSE_DATE = #{record.closeDate,jdbcType=VARCHAR}");
        SET("DOLLAR_AMT = #{record.dollarAmt,jdbcType=DECIMAL}");
        SET("DOLLAR_REMARK = #{record.dollarRemark,jdbcType=VARCHAR}");
        SET("EURO_AMT = #{record.euroAmt,jdbcType=DECIMAL}");
        SET("EURO_REMARK = #{record.euroRemark,jdbcType=VARCHAR}");
        SET("YEN_AMT = #{record.yenAmt,jdbcType=DECIMAL}");
        SET("YEN_REMARK = #{record.yenRemark,jdbcType=VARCHAR}");
        SET("YUAN_AMT = #{record.yuanAmt,jdbcType=DECIMAL}");
        SET("YUAN_REMARK = #{record.yuanRemark,jdbcType=VARCHAR}");
        SET("UPDATE_DATE = #{record.updateDate,jdbcType=TIMESTAMP}");
        SET("UPDATE_UID = #{record.updateUid,jdbcType=VARCHAR}");
        SET("ORG_SEND_YN = #{record.orgSendYn,jdbcType=VARCHAR}");
        
        TFnNotendEmartFrgnSpec spec = (TFnNotendEmartFrgnSpec) parameter.get("spec");
        applyWhere(spec, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_NOTEND_EMART_FRGN
     *
     * @mbggenerated Tue Jul 22 11:13:55 KST 2014
     */
    public String updateByPrimaryKeySelective(TFnNotendEmartFrgn record) {
        BEGIN();
        UPDATE("OP.T_FN_NOTEND_EMART_FRGN");
        
        if (record.getCloseDate() != null) {
            SET("CLOSE_DATE = #{closeDate,jdbcType=VARCHAR}");
        }
        
        if (record.getDollarAmt() != null) {
            SET("DOLLAR_AMT = #{dollarAmt,jdbcType=DECIMAL}");
        }
        
        if (record.getDollarRemark() != null) {
            SET("DOLLAR_REMARK = #{dollarRemark,jdbcType=VARCHAR}");
        }
        
        if (record.getEuroAmt() != null) {
            SET("EURO_AMT = #{euroAmt,jdbcType=DECIMAL}");
        }
        
        if (record.getEuroRemark() != null) {
            SET("EURO_REMARK = #{euroRemark,jdbcType=VARCHAR}");
        }
        
        if (record.getYenAmt() != null) {
            SET("YEN_AMT = #{yenAmt,jdbcType=DECIMAL}");
        }
        
        if (record.getYenRemark() != null) {
            SET("YEN_REMARK = #{yenRemark,jdbcType=VARCHAR}");
        }
        
        if (record.getYuanAmt() != null) {
            SET("YUAN_AMT = #{yuanAmt,jdbcType=DECIMAL}");
        }
        
        if (record.getYuanRemark() != null) {
            SET("YUAN_REMARK = #{yuanRemark,jdbcType=VARCHAR}");
        }
        
        if (record.getUpdateDate() != null) {
            SET("UPDATE_DATE = #{updateDate,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdateUid() != null) {
            SET("UPDATE_UID = #{updateUid,jdbcType=VARCHAR}");
        }
        
        if (record.getOrgSendYn() != null) {
            SET("ORG_SEND_YN = #{orgSendYn,jdbcType=VARCHAR}");
        }
        
        WHERE("DEAL_DATE = #{dealDate,jdbcType=VARCHAR}");
        WHERE("ORG_CD = #{orgCd,jdbcType=VARCHAR}");
        WHERE("BRANCH_CD = #{branchCd,jdbcType=VARCHAR}");
        WHERE("MAC_NO = #{macNo,jdbcType=VARCHAR}");
        WHERE("DEAL_TIME = #{dealTime,jdbcType=VARCHAR}");
        WHERE("MEMBER_ID = #{memberId,jdbcType=VARCHAR}");
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_NOTEND_EMART_FRGN
     *
     * @mbggenerated Tue Jul 22 11:13:55 KST 2014
     */
    protected void applyWhere(TFnNotendEmartFrgnSpec spec, boolean includeSpecPhrase) {
        if (spec == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeSpecPhrase) {
            parmPhrase1 = "%s #{spec.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{spec.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{spec.oredCriteria[%d].allCriteria[%d].value} and #{spec.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{spec.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{spec.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{spec.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{spec.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = spec.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            WHERE(sb.toString());
        }
    }
}