package com.nicetcm.nibsplus.broker.msg.mapper;

import com.nicetcm.nibsplus.broker.msg.model.TFnOperfundsInfo;
import com.nicetcm.nibsplus.broker.msg.model.TFnOperfundsInfoKey;
import com.nicetcm.nibsplus.broker.msg.model.TFnOperfundsInfoSpec;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface TFnOperfundsInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_OPERFUNDS_INFO
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    @SelectProvider(type=TFnOperfundsInfoSqlProvider.class, method="countBySpec")
    int countBySpec(TFnOperfundsInfoSpec spec);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_OPERFUNDS_INFO
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    @DeleteProvider(type=TFnOperfundsInfoSqlProvider.class, method="deleteBySpec")
    int deleteBySpec(TFnOperfundsInfoSpec spec);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_OPERFUNDS_INFO
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    @Delete({
        "delete from OP.T_FN_OPERFUNDS_INFO",
        "where REQ_DATE = #{reqDate,jdbcType=VARCHAR}",
          "and REQ_TYPE = #{reqType,jdbcType=VARCHAR}",
          "and ORG_CD = #{orgCd,jdbcType=VARCHAR}",
          "and BRANCH_CD = #{branchCd,jdbcType=VARCHAR}",
          "and SITE_CD = #{siteCd,jdbcType=VARCHAR}",
          "and MAC_NO = #{macNo,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(TFnOperfundsInfoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_OPERFUNDS_INFO
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    @Insert({
        "insert into OP.T_FN_OPERFUNDS_INFO (REQ_DATE, REQ_TYPE, ",
        "ORG_CD, BRANCH_CD, ",
        "SITE_CD, MAC_NO, MNG_BRANCH_CD, ",
        "BILL_TYPE1, BILL_TYPE1_AMT, ",
        "BILL_TYPE2, BILL_TYPE2_AMT, ",
        "BILL_TYPE3, BILL_TYPE3_AMT, ",
        "BILL_TYPE4, BILL_TYPE4_AMT, ",
        "BILL_TYPE5, BILL_TYPE5_AMT, ",
        "CAR_NO, MBR_NM, MBR_RESIDENT_NO, ",
        "MBR_PHOTO_URL, SIGN_URL, ",
        "CANCEL_YN, INSERT_DATE, ",
        "INSERT_UID, UPDATE_DATE, ",
        "UPDATE_UID, ORG_SEND_YN, ",
        "RESP_CD)",
        "values (#{reqDate,jdbcType=VARCHAR}, #{reqType,jdbcType=VARCHAR}, ",
        "#{orgCd,jdbcType=VARCHAR}, #{branchCd,jdbcType=VARCHAR}, ",
        "#{siteCd,jdbcType=VARCHAR}, #{macNo,jdbcType=VARCHAR}, #{mngBranchCd,jdbcType=VARCHAR}, ",
        "#{billType1,jdbcType=DECIMAL}, #{billType1Amt,jdbcType=DECIMAL}, ",
        "#{billType2,jdbcType=DECIMAL}, #{billType2Amt,jdbcType=DECIMAL}, ",
        "#{billType3,jdbcType=DECIMAL}, #{billType3Amt,jdbcType=DECIMAL}, ",
        "#{billType4,jdbcType=DECIMAL}, #{billType4Amt,jdbcType=DECIMAL}, ",
        "#{billType5,jdbcType=DECIMAL}, #{billType5Amt,jdbcType=DECIMAL}, ",
        "#{carNo,jdbcType=VARCHAR}, #{mbrNm,jdbcType=VARCHAR}, #{mbrResidentNo,jdbcType=DECIMAL}, ",
        "#{mbrPhotoUrl,jdbcType=VARCHAR}, #{signUrl,jdbcType=VARCHAR}, ",
        "#{cancelYn,jdbcType=VARCHAR}, #{insertDate,jdbcType=TIMESTAMP}, ",
        "#{insertUid,jdbcType=VARCHAR}, #{updateDate,jdbcType=TIMESTAMP}, ",
        "#{updateUid,jdbcType=VARCHAR}, #{orgSendYn,jdbcType=VARCHAR}, ",
        "#{respCd,jdbcType=VARCHAR})"
    })
    int insert(TFnOperfundsInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_OPERFUNDS_INFO
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    @InsertProvider(type=TFnOperfundsInfoSqlProvider.class, method="insertSelective")
    int insertSelective(TFnOperfundsInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_OPERFUNDS_INFO
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    @SelectProvider(type=TFnOperfundsInfoSqlProvider.class, method="selectBySpec")
    @Results({
        @Result(column="REQ_DATE", property="reqDate", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="REQ_TYPE", property="reqType", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="ORG_CD", property="orgCd", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="BRANCH_CD", property="branchCd", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="SITE_CD", property="siteCd", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="MAC_NO", property="macNo", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="MNG_BRANCH_CD", property="mngBranchCd", jdbcType=JdbcType.VARCHAR),
        @Result(column="BILL_TYPE1", property="billType1", jdbcType=JdbcType.DECIMAL),
        @Result(column="BILL_TYPE1_AMT", property="billType1Amt", jdbcType=JdbcType.DECIMAL),
        @Result(column="BILL_TYPE2", property="billType2", jdbcType=JdbcType.DECIMAL),
        @Result(column="BILL_TYPE2_AMT", property="billType2Amt", jdbcType=JdbcType.DECIMAL),
        @Result(column="BILL_TYPE3", property="billType3", jdbcType=JdbcType.DECIMAL),
        @Result(column="BILL_TYPE3_AMT", property="billType3Amt", jdbcType=JdbcType.DECIMAL),
        @Result(column="BILL_TYPE4", property="billType4", jdbcType=JdbcType.DECIMAL),
        @Result(column="BILL_TYPE4_AMT", property="billType4Amt", jdbcType=JdbcType.DECIMAL),
        @Result(column="BILL_TYPE5", property="billType5", jdbcType=JdbcType.DECIMAL),
        @Result(column="BILL_TYPE5_AMT", property="billType5Amt", jdbcType=JdbcType.DECIMAL),
        @Result(column="CAR_NO", property="carNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="MBR_NM", property="mbrNm", jdbcType=JdbcType.VARCHAR),
        @Result(column="MBR_RESIDENT_NO", property="mbrResidentNo", jdbcType=JdbcType.DECIMAL),
        @Result(column="MBR_PHOTO_URL", property="mbrPhotoUrl", jdbcType=JdbcType.VARCHAR),
        @Result(column="SIGN_URL", property="signUrl", jdbcType=JdbcType.VARCHAR),
        @Result(column="CANCEL_YN", property="cancelYn", jdbcType=JdbcType.VARCHAR),
        @Result(column="INSERT_DATE", property="insertDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="INSERT_UID", property="insertUid", jdbcType=JdbcType.VARCHAR),
        @Result(column="UPDATE_DATE", property="updateDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="UPDATE_UID", property="updateUid", jdbcType=JdbcType.VARCHAR),
        @Result(column="ORG_SEND_YN", property="orgSendYn", jdbcType=JdbcType.VARCHAR),
        @Result(column="RESP_CD", property="respCd", jdbcType=JdbcType.VARCHAR)
    })
    List<TFnOperfundsInfo> selectBySpec(TFnOperfundsInfoSpec spec);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_OPERFUNDS_INFO
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    @Select({
        "select",
        "REQ_DATE, REQ_TYPE, ORG_CD, BRANCH_CD, SITE_CD, MAC_NO, MNG_BRANCH_CD, BILL_TYPE1, ",
        "BILL_TYPE1_AMT, BILL_TYPE2, BILL_TYPE2_AMT, BILL_TYPE3, BILL_TYPE3_AMT, BILL_TYPE4, ",
        "BILL_TYPE4_AMT, BILL_TYPE5, BILL_TYPE5_AMT, CAR_NO, MBR_NM, MBR_RESIDENT_NO, ",
        "MBR_PHOTO_URL, SIGN_URL, CANCEL_YN, INSERT_DATE, INSERT_UID, UPDATE_DATE, UPDATE_UID, ",
        "ORG_SEND_YN, RESP_CD",
        "from OP.T_FN_OPERFUNDS_INFO",
        "where REQ_DATE = #{reqDate,jdbcType=VARCHAR}",
          "and REQ_TYPE = #{reqType,jdbcType=VARCHAR}",
          "and ORG_CD = #{orgCd,jdbcType=VARCHAR}",
          "and BRANCH_CD = #{branchCd,jdbcType=VARCHAR}",
          "and SITE_CD = #{siteCd,jdbcType=VARCHAR}",
          "and MAC_NO = #{macNo,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="REQ_DATE", property="reqDate", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="REQ_TYPE", property="reqType", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="ORG_CD", property="orgCd", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="BRANCH_CD", property="branchCd", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="SITE_CD", property="siteCd", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="MAC_NO", property="macNo", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="MNG_BRANCH_CD", property="mngBranchCd", jdbcType=JdbcType.VARCHAR),
        @Result(column="BILL_TYPE1", property="billType1", jdbcType=JdbcType.DECIMAL),
        @Result(column="BILL_TYPE1_AMT", property="billType1Amt", jdbcType=JdbcType.DECIMAL),
        @Result(column="BILL_TYPE2", property="billType2", jdbcType=JdbcType.DECIMAL),
        @Result(column="BILL_TYPE2_AMT", property="billType2Amt", jdbcType=JdbcType.DECIMAL),
        @Result(column="BILL_TYPE3", property="billType3", jdbcType=JdbcType.DECIMAL),
        @Result(column="BILL_TYPE3_AMT", property="billType3Amt", jdbcType=JdbcType.DECIMAL),
        @Result(column="BILL_TYPE4", property="billType4", jdbcType=JdbcType.DECIMAL),
        @Result(column="BILL_TYPE4_AMT", property="billType4Amt", jdbcType=JdbcType.DECIMAL),
        @Result(column="BILL_TYPE5", property="billType5", jdbcType=JdbcType.DECIMAL),
        @Result(column="BILL_TYPE5_AMT", property="billType5Amt", jdbcType=JdbcType.DECIMAL),
        @Result(column="CAR_NO", property="carNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="MBR_NM", property="mbrNm", jdbcType=JdbcType.VARCHAR),
        @Result(column="MBR_RESIDENT_NO", property="mbrResidentNo", jdbcType=JdbcType.DECIMAL),
        @Result(column="MBR_PHOTO_URL", property="mbrPhotoUrl", jdbcType=JdbcType.VARCHAR),
        @Result(column="SIGN_URL", property="signUrl", jdbcType=JdbcType.VARCHAR),
        @Result(column="CANCEL_YN", property="cancelYn", jdbcType=JdbcType.VARCHAR),
        @Result(column="INSERT_DATE", property="insertDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="INSERT_UID", property="insertUid", jdbcType=JdbcType.VARCHAR),
        @Result(column="UPDATE_DATE", property="updateDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="UPDATE_UID", property="updateUid", jdbcType=JdbcType.VARCHAR),
        @Result(column="ORG_SEND_YN", property="orgSendYn", jdbcType=JdbcType.VARCHAR),
        @Result(column="RESP_CD", property="respCd", jdbcType=JdbcType.VARCHAR)
    })
    TFnOperfundsInfo selectByPrimaryKey(TFnOperfundsInfoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_OPERFUNDS_INFO
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    @UpdateProvider(type=TFnOperfundsInfoSqlProvider.class, method="updateBySpecSelective")
    int updateBySpecSelective(@Param("record") TFnOperfundsInfo record, @Param("spec") TFnOperfundsInfoSpec spec);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_OPERFUNDS_INFO
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    @UpdateProvider(type=TFnOperfundsInfoSqlProvider.class, method="updateBySpec")
    int updateBySpec(@Param("record") TFnOperfundsInfo record, @Param("spec") TFnOperfundsInfoSpec spec);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_OPERFUNDS_INFO
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    @UpdateProvider(type=TFnOperfundsInfoSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(TFnOperfundsInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_OPERFUNDS_INFO
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    @Update({
        "update OP.T_FN_OPERFUNDS_INFO",
        "set MNG_BRANCH_CD = #{mngBranchCd,jdbcType=VARCHAR},",
          "BILL_TYPE1 = #{billType1,jdbcType=DECIMAL},",
          "BILL_TYPE1_AMT = #{billType1Amt,jdbcType=DECIMAL},",
          "BILL_TYPE2 = #{billType2,jdbcType=DECIMAL},",
          "BILL_TYPE2_AMT = #{billType2Amt,jdbcType=DECIMAL},",
          "BILL_TYPE3 = #{billType3,jdbcType=DECIMAL},",
          "BILL_TYPE3_AMT = #{billType3Amt,jdbcType=DECIMAL},",
          "BILL_TYPE4 = #{billType4,jdbcType=DECIMAL},",
          "BILL_TYPE4_AMT = #{billType4Amt,jdbcType=DECIMAL},",
          "BILL_TYPE5 = #{billType5,jdbcType=DECIMAL},",
          "BILL_TYPE5_AMT = #{billType5Amt,jdbcType=DECIMAL},",
          "CAR_NO = #{carNo,jdbcType=VARCHAR},",
          "MBR_NM = #{mbrNm,jdbcType=VARCHAR},",
          "MBR_RESIDENT_NO = #{mbrResidentNo,jdbcType=DECIMAL},",
          "MBR_PHOTO_URL = #{mbrPhotoUrl,jdbcType=VARCHAR},",
          "SIGN_URL = #{signUrl,jdbcType=VARCHAR},",
          "CANCEL_YN = #{cancelYn,jdbcType=VARCHAR},",
          "INSERT_DATE = #{insertDate,jdbcType=TIMESTAMP},",
          "INSERT_UID = #{insertUid,jdbcType=VARCHAR},",
          "UPDATE_DATE = #{updateDate,jdbcType=TIMESTAMP},",
          "UPDATE_UID = #{updateUid,jdbcType=VARCHAR},",
          "ORG_SEND_YN = #{orgSendYn,jdbcType=VARCHAR},",
          "RESP_CD = #{respCd,jdbcType=VARCHAR}",
        "where REQ_DATE = #{reqDate,jdbcType=VARCHAR}",
          "and REQ_TYPE = #{reqType,jdbcType=VARCHAR}",
          "and ORG_CD = #{orgCd,jdbcType=VARCHAR}",
          "and BRANCH_CD = #{branchCd,jdbcType=VARCHAR}",
          "and SITE_CD = #{siteCd,jdbcType=VARCHAR}",
          "and MAC_NO = #{macNo,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(TFnOperfundsInfo record);
}