package com.nicetcm.nibsplus.broker.msg.mapper;

import com.nicetcm.nibsplus.broker.msg.model.TFnSapDetail;
import com.nicetcm.nibsplus.broker.msg.model.TFnSapDetailKey;
import com.nicetcm.nibsplus.broker.msg.model.TFnSapDetailSpec;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface TFnSapDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_SAP_DETAIL
     *
     * @mbggenerated Thu Aug 14 16:45:51 KST 2014
     */
    @SelectProvider(type=TFnSapDetailSqlProvider.class, method="countBySpec")
    int countBySpec(TFnSapDetailSpec spec);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_SAP_DETAIL
     *
     * @mbggenerated Thu Aug 14 16:45:51 KST 2014
     */
    @DeleteProvider(type=TFnSapDetailSqlProvider.class, method="deleteBySpec")
    int deleteBySpec(TFnSapDetailSpec spec);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_SAP_DETAIL
     *
     * @mbggenerated Thu Aug 14 16:45:51 KST 2014
     */
    @Delete({
        "delete from OP.T_FN_SAP_DETAIL",
        "where DEAL_DATE = #{dealDate,jdbcType=VARCHAR}",
          "and BRANCH_CD = #{branchCd,jdbcType=VARCHAR}",
          "and MEMBER_ID = #{memberId,jdbcType=VARCHAR}",
          "and CUPON_CD = #{cuponCd,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(TFnSapDetailKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_SAP_DETAIL
     *
     * @mbggenerated Thu Aug 14 16:45:51 KST 2014
     */
    @Insert({
        "insert into OP.T_FN_SAP_DETAIL (DEAL_DATE, BRANCH_CD, ",
        "MEMBER_ID, CUPON_CD, ",
        "CUPON_NM, CUPON_TYPE, ",
        "CUPON_AMT, UPDATE_UID, ",
        "UPDATE_DATE, ORG_SEND_YN)",
        "values (#{dealDate,jdbcType=VARCHAR}, #{branchCd,jdbcType=VARCHAR}, ",
        "#{memberId,jdbcType=VARCHAR}, #{cuponCd,jdbcType=VARCHAR}, ",
        "#{cuponNm,jdbcType=VARCHAR}, #{cuponType,jdbcType=VARCHAR}, ",
        "#{cuponAmt,jdbcType=OTHER}, #{updateUid,jdbcType=VARCHAR}, ",
        "#{updateDate,jdbcType=TIMESTAMP}, #{orgSendYn,jdbcType=VARCHAR})"
    })
    int insert(TFnSapDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_SAP_DETAIL
     *
     * @mbggenerated Thu Aug 14 16:45:51 KST 2014
     */
    @InsertProvider(type=TFnSapDetailSqlProvider.class, method="insertSelective")
    int insertSelective(TFnSapDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_SAP_DETAIL
     *
     * @mbggenerated Thu Aug 14 16:45:51 KST 2014
     */
    @SelectProvider(type=TFnSapDetailSqlProvider.class, method="selectBySpec")
    @Results({
        @Result(column="DEAL_DATE", property="dealDate", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="BRANCH_CD", property="branchCd", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="MEMBER_ID", property="memberId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="CUPON_CD", property="cuponCd", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="CUPON_NM", property="cuponNm", jdbcType=JdbcType.VARCHAR),
        @Result(column="CUPON_TYPE", property="cuponType", jdbcType=JdbcType.VARCHAR),
        @Result(column="CUPON_AMT", property="cuponAmt", jdbcType=JdbcType.OTHER),
        @Result(column="UPDATE_UID", property="updateUid", jdbcType=JdbcType.VARCHAR),
        @Result(column="UPDATE_DATE", property="updateDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="ORG_SEND_YN", property="orgSendYn", jdbcType=JdbcType.VARCHAR)
    })
    List<TFnSapDetail> selectBySpec(TFnSapDetailSpec spec);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_SAP_DETAIL
     *
     * @mbggenerated Thu Aug 14 16:45:51 KST 2014
     */
    @Select({
        "select",
        "DEAL_DATE, BRANCH_CD, MEMBER_ID, CUPON_CD, CUPON_NM, CUPON_TYPE, CUPON_AMT, ",
        "UPDATE_UID, UPDATE_DATE, ORG_SEND_YN",
        "from OP.T_FN_SAP_DETAIL",
        "where DEAL_DATE = #{dealDate,jdbcType=VARCHAR}",
          "and BRANCH_CD = #{branchCd,jdbcType=VARCHAR}",
          "and MEMBER_ID = #{memberId,jdbcType=VARCHAR}",
          "and CUPON_CD = #{cuponCd,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="DEAL_DATE", property="dealDate", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="BRANCH_CD", property="branchCd", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="MEMBER_ID", property="memberId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="CUPON_CD", property="cuponCd", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="CUPON_NM", property="cuponNm", jdbcType=JdbcType.VARCHAR),
        @Result(column="CUPON_TYPE", property="cuponType", jdbcType=JdbcType.VARCHAR),
        @Result(column="CUPON_AMT", property="cuponAmt", jdbcType=JdbcType.OTHER),
        @Result(column="UPDATE_UID", property="updateUid", jdbcType=JdbcType.VARCHAR),
        @Result(column="UPDATE_DATE", property="updateDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="ORG_SEND_YN", property="orgSendYn", jdbcType=JdbcType.VARCHAR)
    })
    TFnSapDetail selectByPrimaryKey(TFnSapDetailKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_SAP_DETAIL
     *
     * @mbggenerated Thu Aug 14 16:45:51 KST 2014
     */
    @UpdateProvider(type=TFnSapDetailSqlProvider.class, method="updateBySpecSelective")
    int updateBySpecSelective(@Param("record") TFnSapDetail record, @Param("spec") TFnSapDetailSpec spec);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_SAP_DETAIL
     *
     * @mbggenerated Thu Aug 14 16:45:51 KST 2014
     */
    @UpdateProvider(type=TFnSapDetailSqlProvider.class, method="updateBySpec")
    int updateBySpec(@Param("record") TFnSapDetail record, @Param("spec") TFnSapDetailSpec spec);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_SAP_DETAIL
     *
     * @mbggenerated Thu Aug 14 16:45:51 KST 2014
     */
    @UpdateProvider(type=TFnSapDetailSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(TFnSapDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_SAP_DETAIL
     *
     * @mbggenerated Thu Aug 14 16:45:51 KST 2014
     */
    @Update({
        "update OP.T_FN_SAP_DETAIL",
        "set CUPON_NM = #{cuponNm,jdbcType=VARCHAR},",
          "CUPON_TYPE = #{cuponType,jdbcType=VARCHAR},",
          "CUPON_AMT = #{cuponAmt,jdbcType=OTHER},",
          "UPDATE_UID = #{updateUid,jdbcType=VARCHAR},",
          "UPDATE_DATE = #{updateDate,jdbcType=TIMESTAMP},",
          "ORG_SEND_YN = #{orgSendYn,jdbcType=VARCHAR}",
        "where DEAL_DATE = #{dealDate,jdbcType=VARCHAR}",
          "and BRANCH_CD = #{branchCd,jdbcType=VARCHAR}",
          "and MEMBER_ID = #{memberId,jdbcType=VARCHAR}",
          "and CUPON_CD = #{cuponCd,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(TFnSapDetail record);
}