package com.nicetcm.nibsplus.broker.msg.mapper;

import com.nicetcm.nibsplus.broker.msg.model.TCmGoodsApply;
import com.nicetcm.nibsplus.broker.msg.model.TCmGoodsApplyKey;
import com.nicetcm.nibsplus.broker.msg.model.TCmGoodsApplySpec;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface TCmGoodsApplyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_CM_GOODS_APPLY
     *
     * @mbggenerated Thu Jul 31 14:31:01 KST 2014
     */
    @SelectProvider(type=TCmGoodsApplySqlProvider.class, method="countBySpec")
    int countBySpec(TCmGoodsApplySpec spec);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_CM_GOODS_APPLY
     *
     * @mbggenerated Thu Jul 31 14:31:01 KST 2014
     */
    @DeleteProvider(type=TCmGoodsApplySqlProvider.class, method="deleteBySpec")
    int deleteBySpec(TCmGoodsApplySpec spec);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_CM_GOODS_APPLY
     *
     * @mbggenerated Thu Jul 31 14:31:01 KST 2014
     */
    @Delete({
        "delete from OP.T_CM_GOODS_APPLY",
        "where APPLY_DATE = #{applyDate,jdbcType=VARCHAR}",
          "and ORG_CD = #{orgCd,jdbcType=VARCHAR}",
          "and BRANCH_CD = #{branchCd,jdbcType=VARCHAR}",
          "and GOOD_CD = #{goodCd,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(TCmGoodsApplyKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_CM_GOODS_APPLY
     *
     * @mbggenerated Thu Jul 31 14:31:01 KST 2014
     */
    @Insert({
        "insert into OP.T_CM_GOODS_APPLY (APPLY_DATE, ORG_CD, ",
        "BRANCH_CD, GOOD_CD, ",
        "GOOD_AMT, ORG_SEND_YN, ",
        "UPDATE_UID, UPDATE_DATE)",
        "values (#{applyDate,jdbcType=VARCHAR}, #{orgCd,jdbcType=VARCHAR}, ",
        "#{branchCd,jdbcType=VARCHAR}, #{goodCd,jdbcType=VARCHAR}, ",
        "#{goodAmt,jdbcType=VARCHAR}, #{orgSendYn,jdbcType=VARCHAR}, ",
        "#{updateUid,jdbcType=VARCHAR}, #{updateDate,jdbcType=TIMESTAMP})"
    })
    int insert(TCmGoodsApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_CM_GOODS_APPLY
     *
     * @mbggenerated Thu Jul 31 14:31:01 KST 2014
     */
    @InsertProvider(type=TCmGoodsApplySqlProvider.class, method="insertSelective")
    int insertSelective(TCmGoodsApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_CM_GOODS_APPLY
     *
     * @mbggenerated Thu Jul 31 14:31:01 KST 2014
     */
    @SelectProvider(type=TCmGoodsApplySqlProvider.class, method="selectBySpec")
    @Results({
        @Result(column="APPLY_DATE", property="applyDate", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="ORG_CD", property="orgCd", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="BRANCH_CD", property="branchCd", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="GOOD_CD", property="goodCd", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="GOOD_AMT", property="goodAmt", jdbcType=JdbcType.VARCHAR),
        @Result(column="ORG_SEND_YN", property="orgSendYn", jdbcType=JdbcType.VARCHAR),
        @Result(column="UPDATE_UID", property="updateUid", jdbcType=JdbcType.VARCHAR),
        @Result(column="UPDATE_DATE", property="updateDate", jdbcType=JdbcType.TIMESTAMP)
    })
    List<TCmGoodsApply> selectBySpec(TCmGoodsApplySpec spec);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_CM_GOODS_APPLY
     *
     * @mbggenerated Thu Jul 31 14:31:01 KST 2014
     */
    @Select({
        "select",
        "APPLY_DATE, ORG_CD, BRANCH_CD, GOOD_CD, GOOD_AMT, ORG_SEND_YN, UPDATE_UID, UPDATE_DATE",
        "from OP.T_CM_GOODS_APPLY",
        "where APPLY_DATE = #{applyDate,jdbcType=VARCHAR}",
          "and ORG_CD = #{orgCd,jdbcType=VARCHAR}",
          "and BRANCH_CD = #{branchCd,jdbcType=VARCHAR}",
          "and GOOD_CD = #{goodCd,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="APPLY_DATE", property="applyDate", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="ORG_CD", property="orgCd", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="BRANCH_CD", property="branchCd", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="GOOD_CD", property="goodCd", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="GOOD_AMT", property="goodAmt", jdbcType=JdbcType.VARCHAR),
        @Result(column="ORG_SEND_YN", property="orgSendYn", jdbcType=JdbcType.VARCHAR),
        @Result(column="UPDATE_UID", property="updateUid", jdbcType=JdbcType.VARCHAR),
        @Result(column="UPDATE_DATE", property="updateDate", jdbcType=JdbcType.TIMESTAMP)
    })
    TCmGoodsApply selectByPrimaryKey(TCmGoodsApplyKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_CM_GOODS_APPLY
     *
     * @mbggenerated Thu Jul 31 14:31:01 KST 2014
     */
    @UpdateProvider(type=TCmGoodsApplySqlProvider.class, method="updateBySpecSelective")
    int updateBySpecSelective(@Param("record") TCmGoodsApply record, @Param("spec") TCmGoodsApplySpec spec);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_CM_GOODS_APPLY
     *
     * @mbggenerated Thu Jul 31 14:31:01 KST 2014
     */
    @UpdateProvider(type=TCmGoodsApplySqlProvider.class, method="updateBySpec")
    int updateBySpec(@Param("record") TCmGoodsApply record, @Param("spec") TCmGoodsApplySpec spec);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_CM_GOODS_APPLY
     *
     * @mbggenerated Thu Jul 31 14:31:01 KST 2014
     */
    @UpdateProvider(type=TCmGoodsApplySqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(TCmGoodsApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_CM_GOODS_APPLY
     *
     * @mbggenerated Thu Jul 31 14:31:01 KST 2014
     */
    @Update({
        "update OP.T_CM_GOODS_APPLY",
        "set GOOD_AMT = #{goodAmt,jdbcType=VARCHAR},",
          "ORG_SEND_YN = #{orgSendYn,jdbcType=VARCHAR},",
          "UPDATE_UID = #{updateUid,jdbcType=VARCHAR},",
          "UPDATE_DATE = #{updateDate,jdbcType=TIMESTAMP}",
        "where APPLY_DATE = #{applyDate,jdbcType=VARCHAR}",
          "and ORG_CD = #{orgCd,jdbcType=VARCHAR}",
          "and BRANCH_CD = #{branchCd,jdbcType=VARCHAR}",
          "and GOOD_CD = #{goodCd,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(TCmGoodsApply record);
}