package com.nicetcm.nibsplus.broker.msg.mapper;

import com.nicetcm.nibsplus.broker.msg.model.TCmChangeSiteInfo;
import com.nicetcm.nibsplus.broker.msg.model.TCmChangeSiteInfoKey;
import com.nicetcm.nibsplus.broker.msg.model.TCmChangeSiteInfoSpec;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface TCmChangeSiteInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_CM_CHANGE_SITE_INFO
     *
     * @mbggenerated Wed Aug 06 09:58:31 KST 2014
     */
    @SelectProvider(type=TCmChangeSiteInfoSqlProvider.class, method="countBySpec")
    int countBySpec(TCmChangeSiteInfoSpec spec);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_CM_CHANGE_SITE_INFO
     *
     * @mbggenerated Wed Aug 06 09:58:31 KST 2014
     */
    @DeleteProvider(type=TCmChangeSiteInfoSqlProvider.class, method="deleteBySpec")
    int deleteBySpec(TCmChangeSiteInfoSpec spec);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_CM_CHANGE_SITE_INFO
     *
     * @mbggenerated Wed Aug 06 09:58:31 KST 2014
     */
    @Delete({
        "delete from OP.T_CM_CHANGE_SITE_INFO",
        "where ORG_CD = #{orgCd,jdbcType=VARCHAR}",
          "and ORG_BRANCH_CD = #{orgBranchCd,jdbcType=VARCHAR}",
          "and ORG_SITE_CD = #{orgSiteCd,jdbcType=VARCHAR}",
          "and RECV_DATE = #{recvDate,jdbcType=VARCHAR}",
          "and RECV_TIME = #{recvTime,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(TCmChangeSiteInfoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_CM_CHANGE_SITE_INFO
     *
     * @mbggenerated Wed Aug 06 09:58:31 KST 2014
     */
    @Insert({
        "insert into OP.T_CM_CHANGE_SITE_INFO (ORG_CD, ORG_BRANCH_CD, ",
        "ORG_SITE_CD, RECV_DATE, ",
        "RECV_TIME, ORG_BRANCH_NM, ",
        "ORG_SITE_NM, PLACE_TYPE, ",
        "JP_TYPE, OPER_TIME_TYPE, ",
        "OPER_START_TIME, OPER_END_TIME, ",
        "OPER_DAY, OPER_CHECK_YN, ",
        "GUARD_NM, SET_ADDR, ",
        "SET_PLACE, WORK_RESULT, ",
        "UPDATE_DATE, UPDATE_UID, ",
        "DATA_TYPE, OPER_START_TIME_H, ",
        "OPER_END_TIME_H, OUT_START_TIME, ",
        "OUT_END_TIME, OUT_START_TIME_H, ",
        "OUT_END_TIME_H, OUT_COM_CD, ",
        "CLEAN_COM_CD, SET_DATE)",
        "values (#{orgCd,jdbcType=VARCHAR}, #{orgBranchCd,jdbcType=VARCHAR}, ",
        "#{orgSiteCd,jdbcType=VARCHAR}, #{recvDate,jdbcType=VARCHAR}, ",
        "#{recvTime,jdbcType=VARCHAR}, #{orgBranchNm,jdbcType=VARCHAR}, ",
        "#{orgSiteNm,jdbcType=VARCHAR}, #{placeType,jdbcType=VARCHAR}, ",
        "#{jpType,jdbcType=VARCHAR}, #{operTimeType,jdbcType=VARCHAR}, ",
        "#{operStartTime,jdbcType=VARCHAR}, #{operEndTime,jdbcType=VARCHAR}, ",
        "#{operDay,jdbcType=VARCHAR}, #{operCheckYn,jdbcType=VARCHAR}, ",
        "#{guardNm,jdbcType=VARCHAR}, #{setAddr,jdbcType=VARCHAR}, ",
        "#{setPlace,jdbcType=VARCHAR}, #{workResult,jdbcType=VARCHAR}, ",
        "#{updateDate,jdbcType=TIMESTAMP}, #{updateUid,jdbcType=VARCHAR}, ",
        "#{dataType,jdbcType=VARCHAR}, #{operStartTimeH,jdbcType=VARCHAR}, ",
        "#{operEndTimeH,jdbcType=VARCHAR}, #{outStartTime,jdbcType=VARCHAR}, ",
        "#{outEndTime,jdbcType=VARCHAR}, #{outStartTimeH,jdbcType=VARCHAR}, ",
        "#{outEndTimeH,jdbcType=VARCHAR}, #{outComCd,jdbcType=VARCHAR}, ",
        "#{cleanComCd,jdbcType=VARCHAR}, #{setDate,jdbcType=VARCHAR})"
    })
    int insert(TCmChangeSiteInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_CM_CHANGE_SITE_INFO
     *
     * @mbggenerated Wed Aug 06 09:58:31 KST 2014
     */
    @InsertProvider(type=TCmChangeSiteInfoSqlProvider.class, method="insertSelective")
    int insertSelective(TCmChangeSiteInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_CM_CHANGE_SITE_INFO
     *
     * @mbggenerated Wed Aug 06 09:58:31 KST 2014
     */
    @SelectProvider(type=TCmChangeSiteInfoSqlProvider.class, method="selectBySpec")
    @Results({
        @Result(column="ORG_CD", property="orgCd", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="ORG_BRANCH_CD", property="orgBranchCd", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="ORG_SITE_CD", property="orgSiteCd", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="RECV_DATE", property="recvDate", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="RECV_TIME", property="recvTime", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="ORG_BRANCH_NM", property="orgBranchNm", jdbcType=JdbcType.VARCHAR),
        @Result(column="ORG_SITE_NM", property="orgSiteNm", jdbcType=JdbcType.VARCHAR),
        @Result(column="PLACE_TYPE", property="placeType", jdbcType=JdbcType.VARCHAR),
        @Result(column="JP_TYPE", property="jpType", jdbcType=JdbcType.VARCHAR),
        @Result(column="OPER_TIME_TYPE", property="operTimeType", jdbcType=JdbcType.VARCHAR),
        @Result(column="OPER_START_TIME", property="operStartTime", jdbcType=JdbcType.VARCHAR),
        @Result(column="OPER_END_TIME", property="operEndTime", jdbcType=JdbcType.VARCHAR),
        @Result(column="OPER_DAY", property="operDay", jdbcType=JdbcType.VARCHAR),
        @Result(column="OPER_CHECK_YN", property="operCheckYn", jdbcType=JdbcType.VARCHAR),
        @Result(column="GUARD_NM", property="guardNm", jdbcType=JdbcType.VARCHAR),
        @Result(column="SET_ADDR", property="setAddr", jdbcType=JdbcType.VARCHAR),
        @Result(column="SET_PLACE", property="setPlace", jdbcType=JdbcType.VARCHAR),
        @Result(column="WORK_RESULT", property="workResult", jdbcType=JdbcType.VARCHAR),
        @Result(column="UPDATE_DATE", property="updateDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="UPDATE_UID", property="updateUid", jdbcType=JdbcType.VARCHAR),
        @Result(column="DATA_TYPE", property="dataType", jdbcType=JdbcType.VARCHAR),
        @Result(column="OPER_START_TIME_H", property="operStartTimeH", jdbcType=JdbcType.VARCHAR),
        @Result(column="OPER_END_TIME_H", property="operEndTimeH", jdbcType=JdbcType.VARCHAR),
        @Result(column="OUT_START_TIME", property="outStartTime", jdbcType=JdbcType.VARCHAR),
        @Result(column="OUT_END_TIME", property="outEndTime", jdbcType=JdbcType.VARCHAR),
        @Result(column="OUT_START_TIME_H", property="outStartTimeH", jdbcType=JdbcType.VARCHAR),
        @Result(column="OUT_END_TIME_H", property="outEndTimeH", jdbcType=JdbcType.VARCHAR),
        @Result(column="OUT_COM_CD", property="outComCd", jdbcType=JdbcType.VARCHAR),
        @Result(column="CLEAN_COM_CD", property="cleanComCd", jdbcType=JdbcType.VARCHAR),
        @Result(column="SET_DATE", property="setDate", jdbcType=JdbcType.VARCHAR)
    })
    List<TCmChangeSiteInfo> selectBySpec(TCmChangeSiteInfoSpec spec);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_CM_CHANGE_SITE_INFO
     *
     * @mbggenerated Wed Aug 06 09:58:31 KST 2014
     */
    @Select({
        "select",
        "ORG_CD, ORG_BRANCH_CD, ORG_SITE_CD, RECV_DATE, RECV_TIME, ORG_BRANCH_NM, ORG_SITE_NM, ",
        "PLACE_TYPE, JP_TYPE, OPER_TIME_TYPE, OPER_START_TIME, OPER_END_TIME, OPER_DAY, ",
        "OPER_CHECK_YN, GUARD_NM, SET_ADDR, SET_PLACE, WORK_RESULT, UPDATE_DATE, UPDATE_UID, ",
        "DATA_TYPE, OPER_START_TIME_H, OPER_END_TIME_H, OUT_START_TIME, OUT_END_TIME, ",
        "OUT_START_TIME_H, OUT_END_TIME_H, OUT_COM_CD, CLEAN_COM_CD, SET_DATE",
        "from OP.T_CM_CHANGE_SITE_INFO",
        "where ORG_CD = #{orgCd,jdbcType=VARCHAR}",
          "and ORG_BRANCH_CD = #{orgBranchCd,jdbcType=VARCHAR}",
          "and ORG_SITE_CD = #{orgSiteCd,jdbcType=VARCHAR}",
          "and RECV_DATE = #{recvDate,jdbcType=VARCHAR}",
          "and RECV_TIME = #{recvTime,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="ORG_CD", property="orgCd", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="ORG_BRANCH_CD", property="orgBranchCd", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="ORG_SITE_CD", property="orgSiteCd", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="RECV_DATE", property="recvDate", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="RECV_TIME", property="recvTime", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="ORG_BRANCH_NM", property="orgBranchNm", jdbcType=JdbcType.VARCHAR),
        @Result(column="ORG_SITE_NM", property="orgSiteNm", jdbcType=JdbcType.VARCHAR),
        @Result(column="PLACE_TYPE", property="placeType", jdbcType=JdbcType.VARCHAR),
        @Result(column="JP_TYPE", property="jpType", jdbcType=JdbcType.VARCHAR),
        @Result(column="OPER_TIME_TYPE", property="operTimeType", jdbcType=JdbcType.VARCHAR),
        @Result(column="OPER_START_TIME", property="operStartTime", jdbcType=JdbcType.VARCHAR),
        @Result(column="OPER_END_TIME", property="operEndTime", jdbcType=JdbcType.VARCHAR),
        @Result(column="OPER_DAY", property="operDay", jdbcType=JdbcType.VARCHAR),
        @Result(column="OPER_CHECK_YN", property="operCheckYn", jdbcType=JdbcType.VARCHAR),
        @Result(column="GUARD_NM", property="guardNm", jdbcType=JdbcType.VARCHAR),
        @Result(column="SET_ADDR", property="setAddr", jdbcType=JdbcType.VARCHAR),
        @Result(column="SET_PLACE", property="setPlace", jdbcType=JdbcType.VARCHAR),
        @Result(column="WORK_RESULT", property="workResult", jdbcType=JdbcType.VARCHAR),
        @Result(column="UPDATE_DATE", property="updateDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="UPDATE_UID", property="updateUid", jdbcType=JdbcType.VARCHAR),
        @Result(column="DATA_TYPE", property="dataType", jdbcType=JdbcType.VARCHAR),
        @Result(column="OPER_START_TIME_H", property="operStartTimeH", jdbcType=JdbcType.VARCHAR),
        @Result(column="OPER_END_TIME_H", property="operEndTimeH", jdbcType=JdbcType.VARCHAR),
        @Result(column="OUT_START_TIME", property="outStartTime", jdbcType=JdbcType.VARCHAR),
        @Result(column="OUT_END_TIME", property="outEndTime", jdbcType=JdbcType.VARCHAR),
        @Result(column="OUT_START_TIME_H", property="outStartTimeH", jdbcType=JdbcType.VARCHAR),
        @Result(column="OUT_END_TIME_H", property="outEndTimeH", jdbcType=JdbcType.VARCHAR),
        @Result(column="OUT_COM_CD", property="outComCd", jdbcType=JdbcType.VARCHAR),
        @Result(column="CLEAN_COM_CD", property="cleanComCd", jdbcType=JdbcType.VARCHAR),
        @Result(column="SET_DATE", property="setDate", jdbcType=JdbcType.VARCHAR)
    })
    TCmChangeSiteInfo selectByPrimaryKey(TCmChangeSiteInfoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_CM_CHANGE_SITE_INFO
     *
     * @mbggenerated Wed Aug 06 09:58:31 KST 2014
     */
    @UpdateProvider(type=TCmChangeSiteInfoSqlProvider.class, method="updateBySpecSelective")
    int updateBySpecSelective(@Param("record") TCmChangeSiteInfo record, @Param("spec") TCmChangeSiteInfoSpec spec);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_CM_CHANGE_SITE_INFO
     *
     * @mbggenerated Wed Aug 06 09:58:31 KST 2014
     */
    @UpdateProvider(type=TCmChangeSiteInfoSqlProvider.class, method="updateBySpec")
    int updateBySpec(@Param("record") TCmChangeSiteInfo record, @Param("spec") TCmChangeSiteInfoSpec spec);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_CM_CHANGE_SITE_INFO
     *
     * @mbggenerated Wed Aug 06 09:58:31 KST 2014
     */
    @UpdateProvider(type=TCmChangeSiteInfoSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(TCmChangeSiteInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_CM_CHANGE_SITE_INFO
     *
     * @mbggenerated Wed Aug 06 09:58:31 KST 2014
     */
    @Update({
        "update OP.T_CM_CHANGE_SITE_INFO",
        "set ORG_BRANCH_NM = #{orgBranchNm,jdbcType=VARCHAR},",
          "ORG_SITE_NM = #{orgSiteNm,jdbcType=VARCHAR},",
          "PLACE_TYPE = #{placeType,jdbcType=VARCHAR},",
          "JP_TYPE = #{jpType,jdbcType=VARCHAR},",
          "OPER_TIME_TYPE = #{operTimeType,jdbcType=VARCHAR},",
          "OPER_START_TIME = #{operStartTime,jdbcType=VARCHAR},",
          "OPER_END_TIME = #{operEndTime,jdbcType=VARCHAR},",
          "OPER_DAY = #{operDay,jdbcType=VARCHAR},",
          "OPER_CHECK_YN = #{operCheckYn,jdbcType=VARCHAR},",
          "GUARD_NM = #{guardNm,jdbcType=VARCHAR},",
          "SET_ADDR = #{setAddr,jdbcType=VARCHAR},",
          "SET_PLACE = #{setPlace,jdbcType=VARCHAR},",
          "WORK_RESULT = #{workResult,jdbcType=VARCHAR},",
          "UPDATE_DATE = #{updateDate,jdbcType=TIMESTAMP},",
          "UPDATE_UID = #{updateUid,jdbcType=VARCHAR},",
          "DATA_TYPE = #{dataType,jdbcType=VARCHAR},",
          "OPER_START_TIME_H = #{operStartTimeH,jdbcType=VARCHAR},",
          "OPER_END_TIME_H = #{operEndTimeH,jdbcType=VARCHAR},",
          "OUT_START_TIME = #{outStartTime,jdbcType=VARCHAR},",
          "OUT_END_TIME = #{outEndTime,jdbcType=VARCHAR},",
          "OUT_START_TIME_H = #{outStartTimeH,jdbcType=VARCHAR},",
          "OUT_END_TIME_H = #{outEndTimeH,jdbcType=VARCHAR},",
          "OUT_COM_CD = #{outComCd,jdbcType=VARCHAR},",
          "CLEAN_COM_CD = #{cleanComCd,jdbcType=VARCHAR},",
          "SET_DATE = #{setDate,jdbcType=VARCHAR}",
        "where ORG_CD = #{orgCd,jdbcType=VARCHAR}",
          "and ORG_BRANCH_CD = #{orgBranchCd,jdbcType=VARCHAR}",
          "and ORG_SITE_CD = #{orgSiteCd,jdbcType=VARCHAR}",
          "and RECV_DATE = #{recvDate,jdbcType=VARCHAR}",
          "and RECV_TIME = #{recvTime,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(TCmChangeSiteInfo record);
}