package com.nicetcm.nibsplus.broker.ams.model;

import java.util.Date;

public class TRmMsgHis extends TRmMsgHisKey {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column IN.T_RM_MSG_HIS.CREATE_TIME
     * @mbggenerated  Mon Aug 18 10:55:09 KST 2014
     */
    private String createTime;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column IN.T_RM_MSG_HIS.INSERT_UID
     * @mbggenerated  Mon Aug 18 10:55:09 KST 2014
     */
    private String insertUid;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column IN.T_RM_MSG_HIS.INSERT_DATE
     * @mbggenerated  Mon Aug 18 10:55:09 KST 2014
     */
    private Date insertDate;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column IN.T_RM_MSG_HIS.MAC_NO
     * @mbggenerated  Mon Aug 18 10:55:09 KST 2014
     */
    private String macNo;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column IN.T_RM_MSG_HIS.MAC_MSG_SEQ
     * @mbggenerated  Mon Aug 18 10:55:09 KST 2014
     */
    private String macMsgSeq;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column IN.T_RM_MSG_HIS.MSG_STS
     * @mbggenerated  Mon Aug 18 10:55:09 KST 2014
     */
    private String msgSts;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column IN.T_RM_MSG_HIS.MSG_TYPE
     * @mbggenerated  Mon Aug 18 10:55:09 KST 2014
     */
    private String msgType;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column IN.T_RM_MSG_HIS.MSG_CD
     * @mbggenerated  Mon Aug 18 10:55:09 KST 2014
     */
    private String msgCd;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column IN.T_RM_MSG_HIS.SVC_CD
     * @mbggenerated  Mon Aug 18 10:55:09 KST 2014
     */
    private String svcCd;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column IN.T_RM_MSG_HIS.MAC_SER_NO
     * @mbggenerated  Mon Aug 18 10:55:09 KST 2014
     */
    private String macSerNo;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column IN.T_RM_MSG_HIS.BRANCH_CD
     * @mbggenerated  Mon Aug 18 10:55:09 KST 2014
     */
    private String branchCd;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column IN.T_RM_MSG_HIS.ORG_CD
     * @mbggenerated  Mon Aug 18 10:55:09 KST 2014
     */
    private String orgCd;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column IN.T_RM_MSG_HIS.MSG_CTX
     * @mbggenerated  Mon Aug 18 10:55:09 KST 2014
     */
    private String msgCtx;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column IN.T_RM_MSG_HIS.CREATE_TIME
     * @return  the value of IN.T_RM_MSG_HIS.CREATE_TIME
     * @mbggenerated  Mon Aug 18 10:55:09 KST 2014
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column IN.T_RM_MSG_HIS.CREATE_TIME
     * @param createTime  the value for IN.T_RM_MSG_HIS.CREATE_TIME
     * @mbggenerated  Mon Aug 18 10:55:09 KST 2014
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column IN.T_RM_MSG_HIS.INSERT_UID
     * @return  the value of IN.T_RM_MSG_HIS.INSERT_UID
     * @mbggenerated  Mon Aug 18 10:55:09 KST 2014
     */
    public String getInsertUid() {
        return insertUid;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column IN.T_RM_MSG_HIS.INSERT_UID
     * @param insertUid  the value for IN.T_RM_MSG_HIS.INSERT_UID
     * @mbggenerated  Mon Aug 18 10:55:09 KST 2014
     */
    public void setInsertUid(String insertUid) {
        this.insertUid = insertUid;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column IN.T_RM_MSG_HIS.INSERT_DATE
     * @return  the value of IN.T_RM_MSG_HIS.INSERT_DATE
     * @mbggenerated  Mon Aug 18 10:55:09 KST 2014
     */
    public Date getInsertDate() {
        return insertDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column IN.T_RM_MSG_HIS.INSERT_DATE
     * @param insertDate  the value for IN.T_RM_MSG_HIS.INSERT_DATE
     * @mbggenerated  Mon Aug 18 10:55:09 KST 2014
     */
    public void setInsertDate(Date insertDate) {
        this.insertDate = insertDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column IN.T_RM_MSG_HIS.MAC_NO
     * @return  the value of IN.T_RM_MSG_HIS.MAC_NO
     * @mbggenerated  Mon Aug 18 10:55:09 KST 2014
     */
    public String getMacNo() {
        return macNo;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column IN.T_RM_MSG_HIS.MAC_NO
     * @param macNo  the value for IN.T_RM_MSG_HIS.MAC_NO
     * @mbggenerated  Mon Aug 18 10:55:09 KST 2014
     */
    public void setMacNo(String macNo) {
        this.macNo = macNo;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column IN.T_RM_MSG_HIS.MAC_MSG_SEQ
     * @return  the value of IN.T_RM_MSG_HIS.MAC_MSG_SEQ
     * @mbggenerated  Mon Aug 18 10:55:09 KST 2014
     */
    public String getMacMsgSeq() {
        return macMsgSeq;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column IN.T_RM_MSG_HIS.MAC_MSG_SEQ
     * @param macMsgSeq  the value for IN.T_RM_MSG_HIS.MAC_MSG_SEQ
     * @mbggenerated  Mon Aug 18 10:55:09 KST 2014
     */
    public void setMacMsgSeq(String macMsgSeq) {
        this.macMsgSeq = macMsgSeq;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column IN.T_RM_MSG_HIS.MSG_STS
     * @return  the value of IN.T_RM_MSG_HIS.MSG_STS
     * @mbggenerated  Mon Aug 18 10:55:09 KST 2014
     */
    public String getMsgSts() {
        return msgSts;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column IN.T_RM_MSG_HIS.MSG_STS
     * @param msgSts  the value for IN.T_RM_MSG_HIS.MSG_STS
     * @mbggenerated  Mon Aug 18 10:55:09 KST 2014
     */
    public void setMsgSts(String msgSts) {
        this.msgSts = msgSts;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column IN.T_RM_MSG_HIS.MSG_TYPE
     * @return  the value of IN.T_RM_MSG_HIS.MSG_TYPE
     * @mbggenerated  Mon Aug 18 10:55:09 KST 2014
     */
    public String getMsgType() {
        return msgType;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column IN.T_RM_MSG_HIS.MSG_TYPE
     * @param msgType  the value for IN.T_RM_MSG_HIS.MSG_TYPE
     * @mbggenerated  Mon Aug 18 10:55:09 KST 2014
     */
    public void setMsgType(String msgType) {
        this.msgType = msgType;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column IN.T_RM_MSG_HIS.MSG_CD
     * @return  the value of IN.T_RM_MSG_HIS.MSG_CD
     * @mbggenerated  Mon Aug 18 10:55:09 KST 2014
     */
    public String getMsgCd() {
        return msgCd;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column IN.T_RM_MSG_HIS.MSG_CD
     * @param msgCd  the value for IN.T_RM_MSG_HIS.MSG_CD
     * @mbggenerated  Mon Aug 18 10:55:09 KST 2014
     */
    public void setMsgCd(String msgCd) {
        this.msgCd = msgCd;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column IN.T_RM_MSG_HIS.SVC_CD
     * @return  the value of IN.T_RM_MSG_HIS.SVC_CD
     * @mbggenerated  Mon Aug 18 10:55:09 KST 2014
     */
    public String getSvcCd() {
        return svcCd;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column IN.T_RM_MSG_HIS.SVC_CD
     * @param svcCd  the value for IN.T_RM_MSG_HIS.SVC_CD
     * @mbggenerated  Mon Aug 18 10:55:09 KST 2014
     */
    public void setSvcCd(String svcCd) {
        this.svcCd = svcCd;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column IN.T_RM_MSG_HIS.MAC_SER_NO
     * @return  the value of IN.T_RM_MSG_HIS.MAC_SER_NO
     * @mbggenerated  Mon Aug 18 10:55:09 KST 2014
     */
    public String getMacSerNo() {
        return macSerNo;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column IN.T_RM_MSG_HIS.MAC_SER_NO
     * @param macSerNo  the value for IN.T_RM_MSG_HIS.MAC_SER_NO
     * @mbggenerated  Mon Aug 18 10:55:09 KST 2014
     */
    public void setMacSerNo(String macSerNo) {
        this.macSerNo = macSerNo;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column IN.T_RM_MSG_HIS.BRANCH_CD
     * @return  the value of IN.T_RM_MSG_HIS.BRANCH_CD
     * @mbggenerated  Mon Aug 18 10:55:09 KST 2014
     */
    public String getBranchCd() {
        return branchCd;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column IN.T_RM_MSG_HIS.BRANCH_CD
     * @param branchCd  the value for IN.T_RM_MSG_HIS.BRANCH_CD
     * @mbggenerated  Mon Aug 18 10:55:09 KST 2014
     */
    public void setBranchCd(String branchCd) {
        this.branchCd = branchCd;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column IN.T_RM_MSG_HIS.ORG_CD
     * @return  the value of IN.T_RM_MSG_HIS.ORG_CD
     * @mbggenerated  Mon Aug 18 10:55:09 KST 2014
     */
    public String getOrgCd() {
        return orgCd;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column IN.T_RM_MSG_HIS.ORG_CD
     * @param orgCd  the value for IN.T_RM_MSG_HIS.ORG_CD
     * @mbggenerated  Mon Aug 18 10:55:09 KST 2014
     */
    public void setOrgCd(String orgCd) {
        this.orgCd = orgCd;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column IN.T_RM_MSG_HIS.MSG_CTX
     * @return  the value of IN.T_RM_MSG_HIS.MSG_CTX
     * @mbggenerated  Mon Aug 18 10:55:09 KST 2014
     */
    public String getMsgCtx() {
        return msgCtx;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column IN.T_RM_MSG_HIS.MSG_CTX
     * @param msgCtx  the value for IN.T_RM_MSG_HIS.MSG_CTX
     * @mbggenerated  Mon Aug 18 10:55:09 KST 2014
     */
    public void setMsgCtx(String msgCtx) {
        this.msgCtx = msgCtx;
    }
}