package com.nicetcm.nibsplus.broker.msg.mapper;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.DELETE_FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.ORDER_BY;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT_DISTINCT;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import com.nicetcm.nibsplus.broker.msg.model.TCtErrorNoti;
import com.nicetcm.nibsplus.broker.msg.model.TCtErrorNotiSpec.Criteria;
import com.nicetcm.nibsplus.broker.msg.model.TCtErrorNotiSpec.Criterion;
import com.nicetcm.nibsplus.broker.msg.model.TCtErrorNotiSpec;
import java.util.List;
import java.util.Map;

public class TCtErrorNotiSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_CT_ERROR_NOTI
     *
     * @mbggenerated Fri Jun 27 14:12:12 KST 2014
     */
    public String countBySpec(TCtErrorNotiSpec spec) {
        BEGIN();
        SELECT("count(*)");
        FROM("OP.T_CT_ERROR_NOTI");
        applyWhere(spec, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_CT_ERROR_NOTI
     *
     * @mbggenerated Fri Jun 27 14:12:12 KST 2014
     */
    public String deleteBySpec(TCtErrorNotiSpec spec) {
        BEGIN();
        DELETE_FROM("OP.T_CT_ERROR_NOTI");
        applyWhere(spec, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_CT_ERROR_NOTI
     *
     * @mbggenerated Fri Jun 27 14:12:12 KST 2014
     */
    public String insertSelective(TCtErrorNoti record) {
        BEGIN();
        INSERT_INTO("OP.T_CT_ERROR_NOTI");
        
        if (record.getErrorNo() != null) {
            VALUES("ERROR_NO", "#{errorNo,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateDate() != null) {
            VALUES("CREATE_DATE", "#{createDate,jdbcType=DECIMAL}");
        }
        
        if (record.getCreateTime() != null) {
            VALUES("CREATE_TIME", "#{createTime,jdbcType=VARCHAR}");
        }
        
        if (record.getSendType() != null) {
            VALUES("SEND_TYPE", "#{sendType,jdbcType=CHAR}");
        }
        
        if (record.getSendDate() != null) {
            VALUES("SEND_DATE", "#{sendDate,jdbcType=VARCHAR}");
        }
        
        if (record.getSendTime() != null) {
            VALUES("SEND_TIME", "#{sendTime,jdbcType=VARCHAR}");
        }
        
        if (record.getSendNm() != null) {
            VALUES("SEND_NM", "#{sendNm,jdbcType=VARCHAR}");
        }
        
        if (record.getSendUid() != null) {
            VALUES("SEND_UID", "#{sendUid,jdbcType=VARCHAR}");
        }
        
        if (record.getSendCheckYn() != null) {
            VALUES("SEND_CHECK_YN", "#{sendCheckYn,jdbcType=CHAR}");
        }
        
        if (record.getSendCheckDatetime() != null) {
            VALUES("SEND_CHECK_DATETIME", "#{sendCheckDatetime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getSendPlanDatetime() != null) {
            VALUES("SEND_PLAN_DATETIME", "#{sendPlanDatetime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getSendPlanNm() != null) {
            VALUES("SEND_PLAN_NM", "#{sendPlanNm,jdbcType=VARCHAR}");
        }
        
        if (record.getSendPlanUid() != null) {
            VALUES("SEND_PLAN_UID", "#{sendPlanUid,jdbcType=VARCHAR}");
        }
        
        if (record.getSendStatus() != null) {
            VALUES("SEND_STATUS", "#{sendStatus,jdbcType=CHAR}");
        }
        
        if (record.getSendTool() != null) {
            VALUES("SEND_TOOL", "#{sendTool,jdbcType=VARCHAR}");
        }
        
        if (record.getSendSmsStatus() != null) {
            VALUES("SEND_SMS_STATUS", "#{sendSmsStatus,jdbcType=VARCHAR}");
        }
        
        if (record.getOrgUserType() != null) {
            VALUES("ORG_USER_TYPE", "#{orgUserType,jdbcType=VARCHAR}");
        }
        
        if (record.getOrgUserNm() != null) {
            VALUES("ORG_USER_NM", "#{orgUserNm,jdbcType=VARCHAR}");
        }
        
        if (record.getRecvPlace() != null) {
            VALUES("RECV_PLACE", "#{recvPlace,jdbcType=VARCHAR}");
        }
        
        if (record.getRecvUserNm() != null) {
            VALUES("RECV_USER_NM", "#{recvUserNm,jdbcType=VARCHAR}");
        }
        
        if (record.getRecvUserUid() != null) {
            VALUES("RECV_USER_UID", "#{recvUserUid,jdbcType=VARCHAR}");
        }
        
        if (record.getRecvTeleNo() != null) {
            VALUES("RECV_TELE_NO", "#{recvTeleNo,jdbcType=VARCHAR}");
        }
        
        if (record.getRecvDate() != null) {
            VALUES("RECV_DATE", "#{recvDate,jdbcType=VARCHAR}");
        }
        
        if (record.getRecvTime() != null) {
            VALUES("RECV_TIME", "#{recvTime,jdbcType=VARCHAR}");
        }
        
        if (record.getRecvPdaDate() != null) {
            VALUES("RECV_PDA_DATE", "#{recvPdaDate,jdbcType=VARCHAR}");
        }
        
        if (record.getRecvPdaTime() != null) {
            VALUES("RECV_PDA_TIME", "#{recvPdaTime,jdbcType=VARCHAR}");
        }
        
        if (record.getRecvXpos() != null) {
            VALUES("RECV_XPOS", "#{recvXpos,jdbcType=DECIMAL}");
        }
        
        if (record.getRecvYpos() != null) {
            VALUES("RECV_YPOS", "#{recvYpos,jdbcType=DECIMAL}");
        }
        
        if (record.getRecvSido() != null) {
            VALUES("RECV_SIDO", "#{recvSido,jdbcType=VARCHAR}");
        }
        
        if (record.getRecvGugun() != null) {
            VALUES("RECV_GUGUN", "#{recvGugun,jdbcType=VARCHAR}");
        }
        
        if (record.getRecvDong() != null) {
            VALUES("RECV_DONG", "#{recvDong,jdbcType=VARCHAR}");
        }
        
        if (record.getArrivalEstDate() != null) {
            VALUES("ARRIVAL_EST_DATE", "#{arrivalEstDate,jdbcType=VARCHAR}");
        }
        
        if (record.getArrivalEstTime() != null) {
            VALUES("ARRIVAL_EST_TIME", "#{arrivalEstTime,jdbcType=VARCHAR}");
        }
        
        if (record.getRegDt() != null) {
            VALUES("REG_DT", "#{regDt,jdbcType=TIMESTAMP}");
        }
        
        if (record.getRegId() != null) {
            VALUES("REG_ID", "#{regId,jdbcType=VARCHAR}");
        }
        
        if (record.getUpdateDate() != null) {
            VALUES("UPDATE_DATE", "#{updateDate,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdateUid() != null) {
            VALUES("UPDATE_UID", "#{updateUid,jdbcType=VARCHAR}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_CT_ERROR_NOTI
     *
     * @mbggenerated Fri Jun 27 14:12:12 KST 2014
     */
    public String selectBySpec(TCtErrorNotiSpec spec) {
        BEGIN();
        if (spec != null && spec.isDistinct()) {
            SELECT_DISTINCT("ERROR_NO");
        } else {
            SELECT("ERROR_NO");
        }
        SELECT("CREATE_DATE");
        SELECT("CREATE_TIME");
        SELECT("SEND_TYPE");
        SELECT("SEND_DATE");
        SELECT("SEND_TIME");
        SELECT("SEND_NM");
        SELECT("SEND_UID");
        SELECT("SEND_CHECK_YN");
        SELECT("SEND_CHECK_DATETIME");
        SELECT("SEND_PLAN_DATETIME");
        SELECT("SEND_PLAN_NM");
        SELECT("SEND_PLAN_UID");
        SELECT("SEND_STATUS");
        SELECT("SEND_TOOL");
        SELECT("SEND_SMS_STATUS");
        SELECT("ORG_USER_TYPE");
        SELECT("ORG_USER_NM");
        SELECT("RECV_PLACE");
        SELECT("RECV_USER_NM");
        SELECT("RECV_USER_UID");
        SELECT("RECV_TELE_NO");
        SELECT("RECV_DATE");
        SELECT("RECV_TIME");
        SELECT("RECV_PDA_DATE");
        SELECT("RECV_PDA_TIME");
        SELECT("RECV_XPOS");
        SELECT("RECV_YPOS");
        SELECT("RECV_SIDO");
        SELECT("RECV_GUGUN");
        SELECT("RECV_DONG");
        SELECT("ARRIVAL_EST_DATE");
        SELECT("ARRIVAL_EST_TIME");
        SELECT("REG_DT");
        SELECT("REG_ID");
        SELECT("UPDATE_DATE");
        SELECT("UPDATE_UID");
        FROM("OP.T_CT_ERROR_NOTI");
        applyWhere(spec, false);
        
        if (spec != null && spec.getOrderByClause() != null) {
            ORDER_BY(spec.getOrderByClause());
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_CT_ERROR_NOTI
     *
     * @mbggenerated Fri Jun 27 14:12:12 KST 2014
     */
    public String updateBySpecSelective(Map<String, Object> parameter) {
        TCtErrorNoti record = (TCtErrorNoti) parameter.get("record");
        TCtErrorNotiSpec spec = (TCtErrorNotiSpec) parameter.get("spec");
        
        BEGIN();
        UPDATE("OP.T_CT_ERROR_NOTI");
        
        if (record.getErrorNo() != null) {
            SET("ERROR_NO = #{record.errorNo,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateDate() != null) {
            SET("CREATE_DATE = #{record.createDate,jdbcType=DECIMAL}");
        }
        
        if (record.getCreateTime() != null) {
            SET("CREATE_TIME = #{record.createTime,jdbcType=VARCHAR}");
        }
        
        if (record.getSendType() != null) {
            SET("SEND_TYPE = #{record.sendType,jdbcType=CHAR}");
        }
        
        if (record.getSendDate() != null) {
            SET("SEND_DATE = #{record.sendDate,jdbcType=VARCHAR}");
        }
        
        if (record.getSendTime() != null) {
            SET("SEND_TIME = #{record.sendTime,jdbcType=VARCHAR}");
        }
        
        if (record.getSendNm() != null) {
            SET("SEND_NM = #{record.sendNm,jdbcType=VARCHAR}");
        }
        
        if (record.getSendUid() != null) {
            SET("SEND_UID = #{record.sendUid,jdbcType=VARCHAR}");
        }
        
        if (record.getSendCheckYn() != null) {
            SET("SEND_CHECK_YN = #{record.sendCheckYn,jdbcType=CHAR}");
        }
        
        if (record.getSendCheckDatetime() != null) {
            SET("SEND_CHECK_DATETIME = #{record.sendCheckDatetime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getSendPlanDatetime() != null) {
            SET("SEND_PLAN_DATETIME = #{record.sendPlanDatetime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getSendPlanNm() != null) {
            SET("SEND_PLAN_NM = #{record.sendPlanNm,jdbcType=VARCHAR}");
        }
        
        if (record.getSendPlanUid() != null) {
            SET("SEND_PLAN_UID = #{record.sendPlanUid,jdbcType=VARCHAR}");
        }
        
        if (record.getSendStatus() != null) {
            SET("SEND_STATUS = #{record.sendStatus,jdbcType=CHAR}");
        }
        
        if (record.getSendTool() != null) {
            SET("SEND_TOOL = #{record.sendTool,jdbcType=VARCHAR}");
        }
        
        if (record.getSendSmsStatus() != null) {
            SET("SEND_SMS_STATUS = #{record.sendSmsStatus,jdbcType=VARCHAR}");
        }
        
        if (record.getOrgUserType() != null) {
            SET("ORG_USER_TYPE = #{record.orgUserType,jdbcType=VARCHAR}");
        }
        
        if (record.getOrgUserNm() != null) {
            SET("ORG_USER_NM = #{record.orgUserNm,jdbcType=VARCHAR}");
        }
        
        if (record.getRecvPlace() != null) {
            SET("RECV_PLACE = #{record.recvPlace,jdbcType=VARCHAR}");
        }
        
        if (record.getRecvUserNm() != null) {
            SET("RECV_USER_NM = #{record.recvUserNm,jdbcType=VARCHAR}");
        }
        
        if (record.getRecvUserUid() != null) {
            SET("RECV_USER_UID = #{record.recvUserUid,jdbcType=VARCHAR}");
        }
        
        if (record.getRecvTeleNo() != null) {
            SET("RECV_TELE_NO = #{record.recvTeleNo,jdbcType=VARCHAR}");
        }
        
        if (record.getRecvDate() != null) {
            SET("RECV_DATE = #{record.recvDate,jdbcType=VARCHAR}");
        }
        
        if (record.getRecvTime() != null) {
            SET("RECV_TIME = #{record.recvTime,jdbcType=VARCHAR}");
        }
        
        if (record.getRecvPdaDate() != null) {
            SET("RECV_PDA_DATE = #{record.recvPdaDate,jdbcType=VARCHAR}");
        }
        
        if (record.getRecvPdaTime() != null) {
            SET("RECV_PDA_TIME = #{record.recvPdaTime,jdbcType=VARCHAR}");
        }
        
        if (record.getRecvXpos() != null) {
            SET("RECV_XPOS = #{record.recvXpos,jdbcType=DECIMAL}");
        }
        
        if (record.getRecvYpos() != null) {
            SET("RECV_YPOS = #{record.recvYpos,jdbcType=DECIMAL}");
        }
        
        if (record.getRecvSido() != null) {
            SET("RECV_SIDO = #{record.recvSido,jdbcType=VARCHAR}");
        }
        
        if (record.getRecvGugun() != null) {
            SET("RECV_GUGUN = #{record.recvGugun,jdbcType=VARCHAR}");
        }
        
        if (record.getRecvDong() != null) {
            SET("RECV_DONG = #{record.recvDong,jdbcType=VARCHAR}");
        }
        
        if (record.getArrivalEstDate() != null) {
            SET("ARRIVAL_EST_DATE = #{record.arrivalEstDate,jdbcType=VARCHAR}");
        }
        
        if (record.getArrivalEstTime() != null) {
            SET("ARRIVAL_EST_TIME = #{record.arrivalEstTime,jdbcType=VARCHAR}");
        }
        
        if (record.getRegDt() != null) {
            SET("REG_DT = #{record.regDt,jdbcType=TIMESTAMP}");
        }
        
        if (record.getRegId() != null) {
            SET("REG_ID = #{record.regId,jdbcType=VARCHAR}");
        }
        
        if (record.getUpdateDate() != null) {
            SET("UPDATE_DATE = #{record.updateDate,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdateUid() != null) {
            SET("UPDATE_UID = #{record.updateUid,jdbcType=VARCHAR}");
        }
        
        applyWhere(spec, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_CT_ERROR_NOTI
     *
     * @mbggenerated Fri Jun 27 14:12:12 KST 2014
     */
    public String updateBySpec(Map<String, Object> parameter) {
        BEGIN();
        UPDATE("OP.T_CT_ERROR_NOTI");
        
        SET("ERROR_NO = #{record.errorNo,jdbcType=VARCHAR}");
        SET("CREATE_DATE = #{record.createDate,jdbcType=DECIMAL}");
        SET("CREATE_TIME = #{record.createTime,jdbcType=VARCHAR}");
        SET("SEND_TYPE = #{record.sendType,jdbcType=CHAR}");
        SET("SEND_DATE = #{record.sendDate,jdbcType=VARCHAR}");
        SET("SEND_TIME = #{record.sendTime,jdbcType=VARCHAR}");
        SET("SEND_NM = #{record.sendNm,jdbcType=VARCHAR}");
        SET("SEND_UID = #{record.sendUid,jdbcType=VARCHAR}");
        SET("SEND_CHECK_YN = #{record.sendCheckYn,jdbcType=CHAR}");
        SET("SEND_CHECK_DATETIME = #{record.sendCheckDatetime,jdbcType=TIMESTAMP}");
        SET("SEND_PLAN_DATETIME = #{record.sendPlanDatetime,jdbcType=TIMESTAMP}");
        SET("SEND_PLAN_NM = #{record.sendPlanNm,jdbcType=VARCHAR}");
        SET("SEND_PLAN_UID = #{record.sendPlanUid,jdbcType=VARCHAR}");
        SET("SEND_STATUS = #{record.sendStatus,jdbcType=CHAR}");
        SET("SEND_TOOL = #{record.sendTool,jdbcType=VARCHAR}");
        SET("SEND_SMS_STATUS = #{record.sendSmsStatus,jdbcType=VARCHAR}");
        SET("ORG_USER_TYPE = #{record.orgUserType,jdbcType=VARCHAR}");
        SET("ORG_USER_NM = #{record.orgUserNm,jdbcType=VARCHAR}");
        SET("RECV_PLACE = #{record.recvPlace,jdbcType=VARCHAR}");
        SET("RECV_USER_NM = #{record.recvUserNm,jdbcType=VARCHAR}");
        SET("RECV_USER_UID = #{record.recvUserUid,jdbcType=VARCHAR}");
        SET("RECV_TELE_NO = #{record.recvTeleNo,jdbcType=VARCHAR}");
        SET("RECV_DATE = #{record.recvDate,jdbcType=VARCHAR}");
        SET("RECV_TIME = #{record.recvTime,jdbcType=VARCHAR}");
        SET("RECV_PDA_DATE = #{record.recvPdaDate,jdbcType=VARCHAR}");
        SET("RECV_PDA_TIME = #{record.recvPdaTime,jdbcType=VARCHAR}");
        SET("RECV_XPOS = #{record.recvXpos,jdbcType=DECIMAL}");
        SET("RECV_YPOS = #{record.recvYpos,jdbcType=DECIMAL}");
        SET("RECV_SIDO = #{record.recvSido,jdbcType=VARCHAR}");
        SET("RECV_GUGUN = #{record.recvGugun,jdbcType=VARCHAR}");
        SET("RECV_DONG = #{record.recvDong,jdbcType=VARCHAR}");
        SET("ARRIVAL_EST_DATE = #{record.arrivalEstDate,jdbcType=VARCHAR}");
        SET("ARRIVAL_EST_TIME = #{record.arrivalEstTime,jdbcType=VARCHAR}");
        SET("REG_DT = #{record.regDt,jdbcType=TIMESTAMP}");
        SET("REG_ID = #{record.regId,jdbcType=VARCHAR}");
        SET("UPDATE_DATE = #{record.updateDate,jdbcType=TIMESTAMP}");
        SET("UPDATE_UID = #{record.updateUid,jdbcType=VARCHAR}");
        
        TCtErrorNotiSpec spec = (TCtErrorNotiSpec) parameter.get("spec");
        applyWhere(spec, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_CT_ERROR_NOTI
     *
     * @mbggenerated Fri Jun 27 14:12:12 KST 2014
     */
    public String updateByPrimaryKeySelective(TCtErrorNoti record) {
        BEGIN();
        UPDATE("OP.T_CT_ERROR_NOTI");
        
        if (record.getSendType() != null) {
            SET("SEND_TYPE = #{sendType,jdbcType=CHAR}");
        }
        
        if (record.getSendDate() != null) {
            SET("SEND_DATE = #{sendDate,jdbcType=VARCHAR}");
        }
        
        if (record.getSendTime() != null) {
            SET("SEND_TIME = #{sendTime,jdbcType=VARCHAR}");
        }
        
        if (record.getSendNm() != null) {
            SET("SEND_NM = #{sendNm,jdbcType=VARCHAR}");
        }
        
        if (record.getSendUid() != null) {
            SET("SEND_UID = #{sendUid,jdbcType=VARCHAR}");
        }
        
        if (record.getSendCheckYn() != null) {
            SET("SEND_CHECK_YN = #{sendCheckYn,jdbcType=CHAR}");
        }
        
        if (record.getSendCheckDatetime() != null) {
            SET("SEND_CHECK_DATETIME = #{sendCheckDatetime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getSendPlanDatetime() != null) {
            SET("SEND_PLAN_DATETIME = #{sendPlanDatetime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getSendPlanNm() != null) {
            SET("SEND_PLAN_NM = #{sendPlanNm,jdbcType=VARCHAR}");
        }
        
        if (record.getSendPlanUid() != null) {
            SET("SEND_PLAN_UID = #{sendPlanUid,jdbcType=VARCHAR}");
        }
        
        if (record.getSendStatus() != null) {
            SET("SEND_STATUS = #{sendStatus,jdbcType=CHAR}");
        }
        
        if (record.getSendTool() != null) {
            SET("SEND_TOOL = #{sendTool,jdbcType=VARCHAR}");
        }
        
        if (record.getSendSmsStatus() != null) {
            SET("SEND_SMS_STATUS = #{sendSmsStatus,jdbcType=VARCHAR}");
        }
        
        if (record.getOrgUserType() != null) {
            SET("ORG_USER_TYPE = #{orgUserType,jdbcType=VARCHAR}");
        }
        
        if (record.getOrgUserNm() != null) {
            SET("ORG_USER_NM = #{orgUserNm,jdbcType=VARCHAR}");
        }
        
        if (record.getRecvPlace() != null) {
            SET("RECV_PLACE = #{recvPlace,jdbcType=VARCHAR}");
        }
        
        if (record.getRecvUserNm() != null) {
            SET("RECV_USER_NM = #{recvUserNm,jdbcType=VARCHAR}");
        }
        
        if (record.getRecvUserUid() != null) {
            SET("RECV_USER_UID = #{recvUserUid,jdbcType=VARCHAR}");
        }
        
        if (record.getRecvTeleNo() != null) {
            SET("RECV_TELE_NO = #{recvTeleNo,jdbcType=VARCHAR}");
        }
        
        if (record.getRecvDate() != null) {
            SET("RECV_DATE = #{recvDate,jdbcType=VARCHAR}");
        }
        
        if (record.getRecvTime() != null) {
            SET("RECV_TIME = #{recvTime,jdbcType=VARCHAR}");
        }
        
        if (record.getRecvPdaDate() != null) {
            SET("RECV_PDA_DATE = #{recvPdaDate,jdbcType=VARCHAR}");
        }
        
        if (record.getRecvPdaTime() != null) {
            SET("RECV_PDA_TIME = #{recvPdaTime,jdbcType=VARCHAR}");
        }
        
        if (record.getRecvXpos() != null) {
            SET("RECV_XPOS = #{recvXpos,jdbcType=DECIMAL}");
        }
        
        if (record.getRecvYpos() != null) {
            SET("RECV_YPOS = #{recvYpos,jdbcType=DECIMAL}");
        }
        
        if (record.getRecvSido() != null) {
            SET("RECV_SIDO = #{recvSido,jdbcType=VARCHAR}");
        }
        
        if (record.getRecvGugun() != null) {
            SET("RECV_GUGUN = #{recvGugun,jdbcType=VARCHAR}");
        }
        
        if (record.getRecvDong() != null) {
            SET("RECV_DONG = #{recvDong,jdbcType=VARCHAR}");
        }
        
        if (record.getArrivalEstDate() != null) {
            SET("ARRIVAL_EST_DATE = #{arrivalEstDate,jdbcType=VARCHAR}");
        }
        
        if (record.getArrivalEstTime() != null) {
            SET("ARRIVAL_EST_TIME = #{arrivalEstTime,jdbcType=VARCHAR}");
        }
        
        if (record.getRegDt() != null) {
            SET("REG_DT = #{regDt,jdbcType=TIMESTAMP}");
        }
        
        if (record.getRegId() != null) {
            SET("REG_ID = #{regId,jdbcType=VARCHAR}");
        }
        
        if (record.getUpdateDate() != null) {
            SET("UPDATE_DATE = #{updateDate,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdateUid() != null) {
            SET("UPDATE_UID = #{updateUid,jdbcType=VARCHAR}");
        }
        
        WHERE("ERROR_NO = #{errorNo,jdbcType=VARCHAR}");
        WHERE("CREATE_DATE = #{createDate,jdbcType=DECIMAL}");
        WHERE("CREATE_TIME = #{createTime,jdbcType=VARCHAR}");
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_CT_ERROR_NOTI
     *
     * @mbggenerated Fri Jun 27 14:12:12 KST 2014
     */
    protected void applyWhere(TCtErrorNotiSpec spec, boolean includeSpecPhrase) {
        if (spec == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeSpecPhrase) {
            parmPhrase1 = "%s #{spec.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{spec.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{spec.oredCriteria[%d].allCriteria[%d].value} and #{spec.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{spec.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{spec.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{spec.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{spec.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = spec.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            WHERE(sb.toString());
        }
    }
}