DECLARE 
  PDATE VARCHAR2(200);
  P_STATUS VARCHAR2(200);

BEGIN
  SELECT TO_CHAR(SYSDATE,'YYYYMMDD')
  INTO PDATE
  FROM DUAL;
 
  P_STATUS := NULL;


  NIBS.SP_FN_SENDPLAN_CONFIRM_KI ( PDATE, P_STATUS );
  COMMIT;
END;
/
EXIT;
