#!/bin/ksh

/nibs_dev/app/batch/sh/sp_fn_nice_tran_gift_dsum.sh
/nibs_dev/app/batch/sh/sp_fn_onlycashdatamacclose.sh
/nibs_dev/app/batch/sh/sp_fn_sitecount.sh
/nibs_dev/app/batch/sh/sp_fn_deal_forecast.sh
/nibs_dev/app/batch/sh/sp_fn_officeclose.sh
/nibs_dev/app/batch/sh/sp_fn_servicesend.sh
/nibs_dev/app/batch/sh/sp_fn_man.sh
/nibs_dev/app/batch/sh/sp_fn_notend_nice.sh
/nibs_dev/app/batch/sh/sp_fn_mac_stock_amt.sh
/nibs_dev/app/batch/sh/sp_fn_center.sh
/nibs_dev/app/batch/sh/sp_fn_kbcenter.sh
/nibs_dev/app/batch/sh/sp_fn_nhcenter.sh
/nibs_dev/app/batch/sh/sp_fn_kucenter.sh
/nibs_dev/app/batch/sh/sp_fn_jjcenter.sh
/nibs_dev/app/batch/sh/sp_fn_ctcenter.sh
/nibs_dev/app/batch/sh/sp_fn_nice_endamt.sh
/nibs_dev/app/batch/sh/sp_fn_kebcenter.sh
