package com.nicetcm.nibsplus.broker.msg.mapper;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.DELETE_FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.ORDER_BY;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT_DISTINCT;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import com.nicetcm.nibsplus.broker.msg.model.TCtNiceMng;
import com.nicetcm.nibsplus.broker.msg.model.TCtNiceMngSpec.Criteria;
import com.nicetcm.nibsplus.broker.msg.model.TCtNiceMngSpec.Criterion;
import com.nicetcm.nibsplus.broker.msg.model.TCtNiceMngSpec;
import java.util.List;
import java.util.Map;

public class TCtNiceMngSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_CT_NICE_MNG
     *
     * @mbggenerated Wed Jul 23 18:33:21 KST 2014
     */
    public String countBySpec(TCtNiceMngSpec spec) {
        BEGIN();
        SELECT("count(*)");
        FROM("OP.T_CT_NICE_MNG");
        applyWhere(spec, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_CT_NICE_MNG
     *
     * @mbggenerated Wed Jul 23 18:33:21 KST 2014
     */
    public String deleteBySpec(TCtNiceMngSpec spec) {
        BEGIN();
        DELETE_FROM("OP.T_CT_NICE_MNG");
        applyWhere(spec, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_CT_NICE_MNG
     *
     * @mbggenerated Wed Jul 23 18:33:21 KST 2014
     */
    public String insertSelective(TCtNiceMng record) {
        BEGIN();
        INSERT_INTO("OP.T_CT_NICE_MNG");
        
        if (record.getjDate() != null) {
            VALUES("J_DATE", "#{jDate,jdbcType=VARCHAR}");
        }
        
        if (record.getjTime() != null) {
            VALUES("J_TIME", "#{jTime,jdbcType=VARCHAR}");
        }
        
        if (record.getMacNo() != null) {
            VALUES("MAC_NO", "#{macNo,jdbcType=VARCHAR}");
        }
        
        if (record.getNetS() != null) {
            VALUES("NET_S", "#{netS,jdbcType=VARCHAR}");
        }
        
        if (record.getStat() != null) {
            VALUES("STAT", "#{stat,jdbcType=VARCHAR}");
        }
        
        if (record.getPowerFail() != null) {
            VALUES("POWER_FAIL", "#{powerFail,jdbcType=VARCHAR}");
        }
        
        if (record.getJp1() != null) {
            VALUES("JP1", "#{jp1,jdbcType=VARCHAR}");
        }
        
        if (record.getJp2() != null) {
            VALUES("JP2", "#{jp2,jdbcType=VARCHAR}");
        }
        
        if (record.getJp3() != null) {
            VALUES("JP3", "#{jp3,jdbcType=VARCHAR}");
        }
        
        if (record.getJp4() != null) {
            VALUES("JP4", "#{jp4,jdbcType=VARCHAR}");
        }
        
        if (record.getHsh() != null) {
            VALUES("HSH", "#{hsh,jdbcType=VARCHAR}");
        }
        
        if (record.getMsp1() != null) {
            VALUES("MSP1", "#{msp1,jdbcType=VARCHAR}");
        }
        
        if (record.getGsy1() != null) {
            VALUES("GSY1", "#{gsy1,jdbcType=VARCHAR}");
        }
        
        if (record.getDummy1() != null) {
            VALUES("DUMMY1", "#{dummy1,jdbcType=VARCHAR}");
        }
        
        if (record.getDummy2() != null) {
            VALUES("DUMMY2", "#{dummy2,jdbcType=VARCHAR}");
        }
        
        if (record.getDummy3() != null) {
            VALUES("DUMMY3", "#{dummy3,jdbcType=VARCHAR}");
        }
        
        if (record.getDummy4() != null) {
            VALUES("DUMMY4", "#{dummy4,jdbcType=VARCHAR}");
        }
        
        if (record.getDummy5() != null) {
            VALUES("DUMMY5", "#{dummy5,jdbcType=VARCHAR}");
        }
        
        if (record.getDummy6() != null) {
            VALUES("DUMMY6", "#{dummy6,jdbcType=VARCHAR}");
        }
        
        if (record.getDummy7() != null) {
            VALUES("DUMMY7", "#{dummy7,jdbcType=VARCHAR}");
        }
        
        if (record.getDummy8() != null) {
            VALUES("DUMMY8", "#{dummy8,jdbcType=VARCHAR}");
        }
        
        if (record.getNetErr() != null) {
            VALUES("NET_ERR", "#{netErr,jdbcType=VARCHAR}");
        }
        
        if (record.getJpbc() != null) {
            VALUES("JPBC", "#{jpbc,jdbcType=VARCHAR}");
        }
        
        if (record.getKdpd() != null) {
            VALUES("KDPD", "#{kdpd,jdbcType=VARCHAR}");
        }
        
        if (record.getMspy() != null) {
            VALUES("MSPY", "#{mspy,jdbcType=VARCHAR}");
        }
        
        if (record.getGsyj() != null) {
            VALUES("GSYJ", "#{gsyj,jdbcType=VARCHAR}");
        }
        
        if (record.getIg1() != null) {
            VALUES("IG1", "#{ig1,jdbcType=VARCHAR}");
        }
        
        if (record.getIg2() != null) {
            VALUES("IG2", "#{ig2,jdbcType=VARCHAR}");
        }
        
        if (record.getIg3() != null) {
            VALUES("IG3", "#{ig3,jdbcType=VARCHAR}");
        }
        
        if (record.getIg4() != null) {
            VALUES("IG4", "#{ig4,jdbcType=VARCHAR}");
        }
        
        if (record.getIg5() != null) {
            VALUES("IG5", "#{ig5,jdbcType=VARCHAR}");
        }
        
        if (record.getPassMac() != null) {
            VALUES("PASS_MAC", "#{passMac,jdbcType=VARCHAR}");
        }
        
        if (record.getJpMsc() != null) {
            VALUES("JP_MSC", "#{jpMsc,jdbcType=VARCHAR}");
        }
        
        if (record.getDummy9() != null) {
            VALUES("DUMMY9", "#{dummy9,jdbcType=VARCHAR}");
        }
        
        if (record.getDgi() != null) {
            VALUES("DGI", "#{dgi,jdbcType=VARCHAR}");
        }
        
        if (record.getDummy10() != null) {
            VALUES("DUMMY10", "#{dummy10,jdbcType=VARCHAR}");
        }
        
        if (record.getTermMode() != null) {
            VALUES("TERM_MODE", "#{termMode,jdbcType=VARCHAR}");
        }
        
        if (record.getGggp() != null) {
            VALUES("GGGP", "#{gggp,jdbcType=VARCHAR}");
        }
        
        if (record.getGgjg() != null) {
            VALUES("GGJG", "#{ggjg,jdbcType=VARCHAR}");
        }
        
        if (record.getGgjd() != null) {
            VALUES("GGJD", "#{ggjd,jdbcType=VARCHAR}");
        }
        
        if (record.getGgygj() != null) {
            VALUES("GGYGJ", "#{ggygj,jdbcType=VARCHAR}");
        }
        
        if (record.getGgjc() != null) {
            VALUES("GGJC", "#{ggjc,jdbcType=VARCHAR}");
        }
        
        if (record.getHshtc() != null) {
            VALUES("HSHTC", "#{hshtc,jdbcType=VARCHAR}");
        }
        
        if (record.getJp1tc() != null) {
            VALUES("JP1TC", "#{jp1tc,jdbcType=VARCHAR}");
        }
        
        if (record.getJp2tc() != null) {
            VALUES("JP2TC", "#{jp2tc,jdbcType=VARCHAR}");
        }
        
        if (record.getJp3tc() != null) {
            VALUES("JP3TC", "#{jp3tc,jdbcType=VARCHAR}");
        }
        
        if (record.getJp4tc() != null) {
            VALUES("JP4TC", "#{jp4tc,jdbcType=VARCHAR}");
        }
        
        if (record.getCdpd() != null) {
            VALUES("CDPD", "#{cdpd,jdbcType=VARCHAR}");
        }
        
        if (record.getPass1() != null) {
            VALUES("PASS1", "#{pass1,jdbcType=VARCHAR}");
        }
        
        if (record.getDummy11() != null) {
            VALUES("DUMMY11", "#{dummy11,jdbcType=VARCHAR}");
        }
        
        if (record.getDummy12() != null) {
            VALUES("DUMMY12", "#{dummy12,jdbcType=VARCHAR}");
        }
        
        if (record.getUpdateDate() != null) {
            VALUES("UPDATE_DATE", "#{updateDate,jdbcType=TIMESTAMP}");
        }
        
        if (record.getPgmVer() != null) {
            VALUES("PGM_VER", "#{pgmVer,jdbcType=VARCHAR}");
        }
        
        if (record.getInCheck() != null) {
            VALUES("IN_CHECK", "#{inCheck,jdbcType=VARCHAR}");
        }
        
        if (record.getOutCheck() != null) {
            VALUES("OUT_CHECK", "#{outCheck,jdbcType=VARCHAR}");
        }
        
        if (record.getInCash5() != null) {
            VALUES("IN_CASH_5", "#{inCash5,jdbcType=VARCHAR}");
        }
        
        if (record.getInCash10() != null) {
            VALUES("IN_CASH_10", "#{inCash10,jdbcType=VARCHAR}");
        }
        
        if (record.getRemMoney() != null) {
            VALUES("REM_MONEY", "#{remMoney,jdbcType=VARCHAR}");
        }
        
        if (record.getRpc() != null) {
            VALUES("RPC", "#{rpc,jdbcType=VARCHAR}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_CT_NICE_MNG
     *
     * @mbggenerated Wed Jul 23 18:33:21 KST 2014
     */
    public String selectBySpec(TCtNiceMngSpec spec) {
        BEGIN();
        if (spec != null && spec.isDistinct()) {
            SELECT_DISTINCT("J_DATE");
        } else {
            SELECT("J_DATE");
        }
        SELECT("J_TIME");
        SELECT("MAC_NO");
        SELECT("NET_S");
        SELECT("STAT");
        SELECT("POWER_FAIL");
        SELECT("JP1");
        SELECT("JP2");
        SELECT("JP3");
        SELECT("JP4");
        SELECT("HSH");
        SELECT("MSP1");
        SELECT("GSY1");
        SELECT("DUMMY1");
        SELECT("DUMMY2");
        SELECT("DUMMY3");
        SELECT("DUMMY4");
        SELECT("DUMMY5");
        SELECT("DUMMY6");
        SELECT("DUMMY7");
        SELECT("DUMMY8");
        SELECT("NET_ERR");
        SELECT("JPBC");
        SELECT("KDPD");
        SELECT("MSPY");
        SELECT("GSYJ");
        SELECT("IG1");
        SELECT("IG2");
        SELECT("IG3");
        SELECT("IG4");
        SELECT("IG5");
        SELECT("PASS_MAC");
        SELECT("JP_MSC");
        SELECT("DUMMY9");
        SELECT("DGI");
        SELECT("DUMMY10");
        SELECT("TERM_MODE");
        SELECT("GGGP");
        SELECT("GGJG");
        SELECT("GGJD");
        SELECT("GGYGJ");
        SELECT("GGJC");
        SELECT("HSHTC");
        SELECT("JP1TC");
        SELECT("JP2TC");
        SELECT("JP3TC");
        SELECT("JP4TC");
        SELECT("CDPD");
        SELECT("PASS1");
        SELECT("DUMMY11");
        SELECT("DUMMY12");
        SELECT("UPDATE_DATE");
        SELECT("PGM_VER");
        SELECT("IN_CHECK");
        SELECT("OUT_CHECK");
        SELECT("IN_CASH_5");
        SELECT("IN_CASH_10");
        SELECT("REM_MONEY");
        SELECT("RPC");
        FROM("OP.T_CT_NICE_MNG");
        applyWhere(spec, false);
        
        if (spec != null && spec.getOrderByClause() != null) {
            ORDER_BY(spec.getOrderByClause());
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_CT_NICE_MNG
     *
     * @mbggenerated Wed Jul 23 18:33:21 KST 2014
     */
    public String updateBySpecSelective(Map<String, Object> parameter) {
        TCtNiceMng record = (TCtNiceMng) parameter.get("record");
        TCtNiceMngSpec spec = (TCtNiceMngSpec) parameter.get("spec");
        
        BEGIN();
        UPDATE("OP.T_CT_NICE_MNG");
        
        if (record.getjDate() != null) {
            SET("J_DATE = #{record.jDate,jdbcType=VARCHAR}");
        }
        
        if (record.getjTime() != null) {
            SET("J_TIME = #{record.jTime,jdbcType=VARCHAR}");
        }
        
        if (record.getMacNo() != null) {
            SET("MAC_NO = #{record.macNo,jdbcType=VARCHAR}");
        }
        
        if (record.getNetS() != null) {
            SET("NET_S = #{record.netS,jdbcType=VARCHAR}");
        }
        
        if (record.getStat() != null) {
            SET("STAT = #{record.stat,jdbcType=VARCHAR}");
        }
        
        if (record.getPowerFail() != null) {
            SET("POWER_FAIL = #{record.powerFail,jdbcType=VARCHAR}");
        }
        
        if (record.getJp1() != null) {
            SET("JP1 = #{record.jp1,jdbcType=VARCHAR}");
        }
        
        if (record.getJp2() != null) {
            SET("JP2 = #{record.jp2,jdbcType=VARCHAR}");
        }
        
        if (record.getJp3() != null) {
            SET("JP3 = #{record.jp3,jdbcType=VARCHAR}");
        }
        
        if (record.getJp4() != null) {
            SET("JP4 = #{record.jp4,jdbcType=VARCHAR}");
        }
        
        if (record.getHsh() != null) {
            SET("HSH = #{record.hsh,jdbcType=VARCHAR}");
        }
        
        if (record.getMsp1() != null) {
            SET("MSP1 = #{record.msp1,jdbcType=VARCHAR}");
        }
        
        if (record.getGsy1() != null) {
            SET("GSY1 = #{record.gsy1,jdbcType=VARCHAR}");
        }
        
        if (record.getDummy1() != null) {
            SET("DUMMY1 = #{record.dummy1,jdbcType=VARCHAR}");
        }
        
        if (record.getDummy2() != null) {
            SET("DUMMY2 = #{record.dummy2,jdbcType=VARCHAR}");
        }
        
        if (record.getDummy3() != null) {
            SET("DUMMY3 = #{record.dummy3,jdbcType=VARCHAR}");
        }
        
        if (record.getDummy4() != null) {
            SET("DUMMY4 = #{record.dummy4,jdbcType=VARCHAR}");
        }
        
        if (record.getDummy5() != null) {
            SET("DUMMY5 = #{record.dummy5,jdbcType=VARCHAR}");
        }
        
        if (record.getDummy6() != null) {
            SET("DUMMY6 = #{record.dummy6,jdbcType=VARCHAR}");
        }
        
        if (record.getDummy7() != null) {
            SET("DUMMY7 = #{record.dummy7,jdbcType=VARCHAR}");
        }
        
        if (record.getDummy8() != null) {
            SET("DUMMY8 = #{record.dummy8,jdbcType=VARCHAR}");
        }
        
        if (record.getNetErr() != null) {
            SET("NET_ERR = #{record.netErr,jdbcType=VARCHAR}");
        }
        
        if (record.getJpbc() != null) {
            SET("JPBC = #{record.jpbc,jdbcType=VARCHAR}");
        }
        
        if (record.getKdpd() != null) {
            SET("KDPD = #{record.kdpd,jdbcType=VARCHAR}");
        }
        
        if (record.getMspy() != null) {
            SET("MSPY = #{record.mspy,jdbcType=VARCHAR}");
        }
        
        if (record.getGsyj() != null) {
            SET("GSYJ = #{record.gsyj,jdbcType=VARCHAR}");
        }
        
        if (record.getIg1() != null) {
            SET("IG1 = #{record.ig1,jdbcType=VARCHAR}");
        }
        
        if (record.getIg2() != null) {
            SET("IG2 = #{record.ig2,jdbcType=VARCHAR}");
        }
        
        if (record.getIg3() != null) {
            SET("IG3 = #{record.ig3,jdbcType=VARCHAR}");
        }
        
        if (record.getIg4() != null) {
            SET("IG4 = #{record.ig4,jdbcType=VARCHAR}");
        }
        
        if (record.getIg5() != null) {
            SET("IG5 = #{record.ig5,jdbcType=VARCHAR}");
        }
        
        if (record.getPassMac() != null) {
            SET("PASS_MAC = #{record.passMac,jdbcType=VARCHAR}");
        }
        
        if (record.getJpMsc() != null) {
            SET("JP_MSC = #{record.jpMsc,jdbcType=VARCHAR}");
        }
        
        if (record.getDummy9() != null) {
            SET("DUMMY9 = #{record.dummy9,jdbcType=VARCHAR}");
        }
        
        if (record.getDgi() != null) {
            SET("DGI = #{record.dgi,jdbcType=VARCHAR}");
        }
        
        if (record.getDummy10() != null) {
            SET("DUMMY10 = #{record.dummy10,jdbcType=VARCHAR}");
        }
        
        if (record.getTermMode() != null) {
            SET("TERM_MODE = #{record.termMode,jdbcType=VARCHAR}");
        }
        
        if (record.getGggp() != null) {
            SET("GGGP = #{record.gggp,jdbcType=VARCHAR}");
        }
        
        if (record.getGgjg() != null) {
            SET("GGJG = #{record.ggjg,jdbcType=VARCHAR}");
        }
        
        if (record.getGgjd() != null) {
            SET("GGJD = #{record.ggjd,jdbcType=VARCHAR}");
        }
        
        if (record.getGgygj() != null) {
            SET("GGYGJ = #{record.ggygj,jdbcType=VARCHAR}");
        }
        
        if (record.getGgjc() != null) {
            SET("GGJC = #{record.ggjc,jdbcType=VARCHAR}");
        }
        
        if (record.getHshtc() != null) {
            SET("HSHTC = #{record.hshtc,jdbcType=VARCHAR}");
        }
        
        if (record.getJp1tc() != null) {
            SET("JP1TC = #{record.jp1tc,jdbcType=VARCHAR}");
        }
        
        if (record.getJp2tc() != null) {
            SET("JP2TC = #{record.jp2tc,jdbcType=VARCHAR}");
        }
        
        if (record.getJp3tc() != null) {
            SET("JP3TC = #{record.jp3tc,jdbcType=VARCHAR}");
        }
        
        if (record.getJp4tc() != null) {
            SET("JP4TC = #{record.jp4tc,jdbcType=VARCHAR}");
        }
        
        if (record.getCdpd() != null) {
            SET("CDPD = #{record.cdpd,jdbcType=VARCHAR}");
        }
        
        if (record.getPass1() != null) {
            SET("PASS1 = #{record.pass1,jdbcType=VARCHAR}");
        }
        
        if (record.getDummy11() != null) {
            SET("DUMMY11 = #{record.dummy11,jdbcType=VARCHAR}");
        }
        
        if (record.getDummy12() != null) {
            SET("DUMMY12 = #{record.dummy12,jdbcType=VARCHAR}");
        }
        
        if (record.getUpdateDate() != null) {
            SET("UPDATE_DATE = #{record.updateDate,jdbcType=TIMESTAMP}");
        }
        
        if (record.getPgmVer() != null) {
            SET("PGM_VER = #{record.pgmVer,jdbcType=VARCHAR}");
        }
        
        if (record.getInCheck() != null) {
            SET("IN_CHECK = #{record.inCheck,jdbcType=VARCHAR}");
        }
        
        if (record.getOutCheck() != null) {
            SET("OUT_CHECK = #{record.outCheck,jdbcType=VARCHAR}");
        }
        
        if (record.getInCash5() != null) {
            SET("IN_CASH_5 = #{record.inCash5,jdbcType=VARCHAR}");
        }
        
        if (record.getInCash10() != null) {
            SET("IN_CASH_10 = #{record.inCash10,jdbcType=VARCHAR}");
        }
        
        if (record.getRemMoney() != null) {
            SET("REM_MONEY = #{record.remMoney,jdbcType=VARCHAR}");
        }
        
        if (record.getRpc() != null) {
            SET("RPC = #{record.rpc,jdbcType=VARCHAR}");
        }
        
        applyWhere(spec, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_CT_NICE_MNG
     *
     * @mbggenerated Wed Jul 23 18:33:21 KST 2014
     */
    public String updateBySpec(Map<String, Object> parameter) {
        BEGIN();
        UPDATE("OP.T_CT_NICE_MNG");
        
        SET("J_DATE = #{record.jDate,jdbcType=VARCHAR}");
        SET("J_TIME = #{record.jTime,jdbcType=VARCHAR}");
        SET("MAC_NO = #{record.macNo,jdbcType=VARCHAR}");
        SET("NET_S = #{record.netS,jdbcType=VARCHAR}");
        SET("STAT = #{record.stat,jdbcType=VARCHAR}");
        SET("POWER_FAIL = #{record.powerFail,jdbcType=VARCHAR}");
        SET("JP1 = #{record.jp1,jdbcType=VARCHAR}");
        SET("JP2 = #{record.jp2,jdbcType=VARCHAR}");
        SET("JP3 = #{record.jp3,jdbcType=VARCHAR}");
        SET("JP4 = #{record.jp4,jdbcType=VARCHAR}");
        SET("HSH = #{record.hsh,jdbcType=VARCHAR}");
        SET("MSP1 = #{record.msp1,jdbcType=VARCHAR}");
        SET("GSY1 = #{record.gsy1,jdbcType=VARCHAR}");
        SET("DUMMY1 = #{record.dummy1,jdbcType=VARCHAR}");
        SET("DUMMY2 = #{record.dummy2,jdbcType=VARCHAR}");
        SET("DUMMY3 = #{record.dummy3,jdbcType=VARCHAR}");
        SET("DUMMY4 = #{record.dummy4,jdbcType=VARCHAR}");
        SET("DUMMY5 = #{record.dummy5,jdbcType=VARCHAR}");
        SET("DUMMY6 = #{record.dummy6,jdbcType=VARCHAR}");
        SET("DUMMY7 = #{record.dummy7,jdbcType=VARCHAR}");
        SET("DUMMY8 = #{record.dummy8,jdbcType=VARCHAR}");
        SET("NET_ERR = #{record.netErr,jdbcType=VARCHAR}");
        SET("JPBC = #{record.jpbc,jdbcType=VARCHAR}");
        SET("KDPD = #{record.kdpd,jdbcType=VARCHAR}");
        SET("MSPY = #{record.mspy,jdbcType=VARCHAR}");
        SET("GSYJ = #{record.gsyj,jdbcType=VARCHAR}");
        SET("IG1 = #{record.ig1,jdbcType=VARCHAR}");
        SET("IG2 = #{record.ig2,jdbcType=VARCHAR}");
        SET("IG3 = #{record.ig3,jdbcType=VARCHAR}");
        SET("IG4 = #{record.ig4,jdbcType=VARCHAR}");
        SET("IG5 = #{record.ig5,jdbcType=VARCHAR}");
        SET("PASS_MAC = #{record.passMac,jdbcType=VARCHAR}");
        SET("JP_MSC = #{record.jpMsc,jdbcType=VARCHAR}");
        SET("DUMMY9 = #{record.dummy9,jdbcType=VARCHAR}");
        SET("DGI = #{record.dgi,jdbcType=VARCHAR}");
        SET("DUMMY10 = #{record.dummy10,jdbcType=VARCHAR}");
        SET("TERM_MODE = #{record.termMode,jdbcType=VARCHAR}");
        SET("GGGP = #{record.gggp,jdbcType=VARCHAR}");
        SET("GGJG = #{record.ggjg,jdbcType=VARCHAR}");
        SET("GGJD = #{record.ggjd,jdbcType=VARCHAR}");
        SET("GGYGJ = #{record.ggygj,jdbcType=VARCHAR}");
        SET("GGJC = #{record.ggjc,jdbcType=VARCHAR}");
        SET("HSHTC = #{record.hshtc,jdbcType=VARCHAR}");
        SET("JP1TC = #{record.jp1tc,jdbcType=VARCHAR}");
        SET("JP2TC = #{record.jp2tc,jdbcType=VARCHAR}");
        SET("JP3TC = #{record.jp3tc,jdbcType=VARCHAR}");
        SET("JP4TC = #{record.jp4tc,jdbcType=VARCHAR}");
        SET("CDPD = #{record.cdpd,jdbcType=VARCHAR}");
        SET("PASS1 = #{record.pass1,jdbcType=VARCHAR}");
        SET("DUMMY11 = #{record.dummy11,jdbcType=VARCHAR}");
        SET("DUMMY12 = #{record.dummy12,jdbcType=VARCHAR}");
        SET("UPDATE_DATE = #{record.updateDate,jdbcType=TIMESTAMP}");
        SET("PGM_VER = #{record.pgmVer,jdbcType=VARCHAR}");
        SET("IN_CHECK = #{record.inCheck,jdbcType=VARCHAR}");
        SET("OUT_CHECK = #{record.outCheck,jdbcType=VARCHAR}");
        SET("IN_CASH_5 = #{record.inCash5,jdbcType=VARCHAR}");
        SET("IN_CASH_10 = #{record.inCash10,jdbcType=VARCHAR}");
        SET("REM_MONEY = #{record.remMoney,jdbcType=VARCHAR}");
        SET("RPC = #{record.rpc,jdbcType=VARCHAR}");
        
        TCtNiceMngSpec spec = (TCtNiceMngSpec) parameter.get("spec");
        applyWhere(spec, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_CT_NICE_MNG
     *
     * @mbggenerated Wed Jul 23 18:33:21 KST 2014
     */
    public String updateByPrimaryKeySelective(TCtNiceMng record) {
        BEGIN();
        UPDATE("OP.T_CT_NICE_MNG");
        
        if (record.getStat() != null) {
            SET("STAT = #{stat,jdbcType=VARCHAR}");
        }
        
        if (record.getPowerFail() != null) {
            SET("POWER_FAIL = #{powerFail,jdbcType=VARCHAR}");
        }
        
        if (record.getJp1() != null) {
            SET("JP1 = #{jp1,jdbcType=VARCHAR}");
        }
        
        if (record.getJp2() != null) {
            SET("JP2 = #{jp2,jdbcType=VARCHAR}");
        }
        
        if (record.getJp3() != null) {
            SET("JP3 = #{jp3,jdbcType=VARCHAR}");
        }
        
        if (record.getJp4() != null) {
            SET("JP4 = #{jp4,jdbcType=VARCHAR}");
        }
        
        if (record.getHsh() != null) {
            SET("HSH = #{hsh,jdbcType=VARCHAR}");
        }
        
        if (record.getMsp1() != null) {
            SET("MSP1 = #{msp1,jdbcType=VARCHAR}");
        }
        
        if (record.getGsy1() != null) {
            SET("GSY1 = #{gsy1,jdbcType=VARCHAR}");
        }
        
        if (record.getDummy1() != null) {
            SET("DUMMY1 = #{dummy1,jdbcType=VARCHAR}");
        }
        
        if (record.getDummy2() != null) {
            SET("DUMMY2 = #{dummy2,jdbcType=VARCHAR}");
        }
        
        if (record.getDummy3() != null) {
            SET("DUMMY3 = #{dummy3,jdbcType=VARCHAR}");
        }
        
        if (record.getDummy4() != null) {
            SET("DUMMY4 = #{dummy4,jdbcType=VARCHAR}");
        }
        
        if (record.getDummy5() != null) {
            SET("DUMMY5 = #{dummy5,jdbcType=VARCHAR}");
        }
        
        if (record.getDummy6() != null) {
            SET("DUMMY6 = #{dummy6,jdbcType=VARCHAR}");
        }
        
        if (record.getDummy7() != null) {
            SET("DUMMY7 = #{dummy7,jdbcType=VARCHAR}");
        }
        
        if (record.getDummy8() != null) {
            SET("DUMMY8 = #{dummy8,jdbcType=VARCHAR}");
        }
        
        if (record.getNetErr() != null) {
            SET("NET_ERR = #{netErr,jdbcType=VARCHAR}");
        }
        
        if (record.getJpbc() != null) {
            SET("JPBC = #{jpbc,jdbcType=VARCHAR}");
        }
        
        if (record.getKdpd() != null) {
            SET("KDPD = #{kdpd,jdbcType=VARCHAR}");
        }
        
        if (record.getMspy() != null) {
            SET("MSPY = #{mspy,jdbcType=VARCHAR}");
        }
        
        if (record.getGsyj() != null) {
            SET("GSYJ = #{gsyj,jdbcType=VARCHAR}");
        }
        
        if (record.getIg1() != null) {
            SET("IG1 = #{ig1,jdbcType=VARCHAR}");
        }
        
        if (record.getIg2() != null) {
            SET("IG2 = #{ig2,jdbcType=VARCHAR}");
        }
        
        if (record.getIg3() != null) {
            SET("IG3 = #{ig3,jdbcType=VARCHAR}");
        }
        
        if (record.getIg4() != null) {
            SET("IG4 = #{ig4,jdbcType=VARCHAR}");
        }
        
        if (record.getIg5() != null) {
            SET("IG5 = #{ig5,jdbcType=VARCHAR}");
        }
        
        if (record.getPassMac() != null) {
            SET("PASS_MAC = #{passMac,jdbcType=VARCHAR}");
        }
        
        if (record.getJpMsc() != null) {
            SET("JP_MSC = #{jpMsc,jdbcType=VARCHAR}");
        }
        
        if (record.getDummy9() != null) {
            SET("DUMMY9 = #{dummy9,jdbcType=VARCHAR}");
        }
        
        if (record.getDgi() != null) {
            SET("DGI = #{dgi,jdbcType=VARCHAR}");
        }
        
        if (record.getDummy10() != null) {
            SET("DUMMY10 = #{dummy10,jdbcType=VARCHAR}");
        }
        
        if (record.getTermMode() != null) {
            SET("TERM_MODE = #{termMode,jdbcType=VARCHAR}");
        }
        
        if (record.getGggp() != null) {
            SET("GGGP = #{gggp,jdbcType=VARCHAR}");
        }
        
        if (record.getGgjg() != null) {
            SET("GGJG = #{ggjg,jdbcType=VARCHAR}");
        }
        
        if (record.getGgjd() != null) {
            SET("GGJD = #{ggjd,jdbcType=VARCHAR}");
        }
        
        if (record.getGgygj() != null) {
            SET("GGYGJ = #{ggygj,jdbcType=VARCHAR}");
        }
        
        if (record.getGgjc() != null) {
            SET("GGJC = #{ggjc,jdbcType=VARCHAR}");
        }
        
        if (record.getHshtc() != null) {
            SET("HSHTC = #{hshtc,jdbcType=VARCHAR}");
        }
        
        if (record.getJp1tc() != null) {
            SET("JP1TC = #{jp1tc,jdbcType=VARCHAR}");
        }
        
        if (record.getJp2tc() != null) {
            SET("JP2TC = #{jp2tc,jdbcType=VARCHAR}");
        }
        
        if (record.getJp3tc() != null) {
            SET("JP3TC = #{jp3tc,jdbcType=VARCHAR}");
        }
        
        if (record.getJp4tc() != null) {
            SET("JP4TC = #{jp4tc,jdbcType=VARCHAR}");
        }
        
        if (record.getCdpd() != null) {
            SET("CDPD = #{cdpd,jdbcType=VARCHAR}");
        }
        
        if (record.getPass1() != null) {
            SET("PASS1 = #{pass1,jdbcType=VARCHAR}");
        }
        
        if (record.getDummy11() != null) {
            SET("DUMMY11 = #{dummy11,jdbcType=VARCHAR}");
        }
        
        if (record.getDummy12() != null) {
            SET("DUMMY12 = #{dummy12,jdbcType=VARCHAR}");
        }
        
        if (record.getUpdateDate() != null) {
            SET("UPDATE_DATE = #{updateDate,jdbcType=TIMESTAMP}");
        }
        
        if (record.getPgmVer() != null) {
            SET("PGM_VER = #{pgmVer,jdbcType=VARCHAR}");
        }
        
        if (record.getInCheck() != null) {
            SET("IN_CHECK = #{inCheck,jdbcType=VARCHAR}");
        }
        
        if (record.getOutCheck() != null) {
            SET("OUT_CHECK = #{outCheck,jdbcType=VARCHAR}");
        }
        
        if (record.getInCash5() != null) {
            SET("IN_CASH_5 = #{inCash5,jdbcType=VARCHAR}");
        }
        
        if (record.getInCash10() != null) {
            SET("IN_CASH_10 = #{inCash10,jdbcType=VARCHAR}");
        }
        
        if (record.getRemMoney() != null) {
            SET("REM_MONEY = #{remMoney,jdbcType=VARCHAR}");
        }
        
        if (record.getRpc() != null) {
            SET("RPC = #{rpc,jdbcType=VARCHAR}");
        }
        
        WHERE("J_DATE = #{jDate,jdbcType=VARCHAR}");
        WHERE("J_TIME = #{jTime,jdbcType=VARCHAR}");
        WHERE("MAC_NO = #{macNo,jdbcType=VARCHAR}");
        WHERE("NET_S = #{netS,jdbcType=VARCHAR}");
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_CT_NICE_MNG
     *
     * @mbggenerated Wed Jul 23 18:33:21 KST 2014
     */
    protected void applyWhere(TCtNiceMngSpec spec, boolean includeSpecPhrase) {
        if (spec == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeSpecPhrase) {
            parmPhrase1 = "%s #{spec.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{spec.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{spec.oredCriteria[%d].allCriteria[%d].value} and #{spec.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{spec.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{spec.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{spec.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{spec.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = spec.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            WHERE(sb.toString());
        }
    }
}