package com.nicetcm.nibsplus.broker.msg.model;

public class TCmCommonKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OP.T_CM_COMMON.LARGE_CD
     *
     * @mbggenerated Tue Jun 24 10:40:32 KST 2014
     */
    private String largeCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OP.T_CM_COMMON.SMALL_CD
     *
     * @mbggenerated Tue Jun 24 10:40:32 KST 2014
     */
    private String smallCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OP.T_CM_COMMON.CD_NM
     *
     * @mbggenerated Tue Jun 24 10:40:32 KST 2014
     */
    private String cdNm;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OP.T_CM_COMMON.LARGE_CD
     *
     * @return the value of OP.T_CM_COMMON.LARGE_CD
     *
     * @mbggenerated Tue Jun 24 10:40:32 KST 2014
     */
    public String getLargeCd() {
        return largeCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OP.T_CM_COMMON.LARGE_CD
     *
     * @param largeCd the value for OP.T_CM_COMMON.LARGE_CD
     *
     * @mbggenerated Tue Jun 24 10:40:32 KST 2014
     */
    public void setLargeCd(String largeCd) {
        this.largeCd = largeCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OP.T_CM_COMMON.SMALL_CD
     *
     * @return the value of OP.T_CM_COMMON.SMALL_CD
     *
     * @mbggenerated Tue Jun 24 10:40:32 KST 2014
     */
    public String getSmallCd() {
        return smallCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OP.T_CM_COMMON.SMALL_CD
     *
     * @param smallCd the value for OP.T_CM_COMMON.SMALL_CD
     *
     * @mbggenerated Tue Jun 24 10:40:32 KST 2014
     */
    public void setSmallCd(String smallCd) {
        this.smallCd = smallCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OP.T_CM_COMMON.CD_NM
     *
     * @return the value of OP.T_CM_COMMON.CD_NM
     *
     * @mbggenerated Tue Jun 24 10:40:32 KST 2014
     */
    public String getCdNm() {
        return cdNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OP.T_CM_COMMON.CD_NM
     *
     * @param cdNm the value for OP.T_CM_COMMON.CD_NM
     *
     * @mbggenerated Tue Jun 24 10:40:32 KST 2014
     */
    public void setCdNm(String cdNm) {
        this.cdNm = cdNm;
    }
}