package com.nicetcm.nibsplus.broker.msg.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TFnElandCouponSpec {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table OP.T_FN_ELAND_COUPON
     *
     * @mbggenerated Thu Jul 31 14:31:01 KST 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table OP.T_FN_ELAND_COUPON
     *
     * @mbggenerated Thu Jul 31 14:31:01 KST 2014
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table OP.T_FN_ELAND_COUPON
     *
     * @mbggenerated Thu Jul 31 14:31:01 KST 2014
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_ELAND_COUPON
     *
     * @mbggenerated Thu Jul 31 14:31:01 KST 2014
     */
    public TFnElandCouponSpec() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_ELAND_COUPON
     *
     * @mbggenerated Thu Jul 31 14:31:01 KST 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_ELAND_COUPON
     *
     * @mbggenerated Thu Jul 31 14:31:01 KST 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_ELAND_COUPON
     *
     * @mbggenerated Thu Jul 31 14:31:01 KST 2014
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_ELAND_COUPON
     *
     * @mbggenerated Thu Jul 31 14:31:01 KST 2014
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_ELAND_COUPON
     *
     * @mbggenerated Thu Jul 31 14:31:01 KST 2014
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_ELAND_COUPON
     *
     * @mbggenerated Thu Jul 31 14:31:01 KST 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_ELAND_COUPON
     *
     * @mbggenerated Thu Jul 31 14:31:01 KST 2014
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_ELAND_COUPON
     *
     * @mbggenerated Thu Jul 31 14:31:01 KST 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_ELAND_COUPON
     *
     * @mbggenerated Thu Jul 31 14:31:01 KST 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_ELAND_COUPON
     *
     * @mbggenerated Thu Jul 31 14:31:01 KST 2014
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table OP.T_FN_ELAND_COUPON
     *
     * @mbggenerated Thu Jul 31 14:31:01 KST 2014
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andDealDateIsNull() {
            addCriterion("DEAL_DATE is null");
            return (Criteria) this;
        }

        public Criteria andDealDateIsNotNull() {
            addCriterion("DEAL_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andDealDateEqualTo(String value) {
            addCriterion("DEAL_DATE =", value, "dealDate");
            return (Criteria) this;
        }

        public Criteria andDealDateNotEqualTo(String value) {
            addCriterion("DEAL_DATE <>", value, "dealDate");
            return (Criteria) this;
        }

        public Criteria andDealDateGreaterThan(String value) {
            addCriterion("DEAL_DATE >", value, "dealDate");
            return (Criteria) this;
        }

        public Criteria andDealDateGreaterThanOrEqualTo(String value) {
            addCriterion("DEAL_DATE >=", value, "dealDate");
            return (Criteria) this;
        }

        public Criteria andDealDateLessThan(String value) {
            addCriterion("DEAL_DATE <", value, "dealDate");
            return (Criteria) this;
        }

        public Criteria andDealDateLessThanOrEqualTo(String value) {
            addCriterion("DEAL_DATE <=", value, "dealDate");
            return (Criteria) this;
        }

        public Criteria andDealDateLike(String value) {
            addCriterion("DEAL_DATE like", value, "dealDate");
            return (Criteria) this;
        }

        public Criteria andDealDateNotLike(String value) {
            addCriterion("DEAL_DATE not like", value, "dealDate");
            return (Criteria) this;
        }

        public Criteria andDealDateIn(List<String> values) {
            addCriterion("DEAL_DATE in", values, "dealDate");
            return (Criteria) this;
        }

        public Criteria andDealDateNotIn(List<String> values) {
            addCriterion("DEAL_DATE not in", values, "dealDate");
            return (Criteria) this;
        }

        public Criteria andDealDateBetween(String value1, String value2) {
            addCriterion("DEAL_DATE between", value1, value2, "dealDate");
            return (Criteria) this;
        }

        public Criteria andDealDateNotBetween(String value1, String value2) {
            addCriterion("DEAL_DATE not between", value1, value2, "dealDate");
            return (Criteria) this;
        }

        public Criteria andBranchCdIsNull() {
            addCriterion("BRANCH_CD is null");
            return (Criteria) this;
        }

        public Criteria andBranchCdIsNotNull() {
            addCriterion("BRANCH_CD is not null");
            return (Criteria) this;
        }

        public Criteria andBranchCdEqualTo(String value) {
            addCriterion("BRANCH_CD =", value, "branchCd");
            return (Criteria) this;
        }

        public Criteria andBranchCdNotEqualTo(String value) {
            addCriterion("BRANCH_CD <>", value, "branchCd");
            return (Criteria) this;
        }

        public Criteria andBranchCdGreaterThan(String value) {
            addCriterion("BRANCH_CD >", value, "branchCd");
            return (Criteria) this;
        }

        public Criteria andBranchCdGreaterThanOrEqualTo(String value) {
            addCriterion("BRANCH_CD >=", value, "branchCd");
            return (Criteria) this;
        }

        public Criteria andBranchCdLessThan(String value) {
            addCriterion("BRANCH_CD <", value, "branchCd");
            return (Criteria) this;
        }

        public Criteria andBranchCdLessThanOrEqualTo(String value) {
            addCriterion("BRANCH_CD <=", value, "branchCd");
            return (Criteria) this;
        }

        public Criteria andBranchCdLike(String value) {
            addCriterion("BRANCH_CD like", value, "branchCd");
            return (Criteria) this;
        }

        public Criteria andBranchCdNotLike(String value) {
            addCriterion("BRANCH_CD not like", value, "branchCd");
            return (Criteria) this;
        }

        public Criteria andBranchCdIn(List<String> values) {
            addCriterion("BRANCH_CD in", values, "branchCd");
            return (Criteria) this;
        }

        public Criteria andBranchCdNotIn(List<String> values) {
            addCriterion("BRANCH_CD not in", values, "branchCd");
            return (Criteria) this;
        }

        public Criteria andBranchCdBetween(String value1, String value2) {
            addCriterion("BRANCH_CD between", value1, value2, "branchCd");
            return (Criteria) this;
        }

        public Criteria andBranchCdNotBetween(String value1, String value2) {
            addCriterion("BRANCH_CD not between", value1, value2, "branchCd");
            return (Criteria) this;
        }

        public Criteria andCouponCdIsNull() {
            addCriterion("COUPON_CD is null");
            return (Criteria) this;
        }

        public Criteria andCouponCdIsNotNull() {
            addCriterion("COUPON_CD is not null");
            return (Criteria) this;
        }

        public Criteria andCouponCdEqualTo(String value) {
            addCriterion("COUPON_CD =", value, "couponCd");
            return (Criteria) this;
        }

        public Criteria andCouponCdNotEqualTo(String value) {
            addCriterion("COUPON_CD <>", value, "couponCd");
            return (Criteria) this;
        }

        public Criteria andCouponCdGreaterThan(String value) {
            addCriterion("COUPON_CD >", value, "couponCd");
            return (Criteria) this;
        }

        public Criteria andCouponCdGreaterThanOrEqualTo(String value) {
            addCriterion("COUPON_CD >=", value, "couponCd");
            return (Criteria) this;
        }

        public Criteria andCouponCdLessThan(String value) {
            addCriterion("COUPON_CD <", value, "couponCd");
            return (Criteria) this;
        }

        public Criteria andCouponCdLessThanOrEqualTo(String value) {
            addCriterion("COUPON_CD <=", value, "couponCd");
            return (Criteria) this;
        }

        public Criteria andCouponCdLike(String value) {
            addCriterion("COUPON_CD like", value, "couponCd");
            return (Criteria) this;
        }

        public Criteria andCouponCdNotLike(String value) {
            addCriterion("COUPON_CD not like", value, "couponCd");
            return (Criteria) this;
        }

        public Criteria andCouponCdIn(List<String> values) {
            addCriterion("COUPON_CD in", values, "couponCd");
            return (Criteria) this;
        }

        public Criteria andCouponCdNotIn(List<String> values) {
            addCriterion("COUPON_CD not in", values, "couponCd");
            return (Criteria) this;
        }

        public Criteria andCouponCdBetween(String value1, String value2) {
            addCriterion("COUPON_CD between", value1, value2, "couponCd");
            return (Criteria) this;
        }

        public Criteria andCouponCdNotBetween(String value1, String value2) {
            addCriterion("COUPON_CD not between", value1, value2, "couponCd");
            return (Criteria) this;
        }

        public Criteria andVolumeCdIsNull() {
            addCriterion("VOLUME_CD is null");
            return (Criteria) this;
        }

        public Criteria andVolumeCdIsNotNull() {
            addCriterion("VOLUME_CD is not null");
            return (Criteria) this;
        }

        public Criteria andVolumeCdEqualTo(String value) {
            addCriterion("VOLUME_CD =", value, "volumeCd");
            return (Criteria) this;
        }

        public Criteria andVolumeCdNotEqualTo(String value) {
            addCriterion("VOLUME_CD <>", value, "volumeCd");
            return (Criteria) this;
        }

        public Criteria andVolumeCdGreaterThan(String value) {
            addCriterion("VOLUME_CD >", value, "volumeCd");
            return (Criteria) this;
        }

        public Criteria andVolumeCdGreaterThanOrEqualTo(String value) {
            addCriterion("VOLUME_CD >=", value, "volumeCd");
            return (Criteria) this;
        }

        public Criteria andVolumeCdLessThan(String value) {
            addCriterion("VOLUME_CD <", value, "volumeCd");
            return (Criteria) this;
        }

        public Criteria andVolumeCdLessThanOrEqualTo(String value) {
            addCriterion("VOLUME_CD <=", value, "volumeCd");
            return (Criteria) this;
        }

        public Criteria andVolumeCdLike(String value) {
            addCriterion("VOLUME_CD like", value, "volumeCd");
            return (Criteria) this;
        }

        public Criteria andVolumeCdNotLike(String value) {
            addCriterion("VOLUME_CD not like", value, "volumeCd");
            return (Criteria) this;
        }

        public Criteria andVolumeCdIn(List<String> values) {
            addCriterion("VOLUME_CD in", values, "volumeCd");
            return (Criteria) this;
        }

        public Criteria andVolumeCdNotIn(List<String> values) {
            addCriterion("VOLUME_CD not in", values, "volumeCd");
            return (Criteria) this;
        }

        public Criteria andVolumeCdBetween(String value1, String value2) {
            addCriterion("VOLUME_CD between", value1, value2, "volumeCd");
            return (Criteria) this;
        }

        public Criteria andVolumeCdNotBetween(String value1, String value2) {
            addCriterion("VOLUME_CD not between", value1, value2, "volumeCd");
            return (Criteria) this;
        }

        public Criteria andQuantityIsNull() {
            addCriterion("QUANTITY is null");
            return (Criteria) this;
        }

        public Criteria andQuantityIsNotNull() {
            addCriterion("QUANTITY is not null");
            return (Criteria) this;
        }

        public Criteria andQuantityEqualTo(Short value) {
            addCriterion("QUANTITY =", value, "quantity");
            return (Criteria) this;
        }

        public Criteria andQuantityNotEqualTo(Short value) {
            addCriterion("QUANTITY <>", value, "quantity");
            return (Criteria) this;
        }

        public Criteria andQuantityGreaterThan(Short value) {
            addCriterion("QUANTITY >", value, "quantity");
            return (Criteria) this;
        }

        public Criteria andQuantityGreaterThanOrEqualTo(Short value) {
            addCriterion("QUANTITY >=", value, "quantity");
            return (Criteria) this;
        }

        public Criteria andQuantityLessThan(Short value) {
            addCriterion("QUANTITY <", value, "quantity");
            return (Criteria) this;
        }

        public Criteria andQuantityLessThanOrEqualTo(Short value) {
            addCriterion("QUANTITY <=", value, "quantity");
            return (Criteria) this;
        }

        public Criteria andQuantityIn(List<Short> values) {
            addCriterion("QUANTITY in", values, "quantity");
            return (Criteria) this;
        }

        public Criteria andQuantityNotIn(List<Short> values) {
            addCriterion("QUANTITY not in", values, "quantity");
            return (Criteria) this;
        }

        public Criteria andQuantityBetween(Short value1, Short value2) {
            addCriterion("QUANTITY between", value1, value2, "quantity");
            return (Criteria) this;
        }

        public Criteria andQuantityNotBetween(Short value1, Short value2) {
            addCriterion("QUANTITY not between", value1, value2, "quantity");
            return (Criteria) this;
        }

        public Criteria andConfirmIsNull() {
            addCriterion("CONFIRM is null");
            return (Criteria) this;
        }

        public Criteria andConfirmIsNotNull() {
            addCriterion("CONFIRM is not null");
            return (Criteria) this;
        }

        public Criteria andConfirmEqualTo(String value) {
            addCriterion("CONFIRM =", value, "confirm");
            return (Criteria) this;
        }

        public Criteria andConfirmNotEqualTo(String value) {
            addCriterion("CONFIRM <>", value, "confirm");
            return (Criteria) this;
        }

        public Criteria andConfirmGreaterThan(String value) {
            addCriterion("CONFIRM >", value, "confirm");
            return (Criteria) this;
        }

        public Criteria andConfirmGreaterThanOrEqualTo(String value) {
            addCriterion("CONFIRM >=", value, "confirm");
            return (Criteria) this;
        }

        public Criteria andConfirmLessThan(String value) {
            addCriterion("CONFIRM <", value, "confirm");
            return (Criteria) this;
        }

        public Criteria andConfirmLessThanOrEqualTo(String value) {
            addCriterion("CONFIRM <=", value, "confirm");
            return (Criteria) this;
        }

        public Criteria andConfirmLike(String value) {
            addCriterion("CONFIRM like", value, "confirm");
            return (Criteria) this;
        }

        public Criteria andConfirmNotLike(String value) {
            addCriterion("CONFIRM not like", value, "confirm");
            return (Criteria) this;
        }

        public Criteria andConfirmIn(List<String> values) {
            addCriterion("CONFIRM in", values, "confirm");
            return (Criteria) this;
        }

        public Criteria andConfirmNotIn(List<String> values) {
            addCriterion("CONFIRM not in", values, "confirm");
            return (Criteria) this;
        }

        public Criteria andConfirmBetween(String value1, String value2) {
            addCriterion("CONFIRM between", value1, value2, "confirm");
            return (Criteria) this;
        }

        public Criteria andConfirmNotBetween(String value1, String value2) {
            addCriterion("CONFIRM not between", value1, value2, "confirm");
            return (Criteria) this;
        }

        public Criteria andInsertDateIsNull() {
            addCriterion("INSERT_DATE is null");
            return (Criteria) this;
        }

        public Criteria andInsertDateIsNotNull() {
            addCriterion("INSERT_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andInsertDateEqualTo(Date value) {
            addCriterion("INSERT_DATE =", value, "insertDate");
            return (Criteria) this;
        }

        public Criteria andInsertDateNotEqualTo(Date value) {
            addCriterion("INSERT_DATE <>", value, "insertDate");
            return (Criteria) this;
        }

        public Criteria andInsertDateGreaterThan(Date value) {
            addCriterion("INSERT_DATE >", value, "insertDate");
            return (Criteria) this;
        }

        public Criteria andInsertDateGreaterThanOrEqualTo(Date value) {
            addCriterion("INSERT_DATE >=", value, "insertDate");
            return (Criteria) this;
        }

        public Criteria andInsertDateLessThan(Date value) {
            addCriterion("INSERT_DATE <", value, "insertDate");
            return (Criteria) this;
        }

        public Criteria andInsertDateLessThanOrEqualTo(Date value) {
            addCriterion("INSERT_DATE <=", value, "insertDate");
            return (Criteria) this;
        }

        public Criteria andInsertDateIn(List<Date> values) {
            addCriterion("INSERT_DATE in", values, "insertDate");
            return (Criteria) this;
        }

        public Criteria andInsertDateNotIn(List<Date> values) {
            addCriterion("INSERT_DATE not in", values, "insertDate");
            return (Criteria) this;
        }

        public Criteria andInsertDateBetween(Date value1, Date value2) {
            addCriterion("INSERT_DATE between", value1, value2, "insertDate");
            return (Criteria) this;
        }

        public Criteria andInsertDateNotBetween(Date value1, Date value2) {
            addCriterion("INSERT_DATE not between", value1, value2, "insertDate");
            return (Criteria) this;
        }

        public Criteria andInsertUidIsNull() {
            addCriterion("INSERT_UID is null");
            return (Criteria) this;
        }

        public Criteria andInsertUidIsNotNull() {
            addCriterion("INSERT_UID is not null");
            return (Criteria) this;
        }

        public Criteria andInsertUidEqualTo(String value) {
            addCriterion("INSERT_UID =", value, "insertUid");
            return (Criteria) this;
        }

        public Criteria andInsertUidNotEqualTo(String value) {
            addCriterion("INSERT_UID <>", value, "insertUid");
            return (Criteria) this;
        }

        public Criteria andInsertUidGreaterThan(String value) {
            addCriterion("INSERT_UID >", value, "insertUid");
            return (Criteria) this;
        }

        public Criteria andInsertUidGreaterThanOrEqualTo(String value) {
            addCriterion("INSERT_UID >=", value, "insertUid");
            return (Criteria) this;
        }

        public Criteria andInsertUidLessThan(String value) {
            addCriterion("INSERT_UID <", value, "insertUid");
            return (Criteria) this;
        }

        public Criteria andInsertUidLessThanOrEqualTo(String value) {
            addCriterion("INSERT_UID <=", value, "insertUid");
            return (Criteria) this;
        }

        public Criteria andInsertUidLike(String value) {
            addCriterion("INSERT_UID like", value, "insertUid");
            return (Criteria) this;
        }

        public Criteria andInsertUidNotLike(String value) {
            addCriterion("INSERT_UID not like", value, "insertUid");
            return (Criteria) this;
        }

        public Criteria andInsertUidIn(List<String> values) {
            addCriterion("INSERT_UID in", values, "insertUid");
            return (Criteria) this;
        }

        public Criteria andInsertUidNotIn(List<String> values) {
            addCriterion("INSERT_UID not in", values, "insertUid");
            return (Criteria) this;
        }

        public Criteria andInsertUidBetween(String value1, String value2) {
            addCriterion("INSERT_UID between", value1, value2, "insertUid");
            return (Criteria) this;
        }

        public Criteria andInsertUidNotBetween(String value1, String value2) {
            addCriterion("INSERT_UID not between", value1, value2, "insertUid");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNull() {
            addCriterion("UPDATE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNotNull() {
            addCriterion("UPDATE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateEqualTo(Date value) {
            addCriterion("UPDATE_DATE =", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotEqualTo(Date value) {
            addCriterion("UPDATE_DATE <>", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThan(Date value) {
            addCriterion("UPDATE_DATE >", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDATE_DATE >=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThan(Date value) {
            addCriterion("UPDATE_DATE <", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThanOrEqualTo(Date value) {
            addCriterion("UPDATE_DATE <=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIn(List<Date> values) {
            addCriterion("UPDATE_DATE in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotIn(List<Date> values) {
            addCriterion("UPDATE_DATE not in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateBetween(Date value1, Date value2) {
            addCriterion("UPDATE_DATE between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotBetween(Date value1, Date value2) {
            addCriterion("UPDATE_DATE not between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateUidIsNull() {
            addCriterion("UPDATE_UID is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUidIsNotNull() {
            addCriterion("UPDATE_UID is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUidEqualTo(String value) {
            addCriterion("UPDATE_UID =", value, "updateUid");
            return (Criteria) this;
        }

        public Criteria andUpdateUidNotEqualTo(String value) {
            addCriterion("UPDATE_UID <>", value, "updateUid");
            return (Criteria) this;
        }

        public Criteria andUpdateUidGreaterThan(String value) {
            addCriterion("UPDATE_UID >", value, "updateUid");
            return (Criteria) this;
        }

        public Criteria andUpdateUidGreaterThanOrEqualTo(String value) {
            addCriterion("UPDATE_UID >=", value, "updateUid");
            return (Criteria) this;
        }

        public Criteria andUpdateUidLessThan(String value) {
            addCriterion("UPDATE_UID <", value, "updateUid");
            return (Criteria) this;
        }

        public Criteria andUpdateUidLessThanOrEqualTo(String value) {
            addCriterion("UPDATE_UID <=", value, "updateUid");
            return (Criteria) this;
        }

        public Criteria andUpdateUidLike(String value) {
            addCriterion("UPDATE_UID like", value, "updateUid");
            return (Criteria) this;
        }

        public Criteria andUpdateUidNotLike(String value) {
            addCriterion("UPDATE_UID not like", value, "updateUid");
            return (Criteria) this;
        }

        public Criteria andUpdateUidIn(List<String> values) {
            addCriterion("UPDATE_UID in", values, "updateUid");
            return (Criteria) this;
        }

        public Criteria andUpdateUidNotIn(List<String> values) {
            addCriterion("UPDATE_UID not in", values, "updateUid");
            return (Criteria) this;
        }

        public Criteria andUpdateUidBetween(String value1, String value2) {
            addCriterion("UPDATE_UID between", value1, value2, "updateUid");
            return (Criteria) this;
        }

        public Criteria andUpdateUidNotBetween(String value1, String value2) {
            addCriterion("UPDATE_UID not between", value1, value2, "updateUid");
            return (Criteria) this;
        }

        public Criteria andOrgSendYnIsNull() {
            addCriterion("ORG_SEND_YN is null");
            return (Criteria) this;
        }

        public Criteria andOrgSendYnIsNotNull() {
            addCriterion("ORG_SEND_YN is not null");
            return (Criteria) this;
        }

        public Criteria andOrgSendYnEqualTo(String value) {
            addCriterion("ORG_SEND_YN =", value, "orgSendYn");
            return (Criteria) this;
        }

        public Criteria andOrgSendYnNotEqualTo(String value) {
            addCriterion("ORG_SEND_YN <>", value, "orgSendYn");
            return (Criteria) this;
        }

        public Criteria andOrgSendYnGreaterThan(String value) {
            addCriterion("ORG_SEND_YN >", value, "orgSendYn");
            return (Criteria) this;
        }

        public Criteria andOrgSendYnGreaterThanOrEqualTo(String value) {
            addCriterion("ORG_SEND_YN >=", value, "orgSendYn");
            return (Criteria) this;
        }

        public Criteria andOrgSendYnLessThan(String value) {
            addCriterion("ORG_SEND_YN <", value, "orgSendYn");
            return (Criteria) this;
        }

        public Criteria andOrgSendYnLessThanOrEqualTo(String value) {
            addCriterion("ORG_SEND_YN <=", value, "orgSendYn");
            return (Criteria) this;
        }

        public Criteria andOrgSendYnLike(String value) {
            addCriterion("ORG_SEND_YN like", value, "orgSendYn");
            return (Criteria) this;
        }

        public Criteria andOrgSendYnNotLike(String value) {
            addCriterion("ORG_SEND_YN not like", value, "orgSendYn");
            return (Criteria) this;
        }

        public Criteria andOrgSendYnIn(List<String> values) {
            addCriterion("ORG_SEND_YN in", values, "orgSendYn");
            return (Criteria) this;
        }

        public Criteria andOrgSendYnNotIn(List<String> values) {
            addCriterion("ORG_SEND_YN not in", values, "orgSendYn");
            return (Criteria) this;
        }

        public Criteria andOrgSendYnBetween(String value1, String value2) {
            addCriterion("ORG_SEND_YN between", value1, value2, "orgSendYn");
            return (Criteria) this;
        }

        public Criteria andOrgSendYnNotBetween(String value1, String value2) {
            addCriterion("ORG_SEND_YN not between", value1, value2, "orgSendYn");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table OP.T_FN_ELAND_COUPON
     *
     * @mbggenerated do_not_delete_during_merge Thu Jul 31 14:31:01 KST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table OP.T_FN_ELAND_COUPON
     *
     * @mbggenerated Thu Jul 31 14:31:01 KST 2014
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}