package com.nicetcm.nibsplus.broker.msg.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TFnForeigncurrencySpec {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table OP.T_FN_FOREIGNCURRENCY
     *
     * @mbggenerated Mon Jul 28 16:08:07 KST 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table OP.T_FN_FOREIGNCURRENCY
     *
     * @mbggenerated Mon Jul 28 16:08:07 KST 2014
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table OP.T_FN_FOREIGNCURRENCY
     *
     * @mbggenerated Mon Jul 28 16:08:07 KST 2014
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_FOREIGNCURRENCY
     *
     * @mbggenerated Mon Jul 28 16:08:07 KST 2014
     */
    public TFnForeigncurrencySpec() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_FOREIGNCURRENCY
     *
     * @mbggenerated Mon Jul 28 16:08:07 KST 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_FOREIGNCURRENCY
     *
     * @mbggenerated Mon Jul 28 16:08:07 KST 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_FOREIGNCURRENCY
     *
     * @mbggenerated Mon Jul 28 16:08:07 KST 2014
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_FOREIGNCURRENCY
     *
     * @mbggenerated Mon Jul 28 16:08:07 KST 2014
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_FOREIGNCURRENCY
     *
     * @mbggenerated Mon Jul 28 16:08:07 KST 2014
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_FOREIGNCURRENCY
     *
     * @mbggenerated Mon Jul 28 16:08:07 KST 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_FOREIGNCURRENCY
     *
     * @mbggenerated Mon Jul 28 16:08:07 KST 2014
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_FOREIGNCURRENCY
     *
     * @mbggenerated Mon Jul 28 16:08:07 KST 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_FOREIGNCURRENCY
     *
     * @mbggenerated Mon Jul 28 16:08:07 KST 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_FOREIGNCURRENCY
     *
     * @mbggenerated Mon Jul 28 16:08:07 KST 2014
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table OP.T_FN_FOREIGNCURRENCY
     *
     * @mbggenerated Mon Jul 28 16:08:07 KST 2014
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andDepoDateIsNull() {
            addCriterion("DEPO_DATE is null");
            return (Criteria) this;
        }

        public Criteria andDepoDateIsNotNull() {
            addCriterion("DEPO_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andDepoDateEqualTo(String value) {
            addCriterion("DEPO_DATE =", value, "depoDate");
            return (Criteria) this;
        }

        public Criteria andDepoDateNotEqualTo(String value) {
            addCriterion("DEPO_DATE <>", value, "depoDate");
            return (Criteria) this;
        }

        public Criteria andDepoDateGreaterThan(String value) {
            addCriterion("DEPO_DATE >", value, "depoDate");
            return (Criteria) this;
        }

        public Criteria andDepoDateGreaterThanOrEqualTo(String value) {
            addCriterion("DEPO_DATE >=", value, "depoDate");
            return (Criteria) this;
        }

        public Criteria andDepoDateLessThan(String value) {
            addCriterion("DEPO_DATE <", value, "depoDate");
            return (Criteria) this;
        }

        public Criteria andDepoDateLessThanOrEqualTo(String value) {
            addCriterion("DEPO_DATE <=", value, "depoDate");
            return (Criteria) this;
        }

        public Criteria andDepoDateLike(String value) {
            addCriterion("DEPO_DATE like", value, "depoDate");
            return (Criteria) this;
        }

        public Criteria andDepoDateNotLike(String value) {
            addCriterion("DEPO_DATE not like", value, "depoDate");
            return (Criteria) this;
        }

        public Criteria andDepoDateIn(List<String> values) {
            addCriterion("DEPO_DATE in", values, "depoDate");
            return (Criteria) this;
        }

        public Criteria andDepoDateNotIn(List<String> values) {
            addCriterion("DEPO_DATE not in", values, "depoDate");
            return (Criteria) this;
        }

        public Criteria andDepoDateBetween(String value1, String value2) {
            addCriterion("DEPO_DATE between", value1, value2, "depoDate");
            return (Criteria) this;
        }

        public Criteria andDepoDateNotBetween(String value1, String value2) {
            addCriterion("DEPO_DATE not between", value1, value2, "depoDate");
            return (Criteria) this;
        }

        public Criteria andOrgCdIsNull() {
            addCriterion("ORG_CD is null");
            return (Criteria) this;
        }

        public Criteria andOrgCdIsNotNull() {
            addCriterion("ORG_CD is not null");
            return (Criteria) this;
        }

        public Criteria andOrgCdEqualTo(String value) {
            addCriterion("ORG_CD =", value, "orgCd");
            return (Criteria) this;
        }

        public Criteria andOrgCdNotEqualTo(String value) {
            addCriterion("ORG_CD <>", value, "orgCd");
            return (Criteria) this;
        }

        public Criteria andOrgCdGreaterThan(String value) {
            addCriterion("ORG_CD >", value, "orgCd");
            return (Criteria) this;
        }

        public Criteria andOrgCdGreaterThanOrEqualTo(String value) {
            addCriterion("ORG_CD >=", value, "orgCd");
            return (Criteria) this;
        }

        public Criteria andOrgCdLessThan(String value) {
            addCriterion("ORG_CD <", value, "orgCd");
            return (Criteria) this;
        }

        public Criteria andOrgCdLessThanOrEqualTo(String value) {
            addCriterion("ORG_CD <=", value, "orgCd");
            return (Criteria) this;
        }

        public Criteria andOrgCdLike(String value) {
            addCriterion("ORG_CD like", value, "orgCd");
            return (Criteria) this;
        }

        public Criteria andOrgCdNotLike(String value) {
            addCriterion("ORG_CD not like", value, "orgCd");
            return (Criteria) this;
        }

        public Criteria andOrgCdIn(List<String> values) {
            addCriterion("ORG_CD in", values, "orgCd");
            return (Criteria) this;
        }

        public Criteria andOrgCdNotIn(List<String> values) {
            addCriterion("ORG_CD not in", values, "orgCd");
            return (Criteria) this;
        }

        public Criteria andOrgCdBetween(String value1, String value2) {
            addCriterion("ORG_CD between", value1, value2, "orgCd");
            return (Criteria) this;
        }

        public Criteria andOrgCdNotBetween(String value1, String value2) {
            addCriterion("ORG_CD not between", value1, value2, "orgCd");
            return (Criteria) this;
        }

        public Criteria andBranchCdIsNull() {
            addCriterion("BRANCH_CD is null");
            return (Criteria) this;
        }

        public Criteria andBranchCdIsNotNull() {
            addCriterion("BRANCH_CD is not null");
            return (Criteria) this;
        }

        public Criteria andBranchCdEqualTo(String value) {
            addCriterion("BRANCH_CD =", value, "branchCd");
            return (Criteria) this;
        }

        public Criteria andBranchCdNotEqualTo(String value) {
            addCriterion("BRANCH_CD <>", value, "branchCd");
            return (Criteria) this;
        }

        public Criteria andBranchCdGreaterThan(String value) {
            addCriterion("BRANCH_CD >", value, "branchCd");
            return (Criteria) this;
        }

        public Criteria andBranchCdGreaterThanOrEqualTo(String value) {
            addCriterion("BRANCH_CD >=", value, "branchCd");
            return (Criteria) this;
        }

        public Criteria andBranchCdLessThan(String value) {
            addCriterion("BRANCH_CD <", value, "branchCd");
            return (Criteria) this;
        }

        public Criteria andBranchCdLessThanOrEqualTo(String value) {
            addCriterion("BRANCH_CD <=", value, "branchCd");
            return (Criteria) this;
        }

        public Criteria andBranchCdLike(String value) {
            addCriterion("BRANCH_CD like", value, "branchCd");
            return (Criteria) this;
        }

        public Criteria andBranchCdNotLike(String value) {
            addCriterion("BRANCH_CD not like", value, "branchCd");
            return (Criteria) this;
        }

        public Criteria andBranchCdIn(List<String> values) {
            addCriterion("BRANCH_CD in", values, "branchCd");
            return (Criteria) this;
        }

        public Criteria andBranchCdNotIn(List<String> values) {
            addCriterion("BRANCH_CD not in", values, "branchCd");
            return (Criteria) this;
        }

        public Criteria andBranchCdBetween(String value1, String value2) {
            addCriterion("BRANCH_CD between", value1, value2, "branchCd");
            return (Criteria) this;
        }

        public Criteria andBranchCdNotBetween(String value1, String value2) {
            addCriterion("BRANCH_CD not between", value1, value2, "branchCd");
            return (Criteria) this;
        }

        public Criteria andDeptCdIsNull() {
            addCriterion("DEPT_CD is null");
            return (Criteria) this;
        }

        public Criteria andDeptCdIsNotNull() {
            addCriterion("DEPT_CD is not null");
            return (Criteria) this;
        }

        public Criteria andDeptCdEqualTo(String value) {
            addCriterion("DEPT_CD =", value, "deptCd");
            return (Criteria) this;
        }

        public Criteria andDeptCdNotEqualTo(String value) {
            addCriterion("DEPT_CD <>", value, "deptCd");
            return (Criteria) this;
        }

        public Criteria andDeptCdGreaterThan(String value) {
            addCriterion("DEPT_CD >", value, "deptCd");
            return (Criteria) this;
        }

        public Criteria andDeptCdGreaterThanOrEqualTo(String value) {
            addCriterion("DEPT_CD >=", value, "deptCd");
            return (Criteria) this;
        }

        public Criteria andDeptCdLessThan(String value) {
            addCriterion("DEPT_CD <", value, "deptCd");
            return (Criteria) this;
        }

        public Criteria andDeptCdLessThanOrEqualTo(String value) {
            addCriterion("DEPT_CD <=", value, "deptCd");
            return (Criteria) this;
        }

        public Criteria andDeptCdLike(String value) {
            addCriterion("DEPT_CD like", value, "deptCd");
            return (Criteria) this;
        }

        public Criteria andDeptCdNotLike(String value) {
            addCriterion("DEPT_CD not like", value, "deptCd");
            return (Criteria) this;
        }

        public Criteria andDeptCdIn(List<String> values) {
            addCriterion("DEPT_CD in", values, "deptCd");
            return (Criteria) this;
        }

        public Criteria andDeptCdNotIn(List<String> values) {
            addCriterion("DEPT_CD not in", values, "deptCd");
            return (Criteria) this;
        }

        public Criteria andDeptCdBetween(String value1, String value2) {
            addCriterion("DEPT_CD between", value1, value2, "deptCd");
            return (Criteria) this;
        }

        public Criteria andDeptCdNotBetween(String value1, String value2) {
            addCriterion("DEPT_CD not between", value1, value2, "deptCd");
            return (Criteria) this;
        }

        public Criteria andOfficeCdIsNull() {
            addCriterion("OFFICE_CD is null");
            return (Criteria) this;
        }

        public Criteria andOfficeCdIsNotNull() {
            addCriterion("OFFICE_CD is not null");
            return (Criteria) this;
        }

        public Criteria andOfficeCdEqualTo(String value) {
            addCriterion("OFFICE_CD =", value, "officeCd");
            return (Criteria) this;
        }

        public Criteria andOfficeCdNotEqualTo(String value) {
            addCriterion("OFFICE_CD <>", value, "officeCd");
            return (Criteria) this;
        }

        public Criteria andOfficeCdGreaterThan(String value) {
            addCriterion("OFFICE_CD >", value, "officeCd");
            return (Criteria) this;
        }

        public Criteria andOfficeCdGreaterThanOrEqualTo(String value) {
            addCriterion("OFFICE_CD >=", value, "officeCd");
            return (Criteria) this;
        }

        public Criteria andOfficeCdLessThan(String value) {
            addCriterion("OFFICE_CD <", value, "officeCd");
            return (Criteria) this;
        }

        public Criteria andOfficeCdLessThanOrEqualTo(String value) {
            addCriterion("OFFICE_CD <=", value, "officeCd");
            return (Criteria) this;
        }

        public Criteria andOfficeCdLike(String value) {
            addCriterion("OFFICE_CD like", value, "officeCd");
            return (Criteria) this;
        }

        public Criteria andOfficeCdNotLike(String value) {
            addCriterion("OFFICE_CD not like", value, "officeCd");
            return (Criteria) this;
        }

        public Criteria andOfficeCdIn(List<String> values) {
            addCriterion("OFFICE_CD in", values, "officeCd");
            return (Criteria) this;
        }

        public Criteria andOfficeCdNotIn(List<String> values) {
            addCriterion("OFFICE_CD not in", values, "officeCd");
            return (Criteria) this;
        }

        public Criteria andOfficeCdBetween(String value1, String value2) {
            addCriterion("OFFICE_CD between", value1, value2, "officeCd");
            return (Criteria) this;
        }

        public Criteria andOfficeCdNotBetween(String value1, String value2) {
            addCriterion("OFFICE_CD not between", value1, value2, "officeCd");
            return (Criteria) this;
        }

        public Criteria andDepoSdateIsNull() {
            addCriterion("DEPO_SDATE is null");
            return (Criteria) this;
        }

        public Criteria andDepoSdateIsNotNull() {
            addCriterion("DEPO_SDATE is not null");
            return (Criteria) this;
        }

        public Criteria andDepoSdateEqualTo(String value) {
            addCriterion("DEPO_SDATE =", value, "depoSdate");
            return (Criteria) this;
        }

        public Criteria andDepoSdateNotEqualTo(String value) {
            addCriterion("DEPO_SDATE <>", value, "depoSdate");
            return (Criteria) this;
        }

        public Criteria andDepoSdateGreaterThan(String value) {
            addCriterion("DEPO_SDATE >", value, "depoSdate");
            return (Criteria) this;
        }

        public Criteria andDepoSdateGreaterThanOrEqualTo(String value) {
            addCriterion("DEPO_SDATE >=", value, "depoSdate");
            return (Criteria) this;
        }

        public Criteria andDepoSdateLessThan(String value) {
            addCriterion("DEPO_SDATE <", value, "depoSdate");
            return (Criteria) this;
        }

        public Criteria andDepoSdateLessThanOrEqualTo(String value) {
            addCriterion("DEPO_SDATE <=", value, "depoSdate");
            return (Criteria) this;
        }

        public Criteria andDepoSdateLike(String value) {
            addCriterion("DEPO_SDATE like", value, "depoSdate");
            return (Criteria) this;
        }

        public Criteria andDepoSdateNotLike(String value) {
            addCriterion("DEPO_SDATE not like", value, "depoSdate");
            return (Criteria) this;
        }

        public Criteria andDepoSdateIn(List<String> values) {
            addCriterion("DEPO_SDATE in", values, "depoSdate");
            return (Criteria) this;
        }

        public Criteria andDepoSdateNotIn(List<String> values) {
            addCriterion("DEPO_SDATE not in", values, "depoSdate");
            return (Criteria) this;
        }

        public Criteria andDepoSdateBetween(String value1, String value2) {
            addCriterion("DEPO_SDATE between", value1, value2, "depoSdate");
            return (Criteria) this;
        }

        public Criteria andDepoSdateNotBetween(String value1, String value2) {
            addCriterion("DEPO_SDATE not between", value1, value2, "depoSdate");
            return (Criteria) this;
        }

        public Criteria andDepoStimeIsNull() {
            addCriterion("DEPO_STIME is null");
            return (Criteria) this;
        }

        public Criteria andDepoStimeIsNotNull() {
            addCriterion("DEPO_STIME is not null");
            return (Criteria) this;
        }

        public Criteria andDepoStimeEqualTo(String value) {
            addCriterion("DEPO_STIME =", value, "depoStime");
            return (Criteria) this;
        }

        public Criteria andDepoStimeNotEqualTo(String value) {
            addCriterion("DEPO_STIME <>", value, "depoStime");
            return (Criteria) this;
        }

        public Criteria andDepoStimeGreaterThan(String value) {
            addCriterion("DEPO_STIME >", value, "depoStime");
            return (Criteria) this;
        }

        public Criteria andDepoStimeGreaterThanOrEqualTo(String value) {
            addCriterion("DEPO_STIME >=", value, "depoStime");
            return (Criteria) this;
        }

        public Criteria andDepoStimeLessThan(String value) {
            addCriterion("DEPO_STIME <", value, "depoStime");
            return (Criteria) this;
        }

        public Criteria andDepoStimeLessThanOrEqualTo(String value) {
            addCriterion("DEPO_STIME <=", value, "depoStime");
            return (Criteria) this;
        }

        public Criteria andDepoStimeLike(String value) {
            addCriterion("DEPO_STIME like", value, "depoStime");
            return (Criteria) this;
        }

        public Criteria andDepoStimeNotLike(String value) {
            addCriterion("DEPO_STIME not like", value, "depoStime");
            return (Criteria) this;
        }

        public Criteria andDepoStimeIn(List<String> values) {
            addCriterion("DEPO_STIME in", values, "depoStime");
            return (Criteria) this;
        }

        public Criteria andDepoStimeNotIn(List<String> values) {
            addCriterion("DEPO_STIME not in", values, "depoStime");
            return (Criteria) this;
        }

        public Criteria andDepoStimeBetween(String value1, String value2) {
            addCriterion("DEPO_STIME between", value1, value2, "depoStime");
            return (Criteria) this;
        }

        public Criteria andDepoStimeNotBetween(String value1, String value2) {
            addCriterion("DEPO_STIME not between", value1, value2, "depoStime");
            return (Criteria) this;
        }

        public Criteria andDepoEdateIsNull() {
            addCriterion("DEPO_EDATE is null");
            return (Criteria) this;
        }

        public Criteria andDepoEdateIsNotNull() {
            addCriterion("DEPO_EDATE is not null");
            return (Criteria) this;
        }

        public Criteria andDepoEdateEqualTo(String value) {
            addCriterion("DEPO_EDATE =", value, "depoEdate");
            return (Criteria) this;
        }

        public Criteria andDepoEdateNotEqualTo(String value) {
            addCriterion("DEPO_EDATE <>", value, "depoEdate");
            return (Criteria) this;
        }

        public Criteria andDepoEdateGreaterThan(String value) {
            addCriterion("DEPO_EDATE >", value, "depoEdate");
            return (Criteria) this;
        }

        public Criteria andDepoEdateGreaterThanOrEqualTo(String value) {
            addCriterion("DEPO_EDATE >=", value, "depoEdate");
            return (Criteria) this;
        }

        public Criteria andDepoEdateLessThan(String value) {
            addCriterion("DEPO_EDATE <", value, "depoEdate");
            return (Criteria) this;
        }

        public Criteria andDepoEdateLessThanOrEqualTo(String value) {
            addCriterion("DEPO_EDATE <=", value, "depoEdate");
            return (Criteria) this;
        }

        public Criteria andDepoEdateLike(String value) {
            addCriterion("DEPO_EDATE like", value, "depoEdate");
            return (Criteria) this;
        }

        public Criteria andDepoEdateNotLike(String value) {
            addCriterion("DEPO_EDATE not like", value, "depoEdate");
            return (Criteria) this;
        }

        public Criteria andDepoEdateIn(List<String> values) {
            addCriterion("DEPO_EDATE in", values, "depoEdate");
            return (Criteria) this;
        }

        public Criteria andDepoEdateNotIn(List<String> values) {
            addCriterion("DEPO_EDATE not in", values, "depoEdate");
            return (Criteria) this;
        }

        public Criteria andDepoEdateBetween(String value1, String value2) {
            addCriterion("DEPO_EDATE between", value1, value2, "depoEdate");
            return (Criteria) this;
        }

        public Criteria andDepoEdateNotBetween(String value1, String value2) {
            addCriterion("DEPO_EDATE not between", value1, value2, "depoEdate");
            return (Criteria) this;
        }

        public Criteria andDepoEtimeIsNull() {
            addCriterion("DEPO_ETIME is null");
            return (Criteria) this;
        }

        public Criteria andDepoEtimeIsNotNull() {
            addCriterion("DEPO_ETIME is not null");
            return (Criteria) this;
        }

        public Criteria andDepoEtimeEqualTo(String value) {
            addCriterion("DEPO_ETIME =", value, "depoEtime");
            return (Criteria) this;
        }

        public Criteria andDepoEtimeNotEqualTo(String value) {
            addCriterion("DEPO_ETIME <>", value, "depoEtime");
            return (Criteria) this;
        }

        public Criteria andDepoEtimeGreaterThan(String value) {
            addCriterion("DEPO_ETIME >", value, "depoEtime");
            return (Criteria) this;
        }

        public Criteria andDepoEtimeGreaterThanOrEqualTo(String value) {
            addCriterion("DEPO_ETIME >=", value, "depoEtime");
            return (Criteria) this;
        }

        public Criteria andDepoEtimeLessThan(String value) {
            addCriterion("DEPO_ETIME <", value, "depoEtime");
            return (Criteria) this;
        }

        public Criteria andDepoEtimeLessThanOrEqualTo(String value) {
            addCriterion("DEPO_ETIME <=", value, "depoEtime");
            return (Criteria) this;
        }

        public Criteria andDepoEtimeLike(String value) {
            addCriterion("DEPO_ETIME like", value, "depoEtime");
            return (Criteria) this;
        }

        public Criteria andDepoEtimeNotLike(String value) {
            addCriterion("DEPO_ETIME not like", value, "depoEtime");
            return (Criteria) this;
        }

        public Criteria andDepoEtimeIn(List<String> values) {
            addCriterion("DEPO_ETIME in", values, "depoEtime");
            return (Criteria) this;
        }

        public Criteria andDepoEtimeNotIn(List<String> values) {
            addCriterion("DEPO_ETIME not in", values, "depoEtime");
            return (Criteria) this;
        }

        public Criteria andDepoEtimeBetween(String value1, String value2) {
            addCriterion("DEPO_ETIME between", value1, value2, "depoEtime");
            return (Criteria) this;
        }

        public Criteria andDepoEtimeNotBetween(String value1, String value2) {
            addCriterion("DEPO_ETIME not between", value1, value2, "depoEtime");
            return (Criteria) this;
        }

        public Criteria andDollarAmtIsNull() {
            addCriterion("DOLLAR_AMT is null");
            return (Criteria) this;
        }

        public Criteria andDollarAmtIsNotNull() {
            addCriterion("DOLLAR_AMT is not null");
            return (Criteria) this;
        }

        public Criteria andDollarAmtEqualTo(Object value) {
            addCriterion("DOLLAR_AMT =", value, "dollarAmt");
            return (Criteria) this;
        }

        public Criteria andDollarAmtNotEqualTo(Object value) {
            addCriterion("DOLLAR_AMT <>", value, "dollarAmt");
            return (Criteria) this;
        }

        public Criteria andDollarAmtGreaterThan(Object value) {
            addCriterion("DOLLAR_AMT >", value, "dollarAmt");
            return (Criteria) this;
        }

        public Criteria andDollarAmtGreaterThanOrEqualTo(Object value) {
            addCriterion("DOLLAR_AMT >=", value, "dollarAmt");
            return (Criteria) this;
        }

        public Criteria andDollarAmtLessThan(Object value) {
            addCriterion("DOLLAR_AMT <", value, "dollarAmt");
            return (Criteria) this;
        }

        public Criteria andDollarAmtLessThanOrEqualTo(Object value) {
            addCriterion("DOLLAR_AMT <=", value, "dollarAmt");
            return (Criteria) this;
        }

        public Criteria andDollarAmtIn(List<Object> values) {
            addCriterion("DOLLAR_AMT in", values, "dollarAmt");
            return (Criteria) this;
        }

        public Criteria andDollarAmtNotIn(List<Object> values) {
            addCriterion("DOLLAR_AMT not in", values, "dollarAmt");
            return (Criteria) this;
        }

        public Criteria andDollarAmtBetween(Object value1, Object value2) {
            addCriterion("DOLLAR_AMT between", value1, value2, "dollarAmt");
            return (Criteria) this;
        }

        public Criteria andDollarAmtNotBetween(Object value1, Object value2) {
            addCriterion("DOLLAR_AMT not between", value1, value2, "dollarAmt");
            return (Criteria) this;
        }

        public Criteria andEuroAmtIsNull() {
            addCriterion("EURO_AMT is null");
            return (Criteria) this;
        }

        public Criteria andEuroAmtIsNotNull() {
            addCriterion("EURO_AMT is not null");
            return (Criteria) this;
        }

        public Criteria andEuroAmtEqualTo(Object value) {
            addCriterion("EURO_AMT =", value, "euroAmt");
            return (Criteria) this;
        }

        public Criteria andEuroAmtNotEqualTo(Object value) {
            addCriterion("EURO_AMT <>", value, "euroAmt");
            return (Criteria) this;
        }

        public Criteria andEuroAmtGreaterThan(Object value) {
            addCriterion("EURO_AMT >", value, "euroAmt");
            return (Criteria) this;
        }

        public Criteria andEuroAmtGreaterThanOrEqualTo(Object value) {
            addCriterion("EURO_AMT >=", value, "euroAmt");
            return (Criteria) this;
        }

        public Criteria andEuroAmtLessThan(Object value) {
            addCriterion("EURO_AMT <", value, "euroAmt");
            return (Criteria) this;
        }

        public Criteria andEuroAmtLessThanOrEqualTo(Object value) {
            addCriterion("EURO_AMT <=", value, "euroAmt");
            return (Criteria) this;
        }

        public Criteria andEuroAmtIn(List<Object> values) {
            addCriterion("EURO_AMT in", values, "euroAmt");
            return (Criteria) this;
        }

        public Criteria andEuroAmtNotIn(List<Object> values) {
            addCriterion("EURO_AMT not in", values, "euroAmt");
            return (Criteria) this;
        }

        public Criteria andEuroAmtBetween(Object value1, Object value2) {
            addCriterion("EURO_AMT between", value1, value2, "euroAmt");
            return (Criteria) this;
        }

        public Criteria andEuroAmtNotBetween(Object value1, Object value2) {
            addCriterion("EURO_AMT not between", value1, value2, "euroAmt");
            return (Criteria) this;
        }

        public Criteria andYenAmtIsNull() {
            addCriterion("YEN_AMT is null");
            return (Criteria) this;
        }

        public Criteria andYenAmtIsNotNull() {
            addCriterion("YEN_AMT is not null");
            return (Criteria) this;
        }

        public Criteria andYenAmtEqualTo(Object value) {
            addCriterion("YEN_AMT =", value, "yenAmt");
            return (Criteria) this;
        }

        public Criteria andYenAmtNotEqualTo(Object value) {
            addCriterion("YEN_AMT <>", value, "yenAmt");
            return (Criteria) this;
        }

        public Criteria andYenAmtGreaterThan(Object value) {
            addCriterion("YEN_AMT >", value, "yenAmt");
            return (Criteria) this;
        }

        public Criteria andYenAmtGreaterThanOrEqualTo(Object value) {
            addCriterion("YEN_AMT >=", value, "yenAmt");
            return (Criteria) this;
        }

        public Criteria andYenAmtLessThan(Object value) {
            addCriterion("YEN_AMT <", value, "yenAmt");
            return (Criteria) this;
        }

        public Criteria andYenAmtLessThanOrEqualTo(Object value) {
            addCriterion("YEN_AMT <=", value, "yenAmt");
            return (Criteria) this;
        }

        public Criteria andYenAmtIn(List<Object> values) {
            addCriterion("YEN_AMT in", values, "yenAmt");
            return (Criteria) this;
        }

        public Criteria andYenAmtNotIn(List<Object> values) {
            addCriterion("YEN_AMT not in", values, "yenAmt");
            return (Criteria) this;
        }

        public Criteria andYenAmtBetween(Object value1, Object value2) {
            addCriterion("YEN_AMT between", value1, value2, "yenAmt");
            return (Criteria) this;
        }

        public Criteria andYenAmtNotBetween(Object value1, Object value2) {
            addCriterion("YEN_AMT not between", value1, value2, "yenAmt");
            return (Criteria) this;
        }

        public Criteria andYuanAmtIsNull() {
            addCriterion("YUAN_AMT is null");
            return (Criteria) this;
        }

        public Criteria andYuanAmtIsNotNull() {
            addCriterion("YUAN_AMT is not null");
            return (Criteria) this;
        }

        public Criteria andYuanAmtEqualTo(Object value) {
            addCriterion("YUAN_AMT =", value, "yuanAmt");
            return (Criteria) this;
        }

        public Criteria andYuanAmtNotEqualTo(Object value) {
            addCriterion("YUAN_AMT <>", value, "yuanAmt");
            return (Criteria) this;
        }

        public Criteria andYuanAmtGreaterThan(Object value) {
            addCriterion("YUAN_AMT >", value, "yuanAmt");
            return (Criteria) this;
        }

        public Criteria andYuanAmtGreaterThanOrEqualTo(Object value) {
            addCriterion("YUAN_AMT >=", value, "yuanAmt");
            return (Criteria) this;
        }

        public Criteria andYuanAmtLessThan(Object value) {
            addCriterion("YUAN_AMT <", value, "yuanAmt");
            return (Criteria) this;
        }

        public Criteria andYuanAmtLessThanOrEqualTo(Object value) {
            addCriterion("YUAN_AMT <=", value, "yuanAmt");
            return (Criteria) this;
        }

        public Criteria andYuanAmtIn(List<Object> values) {
            addCriterion("YUAN_AMT in", values, "yuanAmt");
            return (Criteria) this;
        }

        public Criteria andYuanAmtNotIn(List<Object> values) {
            addCriterion("YUAN_AMT not in", values, "yuanAmt");
            return (Criteria) this;
        }

        public Criteria andYuanAmtBetween(Object value1, Object value2) {
            addCriterion("YUAN_AMT between", value1, value2, "yuanAmt");
            return (Criteria) this;
        }

        public Criteria andYuanAmtNotBetween(Object value1, Object value2) {
            addCriterion("YUAN_AMT not between", value1, value2, "yuanAmt");
            return (Criteria) this;
        }

        public Criteria andInsertUidIsNull() {
            addCriterion("INSERT_UID is null");
            return (Criteria) this;
        }

        public Criteria andInsertUidIsNotNull() {
            addCriterion("INSERT_UID is not null");
            return (Criteria) this;
        }

        public Criteria andInsertUidEqualTo(String value) {
            addCriterion("INSERT_UID =", value, "insertUid");
            return (Criteria) this;
        }

        public Criteria andInsertUidNotEqualTo(String value) {
            addCriterion("INSERT_UID <>", value, "insertUid");
            return (Criteria) this;
        }

        public Criteria andInsertUidGreaterThan(String value) {
            addCriterion("INSERT_UID >", value, "insertUid");
            return (Criteria) this;
        }

        public Criteria andInsertUidGreaterThanOrEqualTo(String value) {
            addCriterion("INSERT_UID >=", value, "insertUid");
            return (Criteria) this;
        }

        public Criteria andInsertUidLessThan(String value) {
            addCriterion("INSERT_UID <", value, "insertUid");
            return (Criteria) this;
        }

        public Criteria andInsertUidLessThanOrEqualTo(String value) {
            addCriterion("INSERT_UID <=", value, "insertUid");
            return (Criteria) this;
        }

        public Criteria andInsertUidLike(String value) {
            addCriterion("INSERT_UID like", value, "insertUid");
            return (Criteria) this;
        }

        public Criteria andInsertUidNotLike(String value) {
            addCriterion("INSERT_UID not like", value, "insertUid");
            return (Criteria) this;
        }

        public Criteria andInsertUidIn(List<String> values) {
            addCriterion("INSERT_UID in", values, "insertUid");
            return (Criteria) this;
        }

        public Criteria andInsertUidNotIn(List<String> values) {
            addCriterion("INSERT_UID not in", values, "insertUid");
            return (Criteria) this;
        }

        public Criteria andInsertUidBetween(String value1, String value2) {
            addCriterion("INSERT_UID between", value1, value2, "insertUid");
            return (Criteria) this;
        }

        public Criteria andInsertUidNotBetween(String value1, String value2) {
            addCriterion("INSERT_UID not between", value1, value2, "insertUid");
            return (Criteria) this;
        }

        public Criteria andInsertDateIsNull() {
            addCriterion("INSERT_DATE is null");
            return (Criteria) this;
        }

        public Criteria andInsertDateIsNotNull() {
            addCriterion("INSERT_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andInsertDateEqualTo(Date value) {
            addCriterion("INSERT_DATE =", value, "insertDate");
            return (Criteria) this;
        }

        public Criteria andInsertDateNotEqualTo(Date value) {
            addCriterion("INSERT_DATE <>", value, "insertDate");
            return (Criteria) this;
        }

        public Criteria andInsertDateGreaterThan(Date value) {
            addCriterion("INSERT_DATE >", value, "insertDate");
            return (Criteria) this;
        }

        public Criteria andInsertDateGreaterThanOrEqualTo(Date value) {
            addCriterion("INSERT_DATE >=", value, "insertDate");
            return (Criteria) this;
        }

        public Criteria andInsertDateLessThan(Date value) {
            addCriterion("INSERT_DATE <", value, "insertDate");
            return (Criteria) this;
        }

        public Criteria andInsertDateLessThanOrEqualTo(Date value) {
            addCriterion("INSERT_DATE <=", value, "insertDate");
            return (Criteria) this;
        }

        public Criteria andInsertDateIn(List<Date> values) {
            addCriterion("INSERT_DATE in", values, "insertDate");
            return (Criteria) this;
        }

        public Criteria andInsertDateNotIn(List<Date> values) {
            addCriterion("INSERT_DATE not in", values, "insertDate");
            return (Criteria) this;
        }

        public Criteria andInsertDateBetween(Date value1, Date value2) {
            addCriterion("INSERT_DATE between", value1, value2, "insertDate");
            return (Criteria) this;
        }

        public Criteria andInsertDateNotBetween(Date value1, Date value2) {
            addCriterion("INSERT_DATE not between", value1, value2, "insertDate");
            return (Criteria) this;
        }

        public Criteria andUpdateUidIsNull() {
            addCriterion("UPDATE_UID is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUidIsNotNull() {
            addCriterion("UPDATE_UID is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUidEqualTo(String value) {
            addCriterion("UPDATE_UID =", value, "updateUid");
            return (Criteria) this;
        }

        public Criteria andUpdateUidNotEqualTo(String value) {
            addCriterion("UPDATE_UID <>", value, "updateUid");
            return (Criteria) this;
        }

        public Criteria andUpdateUidGreaterThan(String value) {
            addCriterion("UPDATE_UID >", value, "updateUid");
            return (Criteria) this;
        }

        public Criteria andUpdateUidGreaterThanOrEqualTo(String value) {
            addCriterion("UPDATE_UID >=", value, "updateUid");
            return (Criteria) this;
        }

        public Criteria andUpdateUidLessThan(String value) {
            addCriterion("UPDATE_UID <", value, "updateUid");
            return (Criteria) this;
        }

        public Criteria andUpdateUidLessThanOrEqualTo(String value) {
            addCriterion("UPDATE_UID <=", value, "updateUid");
            return (Criteria) this;
        }

        public Criteria andUpdateUidLike(String value) {
            addCriterion("UPDATE_UID like", value, "updateUid");
            return (Criteria) this;
        }

        public Criteria andUpdateUidNotLike(String value) {
            addCriterion("UPDATE_UID not like", value, "updateUid");
            return (Criteria) this;
        }

        public Criteria andUpdateUidIn(List<String> values) {
            addCriterion("UPDATE_UID in", values, "updateUid");
            return (Criteria) this;
        }

        public Criteria andUpdateUidNotIn(List<String> values) {
            addCriterion("UPDATE_UID not in", values, "updateUid");
            return (Criteria) this;
        }

        public Criteria andUpdateUidBetween(String value1, String value2) {
            addCriterion("UPDATE_UID between", value1, value2, "updateUid");
            return (Criteria) this;
        }

        public Criteria andUpdateUidNotBetween(String value1, String value2) {
            addCriterion("UPDATE_UID not between", value1, value2, "updateUid");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNull() {
            addCriterion("UPDATE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNotNull() {
            addCriterion("UPDATE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateEqualTo(Date value) {
            addCriterion("UPDATE_DATE =", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotEqualTo(Date value) {
            addCriterion("UPDATE_DATE <>", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThan(Date value) {
            addCriterion("UPDATE_DATE >", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDATE_DATE >=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThan(Date value) {
            addCriterion("UPDATE_DATE <", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThanOrEqualTo(Date value) {
            addCriterion("UPDATE_DATE <=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIn(List<Date> values) {
            addCriterion("UPDATE_DATE in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotIn(List<Date> values) {
            addCriterion("UPDATE_DATE not in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateBetween(Date value1, Date value2) {
            addCriterion("UPDATE_DATE between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotBetween(Date value1, Date value2) {
            addCriterion("UPDATE_DATE not between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andOrgSendYnIsNull() {
            addCriterion("ORG_SEND_YN is null");
            return (Criteria) this;
        }

        public Criteria andOrgSendYnIsNotNull() {
            addCriterion("ORG_SEND_YN is not null");
            return (Criteria) this;
        }

        public Criteria andOrgSendYnEqualTo(String value) {
            addCriterion("ORG_SEND_YN =", value, "orgSendYn");
            return (Criteria) this;
        }

        public Criteria andOrgSendYnNotEqualTo(String value) {
            addCriterion("ORG_SEND_YN <>", value, "orgSendYn");
            return (Criteria) this;
        }

        public Criteria andOrgSendYnGreaterThan(String value) {
            addCriterion("ORG_SEND_YN >", value, "orgSendYn");
            return (Criteria) this;
        }

        public Criteria andOrgSendYnGreaterThanOrEqualTo(String value) {
            addCriterion("ORG_SEND_YN >=", value, "orgSendYn");
            return (Criteria) this;
        }

        public Criteria andOrgSendYnLessThan(String value) {
            addCriterion("ORG_SEND_YN <", value, "orgSendYn");
            return (Criteria) this;
        }

        public Criteria andOrgSendYnLessThanOrEqualTo(String value) {
            addCriterion("ORG_SEND_YN <=", value, "orgSendYn");
            return (Criteria) this;
        }

        public Criteria andOrgSendYnLike(String value) {
            addCriterion("ORG_SEND_YN like", value, "orgSendYn");
            return (Criteria) this;
        }

        public Criteria andOrgSendYnNotLike(String value) {
            addCriterion("ORG_SEND_YN not like", value, "orgSendYn");
            return (Criteria) this;
        }

        public Criteria andOrgSendYnIn(List<String> values) {
            addCriterion("ORG_SEND_YN in", values, "orgSendYn");
            return (Criteria) this;
        }

        public Criteria andOrgSendYnNotIn(List<String> values) {
            addCriterion("ORG_SEND_YN not in", values, "orgSendYn");
            return (Criteria) this;
        }

        public Criteria andOrgSendYnBetween(String value1, String value2) {
            addCriterion("ORG_SEND_YN between", value1, value2, "orgSendYn");
            return (Criteria) this;
        }

        public Criteria andOrgSendYnNotBetween(String value1, String value2) {
            addCriterion("ORG_SEND_YN not between", value1, value2, "orgSendYn");
            return (Criteria) this;
        }

        public Criteria andDepoCloseSdateIsNull() {
            addCriterion("DEPO_CLOSE_SDATE is null");
            return (Criteria) this;
        }

        public Criteria andDepoCloseSdateIsNotNull() {
            addCriterion("DEPO_CLOSE_SDATE is not null");
            return (Criteria) this;
        }

        public Criteria andDepoCloseSdateEqualTo(String value) {
            addCriterion("DEPO_CLOSE_SDATE =", value, "depoCloseSdate");
            return (Criteria) this;
        }

        public Criteria andDepoCloseSdateNotEqualTo(String value) {
            addCriterion("DEPO_CLOSE_SDATE <>", value, "depoCloseSdate");
            return (Criteria) this;
        }

        public Criteria andDepoCloseSdateGreaterThan(String value) {
            addCriterion("DEPO_CLOSE_SDATE >", value, "depoCloseSdate");
            return (Criteria) this;
        }

        public Criteria andDepoCloseSdateGreaterThanOrEqualTo(String value) {
            addCriterion("DEPO_CLOSE_SDATE >=", value, "depoCloseSdate");
            return (Criteria) this;
        }

        public Criteria andDepoCloseSdateLessThan(String value) {
            addCriterion("DEPO_CLOSE_SDATE <", value, "depoCloseSdate");
            return (Criteria) this;
        }

        public Criteria andDepoCloseSdateLessThanOrEqualTo(String value) {
            addCriterion("DEPO_CLOSE_SDATE <=", value, "depoCloseSdate");
            return (Criteria) this;
        }

        public Criteria andDepoCloseSdateLike(String value) {
            addCriterion("DEPO_CLOSE_SDATE like", value, "depoCloseSdate");
            return (Criteria) this;
        }

        public Criteria andDepoCloseSdateNotLike(String value) {
            addCriterion("DEPO_CLOSE_SDATE not like", value, "depoCloseSdate");
            return (Criteria) this;
        }

        public Criteria andDepoCloseSdateIn(List<String> values) {
            addCriterion("DEPO_CLOSE_SDATE in", values, "depoCloseSdate");
            return (Criteria) this;
        }

        public Criteria andDepoCloseSdateNotIn(List<String> values) {
            addCriterion("DEPO_CLOSE_SDATE not in", values, "depoCloseSdate");
            return (Criteria) this;
        }

        public Criteria andDepoCloseSdateBetween(String value1, String value2) {
            addCriterion("DEPO_CLOSE_SDATE between", value1, value2, "depoCloseSdate");
            return (Criteria) this;
        }

        public Criteria andDepoCloseSdateNotBetween(String value1, String value2) {
            addCriterion("DEPO_CLOSE_SDATE not between", value1, value2, "depoCloseSdate");
            return (Criteria) this;
        }

        public Criteria andDepoCloseEdateIsNull() {
            addCriterion("DEPO_CLOSE_EDATE is null");
            return (Criteria) this;
        }

        public Criteria andDepoCloseEdateIsNotNull() {
            addCriterion("DEPO_CLOSE_EDATE is not null");
            return (Criteria) this;
        }

        public Criteria andDepoCloseEdateEqualTo(String value) {
            addCriterion("DEPO_CLOSE_EDATE =", value, "depoCloseEdate");
            return (Criteria) this;
        }

        public Criteria andDepoCloseEdateNotEqualTo(String value) {
            addCriterion("DEPO_CLOSE_EDATE <>", value, "depoCloseEdate");
            return (Criteria) this;
        }

        public Criteria andDepoCloseEdateGreaterThan(String value) {
            addCriterion("DEPO_CLOSE_EDATE >", value, "depoCloseEdate");
            return (Criteria) this;
        }

        public Criteria andDepoCloseEdateGreaterThanOrEqualTo(String value) {
            addCriterion("DEPO_CLOSE_EDATE >=", value, "depoCloseEdate");
            return (Criteria) this;
        }

        public Criteria andDepoCloseEdateLessThan(String value) {
            addCriterion("DEPO_CLOSE_EDATE <", value, "depoCloseEdate");
            return (Criteria) this;
        }

        public Criteria andDepoCloseEdateLessThanOrEqualTo(String value) {
            addCriterion("DEPO_CLOSE_EDATE <=", value, "depoCloseEdate");
            return (Criteria) this;
        }

        public Criteria andDepoCloseEdateLike(String value) {
            addCriterion("DEPO_CLOSE_EDATE like", value, "depoCloseEdate");
            return (Criteria) this;
        }

        public Criteria andDepoCloseEdateNotLike(String value) {
            addCriterion("DEPO_CLOSE_EDATE not like", value, "depoCloseEdate");
            return (Criteria) this;
        }

        public Criteria andDepoCloseEdateIn(List<String> values) {
            addCriterion("DEPO_CLOSE_EDATE in", values, "depoCloseEdate");
            return (Criteria) this;
        }

        public Criteria andDepoCloseEdateNotIn(List<String> values) {
            addCriterion("DEPO_CLOSE_EDATE not in", values, "depoCloseEdate");
            return (Criteria) this;
        }

        public Criteria andDepoCloseEdateBetween(String value1, String value2) {
            addCriterion("DEPO_CLOSE_EDATE between", value1, value2, "depoCloseEdate");
            return (Criteria) this;
        }

        public Criteria andDepoCloseEdateNotBetween(String value1, String value2) {
            addCriterion("DEPO_CLOSE_EDATE not between", value1, value2, "depoCloseEdate");
            return (Criteria) this;
        }

        public Criteria andDepoCloseStimeIsNull() {
            addCriterion("DEPO_CLOSE_STIME is null");
            return (Criteria) this;
        }

        public Criteria andDepoCloseStimeIsNotNull() {
            addCriterion("DEPO_CLOSE_STIME is not null");
            return (Criteria) this;
        }

        public Criteria andDepoCloseStimeEqualTo(String value) {
            addCriterion("DEPO_CLOSE_STIME =", value, "depoCloseStime");
            return (Criteria) this;
        }

        public Criteria andDepoCloseStimeNotEqualTo(String value) {
            addCriterion("DEPO_CLOSE_STIME <>", value, "depoCloseStime");
            return (Criteria) this;
        }

        public Criteria andDepoCloseStimeGreaterThan(String value) {
            addCriterion("DEPO_CLOSE_STIME >", value, "depoCloseStime");
            return (Criteria) this;
        }

        public Criteria andDepoCloseStimeGreaterThanOrEqualTo(String value) {
            addCriterion("DEPO_CLOSE_STIME >=", value, "depoCloseStime");
            return (Criteria) this;
        }

        public Criteria andDepoCloseStimeLessThan(String value) {
            addCriterion("DEPO_CLOSE_STIME <", value, "depoCloseStime");
            return (Criteria) this;
        }

        public Criteria andDepoCloseStimeLessThanOrEqualTo(String value) {
            addCriterion("DEPO_CLOSE_STIME <=", value, "depoCloseStime");
            return (Criteria) this;
        }

        public Criteria andDepoCloseStimeLike(String value) {
            addCriterion("DEPO_CLOSE_STIME like", value, "depoCloseStime");
            return (Criteria) this;
        }

        public Criteria andDepoCloseStimeNotLike(String value) {
            addCriterion("DEPO_CLOSE_STIME not like", value, "depoCloseStime");
            return (Criteria) this;
        }

        public Criteria andDepoCloseStimeIn(List<String> values) {
            addCriterion("DEPO_CLOSE_STIME in", values, "depoCloseStime");
            return (Criteria) this;
        }

        public Criteria andDepoCloseStimeNotIn(List<String> values) {
            addCriterion("DEPO_CLOSE_STIME not in", values, "depoCloseStime");
            return (Criteria) this;
        }

        public Criteria andDepoCloseStimeBetween(String value1, String value2) {
            addCriterion("DEPO_CLOSE_STIME between", value1, value2, "depoCloseStime");
            return (Criteria) this;
        }

        public Criteria andDepoCloseStimeNotBetween(String value1, String value2) {
            addCriterion("DEPO_CLOSE_STIME not between", value1, value2, "depoCloseStime");
            return (Criteria) this;
        }

        public Criteria andDepoCloseEtimeIsNull() {
            addCriterion("DEPO_CLOSE_ETIME is null");
            return (Criteria) this;
        }

        public Criteria andDepoCloseEtimeIsNotNull() {
            addCriterion("DEPO_CLOSE_ETIME is not null");
            return (Criteria) this;
        }

        public Criteria andDepoCloseEtimeEqualTo(String value) {
            addCriterion("DEPO_CLOSE_ETIME =", value, "depoCloseEtime");
            return (Criteria) this;
        }

        public Criteria andDepoCloseEtimeNotEqualTo(String value) {
            addCriterion("DEPO_CLOSE_ETIME <>", value, "depoCloseEtime");
            return (Criteria) this;
        }

        public Criteria andDepoCloseEtimeGreaterThan(String value) {
            addCriterion("DEPO_CLOSE_ETIME >", value, "depoCloseEtime");
            return (Criteria) this;
        }

        public Criteria andDepoCloseEtimeGreaterThanOrEqualTo(String value) {
            addCriterion("DEPO_CLOSE_ETIME >=", value, "depoCloseEtime");
            return (Criteria) this;
        }

        public Criteria andDepoCloseEtimeLessThan(String value) {
            addCriterion("DEPO_CLOSE_ETIME <", value, "depoCloseEtime");
            return (Criteria) this;
        }

        public Criteria andDepoCloseEtimeLessThanOrEqualTo(String value) {
            addCriterion("DEPO_CLOSE_ETIME <=", value, "depoCloseEtime");
            return (Criteria) this;
        }

        public Criteria andDepoCloseEtimeLike(String value) {
            addCriterion("DEPO_CLOSE_ETIME like", value, "depoCloseEtime");
            return (Criteria) this;
        }

        public Criteria andDepoCloseEtimeNotLike(String value) {
            addCriterion("DEPO_CLOSE_ETIME not like", value, "depoCloseEtime");
            return (Criteria) this;
        }

        public Criteria andDepoCloseEtimeIn(List<String> values) {
            addCriterion("DEPO_CLOSE_ETIME in", values, "depoCloseEtime");
            return (Criteria) this;
        }

        public Criteria andDepoCloseEtimeNotIn(List<String> values) {
            addCriterion("DEPO_CLOSE_ETIME not in", values, "depoCloseEtime");
            return (Criteria) this;
        }

        public Criteria andDepoCloseEtimeBetween(String value1, String value2) {
            addCriterion("DEPO_CLOSE_ETIME between", value1, value2, "depoCloseEtime");
            return (Criteria) this;
        }

        public Criteria andDepoCloseEtimeNotBetween(String value1, String value2) {
            addCriterion("DEPO_CLOSE_ETIME not between", value1, value2, "depoCloseEtime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table OP.T_FN_FOREIGNCURRENCY
     *
     * @mbggenerated do_not_delete_during_merge Mon Jul 28 16:08:07 KST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table OP.T_FN_FOREIGNCURRENCY
     *
     * @mbggenerated Mon Jul 28 16:08:07 KST 2014
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}