package com.nicetcm.nibsplus.broker.msg.model;

import java.util.Date;

public class TFnNiceTranCupon extends TFnNiceTranCuponKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OP.T_FN_NICE_TRAN_CUPON.DEAL_TYPE
     *
     * @mbggenerated Tue Jul 08 11:42:20 KST 2014
     */
    private String dealType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OP.T_FN_NICE_TRAN_CUPON.DEAL_CLSS
     *
     * @mbggenerated Tue Jul 08 11:42:20 KST 2014
     */
    private String dealClss;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OP.T_FN_NICE_TRAN_CUPON.INST_ORG_CD
     *
     * @mbggenerated Tue Jul 08 11:42:20 KST 2014
     */
    private String instOrgCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OP.T_FN_NICE_TRAN_CUPON.INST_BRANCH_CD
     *
     * @mbggenerated Tue Jul 08 11:42:20 KST 2014
     */
    private String instBranchCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OP.T_FN_NICE_TRAN_CUPON.ACCOUNT_NO
     *
     * @mbggenerated Tue Jul 08 11:42:20 KST 2014
     */
    private String accountNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OP.T_FN_NICE_TRAN_CUPON.REAL_ACCOUNT_NO
     *
     * @mbggenerated Tue Jul 08 11:42:20 KST 2014
     */
    private String realAccountNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OP.T_FN_NICE_TRAN_CUPON.DEAL_AMT
     *
     * @mbggenerated Tue Jul 08 11:42:20 KST 2014
     */
    private Long dealAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OP.T_FN_NICE_TRAN_CUPON.ORG_CD
     *
     * @mbggenerated Tue Jul 08 11:42:20 KST 2014
     */
    private String orgCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OP.T_FN_NICE_TRAN_CUPON.DEAL_YEAR
     *
     * @mbggenerated Tue Jul 08 11:42:20 KST 2014
     */
    private String dealYear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OP.T_FN_NICE_TRAN_CUPON.DEAL_MMDD
     *
     * @mbggenerated Tue Jul 08 11:42:20 KST 2014
     */
    private String dealMmdd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OP.T_FN_NICE_TRAN_CUPON.DEAL_NO
     *
     * @mbggenerated Tue Jul 08 11:42:20 KST 2014
     */
    private String dealNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OP.T_FN_NICE_TRAN_CUPON.DEAL_STATUS
     *
     * @mbggenerated Tue Jul 08 11:42:20 KST 2014
     */
    private String dealStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OP.T_FN_NICE_TRAN_CUPON.DEAL_TIME_TYPE
     *
     * @mbggenerated Tue Jul 08 11:42:20 KST 2014
     */
    private String dealTimeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OP.T_FN_NICE_TRAN_CUPON.DEAL_TIME
     *
     * @mbggenerated Tue Jul 08 11:42:20 KST 2014
     */
    private String dealTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OP.T_FN_NICE_TRAN_CUPON.DEAL_HOUR
     *
     * @mbggenerated Tue Jul 08 11:42:20 KST 2014
     */
    private String dealHour;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OP.T_FN_NICE_TRAN_CUPON.DEAL_MI
     *
     * @mbggenerated Tue Jul 08 11:42:20 KST 2014
     */
    private String dealMi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OP.T_FN_NICE_TRAN_CUPON.DEAL_SEC
     *
     * @mbggenerated Tue Jul 08 11:42:20 KST 2014
     */
    private String dealSec;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OP.T_FN_NICE_TRAN_CUPON.ORNZ_CD
     *
     * @mbggenerated Tue Jul 08 11:42:20 KST 2014
     */
    private String ornzCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OP.T_FN_NICE_TRAN_CUPON.NET_ORG_CD
     *
     * @mbggenerated Tue Jul 08 11:42:20 KST 2014
     */
    private String netOrgCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OP.T_FN_NICE_TRAN_CUPON.CHECK_AMT
     *
     * @mbggenerated Tue Jul 08 11:42:20 KST 2014
     */
    private Long checkAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OP.T_FN_NICE_TRAN_CUPON.FORNZ_CD
     *
     * @mbggenerated Tue Jul 08 11:42:20 KST 2014
     */
    private String fornzCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OP.T_FN_NICE_TRAN_CUPON.DEAL_IN_AMT_CW15
     *
     * @mbggenerated Tue Jul 08 11:42:20 KST 2014
     */
    private Long dealInAmtCw15;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OP.T_FN_NICE_TRAN_CUPON.DEAL_IN_AMT_CW54
     *
     * @mbggenerated Tue Jul 08 11:42:20 KST 2014
     */
    private Long dealInAmtCw54;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OP.T_FN_NICE_TRAN_CUPON.DEAL_IN_AMT_CW14
     *
     * @mbggenerated Tue Jul 08 11:42:20 KST 2014
     */
    private Long dealInAmtCw14;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OP.T_FN_NICE_TRAN_CUPON.DEAL_IN_AMT_CW53
     *
     * @mbggenerated Tue Jul 08 11:42:20 KST 2014
     */
    private Long dealInAmtCw53;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OP.T_FN_NICE_TRAN_CUPON.DEAL_IN_AMT_CW13
     *
     * @mbggenerated Tue Jul 08 11:42:20 KST 2014
     */
    private Long dealInAmtCw13;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OP.T_FN_NICE_TRAN_CUPON.DEAL_OUT_AMT_CW54
     *
     * @mbggenerated Tue Jul 08 11:42:20 KST 2014
     */
    private Long dealOutAmtCw54;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OP.T_FN_NICE_TRAN_CUPON.DEAL_OUT_AMT_CW14
     *
     * @mbggenerated Tue Jul 08 11:42:20 KST 2014
     */
    private Long dealOutAmtCw14;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OP.T_FN_NICE_TRAN_CUPON.DEAL_OUT_AMT_CW53
     *
     * @mbggenerated Tue Jul 08 11:42:20 KST 2014
     */
    private Long dealOutAmtCw53;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OP.T_FN_NICE_TRAN_CUPON.DEAL_OUT_AMT_CW13
     *
     * @mbggenerated Tue Jul 08 11:42:20 KST 2014
     */
    private Long dealOutAmtCw13;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OP.T_FN_NICE_TRAN_CUPON.DEAL_OUT_AMT_CW52
     *
     * @mbggenerated Tue Jul 08 11:42:20 KST 2014
     */
    private Long dealOutAmtCw52;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OP.T_FN_NICE_TRAN_CUPON.DEAL_OUT_AMT_CW12
     *
     * @mbggenerated Tue Jul 08 11:42:20 KST 2014
     */
    private Long dealOutAmtCw12;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OP.T_FN_NICE_TRAN_CUPON.DEAL_OUT_AMT_CW51
     *
     * @mbggenerated Tue Jul 08 11:42:20 KST 2014
     */
    private Long dealOutAmtCw51;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OP.T_FN_NICE_TRAN_CUPON.DEAL_OUT_AMT_CW11
     *
     * @mbggenerated Tue Jul 08 11:42:20 KST 2014
     */
    private Long dealOutAmtCw11;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OP.T_FN_NICE_TRAN_CUPON.INSERT_DATE
     *
     * @mbggenerated Tue Jul 08 11:42:20 KST 2014
     */
    private Date insertDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OP.T_FN_NICE_TRAN_CUPON.INSERT_UID
     *
     * @mbggenerated Tue Jul 08 11:42:20 KST 2014
     */
    private String insertUid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OP.T_FN_NICE_TRAN_CUPON.DEAL_TYPE
     *
     * @return the value of OP.T_FN_NICE_TRAN_CUPON.DEAL_TYPE
     *
     * @mbggenerated Tue Jul 08 11:42:20 KST 2014
     */
    public String getDealType() {
        return dealType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OP.T_FN_NICE_TRAN_CUPON.DEAL_TYPE
     *
     * @param dealType the value for OP.T_FN_NICE_TRAN_CUPON.DEAL_TYPE
     *
     * @mbggenerated Tue Jul 08 11:42:20 KST 2014
     */
    public void setDealType(String dealType) {
        this.dealType = dealType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OP.T_FN_NICE_TRAN_CUPON.DEAL_CLSS
     *
     * @return the value of OP.T_FN_NICE_TRAN_CUPON.DEAL_CLSS
     *
     * @mbggenerated Tue Jul 08 11:42:20 KST 2014
     */
    public String getDealClss() {
        return dealClss;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OP.T_FN_NICE_TRAN_CUPON.DEAL_CLSS
     *
     * @param dealClss the value for OP.T_FN_NICE_TRAN_CUPON.DEAL_CLSS
     *
     * @mbggenerated Tue Jul 08 11:42:20 KST 2014
     */
    public void setDealClss(String dealClss) {
        this.dealClss = dealClss;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OP.T_FN_NICE_TRAN_CUPON.INST_ORG_CD
     *
     * @return the value of OP.T_FN_NICE_TRAN_CUPON.INST_ORG_CD
     *
     * @mbggenerated Tue Jul 08 11:42:20 KST 2014
     */
    public String getInstOrgCd() {
        return instOrgCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OP.T_FN_NICE_TRAN_CUPON.INST_ORG_CD
     *
     * @param instOrgCd the value for OP.T_FN_NICE_TRAN_CUPON.INST_ORG_CD
     *
     * @mbggenerated Tue Jul 08 11:42:20 KST 2014
     */
    public void setInstOrgCd(String instOrgCd) {
        this.instOrgCd = instOrgCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OP.T_FN_NICE_TRAN_CUPON.INST_BRANCH_CD
     *
     * @return the value of OP.T_FN_NICE_TRAN_CUPON.INST_BRANCH_CD
     *
     * @mbggenerated Tue Jul 08 11:42:20 KST 2014
     */
    public String getInstBranchCd() {
        return instBranchCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OP.T_FN_NICE_TRAN_CUPON.INST_BRANCH_CD
     *
     * @param instBranchCd the value for OP.T_FN_NICE_TRAN_CUPON.INST_BRANCH_CD
     *
     * @mbggenerated Tue Jul 08 11:42:20 KST 2014
     */
    public void setInstBranchCd(String instBranchCd) {
        this.instBranchCd = instBranchCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OP.T_FN_NICE_TRAN_CUPON.ACCOUNT_NO
     *
     * @return the value of OP.T_FN_NICE_TRAN_CUPON.ACCOUNT_NO
     *
     * @mbggenerated Tue Jul 08 11:42:20 KST 2014
     */
    public String getAccountNo() {
        return accountNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OP.T_FN_NICE_TRAN_CUPON.ACCOUNT_NO
     *
     * @param accountNo the value for OP.T_FN_NICE_TRAN_CUPON.ACCOUNT_NO
     *
     * @mbggenerated Tue Jul 08 11:42:20 KST 2014
     */
    public void setAccountNo(String accountNo) {
        this.accountNo = accountNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OP.T_FN_NICE_TRAN_CUPON.REAL_ACCOUNT_NO
     *
     * @return the value of OP.T_FN_NICE_TRAN_CUPON.REAL_ACCOUNT_NO
     *
     * @mbggenerated Tue Jul 08 11:42:20 KST 2014
     */
    public String getRealAccountNo() {
        return realAccountNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OP.T_FN_NICE_TRAN_CUPON.REAL_ACCOUNT_NO
     *
     * @param realAccountNo the value for OP.T_FN_NICE_TRAN_CUPON.REAL_ACCOUNT_NO
     *
     * @mbggenerated Tue Jul 08 11:42:20 KST 2014
     */
    public void setRealAccountNo(String realAccountNo) {
        this.realAccountNo = realAccountNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OP.T_FN_NICE_TRAN_CUPON.DEAL_AMT
     *
     * @return the value of OP.T_FN_NICE_TRAN_CUPON.DEAL_AMT
     *
     * @mbggenerated Tue Jul 08 11:42:20 KST 2014
     */
    public Long getDealAmt() {
        return dealAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OP.T_FN_NICE_TRAN_CUPON.DEAL_AMT
     *
     * @param dealAmt the value for OP.T_FN_NICE_TRAN_CUPON.DEAL_AMT
     *
     * @mbggenerated Tue Jul 08 11:42:20 KST 2014
     */
    public void setDealAmt(Long dealAmt) {
        this.dealAmt = dealAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OP.T_FN_NICE_TRAN_CUPON.ORG_CD
     *
     * @return the value of OP.T_FN_NICE_TRAN_CUPON.ORG_CD
     *
     * @mbggenerated Tue Jul 08 11:42:20 KST 2014
     */
    public String getOrgCd() {
        return orgCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OP.T_FN_NICE_TRAN_CUPON.ORG_CD
     *
     * @param orgCd the value for OP.T_FN_NICE_TRAN_CUPON.ORG_CD
     *
     * @mbggenerated Tue Jul 08 11:42:20 KST 2014
     */
    public void setOrgCd(String orgCd) {
        this.orgCd = orgCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OP.T_FN_NICE_TRAN_CUPON.DEAL_YEAR
     *
     * @return the value of OP.T_FN_NICE_TRAN_CUPON.DEAL_YEAR
     *
     * @mbggenerated Tue Jul 08 11:42:20 KST 2014
     */
    public String getDealYear() {
        return dealYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OP.T_FN_NICE_TRAN_CUPON.DEAL_YEAR
     *
     * @param dealYear the value for OP.T_FN_NICE_TRAN_CUPON.DEAL_YEAR
     *
     * @mbggenerated Tue Jul 08 11:42:20 KST 2014
     */
    public void setDealYear(String dealYear) {
        this.dealYear = dealYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OP.T_FN_NICE_TRAN_CUPON.DEAL_MMDD
     *
     * @return the value of OP.T_FN_NICE_TRAN_CUPON.DEAL_MMDD
     *
     * @mbggenerated Tue Jul 08 11:42:20 KST 2014
     */
    public String getDealMmdd() {
        return dealMmdd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OP.T_FN_NICE_TRAN_CUPON.DEAL_MMDD
     *
     * @param dealMmdd the value for OP.T_FN_NICE_TRAN_CUPON.DEAL_MMDD
     *
     * @mbggenerated Tue Jul 08 11:42:20 KST 2014
     */
    public void setDealMmdd(String dealMmdd) {
        this.dealMmdd = dealMmdd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OP.T_FN_NICE_TRAN_CUPON.DEAL_NO
     *
     * @return the value of OP.T_FN_NICE_TRAN_CUPON.DEAL_NO
     *
     * @mbggenerated Tue Jul 08 11:42:20 KST 2014
     */
    public String getDealNo() {
        return dealNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OP.T_FN_NICE_TRAN_CUPON.DEAL_NO
     *
     * @param dealNo the value for OP.T_FN_NICE_TRAN_CUPON.DEAL_NO
     *
     * @mbggenerated Tue Jul 08 11:42:20 KST 2014
     */
    public void setDealNo(String dealNo) {
        this.dealNo = dealNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OP.T_FN_NICE_TRAN_CUPON.DEAL_STATUS
     *
     * @return the value of OP.T_FN_NICE_TRAN_CUPON.DEAL_STATUS
     *
     * @mbggenerated Tue Jul 08 11:42:20 KST 2014
     */
    public String getDealStatus() {
        return dealStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OP.T_FN_NICE_TRAN_CUPON.DEAL_STATUS
     *
     * @param dealStatus the value for OP.T_FN_NICE_TRAN_CUPON.DEAL_STATUS
     *
     * @mbggenerated Tue Jul 08 11:42:20 KST 2014
     */
    public void setDealStatus(String dealStatus) {
        this.dealStatus = dealStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OP.T_FN_NICE_TRAN_CUPON.DEAL_TIME_TYPE
     *
     * @return the value of OP.T_FN_NICE_TRAN_CUPON.DEAL_TIME_TYPE
     *
     * @mbggenerated Tue Jul 08 11:42:20 KST 2014
     */
    public String getDealTimeType() {
        return dealTimeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OP.T_FN_NICE_TRAN_CUPON.DEAL_TIME_TYPE
     *
     * @param dealTimeType the value for OP.T_FN_NICE_TRAN_CUPON.DEAL_TIME_TYPE
     *
     * @mbggenerated Tue Jul 08 11:42:20 KST 2014
     */
    public void setDealTimeType(String dealTimeType) {
        this.dealTimeType = dealTimeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OP.T_FN_NICE_TRAN_CUPON.DEAL_TIME
     *
     * @return the value of OP.T_FN_NICE_TRAN_CUPON.DEAL_TIME
     *
     * @mbggenerated Tue Jul 08 11:42:20 KST 2014
     */
    public String getDealTime() {
        return dealTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OP.T_FN_NICE_TRAN_CUPON.DEAL_TIME
     *
     * @param dealTime the value for OP.T_FN_NICE_TRAN_CUPON.DEAL_TIME
     *
     * @mbggenerated Tue Jul 08 11:42:20 KST 2014
     */
    public void setDealTime(String dealTime) {
        this.dealTime = dealTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OP.T_FN_NICE_TRAN_CUPON.DEAL_HOUR
     *
     * @return the value of OP.T_FN_NICE_TRAN_CUPON.DEAL_HOUR
     *
     * @mbggenerated Tue Jul 08 11:42:20 KST 2014
     */
    public String getDealHour() {
        return dealHour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OP.T_FN_NICE_TRAN_CUPON.DEAL_HOUR
     *
     * @param dealHour the value for OP.T_FN_NICE_TRAN_CUPON.DEAL_HOUR
     *
     * @mbggenerated Tue Jul 08 11:42:20 KST 2014
     */
    public void setDealHour(String dealHour) {
        this.dealHour = dealHour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OP.T_FN_NICE_TRAN_CUPON.DEAL_MI
     *
     * @return the value of OP.T_FN_NICE_TRAN_CUPON.DEAL_MI
     *
     * @mbggenerated Tue Jul 08 11:42:20 KST 2014
     */
    public String getDealMi() {
        return dealMi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OP.T_FN_NICE_TRAN_CUPON.DEAL_MI
     *
     * @param dealMi the value for OP.T_FN_NICE_TRAN_CUPON.DEAL_MI
     *
     * @mbggenerated Tue Jul 08 11:42:20 KST 2014
     */
    public void setDealMi(String dealMi) {
        this.dealMi = dealMi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OP.T_FN_NICE_TRAN_CUPON.DEAL_SEC
     *
     * @return the value of OP.T_FN_NICE_TRAN_CUPON.DEAL_SEC
     *
     * @mbggenerated Tue Jul 08 11:42:20 KST 2014
     */
    public String getDealSec() {
        return dealSec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OP.T_FN_NICE_TRAN_CUPON.DEAL_SEC
     *
     * @param dealSec the value for OP.T_FN_NICE_TRAN_CUPON.DEAL_SEC
     *
     * @mbggenerated Tue Jul 08 11:42:20 KST 2014
     */
    public void setDealSec(String dealSec) {
        this.dealSec = dealSec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OP.T_FN_NICE_TRAN_CUPON.ORNZ_CD
     *
     * @return the value of OP.T_FN_NICE_TRAN_CUPON.ORNZ_CD
     *
     * @mbggenerated Tue Jul 08 11:42:20 KST 2014
     */
    public String getOrnzCd() {
        return ornzCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OP.T_FN_NICE_TRAN_CUPON.ORNZ_CD
     *
     * @param ornzCd the value for OP.T_FN_NICE_TRAN_CUPON.ORNZ_CD
     *
     * @mbggenerated Tue Jul 08 11:42:20 KST 2014
     */
    public void setOrnzCd(String ornzCd) {
        this.ornzCd = ornzCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OP.T_FN_NICE_TRAN_CUPON.NET_ORG_CD
     *
     * @return the value of OP.T_FN_NICE_TRAN_CUPON.NET_ORG_CD
     *
     * @mbggenerated Tue Jul 08 11:42:20 KST 2014
     */
    public String getNetOrgCd() {
        return netOrgCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OP.T_FN_NICE_TRAN_CUPON.NET_ORG_CD
     *
     * @param netOrgCd the value for OP.T_FN_NICE_TRAN_CUPON.NET_ORG_CD
     *
     * @mbggenerated Tue Jul 08 11:42:20 KST 2014
     */
    public void setNetOrgCd(String netOrgCd) {
        this.netOrgCd = netOrgCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OP.T_FN_NICE_TRAN_CUPON.CHECK_AMT
     *
     * @return the value of OP.T_FN_NICE_TRAN_CUPON.CHECK_AMT
     *
     * @mbggenerated Tue Jul 08 11:42:20 KST 2014
     */
    public Long getCheckAmt() {
        return checkAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OP.T_FN_NICE_TRAN_CUPON.CHECK_AMT
     *
     * @param checkAmt the value for OP.T_FN_NICE_TRAN_CUPON.CHECK_AMT
     *
     * @mbggenerated Tue Jul 08 11:42:20 KST 2014
     */
    public void setCheckAmt(Long checkAmt) {
        this.checkAmt = checkAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OP.T_FN_NICE_TRAN_CUPON.FORNZ_CD
     *
     * @return the value of OP.T_FN_NICE_TRAN_CUPON.FORNZ_CD
     *
     * @mbggenerated Tue Jul 08 11:42:20 KST 2014
     */
    public String getFornzCd() {
        return fornzCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OP.T_FN_NICE_TRAN_CUPON.FORNZ_CD
     *
     * @param fornzCd the value for OP.T_FN_NICE_TRAN_CUPON.FORNZ_CD
     *
     * @mbggenerated Tue Jul 08 11:42:20 KST 2014
     */
    public void setFornzCd(String fornzCd) {
        this.fornzCd = fornzCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OP.T_FN_NICE_TRAN_CUPON.DEAL_IN_AMT_CW15
     *
     * @return the value of OP.T_FN_NICE_TRAN_CUPON.DEAL_IN_AMT_CW15
     *
     * @mbggenerated Tue Jul 08 11:42:20 KST 2014
     */
    public Long getDealInAmtCw15() {
        return dealInAmtCw15;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OP.T_FN_NICE_TRAN_CUPON.DEAL_IN_AMT_CW15
     *
     * @param dealInAmtCw15 the value for OP.T_FN_NICE_TRAN_CUPON.DEAL_IN_AMT_CW15
     *
     * @mbggenerated Tue Jul 08 11:42:20 KST 2014
     */
    public void setDealInAmtCw15(Long dealInAmtCw15) {
        this.dealInAmtCw15 = dealInAmtCw15;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OP.T_FN_NICE_TRAN_CUPON.DEAL_IN_AMT_CW54
     *
     * @return the value of OP.T_FN_NICE_TRAN_CUPON.DEAL_IN_AMT_CW54
     *
     * @mbggenerated Tue Jul 08 11:42:20 KST 2014
     */
    public Long getDealInAmtCw54() {
        return dealInAmtCw54;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OP.T_FN_NICE_TRAN_CUPON.DEAL_IN_AMT_CW54
     *
     * @param dealInAmtCw54 the value for OP.T_FN_NICE_TRAN_CUPON.DEAL_IN_AMT_CW54
     *
     * @mbggenerated Tue Jul 08 11:42:20 KST 2014
     */
    public void setDealInAmtCw54(Long dealInAmtCw54) {
        this.dealInAmtCw54 = dealInAmtCw54;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OP.T_FN_NICE_TRAN_CUPON.DEAL_IN_AMT_CW14
     *
     * @return the value of OP.T_FN_NICE_TRAN_CUPON.DEAL_IN_AMT_CW14
     *
     * @mbggenerated Tue Jul 08 11:42:20 KST 2014
     */
    public Long getDealInAmtCw14() {
        return dealInAmtCw14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OP.T_FN_NICE_TRAN_CUPON.DEAL_IN_AMT_CW14
     *
     * @param dealInAmtCw14 the value for OP.T_FN_NICE_TRAN_CUPON.DEAL_IN_AMT_CW14
     *
     * @mbggenerated Tue Jul 08 11:42:20 KST 2014
     */
    public void setDealInAmtCw14(Long dealInAmtCw14) {
        this.dealInAmtCw14 = dealInAmtCw14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OP.T_FN_NICE_TRAN_CUPON.DEAL_IN_AMT_CW53
     *
     * @return the value of OP.T_FN_NICE_TRAN_CUPON.DEAL_IN_AMT_CW53
     *
     * @mbggenerated Tue Jul 08 11:42:20 KST 2014
     */
    public Long getDealInAmtCw53() {
        return dealInAmtCw53;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OP.T_FN_NICE_TRAN_CUPON.DEAL_IN_AMT_CW53
     *
     * @param dealInAmtCw53 the value for OP.T_FN_NICE_TRAN_CUPON.DEAL_IN_AMT_CW53
     *
     * @mbggenerated Tue Jul 08 11:42:20 KST 2014
     */
    public void setDealInAmtCw53(Long dealInAmtCw53) {
        this.dealInAmtCw53 = dealInAmtCw53;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OP.T_FN_NICE_TRAN_CUPON.DEAL_IN_AMT_CW13
     *
     * @return the value of OP.T_FN_NICE_TRAN_CUPON.DEAL_IN_AMT_CW13
     *
     * @mbggenerated Tue Jul 08 11:42:20 KST 2014
     */
    public Long getDealInAmtCw13() {
        return dealInAmtCw13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OP.T_FN_NICE_TRAN_CUPON.DEAL_IN_AMT_CW13
     *
     * @param dealInAmtCw13 the value for OP.T_FN_NICE_TRAN_CUPON.DEAL_IN_AMT_CW13
     *
     * @mbggenerated Tue Jul 08 11:42:20 KST 2014
     */
    public void setDealInAmtCw13(Long dealInAmtCw13) {
        this.dealInAmtCw13 = dealInAmtCw13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OP.T_FN_NICE_TRAN_CUPON.DEAL_OUT_AMT_CW54
     *
     * @return the value of OP.T_FN_NICE_TRAN_CUPON.DEAL_OUT_AMT_CW54
     *
     * @mbggenerated Tue Jul 08 11:42:20 KST 2014
     */
    public Long getDealOutAmtCw54() {
        return dealOutAmtCw54;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OP.T_FN_NICE_TRAN_CUPON.DEAL_OUT_AMT_CW54
     *
     * @param dealOutAmtCw54 the value for OP.T_FN_NICE_TRAN_CUPON.DEAL_OUT_AMT_CW54
     *
     * @mbggenerated Tue Jul 08 11:42:20 KST 2014
     */
    public void setDealOutAmtCw54(Long dealOutAmtCw54) {
        this.dealOutAmtCw54 = dealOutAmtCw54;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OP.T_FN_NICE_TRAN_CUPON.DEAL_OUT_AMT_CW14
     *
     * @return the value of OP.T_FN_NICE_TRAN_CUPON.DEAL_OUT_AMT_CW14
     *
     * @mbggenerated Tue Jul 08 11:42:20 KST 2014
     */
    public Long getDealOutAmtCw14() {
        return dealOutAmtCw14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OP.T_FN_NICE_TRAN_CUPON.DEAL_OUT_AMT_CW14
     *
     * @param dealOutAmtCw14 the value for OP.T_FN_NICE_TRAN_CUPON.DEAL_OUT_AMT_CW14
     *
     * @mbggenerated Tue Jul 08 11:42:20 KST 2014
     */
    public void setDealOutAmtCw14(Long dealOutAmtCw14) {
        this.dealOutAmtCw14 = dealOutAmtCw14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OP.T_FN_NICE_TRAN_CUPON.DEAL_OUT_AMT_CW53
     *
     * @return the value of OP.T_FN_NICE_TRAN_CUPON.DEAL_OUT_AMT_CW53
     *
     * @mbggenerated Tue Jul 08 11:42:20 KST 2014
     */
    public Long getDealOutAmtCw53() {
        return dealOutAmtCw53;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OP.T_FN_NICE_TRAN_CUPON.DEAL_OUT_AMT_CW53
     *
     * @param dealOutAmtCw53 the value for OP.T_FN_NICE_TRAN_CUPON.DEAL_OUT_AMT_CW53
     *
     * @mbggenerated Tue Jul 08 11:42:20 KST 2014
     */
    public void setDealOutAmtCw53(Long dealOutAmtCw53) {
        this.dealOutAmtCw53 = dealOutAmtCw53;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OP.T_FN_NICE_TRAN_CUPON.DEAL_OUT_AMT_CW13
     *
     * @return the value of OP.T_FN_NICE_TRAN_CUPON.DEAL_OUT_AMT_CW13
     *
     * @mbggenerated Tue Jul 08 11:42:20 KST 2014
     */
    public Long getDealOutAmtCw13() {
        return dealOutAmtCw13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OP.T_FN_NICE_TRAN_CUPON.DEAL_OUT_AMT_CW13
     *
     * @param dealOutAmtCw13 the value for OP.T_FN_NICE_TRAN_CUPON.DEAL_OUT_AMT_CW13
     *
     * @mbggenerated Tue Jul 08 11:42:20 KST 2014
     */
    public void setDealOutAmtCw13(Long dealOutAmtCw13) {
        this.dealOutAmtCw13 = dealOutAmtCw13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OP.T_FN_NICE_TRAN_CUPON.DEAL_OUT_AMT_CW52
     *
     * @return the value of OP.T_FN_NICE_TRAN_CUPON.DEAL_OUT_AMT_CW52
     *
     * @mbggenerated Tue Jul 08 11:42:20 KST 2014
     */
    public Long getDealOutAmtCw52() {
        return dealOutAmtCw52;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OP.T_FN_NICE_TRAN_CUPON.DEAL_OUT_AMT_CW52
     *
     * @param dealOutAmtCw52 the value for OP.T_FN_NICE_TRAN_CUPON.DEAL_OUT_AMT_CW52
     *
     * @mbggenerated Tue Jul 08 11:42:20 KST 2014
     */
    public void setDealOutAmtCw52(Long dealOutAmtCw52) {
        this.dealOutAmtCw52 = dealOutAmtCw52;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OP.T_FN_NICE_TRAN_CUPON.DEAL_OUT_AMT_CW12
     *
     * @return the value of OP.T_FN_NICE_TRAN_CUPON.DEAL_OUT_AMT_CW12
     *
     * @mbggenerated Tue Jul 08 11:42:20 KST 2014
     */
    public Long getDealOutAmtCw12() {
        return dealOutAmtCw12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OP.T_FN_NICE_TRAN_CUPON.DEAL_OUT_AMT_CW12
     *
     * @param dealOutAmtCw12 the value for OP.T_FN_NICE_TRAN_CUPON.DEAL_OUT_AMT_CW12
     *
     * @mbggenerated Tue Jul 08 11:42:20 KST 2014
     */
    public void setDealOutAmtCw12(Long dealOutAmtCw12) {
        this.dealOutAmtCw12 = dealOutAmtCw12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OP.T_FN_NICE_TRAN_CUPON.DEAL_OUT_AMT_CW51
     *
     * @return the value of OP.T_FN_NICE_TRAN_CUPON.DEAL_OUT_AMT_CW51
     *
     * @mbggenerated Tue Jul 08 11:42:20 KST 2014
     */
    public Long getDealOutAmtCw51() {
        return dealOutAmtCw51;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OP.T_FN_NICE_TRAN_CUPON.DEAL_OUT_AMT_CW51
     *
     * @param dealOutAmtCw51 the value for OP.T_FN_NICE_TRAN_CUPON.DEAL_OUT_AMT_CW51
     *
     * @mbggenerated Tue Jul 08 11:42:20 KST 2014
     */
    public void setDealOutAmtCw51(Long dealOutAmtCw51) {
        this.dealOutAmtCw51 = dealOutAmtCw51;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OP.T_FN_NICE_TRAN_CUPON.DEAL_OUT_AMT_CW11
     *
     * @return the value of OP.T_FN_NICE_TRAN_CUPON.DEAL_OUT_AMT_CW11
     *
     * @mbggenerated Tue Jul 08 11:42:20 KST 2014
     */
    public Long getDealOutAmtCw11() {
        return dealOutAmtCw11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OP.T_FN_NICE_TRAN_CUPON.DEAL_OUT_AMT_CW11
     *
     * @param dealOutAmtCw11 the value for OP.T_FN_NICE_TRAN_CUPON.DEAL_OUT_AMT_CW11
     *
     * @mbggenerated Tue Jul 08 11:42:20 KST 2014
     */
    public void setDealOutAmtCw11(Long dealOutAmtCw11) {
        this.dealOutAmtCw11 = dealOutAmtCw11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OP.T_FN_NICE_TRAN_CUPON.INSERT_DATE
     *
     * @return the value of OP.T_FN_NICE_TRAN_CUPON.INSERT_DATE
     *
     * @mbggenerated Tue Jul 08 11:42:20 KST 2014
     */
    public Date getInsertDate() {
        return insertDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OP.T_FN_NICE_TRAN_CUPON.INSERT_DATE
     *
     * @param insertDate the value for OP.T_FN_NICE_TRAN_CUPON.INSERT_DATE
     *
     * @mbggenerated Tue Jul 08 11:42:20 KST 2014
     */
    public void setInsertDate(Date insertDate) {
        this.insertDate = insertDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OP.T_FN_NICE_TRAN_CUPON.INSERT_UID
     *
     * @return the value of OP.T_FN_NICE_TRAN_CUPON.INSERT_UID
     *
     * @mbggenerated Tue Jul 08 11:42:20 KST 2014
     */
    public String getInsertUid() {
        return insertUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OP.T_FN_NICE_TRAN_CUPON.INSERT_UID
     *
     * @param insertUid the value for OP.T_FN_NICE_TRAN_CUPON.INSERT_UID
     *
     * @mbggenerated Tue Jul 08 11:42:20 KST 2014
     */
    public void setInsertUid(String insertUid) {
        this.insertUid = insertUid;
    }
}