package com.nicetcm.nibsplus.broker.msg.model;

import java.util.Date;

public class TFnRealtimeTrade extends TFnRealtimeTradeKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OP.T_FN_REALTIME_TRADE.REMAIN_AMT
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    private Long remainAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OP.T_FN_REALTIME_TRADE.IN_10000_REMCNT
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    private Integer in10000Remcnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OP.T_FN_REALTIME_TRADE.IN_5000_REMCNT
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    private Integer in5000Remcnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OP.T_FN_REALTIME_TRADE.IN_1000_REMCNT
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    private Integer in1000Remcnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OP.T_FN_REALTIME_TRADE.OUT_10000_REMCNT
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    private Integer out10000Remcnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OP.T_FN_REALTIME_TRADE.OUT_5000_REMCNT
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    private Integer out5000Remcnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OP.T_FN_REALTIME_TRADE.OUT_1000_REMCNT
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    private Integer out1000Remcnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OP.T_FN_REALTIME_TRADE.OUT_100_REMCNT
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    private Integer out100Remcnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OP.T_FN_REALTIME_TRADE.IN_10000_CNT
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    private Integer in10000Cnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OP.T_FN_REALTIME_TRADE.IN_5000_CNT
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    private Integer in5000Cnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OP.T_FN_REALTIME_TRADE.IN_1000_CNT
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    private Integer in1000Cnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OP.T_FN_REALTIME_TRADE.OUT_10000_CNT
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    private Integer out10000Cnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OP.T_FN_REALTIME_TRADE.OUT_5000_CNT
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    private Integer out5000Cnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OP.T_FN_REALTIME_TRADE.OUT_1000_CNT
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    private Integer out1000Cnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OP.T_FN_REALTIME_TRADE.OUT_100_CNT
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    private Integer out100Cnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OP.T_FN_REALTIME_TRADE.NO_RTN_AMT
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    private Long noRtnAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OP.T_FN_REALTIME_TRADE.NO_RTN_NO
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    private String noRtnNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OP.T_FN_REALTIME_TRADE.UPDATE_DATE
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OP.T_FN_REALTIME_TRADE.UPDATE_UID
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    private String updateUid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OP.T_FN_REALTIME_TRADE.IN_50000_REMCNT
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    private Integer in50000Remcnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OP.T_FN_REALTIME_TRADE.IN_50000_CNT
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    private Integer in50000Cnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OP.T_FN_REALTIME_TRADE.IN_500_REMCNT
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    private Integer in500Remcnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OP.T_FN_REALTIME_TRADE.IN_100_REMCNT
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    private Integer in100Remcnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OP.T_FN_REALTIME_TRADE.IN_50_REMCNT
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    private Integer in50Remcnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OP.T_FN_REALTIME_TRADE.IN_10_REMCNT
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    private Integer in10Remcnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OP.T_FN_REALTIME_TRADE.IN_500_CNT
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    private Integer in500Cnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OP.T_FN_REALTIME_TRADE.IN_100_CNT
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    private Integer in100Cnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OP.T_FN_REALTIME_TRADE.IN_50_CNT
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    private Integer in50Cnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OP.T_FN_REALTIME_TRADE.IN_10_CNT
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    private Integer in10Cnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OP.T_FN_REALTIME_TRADE.OUT_50000_REMCNT
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    private Integer out50000Remcnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OP.T_FN_REALTIME_TRADE.OUT_50000_CNT
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    private Integer out50000Cnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OP.T_FN_REALTIME_TRADE.OUT_500_REMCNT
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    private Integer out500Remcnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OP.T_FN_REALTIME_TRADE.OUT_500_CNT
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    private Integer out500Cnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OP.T_FN_REALTIME_TRADE.OUT_50_REMCNT
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    private Integer out50Remcnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OP.T_FN_REALTIME_TRADE.OUT_50_CNT
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    private Integer out50Cnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OP.T_FN_REALTIME_TRADE.OUT_10_REMCNT
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    private Integer out10Remcnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OP.T_FN_REALTIME_TRADE.OUT_10_CNT
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    private Integer out10Cnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OP.T_FN_REALTIME_TRADE.SUB_ORG_CD
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    private String subOrgCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OP.T_FN_REALTIME_TRADE.ATM_DEAL_NO
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    private Integer atmDealNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OP.T_FN_REALTIME_TRADE.TRANS_SEQ
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    private String transSeq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OP.T_FN_REALTIME_TRADE.TRANS_DATE
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    private String transDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OP.T_FN_REALTIME_TRADE.REMAIN_AMT
     *
     * @return the value of OP.T_FN_REALTIME_TRADE.REMAIN_AMT
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    public Long getRemainAmt() {
        return remainAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OP.T_FN_REALTIME_TRADE.REMAIN_AMT
     *
     * @param remainAmt the value for OP.T_FN_REALTIME_TRADE.REMAIN_AMT
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    public void setRemainAmt(Long remainAmt) {
        this.remainAmt = remainAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OP.T_FN_REALTIME_TRADE.IN_10000_REMCNT
     *
     * @return the value of OP.T_FN_REALTIME_TRADE.IN_10000_REMCNT
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    public Integer getIn10000Remcnt() {
        return in10000Remcnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OP.T_FN_REALTIME_TRADE.IN_10000_REMCNT
     *
     * @param in10000Remcnt the value for OP.T_FN_REALTIME_TRADE.IN_10000_REMCNT
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    public void setIn10000Remcnt(Integer in10000Remcnt) {
        this.in10000Remcnt = in10000Remcnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OP.T_FN_REALTIME_TRADE.IN_5000_REMCNT
     *
     * @return the value of OP.T_FN_REALTIME_TRADE.IN_5000_REMCNT
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    public Integer getIn5000Remcnt() {
        return in5000Remcnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OP.T_FN_REALTIME_TRADE.IN_5000_REMCNT
     *
     * @param in5000Remcnt the value for OP.T_FN_REALTIME_TRADE.IN_5000_REMCNT
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    public void setIn5000Remcnt(Integer in5000Remcnt) {
        this.in5000Remcnt = in5000Remcnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OP.T_FN_REALTIME_TRADE.IN_1000_REMCNT
     *
     * @return the value of OP.T_FN_REALTIME_TRADE.IN_1000_REMCNT
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    public Integer getIn1000Remcnt() {
        return in1000Remcnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OP.T_FN_REALTIME_TRADE.IN_1000_REMCNT
     *
     * @param in1000Remcnt the value for OP.T_FN_REALTIME_TRADE.IN_1000_REMCNT
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    public void setIn1000Remcnt(Integer in1000Remcnt) {
        this.in1000Remcnt = in1000Remcnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OP.T_FN_REALTIME_TRADE.OUT_10000_REMCNT
     *
     * @return the value of OP.T_FN_REALTIME_TRADE.OUT_10000_REMCNT
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    public Integer getOut10000Remcnt() {
        return out10000Remcnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OP.T_FN_REALTIME_TRADE.OUT_10000_REMCNT
     *
     * @param out10000Remcnt the value for OP.T_FN_REALTIME_TRADE.OUT_10000_REMCNT
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    public void setOut10000Remcnt(Integer out10000Remcnt) {
        this.out10000Remcnt = out10000Remcnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OP.T_FN_REALTIME_TRADE.OUT_5000_REMCNT
     *
     * @return the value of OP.T_FN_REALTIME_TRADE.OUT_5000_REMCNT
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    public Integer getOut5000Remcnt() {
        return out5000Remcnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OP.T_FN_REALTIME_TRADE.OUT_5000_REMCNT
     *
     * @param out5000Remcnt the value for OP.T_FN_REALTIME_TRADE.OUT_5000_REMCNT
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    public void setOut5000Remcnt(Integer out5000Remcnt) {
        this.out5000Remcnt = out5000Remcnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OP.T_FN_REALTIME_TRADE.OUT_1000_REMCNT
     *
     * @return the value of OP.T_FN_REALTIME_TRADE.OUT_1000_REMCNT
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    public Integer getOut1000Remcnt() {
        return out1000Remcnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OP.T_FN_REALTIME_TRADE.OUT_1000_REMCNT
     *
     * @param out1000Remcnt the value for OP.T_FN_REALTIME_TRADE.OUT_1000_REMCNT
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    public void setOut1000Remcnt(Integer out1000Remcnt) {
        this.out1000Remcnt = out1000Remcnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OP.T_FN_REALTIME_TRADE.OUT_100_REMCNT
     *
     * @return the value of OP.T_FN_REALTIME_TRADE.OUT_100_REMCNT
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    public Integer getOut100Remcnt() {
        return out100Remcnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OP.T_FN_REALTIME_TRADE.OUT_100_REMCNT
     *
     * @param out100Remcnt the value for OP.T_FN_REALTIME_TRADE.OUT_100_REMCNT
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    public void setOut100Remcnt(Integer out100Remcnt) {
        this.out100Remcnt = out100Remcnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OP.T_FN_REALTIME_TRADE.IN_10000_CNT
     *
     * @return the value of OP.T_FN_REALTIME_TRADE.IN_10000_CNT
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    public Integer getIn10000Cnt() {
        return in10000Cnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OP.T_FN_REALTIME_TRADE.IN_10000_CNT
     *
     * @param in10000Cnt the value for OP.T_FN_REALTIME_TRADE.IN_10000_CNT
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    public void setIn10000Cnt(Integer in10000Cnt) {
        this.in10000Cnt = in10000Cnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OP.T_FN_REALTIME_TRADE.IN_5000_CNT
     *
     * @return the value of OP.T_FN_REALTIME_TRADE.IN_5000_CNT
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    public Integer getIn5000Cnt() {
        return in5000Cnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OP.T_FN_REALTIME_TRADE.IN_5000_CNT
     *
     * @param in5000Cnt the value for OP.T_FN_REALTIME_TRADE.IN_5000_CNT
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    public void setIn5000Cnt(Integer in5000Cnt) {
        this.in5000Cnt = in5000Cnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OP.T_FN_REALTIME_TRADE.IN_1000_CNT
     *
     * @return the value of OP.T_FN_REALTIME_TRADE.IN_1000_CNT
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    public Integer getIn1000Cnt() {
        return in1000Cnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OP.T_FN_REALTIME_TRADE.IN_1000_CNT
     *
     * @param in1000Cnt the value for OP.T_FN_REALTIME_TRADE.IN_1000_CNT
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    public void setIn1000Cnt(Integer in1000Cnt) {
        this.in1000Cnt = in1000Cnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OP.T_FN_REALTIME_TRADE.OUT_10000_CNT
     *
     * @return the value of OP.T_FN_REALTIME_TRADE.OUT_10000_CNT
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    public Integer getOut10000Cnt() {
        return out10000Cnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OP.T_FN_REALTIME_TRADE.OUT_10000_CNT
     *
     * @param out10000Cnt the value for OP.T_FN_REALTIME_TRADE.OUT_10000_CNT
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    public void setOut10000Cnt(Integer out10000Cnt) {
        this.out10000Cnt = out10000Cnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OP.T_FN_REALTIME_TRADE.OUT_5000_CNT
     *
     * @return the value of OP.T_FN_REALTIME_TRADE.OUT_5000_CNT
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    public Integer getOut5000Cnt() {
        return out5000Cnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OP.T_FN_REALTIME_TRADE.OUT_5000_CNT
     *
     * @param out5000Cnt the value for OP.T_FN_REALTIME_TRADE.OUT_5000_CNT
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    public void setOut5000Cnt(Integer out5000Cnt) {
        this.out5000Cnt = out5000Cnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OP.T_FN_REALTIME_TRADE.OUT_1000_CNT
     *
     * @return the value of OP.T_FN_REALTIME_TRADE.OUT_1000_CNT
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    public Integer getOut1000Cnt() {
        return out1000Cnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OP.T_FN_REALTIME_TRADE.OUT_1000_CNT
     *
     * @param out1000Cnt the value for OP.T_FN_REALTIME_TRADE.OUT_1000_CNT
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    public void setOut1000Cnt(Integer out1000Cnt) {
        this.out1000Cnt = out1000Cnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OP.T_FN_REALTIME_TRADE.OUT_100_CNT
     *
     * @return the value of OP.T_FN_REALTIME_TRADE.OUT_100_CNT
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    public Integer getOut100Cnt() {
        return out100Cnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OP.T_FN_REALTIME_TRADE.OUT_100_CNT
     *
     * @param out100Cnt the value for OP.T_FN_REALTIME_TRADE.OUT_100_CNT
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    public void setOut100Cnt(Integer out100Cnt) {
        this.out100Cnt = out100Cnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OP.T_FN_REALTIME_TRADE.NO_RTN_AMT
     *
     * @return the value of OP.T_FN_REALTIME_TRADE.NO_RTN_AMT
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    public Long getNoRtnAmt() {
        return noRtnAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OP.T_FN_REALTIME_TRADE.NO_RTN_AMT
     *
     * @param noRtnAmt the value for OP.T_FN_REALTIME_TRADE.NO_RTN_AMT
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    public void setNoRtnAmt(Long noRtnAmt) {
        this.noRtnAmt = noRtnAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OP.T_FN_REALTIME_TRADE.NO_RTN_NO
     *
     * @return the value of OP.T_FN_REALTIME_TRADE.NO_RTN_NO
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    public String getNoRtnNo() {
        return noRtnNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OP.T_FN_REALTIME_TRADE.NO_RTN_NO
     *
     * @param noRtnNo the value for OP.T_FN_REALTIME_TRADE.NO_RTN_NO
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    public void setNoRtnNo(String noRtnNo) {
        this.noRtnNo = noRtnNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OP.T_FN_REALTIME_TRADE.UPDATE_DATE
     *
     * @return the value of OP.T_FN_REALTIME_TRADE.UPDATE_DATE
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OP.T_FN_REALTIME_TRADE.UPDATE_DATE
     *
     * @param updateDate the value for OP.T_FN_REALTIME_TRADE.UPDATE_DATE
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OP.T_FN_REALTIME_TRADE.UPDATE_UID
     *
     * @return the value of OP.T_FN_REALTIME_TRADE.UPDATE_UID
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    public String getUpdateUid() {
        return updateUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OP.T_FN_REALTIME_TRADE.UPDATE_UID
     *
     * @param updateUid the value for OP.T_FN_REALTIME_TRADE.UPDATE_UID
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    public void setUpdateUid(String updateUid) {
        this.updateUid = updateUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OP.T_FN_REALTIME_TRADE.IN_50000_REMCNT
     *
     * @return the value of OP.T_FN_REALTIME_TRADE.IN_50000_REMCNT
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    public Integer getIn50000Remcnt() {
        return in50000Remcnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OP.T_FN_REALTIME_TRADE.IN_50000_REMCNT
     *
     * @param in50000Remcnt the value for OP.T_FN_REALTIME_TRADE.IN_50000_REMCNT
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    public void setIn50000Remcnt(Integer in50000Remcnt) {
        this.in50000Remcnt = in50000Remcnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OP.T_FN_REALTIME_TRADE.IN_50000_CNT
     *
     * @return the value of OP.T_FN_REALTIME_TRADE.IN_50000_CNT
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    public Integer getIn50000Cnt() {
        return in50000Cnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OP.T_FN_REALTIME_TRADE.IN_50000_CNT
     *
     * @param in50000Cnt the value for OP.T_FN_REALTIME_TRADE.IN_50000_CNT
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    public void setIn50000Cnt(Integer in50000Cnt) {
        this.in50000Cnt = in50000Cnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OP.T_FN_REALTIME_TRADE.IN_500_REMCNT
     *
     * @return the value of OP.T_FN_REALTIME_TRADE.IN_500_REMCNT
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    public Integer getIn500Remcnt() {
        return in500Remcnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OP.T_FN_REALTIME_TRADE.IN_500_REMCNT
     *
     * @param in500Remcnt the value for OP.T_FN_REALTIME_TRADE.IN_500_REMCNT
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    public void setIn500Remcnt(Integer in500Remcnt) {
        this.in500Remcnt = in500Remcnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OP.T_FN_REALTIME_TRADE.IN_100_REMCNT
     *
     * @return the value of OP.T_FN_REALTIME_TRADE.IN_100_REMCNT
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    public Integer getIn100Remcnt() {
        return in100Remcnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OP.T_FN_REALTIME_TRADE.IN_100_REMCNT
     *
     * @param in100Remcnt the value for OP.T_FN_REALTIME_TRADE.IN_100_REMCNT
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    public void setIn100Remcnt(Integer in100Remcnt) {
        this.in100Remcnt = in100Remcnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OP.T_FN_REALTIME_TRADE.IN_50_REMCNT
     *
     * @return the value of OP.T_FN_REALTIME_TRADE.IN_50_REMCNT
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    public Integer getIn50Remcnt() {
        return in50Remcnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OP.T_FN_REALTIME_TRADE.IN_50_REMCNT
     *
     * @param in50Remcnt the value for OP.T_FN_REALTIME_TRADE.IN_50_REMCNT
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    public void setIn50Remcnt(Integer in50Remcnt) {
        this.in50Remcnt = in50Remcnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OP.T_FN_REALTIME_TRADE.IN_10_REMCNT
     *
     * @return the value of OP.T_FN_REALTIME_TRADE.IN_10_REMCNT
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    public Integer getIn10Remcnt() {
        return in10Remcnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OP.T_FN_REALTIME_TRADE.IN_10_REMCNT
     *
     * @param in10Remcnt the value for OP.T_FN_REALTIME_TRADE.IN_10_REMCNT
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    public void setIn10Remcnt(Integer in10Remcnt) {
        this.in10Remcnt = in10Remcnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OP.T_FN_REALTIME_TRADE.IN_500_CNT
     *
     * @return the value of OP.T_FN_REALTIME_TRADE.IN_500_CNT
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    public Integer getIn500Cnt() {
        return in500Cnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OP.T_FN_REALTIME_TRADE.IN_500_CNT
     *
     * @param in500Cnt the value for OP.T_FN_REALTIME_TRADE.IN_500_CNT
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    public void setIn500Cnt(Integer in500Cnt) {
        this.in500Cnt = in500Cnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OP.T_FN_REALTIME_TRADE.IN_100_CNT
     *
     * @return the value of OP.T_FN_REALTIME_TRADE.IN_100_CNT
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    public Integer getIn100Cnt() {
        return in100Cnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OP.T_FN_REALTIME_TRADE.IN_100_CNT
     *
     * @param in100Cnt the value for OP.T_FN_REALTIME_TRADE.IN_100_CNT
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    public void setIn100Cnt(Integer in100Cnt) {
        this.in100Cnt = in100Cnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OP.T_FN_REALTIME_TRADE.IN_50_CNT
     *
     * @return the value of OP.T_FN_REALTIME_TRADE.IN_50_CNT
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    public Integer getIn50Cnt() {
        return in50Cnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OP.T_FN_REALTIME_TRADE.IN_50_CNT
     *
     * @param in50Cnt the value for OP.T_FN_REALTIME_TRADE.IN_50_CNT
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    public void setIn50Cnt(Integer in50Cnt) {
        this.in50Cnt = in50Cnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OP.T_FN_REALTIME_TRADE.IN_10_CNT
     *
     * @return the value of OP.T_FN_REALTIME_TRADE.IN_10_CNT
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    public Integer getIn10Cnt() {
        return in10Cnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OP.T_FN_REALTIME_TRADE.IN_10_CNT
     *
     * @param in10Cnt the value for OP.T_FN_REALTIME_TRADE.IN_10_CNT
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    public void setIn10Cnt(Integer in10Cnt) {
        this.in10Cnt = in10Cnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OP.T_FN_REALTIME_TRADE.OUT_50000_REMCNT
     *
     * @return the value of OP.T_FN_REALTIME_TRADE.OUT_50000_REMCNT
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    public Integer getOut50000Remcnt() {
        return out50000Remcnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OP.T_FN_REALTIME_TRADE.OUT_50000_REMCNT
     *
     * @param out50000Remcnt the value for OP.T_FN_REALTIME_TRADE.OUT_50000_REMCNT
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    public void setOut50000Remcnt(Integer out50000Remcnt) {
        this.out50000Remcnt = out50000Remcnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OP.T_FN_REALTIME_TRADE.OUT_50000_CNT
     *
     * @return the value of OP.T_FN_REALTIME_TRADE.OUT_50000_CNT
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    public Integer getOut50000Cnt() {
        return out50000Cnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OP.T_FN_REALTIME_TRADE.OUT_50000_CNT
     *
     * @param out50000Cnt the value for OP.T_FN_REALTIME_TRADE.OUT_50000_CNT
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    public void setOut50000Cnt(Integer out50000Cnt) {
        this.out50000Cnt = out50000Cnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OP.T_FN_REALTIME_TRADE.OUT_500_REMCNT
     *
     * @return the value of OP.T_FN_REALTIME_TRADE.OUT_500_REMCNT
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    public Integer getOut500Remcnt() {
        return out500Remcnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OP.T_FN_REALTIME_TRADE.OUT_500_REMCNT
     *
     * @param out500Remcnt the value for OP.T_FN_REALTIME_TRADE.OUT_500_REMCNT
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    public void setOut500Remcnt(Integer out500Remcnt) {
        this.out500Remcnt = out500Remcnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OP.T_FN_REALTIME_TRADE.OUT_500_CNT
     *
     * @return the value of OP.T_FN_REALTIME_TRADE.OUT_500_CNT
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    public Integer getOut500Cnt() {
        return out500Cnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OP.T_FN_REALTIME_TRADE.OUT_500_CNT
     *
     * @param out500Cnt the value for OP.T_FN_REALTIME_TRADE.OUT_500_CNT
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    public void setOut500Cnt(Integer out500Cnt) {
        this.out500Cnt = out500Cnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OP.T_FN_REALTIME_TRADE.OUT_50_REMCNT
     *
     * @return the value of OP.T_FN_REALTIME_TRADE.OUT_50_REMCNT
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    public Integer getOut50Remcnt() {
        return out50Remcnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OP.T_FN_REALTIME_TRADE.OUT_50_REMCNT
     *
     * @param out50Remcnt the value for OP.T_FN_REALTIME_TRADE.OUT_50_REMCNT
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    public void setOut50Remcnt(Integer out50Remcnt) {
        this.out50Remcnt = out50Remcnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OP.T_FN_REALTIME_TRADE.OUT_50_CNT
     *
     * @return the value of OP.T_FN_REALTIME_TRADE.OUT_50_CNT
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    public Integer getOut50Cnt() {
        return out50Cnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OP.T_FN_REALTIME_TRADE.OUT_50_CNT
     *
     * @param out50Cnt the value for OP.T_FN_REALTIME_TRADE.OUT_50_CNT
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    public void setOut50Cnt(Integer out50Cnt) {
        this.out50Cnt = out50Cnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OP.T_FN_REALTIME_TRADE.OUT_10_REMCNT
     *
     * @return the value of OP.T_FN_REALTIME_TRADE.OUT_10_REMCNT
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    public Integer getOut10Remcnt() {
        return out10Remcnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OP.T_FN_REALTIME_TRADE.OUT_10_REMCNT
     *
     * @param out10Remcnt the value for OP.T_FN_REALTIME_TRADE.OUT_10_REMCNT
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    public void setOut10Remcnt(Integer out10Remcnt) {
        this.out10Remcnt = out10Remcnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OP.T_FN_REALTIME_TRADE.OUT_10_CNT
     *
     * @return the value of OP.T_FN_REALTIME_TRADE.OUT_10_CNT
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    public Integer getOut10Cnt() {
        return out10Cnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OP.T_FN_REALTIME_TRADE.OUT_10_CNT
     *
     * @param out10Cnt the value for OP.T_FN_REALTIME_TRADE.OUT_10_CNT
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    public void setOut10Cnt(Integer out10Cnt) {
        this.out10Cnt = out10Cnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OP.T_FN_REALTIME_TRADE.SUB_ORG_CD
     *
     * @return the value of OP.T_FN_REALTIME_TRADE.SUB_ORG_CD
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    public String getSubOrgCd() {
        return subOrgCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OP.T_FN_REALTIME_TRADE.SUB_ORG_CD
     *
     * @param subOrgCd the value for OP.T_FN_REALTIME_TRADE.SUB_ORG_CD
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    public void setSubOrgCd(String subOrgCd) {
        this.subOrgCd = subOrgCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OP.T_FN_REALTIME_TRADE.ATM_DEAL_NO
     *
     * @return the value of OP.T_FN_REALTIME_TRADE.ATM_DEAL_NO
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    public Integer getAtmDealNo() {
        return atmDealNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OP.T_FN_REALTIME_TRADE.ATM_DEAL_NO
     *
     * @param atmDealNo the value for OP.T_FN_REALTIME_TRADE.ATM_DEAL_NO
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    public void setAtmDealNo(Integer atmDealNo) {
        this.atmDealNo = atmDealNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OP.T_FN_REALTIME_TRADE.TRANS_SEQ
     *
     * @return the value of OP.T_FN_REALTIME_TRADE.TRANS_SEQ
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    public String getTransSeq() {
        return transSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OP.T_FN_REALTIME_TRADE.TRANS_SEQ
     *
     * @param transSeq the value for OP.T_FN_REALTIME_TRADE.TRANS_SEQ
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    public void setTransSeq(String transSeq) {
        this.transSeq = transSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OP.T_FN_REALTIME_TRADE.TRANS_DATE
     *
     * @return the value of OP.T_FN_REALTIME_TRADE.TRANS_DATE
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    public String getTransDate() {
        return transDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OP.T_FN_REALTIME_TRADE.TRANS_DATE
     *
     * @param transDate the value for OP.T_FN_REALTIME_TRADE.TRANS_DATE
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    public void setTransDate(String transDate) {
        this.transDate = transDate;
    }
}