package com.nicetcm.nibsplus.broker.msg.mapper;

import com.nicetcm.nibsplus.broker.msg.model.TFnAtmsAddCashReport;
import com.nicetcm.nibsplus.broker.msg.model.TFnAtmsAddCashReportKey;
import com.nicetcm.nibsplus.broker.msg.model.TFnAtmsAddCashReportSpec;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface TFnAtmsAddCashReportMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_ATMS_ADD_CASH_REPORT
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    @SelectProvider(type=TFnAtmsAddCashReportSqlProvider.class, method="countBySpec")
    int countBySpec(TFnAtmsAddCashReportSpec spec);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_ATMS_ADD_CASH_REPORT
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    @DeleteProvider(type=TFnAtmsAddCashReportSqlProvider.class, method="deleteBySpec")
    int deleteBySpec(TFnAtmsAddCashReportSpec spec);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_ATMS_ADD_CASH_REPORT
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    @Delete({
        "delete from OP.T_FN_ATMS_ADD_CASH_REPORT",
        "where ORG_CD = #{orgCd,jdbcType=VARCHAR}",
          "and BRANCH_CD = #{branchCd,jdbcType=VARCHAR}",
          "and SITE_CD = #{siteCd,jdbcType=VARCHAR}",
          "and MAC_NO = #{macNo,jdbcType=VARCHAR}",
          "and ADD_DATE = #{addDate,jdbcType=VARCHAR}",
          "and SERIAL_NO = #{serialNo,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(TFnAtmsAddCashReportKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_ATMS_ADD_CASH_REPORT
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    @Insert({
        "insert into OP.T_FN_ATMS_ADD_CASH_REPORT (ORG_CD, BRANCH_CD, ",
        "SITE_CD, MAC_NO, ADD_DATE, ",
        "SERIAL_NO, DEMAND_DATE, ",
        "ADD_CASH_AMT, OFFICE_NM, ",
        "ORG_SEND_YN, UPDATE_DATE, ",
        "UPDATE_UID, ADD_TIME, ",
        "CLOSE_YN, SEND_DATE, ",
        "ADD_CHECK_AMT, CHECK_10_CNT, ",
        "CHECK_30_CNT, CHECK_50_CNT, ",
        "CHECK_100_CNT, SAFE_TYPE, ",
        "ADD_50000_AMT, ADD_10000_AMT)",
        "values (#{orgCd,jdbcType=VARCHAR}, #{branchCd,jdbcType=VARCHAR}, ",
        "#{siteCd,jdbcType=VARCHAR}, #{macNo,jdbcType=VARCHAR}, #{addDate,jdbcType=VARCHAR}, ",
        "#{serialNo,jdbcType=VARCHAR}, #{demandDate,jdbcType=VARCHAR}, ",
        "#{addCashAmt,jdbcType=DECIMAL}, #{officeNm,jdbcType=VARCHAR}, ",
        "#{orgSendYn,jdbcType=VARCHAR}, #{updateDate,jdbcType=TIMESTAMP}, ",
        "#{updateUid,jdbcType=VARCHAR}, #{addTime,jdbcType=VARCHAR}, ",
        "#{closeYn,jdbcType=VARCHAR}, #{sendDate,jdbcType=VARCHAR}, ",
        "#{addCheckAmt,jdbcType=DECIMAL}, #{check10Cnt,jdbcType=DECIMAL}, ",
        "#{check30Cnt,jdbcType=DECIMAL}, #{check50Cnt,jdbcType=DECIMAL}, ",
        "#{check100Cnt,jdbcType=DECIMAL}, #{safeType,jdbcType=VARCHAR}, ",
        "#{add50000Amt,jdbcType=DECIMAL}, #{add10000Amt,jdbcType=DECIMAL})"
    })
    int insert(TFnAtmsAddCashReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_ATMS_ADD_CASH_REPORT
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    @InsertProvider(type=TFnAtmsAddCashReportSqlProvider.class, method="insertSelective")
    int insertSelective(TFnAtmsAddCashReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_ATMS_ADD_CASH_REPORT
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    @SelectProvider(type=TFnAtmsAddCashReportSqlProvider.class, method="selectBySpec")
    @Results({
        @Result(column="ORG_CD", property="orgCd", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="BRANCH_CD", property="branchCd", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="SITE_CD", property="siteCd", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="MAC_NO", property="macNo", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="ADD_DATE", property="addDate", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="SERIAL_NO", property="serialNo", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="DEMAND_DATE", property="demandDate", jdbcType=JdbcType.VARCHAR),
        @Result(column="ADD_CASH_AMT", property="addCashAmt", jdbcType=JdbcType.DECIMAL),
        @Result(column="OFFICE_NM", property="officeNm", jdbcType=JdbcType.VARCHAR),
        @Result(column="ORG_SEND_YN", property="orgSendYn", jdbcType=JdbcType.VARCHAR),
        @Result(column="UPDATE_DATE", property="updateDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="UPDATE_UID", property="updateUid", jdbcType=JdbcType.VARCHAR),
        @Result(column="ADD_TIME", property="addTime", jdbcType=JdbcType.VARCHAR),
        @Result(column="CLOSE_YN", property="closeYn", jdbcType=JdbcType.VARCHAR),
        @Result(column="SEND_DATE", property="sendDate", jdbcType=JdbcType.VARCHAR),
        @Result(column="ADD_CHECK_AMT", property="addCheckAmt", jdbcType=JdbcType.DECIMAL),
        @Result(column="CHECK_10_CNT", property="check10Cnt", jdbcType=JdbcType.DECIMAL),
        @Result(column="CHECK_30_CNT", property="check30Cnt", jdbcType=JdbcType.DECIMAL),
        @Result(column="CHECK_50_CNT", property="check50Cnt", jdbcType=JdbcType.DECIMAL),
        @Result(column="CHECK_100_CNT", property="check100Cnt", jdbcType=JdbcType.DECIMAL),
        @Result(column="SAFE_TYPE", property="safeType", jdbcType=JdbcType.VARCHAR),
        @Result(column="ADD_50000_AMT", property="add50000Amt", jdbcType=JdbcType.DECIMAL),
        @Result(column="ADD_10000_AMT", property="add10000Amt", jdbcType=JdbcType.DECIMAL)
    })
    List<TFnAtmsAddCashReport> selectBySpec(TFnAtmsAddCashReportSpec spec);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_ATMS_ADD_CASH_REPORT
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    @Select({
        "select",
        "ORG_CD, BRANCH_CD, SITE_CD, MAC_NO, ADD_DATE, SERIAL_NO, DEMAND_DATE, ADD_CASH_AMT, ",
        "OFFICE_NM, ORG_SEND_YN, UPDATE_DATE, UPDATE_UID, ADD_TIME, CLOSE_YN, SEND_DATE, ",
        "ADD_CHECK_AMT, CHECK_10_CNT, CHECK_30_CNT, CHECK_50_CNT, CHECK_100_CNT, SAFE_TYPE, ",
        "ADD_50000_AMT, ADD_10000_AMT",
        "from OP.T_FN_ATMS_ADD_CASH_REPORT",
        "where ORG_CD = #{orgCd,jdbcType=VARCHAR}",
          "and BRANCH_CD = #{branchCd,jdbcType=VARCHAR}",
          "and SITE_CD = #{siteCd,jdbcType=VARCHAR}",
          "and MAC_NO = #{macNo,jdbcType=VARCHAR}",
          "and ADD_DATE = #{addDate,jdbcType=VARCHAR}",
          "and SERIAL_NO = #{serialNo,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="ORG_CD", property="orgCd", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="BRANCH_CD", property="branchCd", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="SITE_CD", property="siteCd", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="MAC_NO", property="macNo", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="ADD_DATE", property="addDate", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="SERIAL_NO", property="serialNo", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="DEMAND_DATE", property="demandDate", jdbcType=JdbcType.VARCHAR),
        @Result(column="ADD_CASH_AMT", property="addCashAmt", jdbcType=JdbcType.DECIMAL),
        @Result(column="OFFICE_NM", property="officeNm", jdbcType=JdbcType.VARCHAR),
        @Result(column="ORG_SEND_YN", property="orgSendYn", jdbcType=JdbcType.VARCHAR),
        @Result(column="UPDATE_DATE", property="updateDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="UPDATE_UID", property="updateUid", jdbcType=JdbcType.VARCHAR),
        @Result(column="ADD_TIME", property="addTime", jdbcType=JdbcType.VARCHAR),
        @Result(column="CLOSE_YN", property="closeYn", jdbcType=JdbcType.VARCHAR),
        @Result(column="SEND_DATE", property="sendDate", jdbcType=JdbcType.VARCHAR),
        @Result(column="ADD_CHECK_AMT", property="addCheckAmt", jdbcType=JdbcType.DECIMAL),
        @Result(column="CHECK_10_CNT", property="check10Cnt", jdbcType=JdbcType.DECIMAL),
        @Result(column="CHECK_30_CNT", property="check30Cnt", jdbcType=JdbcType.DECIMAL),
        @Result(column="CHECK_50_CNT", property="check50Cnt", jdbcType=JdbcType.DECIMAL),
        @Result(column="CHECK_100_CNT", property="check100Cnt", jdbcType=JdbcType.DECIMAL),
        @Result(column="SAFE_TYPE", property="safeType", jdbcType=JdbcType.VARCHAR),
        @Result(column="ADD_50000_AMT", property="add50000Amt", jdbcType=JdbcType.DECIMAL),
        @Result(column="ADD_10000_AMT", property="add10000Amt", jdbcType=JdbcType.DECIMAL)
    })
    TFnAtmsAddCashReport selectByPrimaryKey(TFnAtmsAddCashReportKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_ATMS_ADD_CASH_REPORT
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    @UpdateProvider(type=TFnAtmsAddCashReportSqlProvider.class, method="updateBySpecSelective")
    int updateBySpecSelective(@Param("record") TFnAtmsAddCashReport record, @Param("spec") TFnAtmsAddCashReportSpec spec);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_ATMS_ADD_CASH_REPORT
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    @UpdateProvider(type=TFnAtmsAddCashReportSqlProvider.class, method="updateBySpec")
    int updateBySpec(@Param("record") TFnAtmsAddCashReport record, @Param("spec") TFnAtmsAddCashReportSpec spec);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_ATMS_ADD_CASH_REPORT
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    @UpdateProvider(type=TFnAtmsAddCashReportSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(TFnAtmsAddCashReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_ATMS_ADD_CASH_REPORT
     *
     * @mbggenerated Tue Jul 22 10:58:58 KST 2014
     */
    @Update({
        "update OP.T_FN_ATMS_ADD_CASH_REPORT",
        "set DEMAND_DATE = #{demandDate,jdbcType=VARCHAR},",
          "ADD_CASH_AMT = #{addCashAmt,jdbcType=DECIMAL},",
          "OFFICE_NM = #{officeNm,jdbcType=VARCHAR},",
          "ORG_SEND_YN = #{orgSendYn,jdbcType=VARCHAR},",
          "UPDATE_DATE = #{updateDate,jdbcType=TIMESTAMP},",
          "UPDATE_UID = #{updateUid,jdbcType=VARCHAR},",
          "ADD_TIME = #{addTime,jdbcType=VARCHAR},",
          "CLOSE_YN = #{closeYn,jdbcType=VARCHAR},",
          "SEND_DATE = #{sendDate,jdbcType=VARCHAR},",
          "ADD_CHECK_AMT = #{addCheckAmt,jdbcType=DECIMAL},",
          "CHECK_10_CNT = #{check10Cnt,jdbcType=DECIMAL},",
          "CHECK_30_CNT = #{check30Cnt,jdbcType=DECIMAL},",
          "CHECK_50_CNT = #{check50Cnt,jdbcType=DECIMAL},",
          "CHECK_100_CNT = #{check100Cnt,jdbcType=DECIMAL},",
          "SAFE_TYPE = #{safeType,jdbcType=VARCHAR},",
          "ADD_50000_AMT = #{add50000Amt,jdbcType=DECIMAL},",
          "ADD_10000_AMT = #{add10000Amt,jdbcType=DECIMAL}",
        "where ORG_CD = #{orgCd,jdbcType=VARCHAR}",
          "and BRANCH_CD = #{branchCd,jdbcType=VARCHAR}",
          "and SITE_CD = #{siteCd,jdbcType=VARCHAR}",
          "and MAC_NO = #{macNo,jdbcType=VARCHAR}",
          "and ADD_DATE = #{addDate,jdbcType=VARCHAR}",
          "and SERIAL_NO = #{serialNo,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(TFnAtmsAddCashReport record);
}