
DECLARE 
  PCLOSEDATE VARCHAR2(8);
  PORGCODE VARCHAR2(3);
  PJIJUMCODE VARCHAR2(8);
  PMACNO VARCHAR2(12);
  PUSERID VARCHAR2(7);
  VRESULT VARCHAR2(200);

BEGIN 
  PCLOSEDATE := '20100617';
  PORGCODE := '096';
  PJIJUMCODE := '9600';
  PMACNO := '8867';
  PUSERID := 'HOST';
  VRESULT := NULL;

  NIBS.SP_FN_MACCLOSE ( PCLOSEDATE, PORGCODE, PJIJUMCODE, PMACNO, PUSERID, VRESULT );
  dbms_output.put_line('VRESULT : ' ||VRESULT);
  COMMIT; 
END;

exit;
