DECLARE 
  PDATE VARCHAR2(200);

BEGIN 
  SELECT TO_CHAR(SYSDATE - 2,'YYYYMMDD')
  INTO PDATE
  FROM DUAL;

  NIBS.SP_FN_SITECOUNT ( PDATE );
  
  DELETE T_CM_CASH
  WHERE CASH_DATE >= PDATE
  	AND ORG_CD = '0KU';
  
  COMMIT; 
END;
/
EXIT; 