package com.nicetcm.nibsplus.broker.ams.mapper;

import com.nicetcm.nibsplus.broker.ams.model.TRcRegInf;
import com.nicetcm.nibsplus.broker.ams.model.TRcRegInfKey;
import com.nicetcm.nibsplus.broker.ams.model.TRcRegInfSpec;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface TRcRegInfMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IN.T_RC_REG_INF
     *
     * @mbggenerated Tue Aug 19 16:35:31 KST 2014
     */
    @SelectProvider(type=TRcRegInfSqlProvider.class, method="countBySpec")
    int countBySpec(TRcRegInfSpec spec);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IN.T_RC_REG_INF
     *
     * @mbggenerated Tue Aug 19 16:35:31 KST 2014
     */
    @DeleteProvider(type=TRcRegInfSqlProvider.class, method="deleteBySpec")
    int deleteBySpec(TRcRegInfSpec spec);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IN.T_RC_REG_INF
     *
     * @mbggenerated Tue Aug 19 16:35:31 KST 2014
     */
    @Delete({
        "delete from IN.T_RC_REG_INF",
        "where ORG_CD = #{orgCd,jdbcType=VARCHAR}",
          "and BRANCH_CD = #{branchCd,jdbcType=VARCHAR}",
          "and MAC_NO = #{macNo,jdbcType=VARCHAR}",
          "and REG_BASE_KEY = #{regBaseKey,jdbcType=VARCHAR}",
          "and REG_KEY_PATH = #{regKeyPath,jdbcType=VARCHAR}",
          "and REG_KEY_NM = #{regKeyNm,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(TRcRegInfKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IN.T_RC_REG_INF
     *
     * @mbggenerated Tue Aug 19 16:35:31 KST 2014
     */
    @Insert({
        "insert into IN.T_RC_REG_INF (ORG_CD, BRANCH_CD, ",
        "MAC_NO, REG_BASE_KEY, ",
        "REG_KEY_PATH, REG_KEY_NM, ",
        "INSERT_UID, INSERT_DATE, ",
        "UPDATE_UID, UPDATE_DATE, ",
        "REG_VAL)",
        "values (#{orgCd,jdbcType=VARCHAR}, #{branchCd,jdbcType=VARCHAR}, ",
        "#{macNo,jdbcType=VARCHAR}, #{regBaseKey,jdbcType=VARCHAR}, ",
        "#{regKeyPath,jdbcType=VARCHAR}, #{regKeyNm,jdbcType=VARCHAR}, ",
        "#{insertUid,jdbcType=VARCHAR}, #{insertDate,jdbcType=TIMESTAMP}, ",
        "#{updateUid,jdbcType=VARCHAR}, #{updateDate,jdbcType=TIMESTAMP}, ",
        "#{regVal,jdbcType=VARCHAR})"
    })
    int insert(TRcRegInf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IN.T_RC_REG_INF
     *
     * @mbggenerated Tue Aug 19 16:35:31 KST 2014
     */
    @InsertProvider(type=TRcRegInfSqlProvider.class, method="insertSelective")
    int insertSelective(TRcRegInf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IN.T_RC_REG_INF
     *
     * @mbggenerated Tue Aug 19 16:35:31 KST 2014
     */
    @SelectProvider(type=TRcRegInfSqlProvider.class, method="selectBySpec")
    @Results({
        @Result(column="ORG_CD", property="orgCd", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="BRANCH_CD", property="branchCd", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="MAC_NO", property="macNo", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="REG_BASE_KEY", property="regBaseKey", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="REG_KEY_PATH", property="regKeyPath", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="REG_KEY_NM", property="regKeyNm", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="INSERT_UID", property="insertUid", jdbcType=JdbcType.VARCHAR),
        @Result(column="INSERT_DATE", property="insertDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="UPDATE_UID", property="updateUid", jdbcType=JdbcType.VARCHAR),
        @Result(column="UPDATE_DATE", property="updateDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="REG_VAL", property="regVal", jdbcType=JdbcType.VARCHAR)
    })
    List<TRcRegInf> selectBySpec(TRcRegInfSpec spec);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IN.T_RC_REG_INF
     *
     * @mbggenerated Tue Aug 19 16:35:31 KST 2014
     */
    @Select({
        "select",
        "ORG_CD, BRANCH_CD, MAC_NO, REG_BASE_KEY, REG_KEY_PATH, REG_KEY_NM, INSERT_UID, ",
        "INSERT_DATE, UPDATE_UID, UPDATE_DATE, REG_VAL",
        "from IN.T_RC_REG_INF",
        "where ORG_CD = #{orgCd,jdbcType=VARCHAR}",
          "and BRANCH_CD = #{branchCd,jdbcType=VARCHAR}",
          "and MAC_NO = #{macNo,jdbcType=VARCHAR}",
          "and REG_BASE_KEY = #{regBaseKey,jdbcType=VARCHAR}",
          "and REG_KEY_PATH = #{regKeyPath,jdbcType=VARCHAR}",
          "and REG_KEY_NM = #{regKeyNm,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="ORG_CD", property="orgCd", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="BRANCH_CD", property="branchCd", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="MAC_NO", property="macNo", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="REG_BASE_KEY", property="regBaseKey", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="REG_KEY_PATH", property="regKeyPath", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="REG_KEY_NM", property="regKeyNm", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="INSERT_UID", property="insertUid", jdbcType=JdbcType.VARCHAR),
        @Result(column="INSERT_DATE", property="insertDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="UPDATE_UID", property="updateUid", jdbcType=JdbcType.VARCHAR),
        @Result(column="UPDATE_DATE", property="updateDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="REG_VAL", property="regVal", jdbcType=JdbcType.VARCHAR)
    })
    TRcRegInf selectByPrimaryKey(TRcRegInfKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IN.T_RC_REG_INF
     *
     * @mbggenerated Tue Aug 19 16:35:31 KST 2014
     */
    @UpdateProvider(type=TRcRegInfSqlProvider.class, method="updateBySpecSelective")
    int updateBySpecSelective(@Param("record") TRcRegInf record, @Param("spec") TRcRegInfSpec spec);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IN.T_RC_REG_INF
     *
     * @mbggenerated Tue Aug 19 16:35:31 KST 2014
     */
    @UpdateProvider(type=TRcRegInfSqlProvider.class, method="updateBySpec")
    int updateBySpec(@Param("record") TRcRegInf record, @Param("spec") TRcRegInfSpec spec);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IN.T_RC_REG_INF
     *
     * @mbggenerated Tue Aug 19 16:35:31 KST 2014
     */
    @UpdateProvider(type=TRcRegInfSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(TRcRegInf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IN.T_RC_REG_INF
     *
     * @mbggenerated Tue Aug 19 16:35:31 KST 2014
     */
    @Update({
        "update IN.T_RC_REG_INF",
        "set INSERT_UID = #{insertUid,jdbcType=VARCHAR},",
          "INSERT_DATE = #{insertDate,jdbcType=TIMESTAMP},",
          "UPDATE_UID = #{updateUid,jdbcType=VARCHAR},",
          "UPDATE_DATE = #{updateDate,jdbcType=TIMESTAMP},",
          "REG_VAL = #{regVal,jdbcType=VARCHAR}",
        "where ORG_CD = #{orgCd,jdbcType=VARCHAR}",
          "and BRANCH_CD = #{branchCd,jdbcType=VARCHAR}",
          "and MAC_NO = #{macNo,jdbcType=VARCHAR}",
          "and REG_BASE_KEY = #{regBaseKey,jdbcType=VARCHAR}",
          "and REG_KEY_PATH = #{regKeyPath,jdbcType=VARCHAR}",
          "and REG_KEY_NM = #{regKeyNm,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(TRcRegInf record);
}