package com.nicetcm.nibsplus.broker.msg.model;

import java.util.Date;

public class TFnRcCnt extends TFnRcCntKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OP.T_FN_RC_CNT.TYPE_1_CNT
     *
     * @mbggenerated Fri Jul 25 16:26:57 KST 2014
     */
    private Integer type1Cnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OP.T_FN_RC_CNT.TYPE_2_CNT
     *
     * @mbggenerated Fri Jul 25 16:26:57 KST 2014
     */
    private Integer type2Cnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OP.T_FN_RC_CNT.TYPE_3_CNT
     *
     * @mbggenerated Fri Jul 25 16:26:57 KST 2014
     */
    private Integer type3Cnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OP.T_FN_RC_CNT.TYPE_4_CNT
     *
     * @mbggenerated Fri Jul 25 16:26:57 KST 2014
     */
    private Integer type4Cnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OP.T_FN_RC_CNT.UPDATE_DATE
     *
     * @mbggenerated Fri Jul 25 16:26:57 KST 2014
     */
    private Date updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OP.T_FN_RC_CNT.TYPE_1_CNT
     *
     * @return the value of OP.T_FN_RC_CNT.TYPE_1_CNT
     *
     * @mbggenerated Fri Jul 25 16:26:57 KST 2014
     */
    public Integer getType1Cnt() {
        return type1Cnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OP.T_FN_RC_CNT.TYPE_1_CNT
     *
     * @param type1Cnt the value for OP.T_FN_RC_CNT.TYPE_1_CNT
     *
     * @mbggenerated Fri Jul 25 16:26:57 KST 2014
     */
    public void setType1Cnt(Integer type1Cnt) {
        this.type1Cnt = type1Cnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OP.T_FN_RC_CNT.TYPE_2_CNT
     *
     * @return the value of OP.T_FN_RC_CNT.TYPE_2_CNT
     *
     * @mbggenerated Fri Jul 25 16:26:57 KST 2014
     */
    public Integer getType2Cnt() {
        return type2Cnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OP.T_FN_RC_CNT.TYPE_2_CNT
     *
     * @param type2Cnt the value for OP.T_FN_RC_CNT.TYPE_2_CNT
     *
     * @mbggenerated Fri Jul 25 16:26:57 KST 2014
     */
    public void setType2Cnt(Integer type2Cnt) {
        this.type2Cnt = type2Cnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OP.T_FN_RC_CNT.TYPE_3_CNT
     *
     * @return the value of OP.T_FN_RC_CNT.TYPE_3_CNT
     *
     * @mbggenerated Fri Jul 25 16:26:57 KST 2014
     */
    public Integer getType3Cnt() {
        return type3Cnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OP.T_FN_RC_CNT.TYPE_3_CNT
     *
     * @param type3Cnt the value for OP.T_FN_RC_CNT.TYPE_3_CNT
     *
     * @mbggenerated Fri Jul 25 16:26:57 KST 2014
     */
    public void setType3Cnt(Integer type3Cnt) {
        this.type3Cnt = type3Cnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OP.T_FN_RC_CNT.TYPE_4_CNT
     *
     * @return the value of OP.T_FN_RC_CNT.TYPE_4_CNT
     *
     * @mbggenerated Fri Jul 25 16:26:57 KST 2014
     */
    public Integer getType4Cnt() {
        return type4Cnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OP.T_FN_RC_CNT.TYPE_4_CNT
     *
     * @param type4Cnt the value for OP.T_FN_RC_CNT.TYPE_4_CNT
     *
     * @mbggenerated Fri Jul 25 16:26:57 KST 2014
     */
    public void setType4Cnt(Integer type4Cnt) {
        this.type4Cnt = type4Cnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OP.T_FN_RC_CNT.UPDATE_DATE
     *
     * @return the value of OP.T_FN_RC_CNT.UPDATE_DATE
     *
     * @mbggenerated Fri Jul 25 16:26:57 KST 2014
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OP.T_FN_RC_CNT.UPDATE_DATE
     *
     * @param updateDate the value for OP.T_FN_RC_CNT.UPDATE_DATE
     *
     * @mbggenerated Fri Jul 25 16:26:57 KST 2014
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}