package com.nicetcm.nibsplus.broker.msg.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TCtPenaltyListSpec {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table OP.T_CT_PENALTY_LIST
     *
     * @mbggenerated Thu Jul 31 14:31:01 KST 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table OP.T_CT_PENALTY_LIST
     *
     * @mbggenerated Thu Jul 31 14:31:01 KST 2014
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table OP.T_CT_PENALTY_LIST
     *
     * @mbggenerated Thu Jul 31 14:31:01 KST 2014
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_CT_PENALTY_LIST
     *
     * @mbggenerated Thu Jul 31 14:31:01 KST 2014
     */
    public TCtPenaltyListSpec() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_CT_PENALTY_LIST
     *
     * @mbggenerated Thu Jul 31 14:31:01 KST 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_CT_PENALTY_LIST
     *
     * @mbggenerated Thu Jul 31 14:31:01 KST 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_CT_PENALTY_LIST
     *
     * @mbggenerated Thu Jul 31 14:31:01 KST 2014
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_CT_PENALTY_LIST
     *
     * @mbggenerated Thu Jul 31 14:31:01 KST 2014
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_CT_PENALTY_LIST
     *
     * @mbggenerated Thu Jul 31 14:31:01 KST 2014
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_CT_PENALTY_LIST
     *
     * @mbggenerated Thu Jul 31 14:31:01 KST 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_CT_PENALTY_LIST
     *
     * @mbggenerated Thu Jul 31 14:31:01 KST 2014
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_CT_PENALTY_LIST
     *
     * @mbggenerated Thu Jul 31 14:31:01 KST 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_CT_PENALTY_LIST
     *
     * @mbggenerated Thu Jul 31 14:31:01 KST 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_CT_PENALTY_LIST
     *
     * @mbggenerated Thu Jul 31 14:31:01 KST 2014
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table OP.T_CT_PENALTY_LIST
     *
     * @mbggenerated Thu Jul 31 14:31:01 KST 2014
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andOrgCdIsNull() {
            addCriterion("ORG_CD is null");
            return (Criteria) this;
        }

        public Criteria andOrgCdIsNotNull() {
            addCriterion("ORG_CD is not null");
            return (Criteria) this;
        }

        public Criteria andOrgCdEqualTo(String value) {
            addCriterion("ORG_CD =", value, "orgCd");
            return (Criteria) this;
        }

        public Criteria andOrgCdNotEqualTo(String value) {
            addCriterion("ORG_CD <>", value, "orgCd");
            return (Criteria) this;
        }

        public Criteria andOrgCdGreaterThan(String value) {
            addCriterion("ORG_CD >", value, "orgCd");
            return (Criteria) this;
        }

        public Criteria andOrgCdGreaterThanOrEqualTo(String value) {
            addCriterion("ORG_CD >=", value, "orgCd");
            return (Criteria) this;
        }

        public Criteria andOrgCdLessThan(String value) {
            addCriterion("ORG_CD <", value, "orgCd");
            return (Criteria) this;
        }

        public Criteria andOrgCdLessThanOrEqualTo(String value) {
            addCriterion("ORG_CD <=", value, "orgCd");
            return (Criteria) this;
        }

        public Criteria andOrgCdLike(String value) {
            addCriterion("ORG_CD like", value, "orgCd");
            return (Criteria) this;
        }

        public Criteria andOrgCdNotLike(String value) {
            addCriterion("ORG_CD not like", value, "orgCd");
            return (Criteria) this;
        }

        public Criteria andOrgCdIn(List<String> values) {
            addCriterion("ORG_CD in", values, "orgCd");
            return (Criteria) this;
        }

        public Criteria andOrgCdNotIn(List<String> values) {
            addCriterion("ORG_CD not in", values, "orgCd");
            return (Criteria) this;
        }

        public Criteria andOrgCdBetween(String value1, String value2) {
            addCriterion("ORG_CD between", value1, value2, "orgCd");
            return (Criteria) this;
        }

        public Criteria andOrgCdNotBetween(String value1, String value2) {
            addCriterion("ORG_CD not between", value1, value2, "orgCd");
            return (Criteria) this;
        }

        public Criteria andBranchCdIsNull() {
            addCriterion("BRANCH_CD is null");
            return (Criteria) this;
        }

        public Criteria andBranchCdIsNotNull() {
            addCriterion("BRANCH_CD is not null");
            return (Criteria) this;
        }

        public Criteria andBranchCdEqualTo(String value) {
            addCriterion("BRANCH_CD =", value, "branchCd");
            return (Criteria) this;
        }

        public Criteria andBranchCdNotEqualTo(String value) {
            addCriterion("BRANCH_CD <>", value, "branchCd");
            return (Criteria) this;
        }

        public Criteria andBranchCdGreaterThan(String value) {
            addCriterion("BRANCH_CD >", value, "branchCd");
            return (Criteria) this;
        }

        public Criteria andBranchCdGreaterThanOrEqualTo(String value) {
            addCriterion("BRANCH_CD >=", value, "branchCd");
            return (Criteria) this;
        }

        public Criteria andBranchCdLessThan(String value) {
            addCriterion("BRANCH_CD <", value, "branchCd");
            return (Criteria) this;
        }

        public Criteria andBranchCdLessThanOrEqualTo(String value) {
            addCriterion("BRANCH_CD <=", value, "branchCd");
            return (Criteria) this;
        }

        public Criteria andBranchCdLike(String value) {
            addCriterion("BRANCH_CD like", value, "branchCd");
            return (Criteria) this;
        }

        public Criteria andBranchCdNotLike(String value) {
            addCriterion("BRANCH_CD not like", value, "branchCd");
            return (Criteria) this;
        }

        public Criteria andBranchCdIn(List<String> values) {
            addCriterion("BRANCH_CD in", values, "branchCd");
            return (Criteria) this;
        }

        public Criteria andBranchCdNotIn(List<String> values) {
            addCriterion("BRANCH_CD not in", values, "branchCd");
            return (Criteria) this;
        }

        public Criteria andBranchCdBetween(String value1, String value2) {
            addCriterion("BRANCH_CD between", value1, value2, "branchCd");
            return (Criteria) this;
        }

        public Criteria andBranchCdNotBetween(String value1, String value2) {
            addCriterion("BRANCH_CD not between", value1, value2, "branchCd");
            return (Criteria) this;
        }

        public Criteria andMacNoIsNull() {
            addCriterion("MAC_NO is null");
            return (Criteria) this;
        }

        public Criteria andMacNoIsNotNull() {
            addCriterion("MAC_NO is not null");
            return (Criteria) this;
        }

        public Criteria andMacNoEqualTo(String value) {
            addCriterion("MAC_NO =", value, "macNo");
            return (Criteria) this;
        }

        public Criteria andMacNoNotEqualTo(String value) {
            addCriterion("MAC_NO <>", value, "macNo");
            return (Criteria) this;
        }

        public Criteria andMacNoGreaterThan(String value) {
            addCriterion("MAC_NO >", value, "macNo");
            return (Criteria) this;
        }

        public Criteria andMacNoGreaterThanOrEqualTo(String value) {
            addCriterion("MAC_NO >=", value, "macNo");
            return (Criteria) this;
        }

        public Criteria andMacNoLessThan(String value) {
            addCriterion("MAC_NO <", value, "macNo");
            return (Criteria) this;
        }

        public Criteria andMacNoLessThanOrEqualTo(String value) {
            addCriterion("MAC_NO <=", value, "macNo");
            return (Criteria) this;
        }

        public Criteria andMacNoLike(String value) {
            addCriterion("MAC_NO like", value, "macNo");
            return (Criteria) this;
        }

        public Criteria andMacNoNotLike(String value) {
            addCriterion("MAC_NO not like", value, "macNo");
            return (Criteria) this;
        }

        public Criteria andMacNoIn(List<String> values) {
            addCriterion("MAC_NO in", values, "macNo");
            return (Criteria) this;
        }

        public Criteria andMacNoNotIn(List<String> values) {
            addCriterion("MAC_NO not in", values, "macNo");
            return (Criteria) this;
        }

        public Criteria andMacNoBetween(String value1, String value2) {
            addCriterion("MAC_NO between", value1, value2, "macNo");
            return (Criteria) this;
        }

        public Criteria andMacNoNotBetween(String value1, String value2) {
            addCriterion("MAC_NO not between", value1, value2, "macNo");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("CREATE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("CREATE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(String value) {
            addCriterion("CREATE_DATE =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(String value) {
            addCriterion("CREATE_DATE <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(String value) {
            addCriterion("CREATE_DATE >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(String value) {
            addCriterion("CREATE_DATE >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(String value) {
            addCriterion("CREATE_DATE <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(String value) {
            addCriterion("CREATE_DATE <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLike(String value) {
            addCriterion("CREATE_DATE like", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotLike(String value) {
            addCriterion("CREATE_DATE not like", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<String> values) {
            addCriterion("CREATE_DATE in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<String> values) {
            addCriterion("CREATE_DATE not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(String value1, String value2) {
            addCriterion("CREATE_DATE between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(String value1, String value2) {
            addCriterion("CREATE_DATE not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("CREATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("CREATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(String value) {
            addCriterion("CREATE_TIME =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(String value) {
            addCriterion("CREATE_TIME <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(String value) {
            addCriterion("CREATE_TIME >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(String value) {
            addCriterion("CREATE_TIME >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(String value) {
            addCriterion("CREATE_TIME <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(String value) {
            addCriterion("CREATE_TIME <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLike(String value) {
            addCriterion("CREATE_TIME like", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotLike(String value) {
            addCriterion("CREATE_TIME not like", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<String> values) {
            addCriterion("CREATE_TIME in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<String> values) {
            addCriterion("CREATE_TIME not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(String value1, String value2) {
            addCriterion("CREATE_TIME between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(String value1, String value2) {
            addCriterion("CREATE_TIME not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCallDateIsNull() {
            addCriterion("CALL_DATE is null");
            return (Criteria) this;
        }

        public Criteria andCallDateIsNotNull() {
            addCriterion("CALL_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andCallDateEqualTo(String value) {
            addCriterion("CALL_DATE =", value, "callDate");
            return (Criteria) this;
        }

        public Criteria andCallDateNotEqualTo(String value) {
            addCriterion("CALL_DATE <>", value, "callDate");
            return (Criteria) this;
        }

        public Criteria andCallDateGreaterThan(String value) {
            addCriterion("CALL_DATE >", value, "callDate");
            return (Criteria) this;
        }

        public Criteria andCallDateGreaterThanOrEqualTo(String value) {
            addCriterion("CALL_DATE >=", value, "callDate");
            return (Criteria) this;
        }

        public Criteria andCallDateLessThan(String value) {
            addCriterion("CALL_DATE <", value, "callDate");
            return (Criteria) this;
        }

        public Criteria andCallDateLessThanOrEqualTo(String value) {
            addCriterion("CALL_DATE <=", value, "callDate");
            return (Criteria) this;
        }

        public Criteria andCallDateLike(String value) {
            addCriterion("CALL_DATE like", value, "callDate");
            return (Criteria) this;
        }

        public Criteria andCallDateNotLike(String value) {
            addCriterion("CALL_DATE not like", value, "callDate");
            return (Criteria) this;
        }

        public Criteria andCallDateIn(List<String> values) {
            addCriterion("CALL_DATE in", values, "callDate");
            return (Criteria) this;
        }

        public Criteria andCallDateNotIn(List<String> values) {
            addCriterion("CALL_DATE not in", values, "callDate");
            return (Criteria) this;
        }

        public Criteria andCallDateBetween(String value1, String value2) {
            addCriterion("CALL_DATE between", value1, value2, "callDate");
            return (Criteria) this;
        }

        public Criteria andCallDateNotBetween(String value1, String value2) {
            addCriterion("CALL_DATE not between", value1, value2, "callDate");
            return (Criteria) this;
        }

        public Criteria andCallTimeIsNull() {
            addCriterion("CALL_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCallTimeIsNotNull() {
            addCriterion("CALL_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCallTimeEqualTo(String value) {
            addCriterion("CALL_TIME =", value, "callTime");
            return (Criteria) this;
        }

        public Criteria andCallTimeNotEqualTo(String value) {
            addCriterion("CALL_TIME <>", value, "callTime");
            return (Criteria) this;
        }

        public Criteria andCallTimeGreaterThan(String value) {
            addCriterion("CALL_TIME >", value, "callTime");
            return (Criteria) this;
        }

        public Criteria andCallTimeGreaterThanOrEqualTo(String value) {
            addCriterion("CALL_TIME >=", value, "callTime");
            return (Criteria) this;
        }

        public Criteria andCallTimeLessThan(String value) {
            addCriterion("CALL_TIME <", value, "callTime");
            return (Criteria) this;
        }

        public Criteria andCallTimeLessThanOrEqualTo(String value) {
            addCriterion("CALL_TIME <=", value, "callTime");
            return (Criteria) this;
        }

        public Criteria andCallTimeLike(String value) {
            addCriterion("CALL_TIME like", value, "callTime");
            return (Criteria) this;
        }

        public Criteria andCallTimeNotLike(String value) {
            addCriterion("CALL_TIME not like", value, "callTime");
            return (Criteria) this;
        }

        public Criteria andCallTimeIn(List<String> values) {
            addCriterion("CALL_TIME in", values, "callTime");
            return (Criteria) this;
        }

        public Criteria andCallTimeNotIn(List<String> values) {
            addCriterion("CALL_TIME not in", values, "callTime");
            return (Criteria) this;
        }

        public Criteria andCallTimeBetween(String value1, String value2) {
            addCriterion("CALL_TIME between", value1, value2, "callTime");
            return (Criteria) this;
        }

        public Criteria andCallTimeNotBetween(String value1, String value2) {
            addCriterion("CALL_TIME not between", value1, value2, "callTime");
            return (Criteria) this;
        }

        public Criteria andSeqNoIsNull() {
            addCriterion("SEQ_NO is null");
            return (Criteria) this;
        }

        public Criteria andSeqNoIsNotNull() {
            addCriterion("SEQ_NO is not null");
            return (Criteria) this;
        }

        public Criteria andSeqNoEqualTo(Long value) {
            addCriterion("SEQ_NO =", value, "seqNo");
            return (Criteria) this;
        }

        public Criteria andSeqNoNotEqualTo(Long value) {
            addCriterion("SEQ_NO <>", value, "seqNo");
            return (Criteria) this;
        }

        public Criteria andSeqNoGreaterThan(Long value) {
            addCriterion("SEQ_NO >", value, "seqNo");
            return (Criteria) this;
        }

        public Criteria andSeqNoGreaterThanOrEqualTo(Long value) {
            addCriterion("SEQ_NO >=", value, "seqNo");
            return (Criteria) this;
        }

        public Criteria andSeqNoLessThan(Long value) {
            addCriterion("SEQ_NO <", value, "seqNo");
            return (Criteria) this;
        }

        public Criteria andSeqNoLessThanOrEqualTo(Long value) {
            addCriterion("SEQ_NO <=", value, "seqNo");
            return (Criteria) this;
        }

        public Criteria andSeqNoIn(List<Long> values) {
            addCriterion("SEQ_NO in", values, "seqNo");
            return (Criteria) this;
        }

        public Criteria andSeqNoNotIn(List<Long> values) {
            addCriterion("SEQ_NO not in", values, "seqNo");
            return (Criteria) this;
        }

        public Criteria andSeqNoBetween(Long value1, Long value2) {
            addCriterion("SEQ_NO between", value1, value2, "seqNo");
            return (Criteria) this;
        }

        public Criteria andSeqNoNotBetween(Long value1, Long value2) {
            addCriterion("SEQ_NO not between", value1, value2, "seqNo");
            return (Criteria) this;
        }

        public Criteria andSiteCdIsNull() {
            addCriterion("SITE_CD is null");
            return (Criteria) this;
        }

        public Criteria andSiteCdIsNotNull() {
            addCriterion("SITE_CD is not null");
            return (Criteria) this;
        }

        public Criteria andSiteCdEqualTo(String value) {
            addCriterion("SITE_CD =", value, "siteCd");
            return (Criteria) this;
        }

        public Criteria andSiteCdNotEqualTo(String value) {
            addCriterion("SITE_CD <>", value, "siteCd");
            return (Criteria) this;
        }

        public Criteria andSiteCdGreaterThan(String value) {
            addCriterion("SITE_CD >", value, "siteCd");
            return (Criteria) this;
        }

        public Criteria andSiteCdGreaterThanOrEqualTo(String value) {
            addCriterion("SITE_CD >=", value, "siteCd");
            return (Criteria) this;
        }

        public Criteria andSiteCdLessThan(String value) {
            addCriterion("SITE_CD <", value, "siteCd");
            return (Criteria) this;
        }

        public Criteria andSiteCdLessThanOrEqualTo(String value) {
            addCriterion("SITE_CD <=", value, "siteCd");
            return (Criteria) this;
        }

        public Criteria andSiteCdLike(String value) {
            addCriterion("SITE_CD like", value, "siteCd");
            return (Criteria) this;
        }

        public Criteria andSiteCdNotLike(String value) {
            addCriterion("SITE_CD not like", value, "siteCd");
            return (Criteria) this;
        }

        public Criteria andSiteCdIn(List<String> values) {
            addCriterion("SITE_CD in", values, "siteCd");
            return (Criteria) this;
        }

        public Criteria andSiteCdNotIn(List<String> values) {
            addCriterion("SITE_CD not in", values, "siteCd");
            return (Criteria) this;
        }

        public Criteria andSiteCdBetween(String value1, String value2) {
            addCriterion("SITE_CD between", value1, value2, "siteCd");
            return (Criteria) this;
        }

        public Criteria andSiteCdNotBetween(String value1, String value2) {
            addCriterion("SITE_CD not between", value1, value2, "siteCd");
            return (Criteria) this;
        }

        public Criteria andSiteNmIsNull() {
            addCriterion("SITE_NM is null");
            return (Criteria) this;
        }

        public Criteria andSiteNmIsNotNull() {
            addCriterion("SITE_NM is not null");
            return (Criteria) this;
        }

        public Criteria andSiteNmEqualTo(String value) {
            addCriterion("SITE_NM =", value, "siteNm");
            return (Criteria) this;
        }

        public Criteria andSiteNmNotEqualTo(String value) {
            addCriterion("SITE_NM <>", value, "siteNm");
            return (Criteria) this;
        }

        public Criteria andSiteNmGreaterThan(String value) {
            addCriterion("SITE_NM >", value, "siteNm");
            return (Criteria) this;
        }

        public Criteria andSiteNmGreaterThanOrEqualTo(String value) {
            addCriterion("SITE_NM >=", value, "siteNm");
            return (Criteria) this;
        }

        public Criteria andSiteNmLessThan(String value) {
            addCriterion("SITE_NM <", value, "siteNm");
            return (Criteria) this;
        }

        public Criteria andSiteNmLessThanOrEqualTo(String value) {
            addCriterion("SITE_NM <=", value, "siteNm");
            return (Criteria) this;
        }

        public Criteria andSiteNmLike(String value) {
            addCriterion("SITE_NM like", value, "siteNm");
            return (Criteria) this;
        }

        public Criteria andSiteNmNotLike(String value) {
            addCriterion("SITE_NM not like", value, "siteNm");
            return (Criteria) this;
        }

        public Criteria andSiteNmIn(List<String> values) {
            addCriterion("SITE_NM in", values, "siteNm");
            return (Criteria) this;
        }

        public Criteria andSiteNmNotIn(List<String> values) {
            addCriterion("SITE_NM not in", values, "siteNm");
            return (Criteria) this;
        }

        public Criteria andSiteNmBetween(String value1, String value2) {
            addCriterion("SITE_NM between", value1, value2, "siteNm");
            return (Criteria) this;
        }

        public Criteria andSiteNmNotBetween(String value1, String value2) {
            addCriterion("SITE_NM not between", value1, value2, "siteNm");
            return (Criteria) this;
        }

        public Criteria andArrivalDateIsNull() {
            addCriterion("ARRIVAL_DATE is null");
            return (Criteria) this;
        }

        public Criteria andArrivalDateIsNotNull() {
            addCriterion("ARRIVAL_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andArrivalDateEqualTo(String value) {
            addCriterion("ARRIVAL_DATE =", value, "arrivalDate");
            return (Criteria) this;
        }

        public Criteria andArrivalDateNotEqualTo(String value) {
            addCriterion("ARRIVAL_DATE <>", value, "arrivalDate");
            return (Criteria) this;
        }

        public Criteria andArrivalDateGreaterThan(String value) {
            addCriterion("ARRIVAL_DATE >", value, "arrivalDate");
            return (Criteria) this;
        }

        public Criteria andArrivalDateGreaterThanOrEqualTo(String value) {
            addCriterion("ARRIVAL_DATE >=", value, "arrivalDate");
            return (Criteria) this;
        }

        public Criteria andArrivalDateLessThan(String value) {
            addCriterion("ARRIVAL_DATE <", value, "arrivalDate");
            return (Criteria) this;
        }

        public Criteria andArrivalDateLessThanOrEqualTo(String value) {
            addCriterion("ARRIVAL_DATE <=", value, "arrivalDate");
            return (Criteria) this;
        }

        public Criteria andArrivalDateLike(String value) {
            addCriterion("ARRIVAL_DATE like", value, "arrivalDate");
            return (Criteria) this;
        }

        public Criteria andArrivalDateNotLike(String value) {
            addCriterion("ARRIVAL_DATE not like", value, "arrivalDate");
            return (Criteria) this;
        }

        public Criteria andArrivalDateIn(List<String> values) {
            addCriterion("ARRIVAL_DATE in", values, "arrivalDate");
            return (Criteria) this;
        }

        public Criteria andArrivalDateNotIn(List<String> values) {
            addCriterion("ARRIVAL_DATE not in", values, "arrivalDate");
            return (Criteria) this;
        }

        public Criteria andArrivalDateBetween(String value1, String value2) {
            addCriterion("ARRIVAL_DATE between", value1, value2, "arrivalDate");
            return (Criteria) this;
        }

        public Criteria andArrivalDateNotBetween(String value1, String value2) {
            addCriterion("ARRIVAL_DATE not between", value1, value2, "arrivalDate");
            return (Criteria) this;
        }

        public Criteria andArrivalTimeIsNull() {
            addCriterion("ARRIVAL_TIME is null");
            return (Criteria) this;
        }

        public Criteria andArrivalTimeIsNotNull() {
            addCriterion("ARRIVAL_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andArrivalTimeEqualTo(String value) {
            addCriterion("ARRIVAL_TIME =", value, "arrivalTime");
            return (Criteria) this;
        }

        public Criteria andArrivalTimeNotEqualTo(String value) {
            addCriterion("ARRIVAL_TIME <>", value, "arrivalTime");
            return (Criteria) this;
        }

        public Criteria andArrivalTimeGreaterThan(String value) {
            addCriterion("ARRIVAL_TIME >", value, "arrivalTime");
            return (Criteria) this;
        }

        public Criteria andArrivalTimeGreaterThanOrEqualTo(String value) {
            addCriterion("ARRIVAL_TIME >=", value, "arrivalTime");
            return (Criteria) this;
        }

        public Criteria andArrivalTimeLessThan(String value) {
            addCriterion("ARRIVAL_TIME <", value, "arrivalTime");
            return (Criteria) this;
        }

        public Criteria andArrivalTimeLessThanOrEqualTo(String value) {
            addCriterion("ARRIVAL_TIME <=", value, "arrivalTime");
            return (Criteria) this;
        }

        public Criteria andArrivalTimeLike(String value) {
            addCriterion("ARRIVAL_TIME like", value, "arrivalTime");
            return (Criteria) this;
        }

        public Criteria andArrivalTimeNotLike(String value) {
            addCriterion("ARRIVAL_TIME not like", value, "arrivalTime");
            return (Criteria) this;
        }

        public Criteria andArrivalTimeIn(List<String> values) {
            addCriterion("ARRIVAL_TIME in", values, "arrivalTime");
            return (Criteria) this;
        }

        public Criteria andArrivalTimeNotIn(List<String> values) {
            addCriterion("ARRIVAL_TIME not in", values, "arrivalTime");
            return (Criteria) this;
        }

        public Criteria andArrivalTimeBetween(String value1, String value2) {
            addCriterion("ARRIVAL_TIME between", value1, value2, "arrivalTime");
            return (Criteria) this;
        }

        public Criteria andArrivalTimeNotBetween(String value1, String value2) {
            addCriterion("ARRIVAL_TIME not between", value1, value2, "arrivalTime");
            return (Criteria) this;
        }

        public Criteria andRepairDateIsNull() {
            addCriterion("REPAIR_DATE is null");
            return (Criteria) this;
        }

        public Criteria andRepairDateIsNotNull() {
            addCriterion("REPAIR_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andRepairDateEqualTo(String value) {
            addCriterion("REPAIR_DATE =", value, "repairDate");
            return (Criteria) this;
        }

        public Criteria andRepairDateNotEqualTo(String value) {
            addCriterion("REPAIR_DATE <>", value, "repairDate");
            return (Criteria) this;
        }

        public Criteria andRepairDateGreaterThan(String value) {
            addCriterion("REPAIR_DATE >", value, "repairDate");
            return (Criteria) this;
        }

        public Criteria andRepairDateGreaterThanOrEqualTo(String value) {
            addCriterion("REPAIR_DATE >=", value, "repairDate");
            return (Criteria) this;
        }

        public Criteria andRepairDateLessThan(String value) {
            addCriterion("REPAIR_DATE <", value, "repairDate");
            return (Criteria) this;
        }

        public Criteria andRepairDateLessThanOrEqualTo(String value) {
            addCriterion("REPAIR_DATE <=", value, "repairDate");
            return (Criteria) this;
        }

        public Criteria andRepairDateLike(String value) {
            addCriterion("REPAIR_DATE like", value, "repairDate");
            return (Criteria) this;
        }

        public Criteria andRepairDateNotLike(String value) {
            addCriterion("REPAIR_DATE not like", value, "repairDate");
            return (Criteria) this;
        }

        public Criteria andRepairDateIn(List<String> values) {
            addCriterion("REPAIR_DATE in", values, "repairDate");
            return (Criteria) this;
        }

        public Criteria andRepairDateNotIn(List<String> values) {
            addCriterion("REPAIR_DATE not in", values, "repairDate");
            return (Criteria) this;
        }

        public Criteria andRepairDateBetween(String value1, String value2) {
            addCriterion("REPAIR_DATE between", value1, value2, "repairDate");
            return (Criteria) this;
        }

        public Criteria andRepairDateNotBetween(String value1, String value2) {
            addCriterion("REPAIR_DATE not between", value1, value2, "repairDate");
            return (Criteria) this;
        }

        public Criteria andRepairTimeIsNull() {
            addCriterion("REPAIR_TIME is null");
            return (Criteria) this;
        }

        public Criteria andRepairTimeIsNotNull() {
            addCriterion("REPAIR_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andRepairTimeEqualTo(String value) {
            addCriterion("REPAIR_TIME =", value, "repairTime");
            return (Criteria) this;
        }

        public Criteria andRepairTimeNotEqualTo(String value) {
            addCriterion("REPAIR_TIME <>", value, "repairTime");
            return (Criteria) this;
        }

        public Criteria andRepairTimeGreaterThan(String value) {
            addCriterion("REPAIR_TIME >", value, "repairTime");
            return (Criteria) this;
        }

        public Criteria andRepairTimeGreaterThanOrEqualTo(String value) {
            addCriterion("REPAIR_TIME >=", value, "repairTime");
            return (Criteria) this;
        }

        public Criteria andRepairTimeLessThan(String value) {
            addCriterion("REPAIR_TIME <", value, "repairTime");
            return (Criteria) this;
        }

        public Criteria andRepairTimeLessThanOrEqualTo(String value) {
            addCriterion("REPAIR_TIME <=", value, "repairTime");
            return (Criteria) this;
        }

        public Criteria andRepairTimeLike(String value) {
            addCriterion("REPAIR_TIME like", value, "repairTime");
            return (Criteria) this;
        }

        public Criteria andRepairTimeNotLike(String value) {
            addCriterion("REPAIR_TIME not like", value, "repairTime");
            return (Criteria) this;
        }

        public Criteria andRepairTimeIn(List<String> values) {
            addCriterion("REPAIR_TIME in", values, "repairTime");
            return (Criteria) this;
        }

        public Criteria andRepairTimeNotIn(List<String> values) {
            addCriterion("REPAIR_TIME not in", values, "repairTime");
            return (Criteria) this;
        }

        public Criteria andRepairTimeBetween(String value1, String value2) {
            addCriterion("REPAIR_TIME between", value1, value2, "repairTime");
            return (Criteria) this;
        }

        public Criteria andRepairTimeNotBetween(String value1, String value2) {
            addCriterion("REPAIR_TIME not between", value1, value2, "repairTime");
            return (Criteria) this;
        }

        public Criteria andMacModelIsNull() {
            addCriterion("MAC_MODEL is null");
            return (Criteria) this;
        }

        public Criteria andMacModelIsNotNull() {
            addCriterion("MAC_MODEL is not null");
            return (Criteria) this;
        }

        public Criteria andMacModelEqualTo(String value) {
            addCriterion("MAC_MODEL =", value, "macModel");
            return (Criteria) this;
        }

        public Criteria andMacModelNotEqualTo(String value) {
            addCriterion("MAC_MODEL <>", value, "macModel");
            return (Criteria) this;
        }

        public Criteria andMacModelGreaterThan(String value) {
            addCriterion("MAC_MODEL >", value, "macModel");
            return (Criteria) this;
        }

        public Criteria andMacModelGreaterThanOrEqualTo(String value) {
            addCriterion("MAC_MODEL >=", value, "macModel");
            return (Criteria) this;
        }

        public Criteria andMacModelLessThan(String value) {
            addCriterion("MAC_MODEL <", value, "macModel");
            return (Criteria) this;
        }

        public Criteria andMacModelLessThanOrEqualTo(String value) {
            addCriterion("MAC_MODEL <=", value, "macModel");
            return (Criteria) this;
        }

        public Criteria andMacModelLike(String value) {
            addCriterion("MAC_MODEL like", value, "macModel");
            return (Criteria) this;
        }

        public Criteria andMacModelNotLike(String value) {
            addCriterion("MAC_MODEL not like", value, "macModel");
            return (Criteria) this;
        }

        public Criteria andMacModelIn(List<String> values) {
            addCriterion("MAC_MODEL in", values, "macModel");
            return (Criteria) this;
        }

        public Criteria andMacModelNotIn(List<String> values) {
            addCriterion("MAC_MODEL not in", values, "macModel");
            return (Criteria) this;
        }

        public Criteria andMacModelBetween(String value1, String value2) {
            addCriterion("MAC_MODEL between", value1, value2, "macModel");
            return (Criteria) this;
        }

        public Criteria andMacModelNotBetween(String value1, String value2) {
            addCriterion("MAC_MODEL not between", value1, value2, "macModel");
            return (Criteria) this;
        }

        public Criteria andMemoIsNull() {
            addCriterion("MEMO is null");
            return (Criteria) this;
        }

        public Criteria andMemoIsNotNull() {
            addCriterion("MEMO is not null");
            return (Criteria) this;
        }

        public Criteria andMemoEqualTo(String value) {
            addCriterion("MEMO =", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotEqualTo(String value) {
            addCriterion("MEMO <>", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoGreaterThan(String value) {
            addCriterion("MEMO >", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoGreaterThanOrEqualTo(String value) {
            addCriterion("MEMO >=", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoLessThan(String value) {
            addCriterion("MEMO <", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoLessThanOrEqualTo(String value) {
            addCriterion("MEMO <=", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoLike(String value) {
            addCriterion("MEMO like", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotLike(String value) {
            addCriterion("MEMO not like", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoIn(List<String> values) {
            addCriterion("MEMO in", values, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotIn(List<String> values) {
            addCriterion("MEMO not in", values, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoBetween(String value1, String value2) {
            addCriterion("MEMO between", value1, value2, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotBetween(String value1, String value2) {
            addCriterion("MEMO not between", value1, value2, "memo");
            return (Criteria) this;
        }

        public Criteria andPenaltyAmtIsNull() {
            addCriterion("PENALTY_AMT is null");
            return (Criteria) this;
        }

        public Criteria andPenaltyAmtIsNotNull() {
            addCriterion("PENALTY_AMT is not null");
            return (Criteria) this;
        }

        public Criteria andPenaltyAmtEqualTo(Long value) {
            addCriterion("PENALTY_AMT =", value, "penaltyAmt");
            return (Criteria) this;
        }

        public Criteria andPenaltyAmtNotEqualTo(Long value) {
            addCriterion("PENALTY_AMT <>", value, "penaltyAmt");
            return (Criteria) this;
        }

        public Criteria andPenaltyAmtGreaterThan(Long value) {
            addCriterion("PENALTY_AMT >", value, "penaltyAmt");
            return (Criteria) this;
        }

        public Criteria andPenaltyAmtGreaterThanOrEqualTo(Long value) {
            addCriterion("PENALTY_AMT >=", value, "penaltyAmt");
            return (Criteria) this;
        }

        public Criteria andPenaltyAmtLessThan(Long value) {
            addCriterion("PENALTY_AMT <", value, "penaltyAmt");
            return (Criteria) this;
        }

        public Criteria andPenaltyAmtLessThanOrEqualTo(Long value) {
            addCriterion("PENALTY_AMT <=", value, "penaltyAmt");
            return (Criteria) this;
        }

        public Criteria andPenaltyAmtIn(List<Long> values) {
            addCriterion("PENALTY_AMT in", values, "penaltyAmt");
            return (Criteria) this;
        }

        public Criteria andPenaltyAmtNotIn(List<Long> values) {
            addCriterion("PENALTY_AMT not in", values, "penaltyAmt");
            return (Criteria) this;
        }

        public Criteria andPenaltyAmtBetween(Long value1, Long value2) {
            addCriterion("PENALTY_AMT between", value1, value2, "penaltyAmt");
            return (Criteria) this;
        }

        public Criteria andPenaltyAmtNotBetween(Long value1, Long value2) {
            addCriterion("PENALTY_AMT not between", value1, value2, "penaltyAmt");
            return (Criteria) this;
        }

        public Criteria andPenaltyYnIsNull() {
            addCriterion("PENALTY_YN is null");
            return (Criteria) this;
        }

        public Criteria andPenaltyYnIsNotNull() {
            addCriterion("PENALTY_YN is not null");
            return (Criteria) this;
        }

        public Criteria andPenaltyYnEqualTo(String value) {
            addCriterion("PENALTY_YN =", value, "penaltyYn");
            return (Criteria) this;
        }

        public Criteria andPenaltyYnNotEqualTo(String value) {
            addCriterion("PENALTY_YN <>", value, "penaltyYn");
            return (Criteria) this;
        }

        public Criteria andPenaltyYnGreaterThan(String value) {
            addCriterion("PENALTY_YN >", value, "penaltyYn");
            return (Criteria) this;
        }

        public Criteria andPenaltyYnGreaterThanOrEqualTo(String value) {
            addCriterion("PENALTY_YN >=", value, "penaltyYn");
            return (Criteria) this;
        }

        public Criteria andPenaltyYnLessThan(String value) {
            addCriterion("PENALTY_YN <", value, "penaltyYn");
            return (Criteria) this;
        }

        public Criteria andPenaltyYnLessThanOrEqualTo(String value) {
            addCriterion("PENALTY_YN <=", value, "penaltyYn");
            return (Criteria) this;
        }

        public Criteria andPenaltyYnLike(String value) {
            addCriterion("PENALTY_YN like", value, "penaltyYn");
            return (Criteria) this;
        }

        public Criteria andPenaltyYnNotLike(String value) {
            addCriterion("PENALTY_YN not like", value, "penaltyYn");
            return (Criteria) this;
        }

        public Criteria andPenaltyYnIn(List<String> values) {
            addCriterion("PENALTY_YN in", values, "penaltyYn");
            return (Criteria) this;
        }

        public Criteria andPenaltyYnNotIn(List<String> values) {
            addCriterion("PENALTY_YN not in", values, "penaltyYn");
            return (Criteria) this;
        }

        public Criteria andPenaltyYnBetween(String value1, String value2) {
            addCriterion("PENALTY_YN between", value1, value2, "penaltyYn");
            return (Criteria) this;
        }

        public Criteria andPenaltyYnNotBetween(String value1, String value2) {
            addCriterion("PENALTY_YN not between", value1, value2, "penaltyYn");
            return (Criteria) this;
        }

        public Criteria andPenaltyReasonIsNull() {
            addCriterion("PENALTY_REASON is null");
            return (Criteria) this;
        }

        public Criteria andPenaltyReasonIsNotNull() {
            addCriterion("PENALTY_REASON is not null");
            return (Criteria) this;
        }

        public Criteria andPenaltyReasonEqualTo(String value) {
            addCriterion("PENALTY_REASON =", value, "penaltyReason");
            return (Criteria) this;
        }

        public Criteria andPenaltyReasonNotEqualTo(String value) {
            addCriterion("PENALTY_REASON <>", value, "penaltyReason");
            return (Criteria) this;
        }

        public Criteria andPenaltyReasonGreaterThan(String value) {
            addCriterion("PENALTY_REASON >", value, "penaltyReason");
            return (Criteria) this;
        }

        public Criteria andPenaltyReasonGreaterThanOrEqualTo(String value) {
            addCriterion("PENALTY_REASON >=", value, "penaltyReason");
            return (Criteria) this;
        }

        public Criteria andPenaltyReasonLessThan(String value) {
            addCriterion("PENALTY_REASON <", value, "penaltyReason");
            return (Criteria) this;
        }

        public Criteria andPenaltyReasonLessThanOrEqualTo(String value) {
            addCriterion("PENALTY_REASON <=", value, "penaltyReason");
            return (Criteria) this;
        }

        public Criteria andPenaltyReasonLike(String value) {
            addCriterion("PENALTY_REASON like", value, "penaltyReason");
            return (Criteria) this;
        }

        public Criteria andPenaltyReasonNotLike(String value) {
            addCriterion("PENALTY_REASON not like", value, "penaltyReason");
            return (Criteria) this;
        }

        public Criteria andPenaltyReasonIn(List<String> values) {
            addCriterion("PENALTY_REASON in", values, "penaltyReason");
            return (Criteria) this;
        }

        public Criteria andPenaltyReasonNotIn(List<String> values) {
            addCriterion("PENALTY_REASON not in", values, "penaltyReason");
            return (Criteria) this;
        }

        public Criteria andPenaltyReasonBetween(String value1, String value2) {
            addCriterion("PENALTY_REASON between", value1, value2, "penaltyReason");
            return (Criteria) this;
        }

        public Criteria andPenaltyReasonNotBetween(String value1, String value2) {
            addCriterion("PENALTY_REASON not between", value1, value2, "penaltyReason");
            return (Criteria) this;
        }

        public Criteria andUpdateUidIsNull() {
            addCriterion("UPDATE_UID is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUidIsNotNull() {
            addCriterion("UPDATE_UID is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUidEqualTo(String value) {
            addCriterion("UPDATE_UID =", value, "updateUid");
            return (Criteria) this;
        }

        public Criteria andUpdateUidNotEqualTo(String value) {
            addCriterion("UPDATE_UID <>", value, "updateUid");
            return (Criteria) this;
        }

        public Criteria andUpdateUidGreaterThan(String value) {
            addCriterion("UPDATE_UID >", value, "updateUid");
            return (Criteria) this;
        }

        public Criteria andUpdateUidGreaterThanOrEqualTo(String value) {
            addCriterion("UPDATE_UID >=", value, "updateUid");
            return (Criteria) this;
        }

        public Criteria andUpdateUidLessThan(String value) {
            addCriterion("UPDATE_UID <", value, "updateUid");
            return (Criteria) this;
        }

        public Criteria andUpdateUidLessThanOrEqualTo(String value) {
            addCriterion("UPDATE_UID <=", value, "updateUid");
            return (Criteria) this;
        }

        public Criteria andUpdateUidLike(String value) {
            addCriterion("UPDATE_UID like", value, "updateUid");
            return (Criteria) this;
        }

        public Criteria andUpdateUidNotLike(String value) {
            addCriterion("UPDATE_UID not like", value, "updateUid");
            return (Criteria) this;
        }

        public Criteria andUpdateUidIn(List<String> values) {
            addCriterion("UPDATE_UID in", values, "updateUid");
            return (Criteria) this;
        }

        public Criteria andUpdateUidNotIn(List<String> values) {
            addCriterion("UPDATE_UID not in", values, "updateUid");
            return (Criteria) this;
        }

        public Criteria andUpdateUidBetween(String value1, String value2) {
            addCriterion("UPDATE_UID between", value1, value2, "updateUid");
            return (Criteria) this;
        }

        public Criteria andUpdateUidNotBetween(String value1, String value2) {
            addCriterion("UPDATE_UID not between", value1, value2, "updateUid");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNull() {
            addCriterion("UPDATE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNotNull() {
            addCriterion("UPDATE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateEqualTo(Date value) {
            addCriterion("UPDATE_DATE =", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotEqualTo(Date value) {
            addCriterion("UPDATE_DATE <>", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThan(Date value) {
            addCriterion("UPDATE_DATE >", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDATE_DATE >=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThan(Date value) {
            addCriterion("UPDATE_DATE <", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThanOrEqualTo(Date value) {
            addCriterion("UPDATE_DATE <=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIn(List<Date> values) {
            addCriterion("UPDATE_DATE in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotIn(List<Date> values) {
            addCriterion("UPDATE_DATE not in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateBetween(Date value1, Date value2) {
            addCriterion("UPDATE_DATE between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotBetween(Date value1, Date value2) {
            addCriterion("UPDATE_DATE not between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andOrgSendYnIsNull() {
            addCriterion("ORG_SEND_YN is null");
            return (Criteria) this;
        }

        public Criteria andOrgSendYnIsNotNull() {
            addCriterion("ORG_SEND_YN is not null");
            return (Criteria) this;
        }

        public Criteria andOrgSendYnEqualTo(String value) {
            addCriterion("ORG_SEND_YN =", value, "orgSendYn");
            return (Criteria) this;
        }

        public Criteria andOrgSendYnNotEqualTo(String value) {
            addCriterion("ORG_SEND_YN <>", value, "orgSendYn");
            return (Criteria) this;
        }

        public Criteria andOrgSendYnGreaterThan(String value) {
            addCriterion("ORG_SEND_YN >", value, "orgSendYn");
            return (Criteria) this;
        }

        public Criteria andOrgSendYnGreaterThanOrEqualTo(String value) {
            addCriterion("ORG_SEND_YN >=", value, "orgSendYn");
            return (Criteria) this;
        }

        public Criteria andOrgSendYnLessThan(String value) {
            addCriterion("ORG_SEND_YN <", value, "orgSendYn");
            return (Criteria) this;
        }

        public Criteria andOrgSendYnLessThanOrEqualTo(String value) {
            addCriterion("ORG_SEND_YN <=", value, "orgSendYn");
            return (Criteria) this;
        }

        public Criteria andOrgSendYnLike(String value) {
            addCriterion("ORG_SEND_YN like", value, "orgSendYn");
            return (Criteria) this;
        }

        public Criteria andOrgSendYnNotLike(String value) {
            addCriterion("ORG_SEND_YN not like", value, "orgSendYn");
            return (Criteria) this;
        }

        public Criteria andOrgSendYnIn(List<String> values) {
            addCriterion("ORG_SEND_YN in", values, "orgSendYn");
            return (Criteria) this;
        }

        public Criteria andOrgSendYnNotIn(List<String> values) {
            addCriterion("ORG_SEND_YN not in", values, "orgSendYn");
            return (Criteria) this;
        }

        public Criteria andOrgSendYnBetween(String value1, String value2) {
            addCriterion("ORG_SEND_YN between", value1, value2, "orgSendYn");
            return (Criteria) this;
        }

        public Criteria andOrgSendYnNotBetween(String value1, String value2) {
            addCriterion("ORG_SEND_YN not between", value1, value2, "orgSendYn");
            return (Criteria) this;
        }

        public Criteria andTransDateIsNull() {
            addCriterion("TRANS_DATE is null");
            return (Criteria) this;
        }

        public Criteria andTransDateIsNotNull() {
            addCriterion("TRANS_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andTransDateEqualTo(Date value) {
            addCriterion("TRANS_DATE =", value, "transDate");
            return (Criteria) this;
        }

        public Criteria andTransDateNotEqualTo(Date value) {
            addCriterion("TRANS_DATE <>", value, "transDate");
            return (Criteria) this;
        }

        public Criteria andTransDateGreaterThan(Date value) {
            addCriterion("TRANS_DATE >", value, "transDate");
            return (Criteria) this;
        }

        public Criteria andTransDateGreaterThanOrEqualTo(Date value) {
            addCriterion("TRANS_DATE >=", value, "transDate");
            return (Criteria) this;
        }

        public Criteria andTransDateLessThan(Date value) {
            addCriterion("TRANS_DATE <", value, "transDate");
            return (Criteria) this;
        }

        public Criteria andTransDateLessThanOrEqualTo(Date value) {
            addCriterion("TRANS_DATE <=", value, "transDate");
            return (Criteria) this;
        }

        public Criteria andTransDateIn(List<Date> values) {
            addCriterion("TRANS_DATE in", values, "transDate");
            return (Criteria) this;
        }

        public Criteria andTransDateNotIn(List<Date> values) {
            addCriterion("TRANS_DATE not in", values, "transDate");
            return (Criteria) this;
        }

        public Criteria andTransDateBetween(Date value1, Date value2) {
            addCriterion("TRANS_DATE between", value1, value2, "transDate");
            return (Criteria) this;
        }

        public Criteria andTransDateNotBetween(Date value1, Date value2) {
            addCriterion("TRANS_DATE not between", value1, value2, "transDate");
            return (Criteria) this;
        }

        public Criteria andOrgMsgNoIsNull() {
            addCriterion("ORG_MSG_NO is null");
            return (Criteria) this;
        }

        public Criteria andOrgMsgNoIsNotNull() {
            addCriterion("ORG_MSG_NO is not null");
            return (Criteria) this;
        }

        public Criteria andOrgMsgNoEqualTo(String value) {
            addCriterion("ORG_MSG_NO =", value, "orgMsgNo");
            return (Criteria) this;
        }

        public Criteria andOrgMsgNoNotEqualTo(String value) {
            addCriterion("ORG_MSG_NO <>", value, "orgMsgNo");
            return (Criteria) this;
        }

        public Criteria andOrgMsgNoGreaterThan(String value) {
            addCriterion("ORG_MSG_NO >", value, "orgMsgNo");
            return (Criteria) this;
        }

        public Criteria andOrgMsgNoGreaterThanOrEqualTo(String value) {
            addCriterion("ORG_MSG_NO >=", value, "orgMsgNo");
            return (Criteria) this;
        }

        public Criteria andOrgMsgNoLessThan(String value) {
            addCriterion("ORG_MSG_NO <", value, "orgMsgNo");
            return (Criteria) this;
        }

        public Criteria andOrgMsgNoLessThanOrEqualTo(String value) {
            addCriterion("ORG_MSG_NO <=", value, "orgMsgNo");
            return (Criteria) this;
        }

        public Criteria andOrgMsgNoLike(String value) {
            addCriterion("ORG_MSG_NO like", value, "orgMsgNo");
            return (Criteria) this;
        }

        public Criteria andOrgMsgNoNotLike(String value) {
            addCriterion("ORG_MSG_NO not like", value, "orgMsgNo");
            return (Criteria) this;
        }

        public Criteria andOrgMsgNoIn(List<String> values) {
            addCriterion("ORG_MSG_NO in", values, "orgMsgNo");
            return (Criteria) this;
        }

        public Criteria andOrgMsgNoNotIn(List<String> values) {
            addCriterion("ORG_MSG_NO not in", values, "orgMsgNo");
            return (Criteria) this;
        }

        public Criteria andOrgMsgNoBetween(String value1, String value2) {
            addCriterion("ORG_MSG_NO between", value1, value2, "orgMsgNo");
            return (Criteria) this;
        }

        public Criteria andOrgMsgNoNotBetween(String value1, String value2) {
            addCriterion("ORG_MSG_NO not between", value1, value2, "orgMsgNo");
            return (Criteria) this;
        }

        public Criteria andOrgCallCntIsNull() {
            addCriterion("ORG_CALL_CNT is null");
            return (Criteria) this;
        }

        public Criteria andOrgCallCntIsNotNull() {
            addCriterion("ORG_CALL_CNT is not null");
            return (Criteria) this;
        }

        public Criteria andOrgCallCntEqualTo(String value) {
            addCriterion("ORG_CALL_CNT =", value, "orgCallCnt");
            return (Criteria) this;
        }

        public Criteria andOrgCallCntNotEqualTo(String value) {
            addCriterion("ORG_CALL_CNT <>", value, "orgCallCnt");
            return (Criteria) this;
        }

        public Criteria andOrgCallCntGreaterThan(String value) {
            addCriterion("ORG_CALL_CNT >", value, "orgCallCnt");
            return (Criteria) this;
        }

        public Criteria andOrgCallCntGreaterThanOrEqualTo(String value) {
            addCriterion("ORG_CALL_CNT >=", value, "orgCallCnt");
            return (Criteria) this;
        }

        public Criteria andOrgCallCntLessThan(String value) {
            addCriterion("ORG_CALL_CNT <", value, "orgCallCnt");
            return (Criteria) this;
        }

        public Criteria andOrgCallCntLessThanOrEqualTo(String value) {
            addCriterion("ORG_CALL_CNT <=", value, "orgCallCnt");
            return (Criteria) this;
        }

        public Criteria andOrgCallCntLike(String value) {
            addCriterion("ORG_CALL_CNT like", value, "orgCallCnt");
            return (Criteria) this;
        }

        public Criteria andOrgCallCntNotLike(String value) {
            addCriterion("ORG_CALL_CNT not like", value, "orgCallCnt");
            return (Criteria) this;
        }

        public Criteria andOrgCallCntIn(List<String> values) {
            addCriterion("ORG_CALL_CNT in", values, "orgCallCnt");
            return (Criteria) this;
        }

        public Criteria andOrgCallCntNotIn(List<String> values) {
            addCriterion("ORG_CALL_CNT not in", values, "orgCallCnt");
            return (Criteria) this;
        }

        public Criteria andOrgCallCntBetween(String value1, String value2) {
            addCriterion("ORG_CALL_CNT between", value1, value2, "orgCallCnt");
            return (Criteria) this;
        }

        public Criteria andOrgCallCntNotBetween(String value1, String value2) {
            addCriterion("ORG_CALL_CNT not between", value1, value2, "orgCallCnt");
            return (Criteria) this;
        }

        public Criteria andOrgCallClassIsNull() {
            addCriterion("ORG_CALL_CLASS is null");
            return (Criteria) this;
        }

        public Criteria andOrgCallClassIsNotNull() {
            addCriterion("ORG_CALL_CLASS is not null");
            return (Criteria) this;
        }

        public Criteria andOrgCallClassEqualTo(String value) {
            addCriterion("ORG_CALL_CLASS =", value, "orgCallClass");
            return (Criteria) this;
        }

        public Criteria andOrgCallClassNotEqualTo(String value) {
            addCriterion("ORG_CALL_CLASS <>", value, "orgCallClass");
            return (Criteria) this;
        }

        public Criteria andOrgCallClassGreaterThan(String value) {
            addCriterion("ORG_CALL_CLASS >", value, "orgCallClass");
            return (Criteria) this;
        }

        public Criteria andOrgCallClassGreaterThanOrEqualTo(String value) {
            addCriterion("ORG_CALL_CLASS >=", value, "orgCallClass");
            return (Criteria) this;
        }

        public Criteria andOrgCallClassLessThan(String value) {
            addCriterion("ORG_CALL_CLASS <", value, "orgCallClass");
            return (Criteria) this;
        }

        public Criteria andOrgCallClassLessThanOrEqualTo(String value) {
            addCriterion("ORG_CALL_CLASS <=", value, "orgCallClass");
            return (Criteria) this;
        }

        public Criteria andOrgCallClassLike(String value) {
            addCriterion("ORG_CALL_CLASS like", value, "orgCallClass");
            return (Criteria) this;
        }

        public Criteria andOrgCallClassNotLike(String value) {
            addCriterion("ORG_CALL_CLASS not like", value, "orgCallClass");
            return (Criteria) this;
        }

        public Criteria andOrgCallClassIn(List<String> values) {
            addCriterion("ORG_CALL_CLASS in", values, "orgCallClass");
            return (Criteria) this;
        }

        public Criteria andOrgCallClassNotIn(List<String> values) {
            addCriterion("ORG_CALL_CLASS not in", values, "orgCallClass");
            return (Criteria) this;
        }

        public Criteria andOrgCallClassBetween(String value1, String value2) {
            addCriterion("ORG_CALL_CLASS between", value1, value2, "orgCallClass");
            return (Criteria) this;
        }

        public Criteria andOrgCallClassNotBetween(String value1, String value2) {
            addCriterion("ORG_CALL_CLASS not between", value1, value2, "orgCallClass");
            return (Criteria) this;
        }

        public Criteria andRepairElapseIsNull() {
            addCriterion("REPAIR_ELAPSE is null");
            return (Criteria) this;
        }

        public Criteria andRepairElapseIsNotNull() {
            addCriterion("REPAIR_ELAPSE is not null");
            return (Criteria) this;
        }

        public Criteria andRepairElapseEqualTo(String value) {
            addCriterion("REPAIR_ELAPSE =", value, "repairElapse");
            return (Criteria) this;
        }

        public Criteria andRepairElapseNotEqualTo(String value) {
            addCriterion("REPAIR_ELAPSE <>", value, "repairElapse");
            return (Criteria) this;
        }

        public Criteria andRepairElapseGreaterThan(String value) {
            addCriterion("REPAIR_ELAPSE >", value, "repairElapse");
            return (Criteria) this;
        }

        public Criteria andRepairElapseGreaterThanOrEqualTo(String value) {
            addCriterion("REPAIR_ELAPSE >=", value, "repairElapse");
            return (Criteria) this;
        }

        public Criteria andRepairElapseLessThan(String value) {
            addCriterion("REPAIR_ELAPSE <", value, "repairElapse");
            return (Criteria) this;
        }

        public Criteria andRepairElapseLessThanOrEqualTo(String value) {
            addCriterion("REPAIR_ELAPSE <=", value, "repairElapse");
            return (Criteria) this;
        }

        public Criteria andRepairElapseLike(String value) {
            addCriterion("REPAIR_ELAPSE like", value, "repairElapse");
            return (Criteria) this;
        }

        public Criteria andRepairElapseNotLike(String value) {
            addCriterion("REPAIR_ELAPSE not like", value, "repairElapse");
            return (Criteria) this;
        }

        public Criteria andRepairElapseIn(List<String> values) {
            addCriterion("REPAIR_ELAPSE in", values, "repairElapse");
            return (Criteria) this;
        }

        public Criteria andRepairElapseNotIn(List<String> values) {
            addCriterion("REPAIR_ELAPSE not in", values, "repairElapse");
            return (Criteria) this;
        }

        public Criteria andRepairElapseBetween(String value1, String value2) {
            addCriterion("REPAIR_ELAPSE between", value1, value2, "repairElapse");
            return (Criteria) this;
        }

        public Criteria andRepairElapseNotBetween(String value1, String value2) {
            addCriterion("REPAIR_ELAPSE not between", value1, value2, "repairElapse");
            return (Criteria) this;
        }

        public Criteria andBrandOrgCdIsNull() {
            addCriterion("BRAND_ORG_CD is null");
            return (Criteria) this;
        }

        public Criteria andBrandOrgCdIsNotNull() {
            addCriterion("BRAND_ORG_CD is not null");
            return (Criteria) this;
        }

        public Criteria andBrandOrgCdEqualTo(String value) {
            addCriterion("BRAND_ORG_CD =", value, "brandOrgCd");
            return (Criteria) this;
        }

        public Criteria andBrandOrgCdNotEqualTo(String value) {
            addCriterion("BRAND_ORG_CD <>", value, "brandOrgCd");
            return (Criteria) this;
        }

        public Criteria andBrandOrgCdGreaterThan(String value) {
            addCriterion("BRAND_ORG_CD >", value, "brandOrgCd");
            return (Criteria) this;
        }

        public Criteria andBrandOrgCdGreaterThanOrEqualTo(String value) {
            addCriterion("BRAND_ORG_CD >=", value, "brandOrgCd");
            return (Criteria) this;
        }

        public Criteria andBrandOrgCdLessThan(String value) {
            addCriterion("BRAND_ORG_CD <", value, "brandOrgCd");
            return (Criteria) this;
        }

        public Criteria andBrandOrgCdLessThanOrEqualTo(String value) {
            addCriterion("BRAND_ORG_CD <=", value, "brandOrgCd");
            return (Criteria) this;
        }

        public Criteria andBrandOrgCdLike(String value) {
            addCriterion("BRAND_ORG_CD like", value, "brandOrgCd");
            return (Criteria) this;
        }

        public Criteria andBrandOrgCdNotLike(String value) {
            addCriterion("BRAND_ORG_CD not like", value, "brandOrgCd");
            return (Criteria) this;
        }

        public Criteria andBrandOrgCdIn(List<String> values) {
            addCriterion("BRAND_ORG_CD in", values, "brandOrgCd");
            return (Criteria) this;
        }

        public Criteria andBrandOrgCdNotIn(List<String> values) {
            addCriterion("BRAND_ORG_CD not in", values, "brandOrgCd");
            return (Criteria) this;
        }

        public Criteria andBrandOrgCdBetween(String value1, String value2) {
            addCriterion("BRAND_ORG_CD between", value1, value2, "brandOrgCd");
            return (Criteria) this;
        }

        public Criteria andBrandOrgCdNotBetween(String value1, String value2) {
            addCriterion("BRAND_ORG_CD not between", value1, value2, "brandOrgCd");
            return (Criteria) this;
        }

        public Criteria andPenaltyCdIsNull() {
            addCriterion("PENALTY_CD is null");
            return (Criteria) this;
        }

        public Criteria andPenaltyCdIsNotNull() {
            addCriterion("PENALTY_CD is not null");
            return (Criteria) this;
        }

        public Criteria andPenaltyCdEqualTo(String value) {
            addCriterion("PENALTY_CD =", value, "penaltyCd");
            return (Criteria) this;
        }

        public Criteria andPenaltyCdNotEqualTo(String value) {
            addCriterion("PENALTY_CD <>", value, "penaltyCd");
            return (Criteria) this;
        }

        public Criteria andPenaltyCdGreaterThan(String value) {
            addCriterion("PENALTY_CD >", value, "penaltyCd");
            return (Criteria) this;
        }

        public Criteria andPenaltyCdGreaterThanOrEqualTo(String value) {
            addCriterion("PENALTY_CD >=", value, "penaltyCd");
            return (Criteria) this;
        }

        public Criteria andPenaltyCdLessThan(String value) {
            addCriterion("PENALTY_CD <", value, "penaltyCd");
            return (Criteria) this;
        }

        public Criteria andPenaltyCdLessThanOrEqualTo(String value) {
            addCriterion("PENALTY_CD <=", value, "penaltyCd");
            return (Criteria) this;
        }

        public Criteria andPenaltyCdLike(String value) {
            addCriterion("PENALTY_CD like", value, "penaltyCd");
            return (Criteria) this;
        }

        public Criteria andPenaltyCdNotLike(String value) {
            addCriterion("PENALTY_CD not like", value, "penaltyCd");
            return (Criteria) this;
        }

        public Criteria andPenaltyCdIn(List<String> values) {
            addCriterion("PENALTY_CD in", values, "penaltyCd");
            return (Criteria) this;
        }

        public Criteria andPenaltyCdNotIn(List<String> values) {
            addCriterion("PENALTY_CD not in", values, "penaltyCd");
            return (Criteria) this;
        }

        public Criteria andPenaltyCdBetween(String value1, String value2) {
            addCriterion("PENALTY_CD between", value1, value2, "penaltyCd");
            return (Criteria) this;
        }

        public Criteria andPenaltyCdNotBetween(String value1, String value2) {
            addCriterion("PENALTY_CD not between", value1, value2, "penaltyCd");
            return (Criteria) this;
        }

        public Criteria andExceptYnConfirmIsNull() {
            addCriterion("EXCEPT_YN_CONFIRM is null");
            return (Criteria) this;
        }

        public Criteria andExceptYnConfirmIsNotNull() {
            addCriterion("EXCEPT_YN_CONFIRM is not null");
            return (Criteria) this;
        }

        public Criteria andExceptYnConfirmEqualTo(String value) {
            addCriterion("EXCEPT_YN_CONFIRM =", value, "exceptYnConfirm");
            return (Criteria) this;
        }

        public Criteria andExceptYnConfirmNotEqualTo(String value) {
            addCriterion("EXCEPT_YN_CONFIRM <>", value, "exceptYnConfirm");
            return (Criteria) this;
        }

        public Criteria andExceptYnConfirmGreaterThan(String value) {
            addCriterion("EXCEPT_YN_CONFIRM >", value, "exceptYnConfirm");
            return (Criteria) this;
        }

        public Criteria andExceptYnConfirmGreaterThanOrEqualTo(String value) {
            addCriterion("EXCEPT_YN_CONFIRM >=", value, "exceptYnConfirm");
            return (Criteria) this;
        }

        public Criteria andExceptYnConfirmLessThan(String value) {
            addCriterion("EXCEPT_YN_CONFIRM <", value, "exceptYnConfirm");
            return (Criteria) this;
        }

        public Criteria andExceptYnConfirmLessThanOrEqualTo(String value) {
            addCriterion("EXCEPT_YN_CONFIRM <=", value, "exceptYnConfirm");
            return (Criteria) this;
        }

        public Criteria andExceptYnConfirmLike(String value) {
            addCriterion("EXCEPT_YN_CONFIRM like", value, "exceptYnConfirm");
            return (Criteria) this;
        }

        public Criteria andExceptYnConfirmNotLike(String value) {
            addCriterion("EXCEPT_YN_CONFIRM not like", value, "exceptYnConfirm");
            return (Criteria) this;
        }

        public Criteria andExceptYnConfirmIn(List<String> values) {
            addCriterion("EXCEPT_YN_CONFIRM in", values, "exceptYnConfirm");
            return (Criteria) this;
        }

        public Criteria andExceptYnConfirmNotIn(List<String> values) {
            addCriterion("EXCEPT_YN_CONFIRM not in", values, "exceptYnConfirm");
            return (Criteria) this;
        }

        public Criteria andExceptYnConfirmBetween(String value1, String value2) {
            addCriterion("EXCEPT_YN_CONFIRM between", value1, value2, "exceptYnConfirm");
            return (Criteria) this;
        }

        public Criteria andExceptYnConfirmNotBetween(String value1, String value2) {
            addCriterion("EXCEPT_YN_CONFIRM not between", value1, value2, "exceptYnConfirm");
            return (Criteria) this;
        }

        public Criteria andExceptYnRsnIsNull() {
            addCriterion("EXCEPT_YN_RSN is null");
            return (Criteria) this;
        }

        public Criteria andExceptYnRsnIsNotNull() {
            addCriterion("EXCEPT_YN_RSN is not null");
            return (Criteria) this;
        }

        public Criteria andExceptYnRsnEqualTo(String value) {
            addCriterion("EXCEPT_YN_RSN =", value, "exceptYnRsn");
            return (Criteria) this;
        }

        public Criteria andExceptYnRsnNotEqualTo(String value) {
            addCriterion("EXCEPT_YN_RSN <>", value, "exceptYnRsn");
            return (Criteria) this;
        }

        public Criteria andExceptYnRsnGreaterThan(String value) {
            addCriterion("EXCEPT_YN_RSN >", value, "exceptYnRsn");
            return (Criteria) this;
        }

        public Criteria andExceptYnRsnGreaterThanOrEqualTo(String value) {
            addCriterion("EXCEPT_YN_RSN >=", value, "exceptYnRsn");
            return (Criteria) this;
        }

        public Criteria andExceptYnRsnLessThan(String value) {
            addCriterion("EXCEPT_YN_RSN <", value, "exceptYnRsn");
            return (Criteria) this;
        }

        public Criteria andExceptYnRsnLessThanOrEqualTo(String value) {
            addCriterion("EXCEPT_YN_RSN <=", value, "exceptYnRsn");
            return (Criteria) this;
        }

        public Criteria andExceptYnRsnLike(String value) {
            addCriterion("EXCEPT_YN_RSN like", value, "exceptYnRsn");
            return (Criteria) this;
        }

        public Criteria andExceptYnRsnNotLike(String value) {
            addCriterion("EXCEPT_YN_RSN not like", value, "exceptYnRsn");
            return (Criteria) this;
        }

        public Criteria andExceptYnRsnIn(List<String> values) {
            addCriterion("EXCEPT_YN_RSN in", values, "exceptYnRsn");
            return (Criteria) this;
        }

        public Criteria andExceptYnRsnNotIn(List<String> values) {
            addCriterion("EXCEPT_YN_RSN not in", values, "exceptYnRsn");
            return (Criteria) this;
        }

        public Criteria andExceptYnRsnBetween(String value1, String value2) {
            addCriterion("EXCEPT_YN_RSN between", value1, value2, "exceptYnRsn");
            return (Criteria) this;
        }

        public Criteria andExceptYnRsnNotBetween(String value1, String value2) {
            addCriterion("EXCEPT_YN_RSN not between", value1, value2, "exceptYnRsn");
            return (Criteria) this;
        }

        public Criteria andFinPenaltyAmtIsNull() {
            addCriterion("FIN_PENALTY_AMT is null");
            return (Criteria) this;
        }

        public Criteria andFinPenaltyAmtIsNotNull() {
            addCriterion("FIN_PENALTY_AMT is not null");
            return (Criteria) this;
        }

        public Criteria andFinPenaltyAmtEqualTo(String value) {
            addCriterion("FIN_PENALTY_AMT =", value, "finPenaltyAmt");
            return (Criteria) this;
        }

        public Criteria andFinPenaltyAmtNotEqualTo(String value) {
            addCriterion("FIN_PENALTY_AMT <>", value, "finPenaltyAmt");
            return (Criteria) this;
        }

        public Criteria andFinPenaltyAmtGreaterThan(String value) {
            addCriterion("FIN_PENALTY_AMT >", value, "finPenaltyAmt");
            return (Criteria) this;
        }

        public Criteria andFinPenaltyAmtGreaterThanOrEqualTo(String value) {
            addCriterion("FIN_PENALTY_AMT >=", value, "finPenaltyAmt");
            return (Criteria) this;
        }

        public Criteria andFinPenaltyAmtLessThan(String value) {
            addCriterion("FIN_PENALTY_AMT <", value, "finPenaltyAmt");
            return (Criteria) this;
        }

        public Criteria andFinPenaltyAmtLessThanOrEqualTo(String value) {
            addCriterion("FIN_PENALTY_AMT <=", value, "finPenaltyAmt");
            return (Criteria) this;
        }

        public Criteria andFinPenaltyAmtLike(String value) {
            addCriterion("FIN_PENALTY_AMT like", value, "finPenaltyAmt");
            return (Criteria) this;
        }

        public Criteria andFinPenaltyAmtNotLike(String value) {
            addCriterion("FIN_PENALTY_AMT not like", value, "finPenaltyAmt");
            return (Criteria) this;
        }

        public Criteria andFinPenaltyAmtIn(List<String> values) {
            addCriterion("FIN_PENALTY_AMT in", values, "finPenaltyAmt");
            return (Criteria) this;
        }

        public Criteria andFinPenaltyAmtNotIn(List<String> values) {
            addCriterion("FIN_PENALTY_AMT not in", values, "finPenaltyAmt");
            return (Criteria) this;
        }

        public Criteria andFinPenaltyAmtBetween(String value1, String value2) {
            addCriterion("FIN_PENALTY_AMT between", value1, value2, "finPenaltyAmt");
            return (Criteria) this;
        }

        public Criteria andFinPenaltyAmtNotBetween(String value1, String value2) {
            addCriterion("FIN_PENALTY_AMT not between", value1, value2, "finPenaltyAmt");
            return (Criteria) this;
        }

        public Criteria andGroupErrorCdIsNull() {
            addCriterion("GROUP_ERROR_CD is null");
            return (Criteria) this;
        }

        public Criteria andGroupErrorCdIsNotNull() {
            addCriterion("GROUP_ERROR_CD is not null");
            return (Criteria) this;
        }

        public Criteria andGroupErrorCdEqualTo(String value) {
            addCriterion("GROUP_ERROR_CD =", value, "groupErrorCd");
            return (Criteria) this;
        }

        public Criteria andGroupErrorCdNotEqualTo(String value) {
            addCriterion("GROUP_ERROR_CD <>", value, "groupErrorCd");
            return (Criteria) this;
        }

        public Criteria andGroupErrorCdGreaterThan(String value) {
            addCriterion("GROUP_ERROR_CD >", value, "groupErrorCd");
            return (Criteria) this;
        }

        public Criteria andGroupErrorCdGreaterThanOrEqualTo(String value) {
            addCriterion("GROUP_ERROR_CD >=", value, "groupErrorCd");
            return (Criteria) this;
        }

        public Criteria andGroupErrorCdLessThan(String value) {
            addCriterion("GROUP_ERROR_CD <", value, "groupErrorCd");
            return (Criteria) this;
        }

        public Criteria andGroupErrorCdLessThanOrEqualTo(String value) {
            addCriterion("GROUP_ERROR_CD <=", value, "groupErrorCd");
            return (Criteria) this;
        }

        public Criteria andGroupErrorCdLike(String value) {
            addCriterion("GROUP_ERROR_CD like", value, "groupErrorCd");
            return (Criteria) this;
        }

        public Criteria andGroupErrorCdNotLike(String value) {
            addCriterion("GROUP_ERROR_CD not like", value, "groupErrorCd");
            return (Criteria) this;
        }

        public Criteria andGroupErrorCdIn(List<String> values) {
            addCriterion("GROUP_ERROR_CD in", values, "groupErrorCd");
            return (Criteria) this;
        }

        public Criteria andGroupErrorCdNotIn(List<String> values) {
            addCriterion("GROUP_ERROR_CD not in", values, "groupErrorCd");
            return (Criteria) this;
        }

        public Criteria andGroupErrorCdBetween(String value1, String value2) {
            addCriterion("GROUP_ERROR_CD between", value1, value2, "groupErrorCd");
            return (Criteria) this;
        }

        public Criteria andGroupErrorCdNotBetween(String value1, String value2) {
            addCriterion("GROUP_ERROR_CD not between", value1, value2, "groupErrorCd");
            return (Criteria) this;
        }

        public Criteria andStdErrorCdIsNull() {
            addCriterion("STD_ERROR_CD is null");
            return (Criteria) this;
        }

        public Criteria andStdErrorCdIsNotNull() {
            addCriterion("STD_ERROR_CD is not null");
            return (Criteria) this;
        }

        public Criteria andStdErrorCdEqualTo(String value) {
            addCriterion("STD_ERROR_CD =", value, "stdErrorCd");
            return (Criteria) this;
        }

        public Criteria andStdErrorCdNotEqualTo(String value) {
            addCriterion("STD_ERROR_CD <>", value, "stdErrorCd");
            return (Criteria) this;
        }

        public Criteria andStdErrorCdGreaterThan(String value) {
            addCriterion("STD_ERROR_CD >", value, "stdErrorCd");
            return (Criteria) this;
        }

        public Criteria andStdErrorCdGreaterThanOrEqualTo(String value) {
            addCriterion("STD_ERROR_CD >=", value, "stdErrorCd");
            return (Criteria) this;
        }

        public Criteria andStdErrorCdLessThan(String value) {
            addCriterion("STD_ERROR_CD <", value, "stdErrorCd");
            return (Criteria) this;
        }

        public Criteria andStdErrorCdLessThanOrEqualTo(String value) {
            addCriterion("STD_ERROR_CD <=", value, "stdErrorCd");
            return (Criteria) this;
        }

        public Criteria andStdErrorCdLike(String value) {
            addCriterion("STD_ERROR_CD like", value, "stdErrorCd");
            return (Criteria) this;
        }

        public Criteria andStdErrorCdNotLike(String value) {
            addCriterion("STD_ERROR_CD not like", value, "stdErrorCd");
            return (Criteria) this;
        }

        public Criteria andStdErrorCdIn(List<String> values) {
            addCriterion("STD_ERROR_CD in", values, "stdErrorCd");
            return (Criteria) this;
        }

        public Criteria andStdErrorCdNotIn(List<String> values) {
            addCriterion("STD_ERROR_CD not in", values, "stdErrorCd");
            return (Criteria) this;
        }

        public Criteria andStdErrorCdBetween(String value1, String value2) {
            addCriterion("STD_ERROR_CD between", value1, value2, "stdErrorCd");
            return (Criteria) this;
        }

        public Criteria andStdErrorCdNotBetween(String value1, String value2) {
            addCriterion("STD_ERROR_CD not between", value1, value2, "stdErrorCd");
            return (Criteria) this;
        }

        public Criteria andErrorCdIsNull() {
            addCriterion("ERROR_CD is null");
            return (Criteria) this;
        }

        public Criteria andErrorCdIsNotNull() {
            addCriterion("ERROR_CD is not null");
            return (Criteria) this;
        }

        public Criteria andErrorCdEqualTo(String value) {
            addCriterion("ERROR_CD =", value, "errorCd");
            return (Criteria) this;
        }

        public Criteria andErrorCdNotEqualTo(String value) {
            addCriterion("ERROR_CD <>", value, "errorCd");
            return (Criteria) this;
        }

        public Criteria andErrorCdGreaterThan(String value) {
            addCriterion("ERROR_CD >", value, "errorCd");
            return (Criteria) this;
        }

        public Criteria andErrorCdGreaterThanOrEqualTo(String value) {
            addCriterion("ERROR_CD >=", value, "errorCd");
            return (Criteria) this;
        }

        public Criteria andErrorCdLessThan(String value) {
            addCriterion("ERROR_CD <", value, "errorCd");
            return (Criteria) this;
        }

        public Criteria andErrorCdLessThanOrEqualTo(String value) {
            addCriterion("ERROR_CD <=", value, "errorCd");
            return (Criteria) this;
        }

        public Criteria andErrorCdLike(String value) {
            addCriterion("ERROR_CD like", value, "errorCd");
            return (Criteria) this;
        }

        public Criteria andErrorCdNotLike(String value) {
            addCriterion("ERROR_CD not like", value, "errorCd");
            return (Criteria) this;
        }

        public Criteria andErrorCdIn(List<String> values) {
            addCriterion("ERROR_CD in", values, "errorCd");
            return (Criteria) this;
        }

        public Criteria andErrorCdNotIn(List<String> values) {
            addCriterion("ERROR_CD not in", values, "errorCd");
            return (Criteria) this;
        }

        public Criteria andErrorCdBetween(String value1, String value2) {
            addCriterion("ERROR_CD between", value1, value2, "errorCd");
            return (Criteria) this;
        }

        public Criteria andErrorCdNotBetween(String value1, String value2) {
            addCriterion("ERROR_CD not between", value1, value2, "errorCd");
            return (Criteria) this;
        }

        public Criteria andExceptCdIsNull() {
            addCriterion("EXCEPT_CD is null");
            return (Criteria) this;
        }

        public Criteria andExceptCdIsNotNull() {
            addCriterion("EXCEPT_CD is not null");
            return (Criteria) this;
        }

        public Criteria andExceptCdEqualTo(String value) {
            addCriterion("EXCEPT_CD =", value, "exceptCd");
            return (Criteria) this;
        }

        public Criteria andExceptCdNotEqualTo(String value) {
            addCriterion("EXCEPT_CD <>", value, "exceptCd");
            return (Criteria) this;
        }

        public Criteria andExceptCdGreaterThan(String value) {
            addCriterion("EXCEPT_CD >", value, "exceptCd");
            return (Criteria) this;
        }

        public Criteria andExceptCdGreaterThanOrEqualTo(String value) {
            addCriterion("EXCEPT_CD >=", value, "exceptCd");
            return (Criteria) this;
        }

        public Criteria andExceptCdLessThan(String value) {
            addCriterion("EXCEPT_CD <", value, "exceptCd");
            return (Criteria) this;
        }

        public Criteria andExceptCdLessThanOrEqualTo(String value) {
            addCriterion("EXCEPT_CD <=", value, "exceptCd");
            return (Criteria) this;
        }

        public Criteria andExceptCdLike(String value) {
            addCriterion("EXCEPT_CD like", value, "exceptCd");
            return (Criteria) this;
        }

        public Criteria andExceptCdNotLike(String value) {
            addCriterion("EXCEPT_CD not like", value, "exceptCd");
            return (Criteria) this;
        }

        public Criteria andExceptCdIn(List<String> values) {
            addCriterion("EXCEPT_CD in", values, "exceptCd");
            return (Criteria) this;
        }

        public Criteria andExceptCdNotIn(List<String> values) {
            addCriterion("EXCEPT_CD not in", values, "exceptCd");
            return (Criteria) this;
        }

        public Criteria andExceptCdBetween(String value1, String value2) {
            addCriterion("EXCEPT_CD between", value1, value2, "exceptCd");
            return (Criteria) this;
        }

        public Criteria andExceptCdNotBetween(String value1, String value2) {
            addCriterion("EXCEPT_CD not between", value1, value2, "exceptCd");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table OP.T_CT_PENALTY_LIST
     *
     * @mbggenerated do_not_delete_during_merge Thu Jul 31 14:31:01 KST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table OP.T_CT_PENALTY_LIST
     *
     * @mbggenerated Thu Jul 31 14:31:01 KST 2014
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}