package com.nicetcm.nibsplus.broker.msg.mapper;

import com.nicetcm.nibsplus.broker.msg.model.TFnEmartDemandDate;
import com.nicetcm.nibsplus.broker.msg.model.TFnEmartDemandDateKey;
import com.nicetcm.nibsplus.broker.msg.model.TFnEmartDemandDateSpec;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface TFnEmartDemandDateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_EMART_DEMAND_DATE
     *
     * @mbggenerated Tue Jul 22 11:13:55 KST 2014
     */
    @SelectProvider(type=TFnEmartDemandDateSqlProvider.class, method="countBySpec")
    int countBySpec(TFnEmartDemandDateSpec spec);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_EMART_DEMAND_DATE
     *
     * @mbggenerated Tue Jul 22 11:13:55 KST 2014
     */
    @DeleteProvider(type=TFnEmartDemandDateSqlProvider.class, method="deleteBySpec")
    int deleteBySpec(TFnEmartDemandDateSpec spec);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_EMART_DEMAND_DATE
     *
     * @mbggenerated Tue Jul 22 11:13:55 KST 2014
     */
    @Delete({
        "delete from OP.T_FN_EMART_DEMAND_DATE",
        "where BASE_DATE = #{baseDate,jdbcType=VARCHAR}",
          "and ORG_CD = #{orgCd,jdbcType=VARCHAR}",
          "and BRANCH_CD = #{branchCd,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(TFnEmartDemandDateKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_EMART_DEMAND_DATE
     *
     * @mbggenerated Tue Jul 22 11:13:55 KST 2014
     */
    @Insert({
        "insert into OP.T_FN_EMART_DEMAND_DATE (BASE_DATE, ORG_CD, ",
        "BRANCH_CD, DEPT_CD, ",
        "OFFICE_CD, START_DATE, ",
        "END_DATE, UPDATE_DATE, ",
        "UPDATE_UID, ORG_SEND_YN)",
        "values (#{baseDate,jdbcType=VARCHAR}, #{orgCd,jdbcType=VARCHAR}, ",
        "#{branchCd,jdbcType=VARCHAR}, #{deptCd,jdbcType=VARCHAR}, ",
        "#{officeCd,jdbcType=VARCHAR}, #{startDate,jdbcType=VARCHAR}, ",
        "#{endDate,jdbcType=VARCHAR}, #{updateDate,jdbcType=TIMESTAMP}, ",
        "#{updateUid,jdbcType=VARCHAR}, #{orgSendYn,jdbcType=VARCHAR})"
    })
    int insert(TFnEmartDemandDate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_EMART_DEMAND_DATE
     *
     * @mbggenerated Tue Jul 22 11:13:55 KST 2014
     */
    @InsertProvider(type=TFnEmartDemandDateSqlProvider.class, method="insertSelective")
    int insertSelective(TFnEmartDemandDate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_EMART_DEMAND_DATE
     *
     * @mbggenerated Tue Jul 22 11:13:55 KST 2014
     */
    @SelectProvider(type=TFnEmartDemandDateSqlProvider.class, method="selectBySpec")
    @Results({
        @Result(column="BASE_DATE", property="baseDate", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="ORG_CD", property="orgCd", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="BRANCH_CD", property="branchCd", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="DEPT_CD", property="deptCd", jdbcType=JdbcType.VARCHAR),
        @Result(column="OFFICE_CD", property="officeCd", jdbcType=JdbcType.VARCHAR),
        @Result(column="START_DATE", property="startDate", jdbcType=JdbcType.VARCHAR),
        @Result(column="END_DATE", property="endDate", jdbcType=JdbcType.VARCHAR),
        @Result(column="UPDATE_DATE", property="updateDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="UPDATE_UID", property="updateUid", jdbcType=JdbcType.VARCHAR),
        @Result(column="ORG_SEND_YN", property="orgSendYn", jdbcType=JdbcType.VARCHAR)
    })
    List<TFnEmartDemandDate> selectBySpec(TFnEmartDemandDateSpec spec);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_EMART_DEMAND_DATE
     *
     * @mbggenerated Tue Jul 22 11:13:55 KST 2014
     */
    @Select({
        "select",
        "BASE_DATE, ORG_CD, BRANCH_CD, DEPT_CD, OFFICE_CD, START_DATE, END_DATE, UPDATE_DATE, ",
        "UPDATE_UID, ORG_SEND_YN",
        "from OP.T_FN_EMART_DEMAND_DATE",
        "where BASE_DATE = #{baseDate,jdbcType=VARCHAR}",
          "and ORG_CD = #{orgCd,jdbcType=VARCHAR}",
          "and BRANCH_CD = #{branchCd,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="BASE_DATE", property="baseDate", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="ORG_CD", property="orgCd", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="BRANCH_CD", property="branchCd", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="DEPT_CD", property="deptCd", jdbcType=JdbcType.VARCHAR),
        @Result(column="OFFICE_CD", property="officeCd", jdbcType=JdbcType.VARCHAR),
        @Result(column="START_DATE", property="startDate", jdbcType=JdbcType.VARCHAR),
        @Result(column="END_DATE", property="endDate", jdbcType=JdbcType.VARCHAR),
        @Result(column="UPDATE_DATE", property="updateDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="UPDATE_UID", property="updateUid", jdbcType=JdbcType.VARCHAR),
        @Result(column="ORG_SEND_YN", property="orgSendYn", jdbcType=JdbcType.VARCHAR)
    })
    TFnEmartDemandDate selectByPrimaryKey(TFnEmartDemandDateKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_EMART_DEMAND_DATE
     *
     * @mbggenerated Tue Jul 22 11:13:55 KST 2014
     */
    @UpdateProvider(type=TFnEmartDemandDateSqlProvider.class, method="updateBySpecSelective")
    int updateBySpecSelective(@Param("record") TFnEmartDemandDate record, @Param("spec") TFnEmartDemandDateSpec spec);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_EMART_DEMAND_DATE
     *
     * @mbggenerated Tue Jul 22 11:13:55 KST 2014
     */
    @UpdateProvider(type=TFnEmartDemandDateSqlProvider.class, method="updateBySpec")
    int updateBySpec(@Param("record") TFnEmartDemandDate record, @Param("spec") TFnEmartDemandDateSpec spec);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_EMART_DEMAND_DATE
     *
     * @mbggenerated Tue Jul 22 11:13:55 KST 2014
     */
    @UpdateProvider(type=TFnEmartDemandDateSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(TFnEmartDemandDate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_FN_EMART_DEMAND_DATE
     *
     * @mbggenerated Tue Jul 22 11:13:55 KST 2014
     */
    @Update({
        "update OP.T_FN_EMART_DEMAND_DATE",
        "set DEPT_CD = #{deptCd,jdbcType=VARCHAR},",
          "OFFICE_CD = #{officeCd,jdbcType=VARCHAR},",
          "START_DATE = #{startDate,jdbcType=VARCHAR},",
          "END_DATE = #{endDate,jdbcType=VARCHAR},",
          "UPDATE_DATE = #{updateDate,jdbcType=TIMESTAMP},",
          "UPDATE_UID = #{updateUid,jdbcType=VARCHAR},",
          "ORG_SEND_YN = #{orgSendYn,jdbcType=VARCHAR}",
        "where BASE_DATE = #{baseDate,jdbcType=VARCHAR}",
          "and ORG_CD = #{orgCd,jdbcType=VARCHAR}",
          "and BRANCH_CD = #{branchCd,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(TFnEmartDemandDate record);
}