package com.nicetcm.nibsplus.broker.msg.mapper;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.DELETE_FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.ORDER_BY;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT_DISTINCT;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import com.nicetcm.nibsplus.broker.msg.model.TCmSetFacInfo;
import com.nicetcm.nibsplus.broker.msg.model.TCmSetFacInfoSpec.Criteria;
import com.nicetcm.nibsplus.broker.msg.model.TCmSetFacInfoSpec.Criterion;
import com.nicetcm.nibsplus.broker.msg.model.TCmSetFacInfoSpec;
import java.util.List;
import java.util.Map;

public class TCmSetFacInfoSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_CM_SET_FAC_INFO
     *
     * @mbggenerated Wed Aug 06 09:58:31 KST 2014
     */
    public String countBySpec(TCmSetFacInfoSpec spec) {
        BEGIN();
        SELECT("count(*)");
        FROM("OP.T_CM_SET_FAC_INFO");
        applyWhere(spec, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_CM_SET_FAC_INFO
     *
     * @mbggenerated Wed Aug 06 09:58:31 KST 2014
     */
    public String deleteBySpec(TCmSetFacInfoSpec spec) {
        BEGIN();
        DELETE_FROM("OP.T_CM_SET_FAC_INFO");
        applyWhere(spec, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_CM_SET_FAC_INFO
     *
     * @mbggenerated Wed Aug 06 09:58:31 KST 2014
     */
    public String insertSelective(TCmSetFacInfo record) {
        BEGIN();
        INSERT_INTO("OP.T_CM_SET_FAC_INFO");

        if (record.getOrgCd() != null) {
            VALUES("ORG_CD", "#{orgCd,jdbcType=VARCHAR}");
        }

        if (record.getWorkSeq() != null) {
            VALUES("WORK_SEQ", "#{workSeq,jdbcType=VARCHAR}");
        }

        if (record.getWorkClass() != null) {
            VALUES("WORK_CLASS", "#{workClass,jdbcType=VARCHAR}");
        }

        if (record.getFacSeqNo() != null) {
            VALUES("FAC_SEQ_NO", "#{facSeqNo,jdbcType=VARCHAR}");
        }

        if (record.getCloseType() != null) {
            VALUES("CLOSE_TYPE", "#{closeType,jdbcType=VARCHAR}");
        }

        if (record.getChangeNo() != null) {
            VALUES("CHANGE_NO", "#{changeNo,jdbcType=DECIMAL}");
        }

        if (record.getOrgBranchCd() != null) {
            VALUES("ORG_BRANCH_CD", "#{orgBranchCd,jdbcType=VARCHAR}");
        }

        if (record.getOrgSiteCd() != null) {
            VALUES("ORG_SITE_CD", "#{orgSiteCd,jdbcType=VARCHAR}");
        }

        if (record.getFacType() != null) {
            VALUES("FAC_TYPE", "#{facType,jdbcType=VARCHAR}");
        }

        if (record.getFacCd() != null) {
            VALUES("FAC_CD", "#{facCd,jdbcType=VARCHAR}");
        }

        if (record.getFacNm() != null) {
            VALUES("FAC_NM", "#{facNm,jdbcType=VARCHAR}");
        }

        if (record.getFacRentYn() != null) {
            VALUES("FAC_RENT_YN", "#{facRentYn,jdbcType=VARCHAR}");
        }

        if (record.getItemGubun() != null) {
            VALUES("ITEM_GUBUN", "#{itemGubun,jdbcType=VARCHAR}");
        }

        if (record.getAssetSeqno() != null) {
            VALUES("ASSET_SEQNO", "#{assetSeqno,jdbcType=VARCHAR}");
        }

        if (record.getFacIp() != null) {
            VALUES("FAC_IP", "#{facIp,jdbcType=VARCHAR}");
        }

        if (record.getFacGw() != null) {
            VALUES("FAC_GW", "#{facGw,jdbcType=VARCHAR}");
        }

        if (record.getFacSm() != null) {
            VALUES("FAC_SM", "#{facSm,jdbcType=VARCHAR}");
        }

        if (record.getRentFee() != null) {
            VALUES("RENT_FEE", "#{rentFee,jdbcType=OTHER}");
        }

        if (record.getDetailFacInfo() != null) {
            VALUES("DETAIL_FAC_INFO", "#{detailFacInfo,jdbcType=VARCHAR}");
        }

        if (record.getCloseOrgBranchCd() != null) {
            VALUES("CLOSE_ORG_BRANCH_CD", "#{closeOrgBranchCd,jdbcType=VARCHAR}");
        }

        if (record.getCloseOrgSiteCd() != null) {
            VALUES("CLOSE_ORG_SITE_CD", "#{closeOrgSiteCd,jdbcType=VARCHAR}");
        }

        if (record.getCloseFacType() != null) {
            VALUES("CLOSE_FAC_TYPE", "#{closeFacType,jdbcType=VARCHAR}");
        }

        if (record.getCloseFacCd() != null) {
            VALUES("CLOSE_FAC_CD", "#{closeFacCd,jdbcType=VARCHAR}");
        }

        if (record.getCloseAssetSeqno() != null) {
            VALUES("CLOSE_ASSET_SEQNO", "#{closeAssetSeqno,jdbcType=VARCHAR}");
        }

        if (record.getOpenDate() != null) {
            VALUES("OPEN_DATE", "#{openDate,jdbcType=VARCHAR}");
        }

        if (record.getWorkResult() != null) {
            VALUES("WORK_RESULT", "#{workResult,jdbcType=VARCHAR}");
        }

        if (record.getWorkEndDate() != null) {
            VALUES("WORK_END_DATE", "#{workEndDate,jdbcType=VARCHAR}");
        }

        if (record.getWorkMsg() != null) {
            VALUES("WORK_MSG", "#{workMsg,jdbcType=VARCHAR}");
        }

        if (record.getUpdateDate() != null) {
            VALUES("UPDATE_DATE", "#{updateDate,jdbcType=TIMESTAMP}");
        }

        if (record.getUpdateUid() != null) {
            VALUES("UPDATE_UID", "#{updateUid,jdbcType=VARCHAR}");
        }

        if (record.getDataType() != null) {
            VALUES("DATA_TYPE", "#{dataType,jdbcType=VARCHAR}");
        }

        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_CM_SET_FAC_INFO
     *
     * @mbggenerated Wed Aug 06 09:58:31 KST 2014
     */
    public String selectBySpec(TCmSetFacInfoSpec spec) {
        BEGIN();
        if (spec != null && spec.isDistinct()) {
            SELECT_DISTINCT("ORG_CD");
        } else {
            SELECT("ORG_CD");
        }
        SELECT("WORK_SEQ");
        SELECT("WORK_CLASS");
        SELECT("FAC_SEQ_NO");
        SELECT("CLOSE_TYPE");
        SELECT("CHANGE_NO");
        SELECT("ORG_BRANCH_CD");
        SELECT("ORG_SITE_CD");
        SELECT("FAC_TYPE");
        SELECT("FAC_CD");
        SELECT("FAC_NM");
        SELECT("FAC_RENT_YN");
        SELECT("ITEM_GUBUN");
        SELECT("ASSET_SEQNO");
        SELECT("FAC_IP");
        SELECT("FAC_GW");
        SELECT("FAC_SM");
        SELECT("RENT_FEE");
        SELECT("DETAIL_FAC_INFO");
        SELECT("CLOSE_ORG_BRANCH_CD");
        SELECT("CLOSE_ORG_SITE_CD");
        SELECT("CLOSE_FAC_TYPE");
        SELECT("CLOSE_FAC_CD");
        SELECT("CLOSE_ASSET_SEQNO");
        SELECT("OPEN_DATE");
        SELECT("WORK_RESULT");
        SELECT("WORK_END_DATE");
        SELECT("WORK_MSG");
        SELECT("UPDATE_DATE");
        SELECT("UPDATE_UID");
        SELECT("DATA_TYPE");
        FROM("OP.T_CM_SET_FAC_INFO");
        applyWhere(spec, false);

        if (spec != null && spec.getOrderByClause() != null) {
            ORDER_BY(spec.getOrderByClause());
        }

        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_CM_SET_FAC_INFO
     *
     * @mbggenerated Wed Aug 06 09:58:31 KST 2014
     */
    public String updateBySpecSelective(Map<String, Object> parameter) {
        TCmSetFacInfo record = (TCmSetFacInfo) parameter.get("record");
        TCmSetFacInfoSpec spec = (TCmSetFacInfoSpec) parameter.get("spec");

        BEGIN();
        UPDATE("OP.T_CM_SET_FAC_INFO");

        if (record.getOrgCd() != null) {
            SET("ORG_CD = #{record.orgCd,jdbcType=VARCHAR}");
        }

        if (record.getWorkSeq() != null) {
            SET("WORK_SEQ = #{record.workSeq,jdbcType=VARCHAR}");
        }

        if (record.getWorkClass() != null) {
            SET("WORK_CLASS = #{record.workClass,jdbcType=VARCHAR}");
        }

        if (record.getFacSeqNo() != null) {
            SET("FAC_SEQ_NO = #{record.facSeqNo,jdbcType=VARCHAR}");
        }

        if (record.getCloseType() != null) {
            SET("CLOSE_TYPE = #{record.closeType,jdbcType=VARCHAR}");
        }

        if (record.getChangeNo() != null) {
            SET("CHANGE_NO = #{record.changeNo,jdbcType=DECIMAL}");
        }

        if (record.getOrgBranchCd() != null) {
            SET("ORG_BRANCH_CD = #{record.orgBranchCd,jdbcType=VARCHAR}");
        }

        if (record.getOrgSiteCd() != null) {
            SET("ORG_SITE_CD = #{record.orgSiteCd,jdbcType=VARCHAR}");
        }

        if (record.getFacType() != null) {
            SET("FAC_TYPE = #{record.facType,jdbcType=VARCHAR}");
        }

        if (record.getFacCd() != null) {
            SET("FAC_CD = #{record.facCd,jdbcType=VARCHAR}");
        }

        if (record.getFacNm() != null) {
            SET("FAC_NM = #{record.facNm,jdbcType=VARCHAR}");
        }

        if (record.getFacRentYn() != null) {
            SET("FAC_RENT_YN = #{record.facRentYn,jdbcType=VARCHAR}");
        }

        if (record.getItemGubun() != null) {
            SET("ITEM_GUBUN = #{record.itemGubun,jdbcType=VARCHAR}");
        }

        if (record.getAssetSeqno() != null) {
            SET("ASSET_SEQNO = #{record.assetSeqno,jdbcType=VARCHAR}");
        }

        if (record.getFacIp() != null) {
            SET("FAC_IP = #{record.facIp,jdbcType=VARCHAR}");
        }

        if (record.getFacGw() != null) {
            SET("FAC_GW = #{record.facGw,jdbcType=VARCHAR}");
        }

        if (record.getFacSm() != null) {
            SET("FAC_SM = #{record.facSm,jdbcType=VARCHAR}");
        }

        if (record.getRentFee() != null) {
            SET("RENT_FEE = #{record.rentFee,jdbcType=OTHER}");
        }

        if (record.getDetailFacInfo() != null) {
            SET("DETAIL_FAC_INFO = #{record.detailFacInfo,jdbcType=VARCHAR}");
        }

        if (record.getCloseOrgBranchCd() != null) {
            SET("CLOSE_ORG_BRANCH_CD = #{record.closeOrgBranchCd,jdbcType=VARCHAR}");
        }

        if (record.getCloseOrgSiteCd() != null) {
            SET("CLOSE_ORG_SITE_CD = #{record.closeOrgSiteCd,jdbcType=VARCHAR}");
        }

        if (record.getCloseFacType() != null) {
            SET("CLOSE_FAC_TYPE = #{record.closeFacType,jdbcType=VARCHAR}");
        }

        if (record.getCloseFacCd() != null) {
            SET("CLOSE_FAC_CD = #{record.closeFacCd,jdbcType=VARCHAR}");
        }

        if (record.getCloseAssetSeqno() != null) {
            SET("CLOSE_ASSET_SEQNO = #{record.closeAssetSeqno,jdbcType=VARCHAR}");
        }

        if (record.getOpenDate() != null) {
            SET("OPEN_DATE = #{record.openDate,jdbcType=VARCHAR}");
        }

        if (record.getWorkResult() != null) {
            SET("WORK_RESULT = #{record.workResult,jdbcType=VARCHAR}");
        }

        if (record.getWorkEndDate() != null) {
            SET("WORK_END_DATE = #{record.workEndDate,jdbcType=VARCHAR}");
        }

        if (record.getWorkMsg() != null) {
            SET("WORK_MSG = #{record.workMsg,jdbcType=VARCHAR}");
        }

        if (record.getUpdateDate() != null) {
            SET("UPDATE_DATE = #{record.updateDate,jdbcType=TIMESTAMP}");
        }

        if (record.getUpdateUid() != null) {
            SET("UPDATE_UID = #{record.updateUid,jdbcType=VARCHAR}");
        }

        if (record.getDataType() != null) {
            SET("DATA_TYPE = #{record.dataType,jdbcType=VARCHAR}");
        }

        applyWhere(spec, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_CM_SET_FAC_INFO
     *
     * @mbggenerated Wed Aug 06 09:58:31 KST 2014
     */
    public String updateBySpec(Map<String, Object> parameter) {
        BEGIN();
        UPDATE("OP.T_CM_SET_FAC_INFO");

        SET("ORG_CD = #{record.orgCd,jdbcType=VARCHAR}");
        SET("WORK_SEQ = #{record.workSeq,jdbcType=VARCHAR}");
        SET("WORK_CLASS = #{record.workClass,jdbcType=VARCHAR}");
        SET("FAC_SEQ_NO = #{record.facSeqNo,jdbcType=VARCHAR}");
        SET("CLOSE_TYPE = #{record.closeType,jdbcType=VARCHAR}");
        SET("CHANGE_NO = #{record.changeNo,jdbcType=DECIMAL}");
        SET("ORG_BRANCH_CD = #{record.orgBranchCd,jdbcType=VARCHAR}");
        SET("ORG_SITE_CD = #{record.orgSiteCd,jdbcType=VARCHAR}");
        SET("FAC_TYPE = #{record.facType,jdbcType=VARCHAR}");
        SET("FAC_CD = #{record.facCd,jdbcType=VARCHAR}");
        SET("FAC_NM = #{record.facNm,jdbcType=VARCHAR}");
        SET("FAC_RENT_YN = #{record.facRentYn,jdbcType=VARCHAR}");
        SET("ITEM_GUBUN = #{record.itemGubun,jdbcType=VARCHAR}");
        SET("ASSET_SEQNO = #{record.assetSeqno,jdbcType=VARCHAR}");
        SET("FAC_IP = #{record.facIp,jdbcType=VARCHAR}");
        SET("FAC_GW = #{record.facGw,jdbcType=VARCHAR}");
        SET("FAC_SM = #{record.facSm,jdbcType=VARCHAR}");
        SET("RENT_FEE = #{record.rentFee,jdbcType=OTHER}");
        SET("DETAIL_FAC_INFO = #{record.detailFacInfo,jdbcType=VARCHAR}");
        SET("CLOSE_ORG_BRANCH_CD = #{record.closeOrgBranchCd,jdbcType=VARCHAR}");
        SET("CLOSE_ORG_SITE_CD = #{record.closeOrgSiteCd,jdbcType=VARCHAR}");
        SET("CLOSE_FAC_TYPE = #{record.closeFacType,jdbcType=VARCHAR}");
        SET("CLOSE_FAC_CD = #{record.closeFacCd,jdbcType=VARCHAR}");
        SET("CLOSE_ASSET_SEQNO = #{record.closeAssetSeqno,jdbcType=VARCHAR}");
        SET("OPEN_DATE = #{record.openDate,jdbcType=VARCHAR}");
        SET("WORK_RESULT = #{record.workResult,jdbcType=VARCHAR}");
        SET("WORK_END_DATE = #{record.workEndDate,jdbcType=VARCHAR}");
        SET("WORK_MSG = #{record.workMsg,jdbcType=VARCHAR}");
        SET("UPDATE_DATE = #{record.updateDate,jdbcType=TIMESTAMP}");
        SET("UPDATE_UID = #{record.updateUid,jdbcType=VARCHAR}");
        SET("DATA_TYPE = #{record.dataType,jdbcType=VARCHAR}");

        TCmSetFacInfoSpec spec = (TCmSetFacInfoSpec) parameter.get("spec");
        applyWhere(spec, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_CM_SET_FAC_INFO
     *
     * @mbggenerated Wed Aug 06 09:58:31 KST 2014
     */
    public String updateByPrimaryKeySelective(TCmSetFacInfo record) {
        BEGIN();
        UPDATE("OP.T_CM_SET_FAC_INFO");

        if (record.getCloseType() != null) {
            SET("CLOSE_TYPE = #{closeType,jdbcType=VARCHAR}");
        }

        if (record.getChangeNo() != null) {
            SET("CHANGE_NO = #{changeNo,jdbcType=DECIMAL}");
        }

        if (record.getOrgBranchCd() != null) {
            SET("ORG_BRANCH_CD = #{orgBranchCd,jdbcType=VARCHAR}");
        }

        if (record.getOrgSiteCd() != null) {
            SET("ORG_SITE_CD = #{orgSiteCd,jdbcType=VARCHAR}");
        }

        if (record.getFacType() != null) {
            SET("FAC_TYPE = #{facType,jdbcType=VARCHAR}");
        }

        if (record.getFacCd() != null) {
            SET("FAC_CD = #{facCd,jdbcType=VARCHAR}");
        }

        if (record.getFacNm() != null) {
            SET("FAC_NM = #{facNm,jdbcType=VARCHAR}");
        }

        if (record.getFacRentYn() != null) {
            SET("FAC_RENT_YN = #{facRentYn,jdbcType=VARCHAR}");
        }

        if (record.getItemGubun() != null) {
            SET("ITEM_GUBUN = #{itemGubun,jdbcType=VARCHAR}");
        }

        if (record.getAssetSeqno() != null) {
            SET("ASSET_SEQNO = #{assetSeqno,jdbcType=VARCHAR}");
        }

        if (record.getFacIp() != null) {
            SET("FAC_IP = #{facIp,jdbcType=VARCHAR}");
        }

        if (record.getFacGw() != null) {
            SET("FAC_GW = #{facGw,jdbcType=VARCHAR}");
        }

        if (record.getFacSm() != null) {
            SET("FAC_SM = #{facSm,jdbcType=VARCHAR}");
        }

        if (record.getRentFee() != null) {
            SET("RENT_FEE = #{rentFee,jdbcType=OTHER}");
        }

        if (record.getDetailFacInfo() != null) {
            SET("DETAIL_FAC_INFO = #{detailFacInfo,jdbcType=VARCHAR}");
        }

        if (record.getCloseOrgBranchCd() != null) {
            SET("CLOSE_ORG_BRANCH_CD = #{closeOrgBranchCd,jdbcType=VARCHAR}");
        }

        if (record.getCloseOrgSiteCd() != null) {
            SET("CLOSE_ORG_SITE_CD = #{closeOrgSiteCd,jdbcType=VARCHAR}");
        }

        if (record.getCloseFacType() != null) {
            SET("CLOSE_FAC_TYPE = #{closeFacType,jdbcType=VARCHAR}");
        }

        if (record.getCloseFacCd() != null) {
            SET("CLOSE_FAC_CD = #{closeFacCd,jdbcType=VARCHAR}");
        }

        if (record.getCloseAssetSeqno() != null) {
            SET("CLOSE_ASSET_SEQNO = #{closeAssetSeqno,jdbcType=VARCHAR}");
        }

        if (record.getOpenDate() != null) {
            SET("OPEN_DATE = #{openDate,jdbcType=VARCHAR}");
        }

        if (record.getWorkResult() != null) {
            SET("WORK_RESULT = #{workResult,jdbcType=VARCHAR}");
        }

        if (record.getWorkEndDate() != null) {
            SET("WORK_END_DATE = #{workEndDate,jdbcType=VARCHAR}");
        }

        if (record.getWorkMsg() != null) {
            SET("WORK_MSG = #{workMsg,jdbcType=VARCHAR}");
        }

        if (record.getUpdateDate() != null) {
            SET("UPDATE_DATE = #{updateDate,jdbcType=TIMESTAMP}");
        }

        if (record.getUpdateUid() != null) {
            SET("UPDATE_UID = #{updateUid,jdbcType=VARCHAR}");
        }

        if (record.getDataType() != null) {
            SET("DATA_TYPE = #{dataType,jdbcType=VARCHAR}");
        }

        WHERE("ORG_CD = #{orgCd,jdbcType=VARCHAR}");
        WHERE("WORK_SEQ = #{workSeq,jdbcType=VARCHAR}");
        WHERE("WORK_CLASS = #{workClass,jdbcType=VARCHAR}");
        WHERE("FAC_SEQ_NO = #{facSeqNo,jdbcType=VARCHAR}");

        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OP.T_CM_SET_FAC_INFO
     *
     * @mbggenerated Wed Aug 06 09:58:31 KST 2014
     */
    protected void applyWhere(TCmSetFacInfoSpec spec, boolean includeSpecPhrase) {
        if (spec == null) {
            return;
        }

        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeSpecPhrase) {
            parmPhrase1 = "%s #{spec.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{spec.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{spec.oredCriteria[%d].allCriteria[%d].value} and #{spec.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{spec.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{spec.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{spec.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{spec.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }

        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = spec.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }

                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }

                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }

        if (sb.length() > 0) {
            WHERE(sb.toString());
        }
    }
}