DECLARE 
  PDATE VARCHAR2(200);

BEGIN 
  SELECT TO_CHAR(SYSDATE - 1,'YYYYMM')
  INTO PDATE
  FROM DUAL;

  NIBS.SP_FN_LARGEMONTH;
  COMMIT; 
  NIBS.sp_fn_risk_month ( PDATE );
  COMMIT; 
END;
/
EXIT;