DECLARE 
  PDATE VARCHAR2(200);

BEGIN 
  SELECT TO_CHAR(SYSDATE - 1,'YYYYMMDD')
  INTO PDATE
  FROM DUAL;

  NIBS.SP_FN_MAN ( PDATE );
  COMMIT; 
  NIBS.sp_fn_risk_day ( PDATE );
  COMMIT; 
END;
/
EXIT;