-- 현송계획 프로시져 실행(05:00 실행)

DECLARE 
  P_WORK_DATE VARCHAR2(200);
  P_STATUS VARCHAR2(200);

BEGIN 
  SELECT TO_CHAR(SYSDATE,'YYYYMMDD')
  INTO   P_WORK_DATE
  FROM   DUAL;
  
  P_STATUS := NULL;

  NIBS.SP_FN_DEAL_FORECAST ( P_WORK_DATE, P_STATUS );

  COMMIT; 
END;
/
EXIT;
